pinterest/gestalt

- docs/components/GeneratedPropTable.js
- docs/components/docgen.js
- docs/pages/dropdown.js
- packages/gestalt/src/Dropdown.js
- packages/gestalt/src/DropdownItem.js
- packages/gestalt/src/DropdownLink.js
- packages/gestalt/src/DropdownSection.js
Dropdown: updated Docs to use autogenerated prop table
Added a second `docgen` function (`multipledocgen`) that allows retrieving multiple components' proptables in the same docs page to allow more flexibility for designers to redesign and improve subcomponent discoverability
> Dropdown: updated Docs to use autogenerated prop table

- docs/components/Toc.js
The right sidenav was overlapping the footer on components with a ton of sub-sections, like Table. This PR adjusts bottom margin to account for the increased footer height.
_Before_
_After_
> Docs: fix right sidenav overlap bug

- packages/gestalt-codemods/45.0.0/__testfixtures__/rename-popover-handleKeyDown-to-onKeyDown.input.js
- packages/gestalt-codemods/45.0.0/__testfixtures__/rename-popover-handleKeyDown-to-onKeyDown.output.js
- packages/gestalt-codemods/45.0.0/__testfixtures__/rename-renamed-popover-handleKeyDown-to-onKeyDown.input.js
- packages/gestalt-codemods/45.0.0/__testfixtures__/rename-renamed-popover-handleKeyDown-to-onKeyDown.output.js
- packages/gestalt-codemods/45.0.0/__tests__/rename-popover-handleKeyDown-to-onKeyDown.test.js
- packages/gestalt-codemods/45.0.0/rename-popover-handleKeyDown-to-onKeyDown.js
- packages/gestalt/src/ComboBox.js
- packages/gestalt/src/Controller.js
- packages/gestalt/src/Dropdown.js
- packages/gestalt/src/Popover.js
Popover's `handleOnKeyDown` prop is renamed to `onKeyDown` and the event type is standardized from `(event)` to `({| event |})`
Dropdown implemented `handleOnKeyDown` to support keyboard navigation within Dropdown. ComboBox followed the same implementation. `handleOnKeyDown` has stayed undocumented, and moving forward there were 2 options: keep it private prefixing underscore (`_handleOnKeyDown`) or documenting it.
Popover is a building component and there's a clear use case for building custom components and needing `onKeyDown` to allow keyboard navigation within Popover's children.
NOTE: This is a breaking change as we are changing API, but prop was private so there are no uses in Pinboard and it's safe to merge.
- [X ] Added documentation + accessibility tests
> Popover: rename handleOnKeyDown to onKeyDown and standardize event type 

- docs/pages/dropdown.js
- packages/gestalt/src/Dropdown.js
- packages/gestalt/src/DropdownItem.js
- packages/gestalt/src/DropdownLink.js
index private prop in Dropdown.Item and Dropdown.Link are prefixed with underscore ('_') following new pattern
Following new pattern to name private props
> Dropdown: prefixed private props (index) with underscore

- docs/pages/module.js
- packages/gestalt/src/ModuleExpandable.js
Module: updated Docs to use autogenerated prop table [Module.Expandable]
> Module: updated Docs to use autogenerated prop table [Module.Expandable]

- packages/gestalt/src/IconButton.css
- packages/gestalt/src/IconButton.css.flow
- packages/gestalt/src/IconButton.js
- packages/gestalt/src/__snapshots__/ActivationCard.test.js.snap
- packages/gestalt/src/__snapshots__/Callout.test.js.snap
- packages/gestalt/src/__snapshots__/IconButton.test.js.snap
- packages/gestalt/src/__snapshots__/Module.test.js.snap
- packages/gestalt/src/__snapshots__/ModuleExpandableItem.test.js.snap
- packages/gestalt/src/__snapshots__/Sheet.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/TableRowExpandable.test.js.snap
- packages/gestalt/src/__snapshots__/Upsell.test.js.snap
Fixed bug due to Dropdown's positioning shift on rerender.
Solution: moving compression and style to a new direct div children of the button parent tag.  This allows the button element to not compress on click and the ref passed to Dropdown's Popover to stay constant.
Discarded solutions: 
- add timeout to render Dropdown with a delay equivalent to the ease-out compression transition in Button. This prevents Dropdown to use the anchor's position based on the initial Button position on compression. Requires leaking info from Button to Dropdown to testing.
- add event listeners to keyup, keydown, transitionstart, and transitionend inside Dropdown that control the component's rendering. All of them had some sort of incompatibility with mouse/keyboard navigation. For example, transitionstart …
> IconButton: refactor to fix Dropdown positioning shift on rerender

- packages/gestalt/src/Badge.css
- packages/gestalt/src/Badge.js
- packages/gestalt/src/Badge.test.js
- packages/gestalt/src/__snapshots__/Badge.test.js.snap
- packages/gestalt/src/__snapshots__/Dropdown.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/Module.test.js.snap
- packages/gestalt/src/__snapshots__/ModuleExpandableItem.test.js.snap
Badge currently behaves in funky ways in Flex layouts. Unless `gap` is set, Badge will expand to fill vertical space, and the `position` prop becomes useless. This PR fixes that behavior by setting a specific height on Badge.
Test code:
```js
<Flex>
<Text>Some text that uses Badge component</Text>
<Badge text="New" />
</Flex>
```
_Before, no gap_
_Before, with gap_
_After, no gap_
> Badge: fix layout issues

- docs/components/GeneratedPropTable.js
- docs/components/docgen.js
- docs/pages/link.js
- packages/gestalt/src/Link.js
Link: updated Docs to use autogenerated prop table
> Link: updated Docs to use autogenerated prop table

- packages/gestalt/src/Masonry.js
This reverts commit 417f3dfb5f2fc7890f62f3a2bcd7529aa87ccc54.
A clean revert of #1774.
While this experiment had some great scroll wins, it was seeing session/engagement loss in both mobile and desktop versions that I couldn't root cause. The only lead I had was to check invocations of `fetchMore()`, but I did a quick smoke test and found that both enabled and controlled called the function a similar number of times.
Experiment will be cleaned up internally to Pinterest, of course.
- [Jira](https://jira.pinadmin.com/browse/PERF-11249)
- [Web Experiment](https://helium.pinadmin.com/scroll_gestalt_defer_pos_update/combined/homefeed-volume/)
- [Mobile Web Experiment](https://helium.pinadmin.com/mweb_scroll_gestalt_defer_pos_update/combined/days-in-volume/)
> Masonry: revert scroll state optimization (#1774)

- packages/gestalt/src/ComboBox.js
We see some users still searching for "Typeahead", which currently yields no results since we no longer mention that component. This PR adds a small reference in ComboBox's description such that it will pop up in search results.
(Note that given the infrequency of Algolia's crawls currently, this won't take effect until the Wednesday after it's merged)
> ComboBox: add reference to Typeahead

- docs/components/GeneratedPropTable.js
- docs/pages/table.js
- packages/gestalt/src/Table.js
- packages/gestalt/src/TableBody.js
- packages/gestalt/src/TableCell.js
- packages/gestalt/src/TableFooter.js
- packages/gestalt/src/TableHeader.js
- packages/gestalt/src/TableHeaderCell.js
- packages/gestalt/src/TableRow.js
- packages/gestalt/src/TableRowExpandable.js
- packages/gestalt/src/TableSortableHeaderCell.js
Table: updated Docs to use autogenerated prop table
> Table: updated Docs to use autogenerated prop table

- packages/gestalt-codemods/46.0.0/__testfixtures__/link_deprecate_disabled_prop.input.js
- packages/gestalt-codemods/46.0.0/__testfixtures__/link_deprecate_disabled_prop.output.js
- packages/gestalt-codemods/46.0.0/__testfixtures__/rename-link_deprecate_disabled_prop.input.js
- packages/gestalt-codemods/46.0.0/__testfixtures__/rename-link_deprecate_disabled_prop.output.js
- packages/gestalt-codemods/46.0.0/__tests__/link_deprecate_disabled_prop.test.js
- packages/gestalt-codemods/46.0.0/link_deprecate_disabled_prop.js
- packages/gestalt/src/Link.js
Link: deprecate unused disabled prop + codemod
reference PR https://github.com/pinterest/gestalt/pull/1169
This prop was old code pre InternalLink cmp when Button role='link" used Link cmp and disabled state was needed. After moving to InternalLink, this code became unused.
> Link: deprecate private "disabled" prop + codemod

- packages/gestalt/src/IconButton.css
- packages/gestalt/src/IconButton.css.flow
- packages/gestalt/src/IconButton.js
- packages/gestalt/src/__snapshots__/ActivationCard.test.js.snap
- packages/gestalt/src/__snapshots__/Callout.test.js.snap
- packages/gestalt/src/__snapshots__/IconButton.test.js.snap
- packages/gestalt/src/__snapshots__/Module.test.js.snap
- packages/gestalt/src/__snapshots__/ModuleExpandableItem.test.js.snap
- packages/gestalt/src/__snapshots__/Sheet.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/TableRowExpandable.test.js.snap
- packages/gestalt/src/__snapshots__/Upsell.test.js.snap
Reverts #1924, which was a revert of #1914, + small fix
This reverts commit fd0124f7a7e930dd627633d3f00f523ee0fba976.
Small additional fix: 
to prevent 
From my research the integration tests failing that caused the revert of this change are inconsistent. They systematically fail locally on different devapps but not on latest or pinterest.com. I used the Gestalt v45.1.2 in Pinboard and diffed the PR to get testing url. The integration test successfully passed. 
Re-merging this PR with a small fix to try again.
> IconButton: refactor to fix Dropdown positioning shift on rerender + small fix

- packages/gestalt-datepicker/src/DatePicker.js
- packages/gestalt/src/ActivationCard.js
- packages/gestalt/src/Checkbox.js
- packages/gestalt/src/ComboBoxItem.js
- packages/gestalt/src/Datapoint.js
- packages/gestalt/src/DatapointTrend.js
- packages/gestalt/src/DropdownSection.js
- packages/gestalt/src/Fieldset.js
- packages/gestalt/src/FormErrorMessage.js
- packages/gestalt/src/FormHelperText.js
- packages/gestalt/src/FormLabel.js
- packages/gestalt/src/Heading.flowtest.js
- packages/gestalt/src/Modal.js
- packages/gestalt/src/ModuleExpandableItem.js
- packages/gestalt/src/OptionItem.js
- packages/gestalt/src/PageHeader.js
- packages/gestalt/src/RadioButton.js
- packages/gestalt/src/SegmentedControl.js
- packages/gestalt/src/Sheet.js
- packages/gestalt/src/Status.js
- packages/gestalt/src/Tabs.js
- packages/gestalt/src/Tag.js
- packages/gestalt/src/Tooltip.js
- packages/gestalt/src/Tooltip.jsdom.test.js
- packages/gestalt/src/VideoControls.js
- packages/gestalt/src/__snapshots__/Datapoint.test.js.snap
For any instances of Heading or Text inside our components, switch out size values as follows:
| Size | Text | TextArea | px |
|------|------|----------|----|
| 100  | sm   |     --     | 12 |
| 200  | md   |    --      | 14 |
| 300  | lg   |     --     | 16 |
| 400  |   --   | sm       | 20 |
| 500  |   --   | md       | 28 |
| 600  |  --    | lg       | 36 |
In order to deprecate our old values, we need to convert any current instances over. Also helps us eliminate the use of accessibilityLevel="none" on Heading (which will be deprecated in a future ticket)
- [Jira](https://jira.pinadmin.com/browse/GESTALT-3889)
> Heading, Text: Update internal usages to use new size values

- docs/pages/status.js
- packages/gestalt/src/Status.js
Added Best Practices and Related section and updated Accessibility section of Status docs.
> Docs: Updated Status docs to include design guidelines

- .github/ISSUE_TEMPLATE/bug-template-for-jira.md
Updating bug template to guide Pinployees to use Jira instead
> Internal: add note about Jira on bug template

- docs/pages/flex.js
- docs/pages/module.js
- packages/gestalt/src/Flex.js
- packages/gestalt/src/FlexItem.js
Of note: this also makes use of the component name and description for the sub-component. I'll update the rest of our sub-component-havin' components unless people hate this for some reason.
> Flex: use autogenerated props/description

- cypress/integration/accessibility_Table_spec.js
- docs/pages/table.js
- packages/gestalt/src/Table.js
- packages/gestalt/src/__snapshots__/Table.test.js.snap
Add tabindex="0" to tables to ensure they are keyboard accessible and get focus 
In order to ensure keyboard accessibility and focus states of the table, the tabindex of 0 allows keyboard users to reach the table and anything inside while triggering a focus ring
More details: https://dev.to/lukekyl/3-steps-to-make-html-tables-web-accessible-3jjf
Before:
After
- [Jira](https://jira.pinadmin.com/browse/GESTALT-3531)
> Table: Ensure tables are keyboard accessible

- docs/pages/iconbutton.js
Based on our Color guidance, I updated the background color section to better describe when to use which color.
Until we switch over to using token names, clarify when to use which color as the IconButton background, now follows teh color usage guidelines 
- [Jira](https://jira.pinadmin.com/browse/GESTALT-3530)
> IconButton: Clarify color documentation

- cypress/integration/accessibility_DeviceTypeProvider_spec.js
- docs/pages/devicetypeprovider.js
- packages/gestalt/src/contexts/DeviceTypeProvider.js
- packages/gestalt/src/index.js
This PR introduces a new component, DeviceTypeProvider. The associated docs page is skeletal for now, as this component is an alpha that may change. The docs page can be navigated to directly but has not yet been added to the sidebar index, so it is somewhat hidden for now. I will flesh out the rest of the docs page before this component officially launches.
We'd like to start offering device-specific UI for certain components, e.g. migrating Pinboard's MobileModal into Gestalt and rendering that UI for mobile devices. Using the same `'desktop' | 'mobile' | 'tablet'` device types as Pinboard, this context provider is the first step in this project, making device type available within components. Future work will add logic within components to use this device type.
I'm imagining this will …
> DeviceTypeProvider: add new component

- packages/gestalt/src/Masonry.js
Masonry is a list of items, but we don't present it as such semantically. That's not great for accessibility.
As best I can tell, there are three rendering scenarios for Masonry. In two of them, we render some form of a container with items. In the remaining one we render an empty container. For the first two, this PR adds `role="list"` to the main container, and `role="listitem"` to the individual Pin items. No changes were made to the empty container div, since (I think) it doesn't need a role.
> Masonry: add a11y roles

- docs/pages/whats_new.js
making sure our "What's New" page shows badges for all our packages:
> Docs: add npm badges for design token and eslint plugin packages

- docs/pages/whats_new.js
whoops — this PR allows the npm badges to wrap so they don't break mobile layouts:
> Docs: fix npm badges wrapping

- packages/gestalt/src/Flex.js
- packages/gestalt/src/FlexItem.js
- packages/gestalt/src/Toast.js
- packages/gestalt/src/__snapshots__/Toast.test.js.snap
This PR tweaks the layout of Toast to better accommodate long text + button text, which can lead to this visual bug:
_before_
_after, desktop_
_after, mobile_
(Note: wrap the Toast in Layer to get the width of the viewport rather than the doc section container, reflecting real world usage)
This does have the side effect of slightly increasing Toast width when the button is present, even if not strictly required by the text length:
Though these fixes aren't _ideal_, given the future messaging work, these are acceptable for now. The stress-test case (especially for mobile) doesn't look great, but it at least doesn't look buggy.
- [Jira](https://jira.pinadmin.com/browse/BUG-137320)
> Toast: fix layout bug with long text + button text

- packages/gestalt/src/Toast.js
The `text` type change from https://github.com/pinterest/gestalt/pull/1961 had unintended downstream effects in Pinboard's toast wrapper component, so this PR reverts that change.
> Toast: revert `text` type change

- docs/pages/box.js
- packages/gestalt/src/Box.js
- packages/gestalt/src/Colors.css
- packages/gestalt/src/Colors.css.flow
- packages/gestalt/src/boxTransforms.js
Add elevationAccent as a color option on Box
Now that we've added elevation options, we need to make that option available on Box as a background color (just the background elevation accent token)
Dark mode is coming soon
> Box: add elevation accent color option

- docs/pages/datapoint.js
A few grammar nits from recent Datapoint docs work, and reworking a couple of sections vis-a-vis numerical localization
> Datapoint: docs nits

- packages/gestalt/src/ActivationCard.js
- packages/gestalt/src/__snapshots__/ActivationCard.test.js.snap
Uses `Text` instead of `Heading` when rendering `ActivationCard`
* Using `Heading` results in an implicit accessibilityLevel to be set inside the `ActivationCard` component. That causes pinboard a11y tests to fail since we don't aren't able to override it from the outside.
* It doesn't make sense to use `Heading` since this is not describing a specific section on the page. It would make more sense to have `Heading` before the `ActivationCard` component.
* No visual differences
> ActivationCard: Use Text instead of Heading

- docs/components/PropTable.js
- docs/components/Toc.js
Now that we have updated Text colors that work in dark mode, I updated the TOC green to use the new color, and updated the required badges to use "warning"
With recently color updates that better support dark mode, this enhances our docs in dark mode
> Docs: Update navigation and badge colors

- packages/gestalt/src/ActivationCard.js
- packages/gestalt/src/__snapshots__/ActivationCard.test.js.snap
Follow up from #1980 - I only changed it for `CompletedCard`, not `UncompletedCard`
See #1980
> ActivationCard: Use Text instead of Heading for UncompletedCard

- packages/gestalt/src/Callout.js
- packages/gestalt/src/__snapshots__/Callout.test.js.snap
Use our new Text color for Callout to avoid the font color changing in dark mode
Previously the title and message of Callout were unreadable in dark mode. This updates the text color used to be one that does not change in dark mode, making the text readable
> Callout: Update text to be readable in dark mode

- docs/pages/text.js
- packages/gestalt/src/Text.js
Currently in Text, we populate the `title` attribute on the element if the text is truncated using `lineClamp`, making the full text visible on hover. However, we only do this when `children` is a not Node, otherwise the title would show `[object Object]`.
This PR adds an optional prop `title` to Text, so that the title attribute can be set manually during truncation if `children` is a Node (e.g. when using Link).
> Text: Add title prop

- packages/gestalt/src/Text.js
Flow is failing on CI due to recent `color` changes in Text, though I can't repro locally. This PR is an attempt to fix the Flow issue and also make the related logic a bit more readable.
> Text: rework color class logic to appease Flow

- packages/gestalt/src/ComboBox.js
- packages/gestalt/src/InternalTextField.js
- packages/gestalt/src/InternalTextFieldIconButton.js
- packages/gestalt/src/__snapshots__/ComboBox.jsdom.test.js.snap
In preparation for future work using the icon button available on InternalTextField, this PR extracts that markup to a standalone component. This alters the API of InternalTextField a bit, and moves some ComboBox-specific logic back into ComboBox.
> InternalTextFieldIconButton: create component from InternalTextField

- docs/pages/iconbutton.js
- packages/gestalt/src/IconButton.js
In some situations, particularly UIs with space constraints, it can make sense to use icon buttons for form submission. To enable this, this PR adds a `type` prop to IconButton (similar to Button's `type` prop).
> IconButton: add type prop

- packages/gestalt/src/contexts/ExperimentProvider.js
- packages/gestalt/src/index.js
[plan for experimentation in Gestalt](https://paper.dropbox.com/doc/Experimentation-in-Gestalt--BddgXa8eh85dBvzWzoUx3ki0Ag-SG2FCNEsklOe5lJ7gznTa)
tl;dr of that ⬆️ doc: we need a better way of running experiments on Gestalt components. Undocumented props (`_expProp`) aren't great.
This PR creates a new ExperimentProvider which I'll implement in Pinboard and start playing around with. Similar to DeviceTypeProvider, this is an alpha and the API may change considerably in the near future, so I'm leaving it undocumented for now. I'll add documentation when our story around experimentation in Gestalt components is a bit more solidified.
> ExperimentProvider: create new Context

- packages/gestalt/src/Text.js
Fixes a flaky flow issue on `Text`.
To unblock other developers
Flow doesn't understand the following line:
```
const colorName = semanticColors.includes(color) ? `${color}Text` : color;
```
even though `warning` is included in `semanticColors`, so the colorName would always be `warningText`, it still thinks `colorName` can be `warning`, which is not the case.
The fix is to manually remove `success` / `warning` / `subtle` / `light` / `error` / `dark` in the `if` check.
Ideally though, we should finish the migration and remove the literal colors
> Internal: Fix flaky flow issue on Text

- docs/pages/combobox.js
- docs/pages/fieldset.js
- docs/pages/selectlist.js
- packages/gestalt/src/SelectList.js
- packages/gestalt/src/SelectList.test.js
- packages/gestalt/src/__snapshots__/SelectList.test.js.snap
To help with accessibility, add the option to make the label of SelectList visually hidden
Sometime the thing that labels a SelectList is visually different from the default label style. This allows people to supply a label for screen readers, but make it visually hidden. 
> SelectList: Add option for hidden label

- docs/pages/numberfield.js
- docs/pages/textfield.js
As caught in [this issue](https://github.com/pinterest/gestalt/issues/1830), the way we handle parsing in NumberField doesn't support leading 0's, which are necessary for things like ZIP codes. This PR updates the docs for NumberField and TextField to make it more clear which should be used in a given situation.
> NumberField, TextField: update docs on usage

- docs/components/ColorTile.js
- docs/pages/color_palette.js
- docs/pages/color_usage.js
Add examples of our colors in dark mode on the Color Usage and Color Palette pages
Help designers and engineers understand how our color tokens change in dark mode 
- [Figma](https://www.figma.com/file/Lacd4Q9LkpX4KRqVOKLQnA/Color-usage?node-id=0%3A1)
> Color usage: Add dark mode examples

- docs/pages/development.js
- rfcs/README.md
- rfcs/template.md
Development: Added RFCS section and /RFCS folder with process
Gestalt needs a formal request for comment process as other design systems and packages have. Beyond the formal review process,  it will create a repository that will act as a source of institutional knowledge around Gestalt's decision process and development. New engineers will be able to go and read the decision behind some implementations and patterns found in the system.
**Thanks to the [Ember RFC process](https://github.com/emberjs/rfcs), [ESLint RFC Process](https://github.com/eslint/rfcs/), and [Spectrum RFC Process](https://github.com/adobe/react-spectrum/tree/main/rfcs) and the for the inspiration for Gestalt's RFC process.**
> Development: Added RFCs (request for comments) section and /RFCS folder with process

- docs/components/App.js
- docs/components/contexts/DocsExperimentProvider.js
- docs/components/contexts/DocsI18nProvider.js
- docs/pages/_app.js
- docs/pages/textfield.js
- packages/gestalt-datepicker/src/DatePicker.jsdom.test.js
- packages/gestalt/src/ComboBox.js
- packages/gestalt/src/InternalTextFieldIconButton.js
- packages/gestalt/src/TapArea.js
- packages/gestalt/src/TextField.js
- packages/gestalt/src/TextField.jsdom.test.js
- packages/gestalt/src/TextField.test.js
- packages/gestalt/src/Upsell.jsdom.test.js
- packages/gestalt/src/Upsell.test.js
- packages/gestalt/src/UpsellForm.test.js
- packages/gestalt/src/contexts/ExperimentProvider.js
- packages/gestalt/src/contexts/I18nProvider.js
- packages/gestalt/src/contexts/__mocks__/I18nProvider.js
Currently TextField doesn't give users any way of viewing what they've typed so far when `type="password"`. This is a frustrating UX and is likely leading to failed logins. This PR adds an experimental "show/hide password" button to solve this problem.
> TextField: Add experimental show/hide password button

- .prettierrc.json
Prettier has been complaining about this since the most recent upgrade:
```
[warn] jsxBracketSameLine is deprecated.
```
This PR removes that option from our `.prettierrc.json`.
> Internal: remove deprecated Prettier option

- packages/gestalt/src/contexts/I18nProvider.js
- packages/gestalt/src/contexts/I18nProvider.jsdom.test.js
While the previous approach worked fine in the product, I was unable to successfully mock the implemented provider (with translations) unless included in the `render`/`shallow` call in each component using TextField, or whose children use TextField. That's impractical for now and unreasonable for the future (every component with a string in I18nProvider would have to have such a mock), so I'm backing off throwing errors for missing translations for now. We can perhaps revisit in the future but it's not worth blocking our merge/bump pipeline for this.
Also, after discussions with @jennyscript, I warmed to the idea of providing default English strings within Gestalt. This replicates the behavior of Pinboard's i18n function, so it's not actually different from behavior on non-Gestalt …
> I18nProvider: provide default strings, downgrade throwing errors to console

- docs/components/sidebarIndex.js
it looks like Icon was unintentionally removed as part of #2008 😬
> Icon: add back to sidebar index

- packages/gestalt/src/TextField.js
_sigh_ this is why initializing a state variable with a prop value is dangerous 😬 
This PR adds a useEffect to keep the value of the state variable updated when the prop value changes.
> TextField: fix stale type value when passed dynamically

- cypress.json
We've been seeing issues with visual diff snapshot tests timing out and failing randomly. This PR bumps the timeout threshold from 30000 to 50000 in hopes of fixing the issue. (Future work should address why these tests take so damn long in the first place)
> Internal: increase Cypress timeout threshold

- docs/components/Header.js
- docs/pages/box.js
- docs/pages/elevation.js
- packages/gestalt/src/Borders.css
- packages/gestalt/src/Borders.css.flow
- packages/gestalt/src/Box.js
- packages/gestalt/src/Box.test.js
- packages/gestalt/src/__snapshots__/Box.test.js.snap
- packages/gestalt/src/boxTransforms.js
- packages/gestalt/src/boxTypes.js
after adding 2 new ways to show elevated items, a raised top or raised bottom shadow, this PR adds those options to Box
We have a full shadow option in Box, and now this adds two new options to showcase raised headers or footers with a corresponding top or bottom box-shadow. We discussed as a group and found that leaving these on borderStyle for now is an ideal way to move forward, so that we prevent users trying to add both a solid pixel border and a shadow.
> Box: Add new raised shadow options to borderStyle

- packages/gestalt/src/TextField.js
We're showing the exp treatment too much:
_Scenario A_
User is 'enabled' in desktop experiment, not in mweb experiment at all. User views mweb app. Though not activated into the experiment (won't be counted), user sees experimental treatment. Not good. 😕 
_Scenario B_
User is 'enabled' in desktop experiment, 'control' in mweb experiment. User views mweb app. User is now counted with the 'control' group *while seeing the experimental treatment*. Very not good! 😬 
This PR adds a device type check to make sure that the experimental treatment is only shown to users enabled in that device's experiment. (I still need to implement that Provider in Pinboard)
> TextField: use device type in exp checks

- docs/pages/iconography_and_svgs.js
Fixes the flaky flow issue without using a `.map` as we did in #2025
> Internal: Fix flow issue without .map() in Iconography and SVGs docs

- packages/gestalt/src/Contents.js
- packages/gestalt/src/__snapshots__/Controller.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/Dropdown.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/Popover.jsdom.test.js.snap
Remove caret stroke style as it's not needed anymore (PRs that introduced code https://github.com/pinterest/gestalt/pull/1017, https://github.com/pinterest/gestalt/pull/1081)
The previous stroke color logic was overriding strokes in SVGs contained within Popover as seeing here which was causing bugs in Dropdown containing avatars without image.
> Popover: remove unused caret stroke style

- docs/pages/heading.js
- packages/gestalt/src/Heading.js
- packages/gestalt/src/__snapshots__/Heading.test.js.snap
- packages/gestalt/src/__snapshots__/PageHeader.test.js.snap
- packages/gestalt/src/__snapshots__/Sheet.jsdom.test.js.snap
- packages/gestalt/src/textTypes.js
Remove old colors from Heading, switch to new semantic colors.
Align with design tokens and avoid arbitrary color usage
To make any conversions using our codemods, run 
`yarn codemod modifyPropValue [path-to-files] --component=Heading --previousProp=color --previousValue=[value to replace] --nextValue=[new value]`
Typically, conversions are as follows:
| Old | New |
|---|--|
|red| error|
|darkGray| default|
|white | inverse|
|gray | subtle|
|blue/navy/etc. | shopping, if shopping related|
| white on dark backgrounds | light |
| darkGray on light backgrounds | dark |
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4063)
> Heading: Deprecate old color options, add new semantic colors

- packages/gestalt-datepicker/src/DatePicker.js
Added useEffect to update date value if programatically changes.
To programmatically change the value prop used to supply [pre-selected dates to the datepicker](https://gestalt.netlify.app/datepicker#preselectedValue). The actual displayed value on the datepicker does not appear to change with the variable given to the value prop.
NOTE: This is a quick fix. Ideally, we would rewrite DatePicker to be fully controlled rather than have internal state. This fix works well, but the nicer/more elegant fix would require going to all DatePickers and implementing the logic from the onChange to control the Datepicker value.
This is a fix for the current component state, which we know we have to sit down and reevaluate.
Repro  https://codesandbox.io/s/datepicker-preselected-date-change-forked-djdm48 …
> Datepicker: fix controlled state [bug]

- packages/gestalt-datepicker/package.json
- packages/gestalt/package.json
Updates the react/react-dom peer dependencies for gestalt and gestalt-datepicker  to support 18.x.  We currently aren't leveraging any React 18 specific APIs so this change is safe.  In the future, if we start using some of the React 18 APIs, we'll need to think about backwards compatibility or dropping support for older versions of React.  
Note: this does not update the React version for docs.
> Internal: Bump peer dependencies to support React 18

- packages/gestalt-datepicker/src/DatePicker.js
Datepicker: fix useEffect side effect (misusing cleanup side effect)
We’re passing useEffect a function that returns the setter call, which is a bit odd. The syntax for useEffect:
```
useEffect(() => {
// do some stuff
return () => {
// clean up stuff
};
}, [dependencies]);
```
[react Docs info
](https://user-images.githubusercontent.com/10593890/164085712-61419522-a1ed-44d1-b30f-897b9b4f2e49.png)
So returning the setter is a bit odd, and it could potentially lead to subtle bugs in the future. Some curlies will prevent the return:
`useEffect(() => { setSelected(...); }, [...]);
`
> Datepicker: fix useEffect side effect

- docs/pages/tooltip.js
- packages/gestalt/src/Tooltip.js
Added a note at the top of the Tooltip doc and added a bullet point in the Don't's Best Practices section.
> Docs: Tooltip / IconButton usage guidance

- docs/pages/icon.js
- packages/gestalt-design-tokens/tokens/color/alias.json
- packages/gestalt/src/Colors.css
- packages/gestalt/src/Colors.css.flow
- packages/gestalt/src/Icon.js
We often use Icon to represent the Pinterest logo. In these cases, the color option should be set to 'brandPrimary'
Avoid using 'error' to represent the brand color, avoid confusion around color usage
> Icon: Add brandPrimary color option

- docs/pages/video.js
- docs/pages/visual-test/Video.js
- packages/gestalt/src/Video.flowtest.js
- packages/gestalt/src/Video.js
- packages/gestalt/src/Video.jsdom.test.js
- packages/gestalt/src/Video.test.js
- packages/gestalt/src/__snapshots__/Video.test.js.snap
- scripts/setupJest.js
**1. Handle HTMLMediaElement.play() Promise rejection and autoplay blocking**
Implemented try, catch statement around HTMLMediaElement.play() method within Gestalt's Video component to catch Promise rejection and consequent associated errors. Implemented `onPlayError` prop (callback) which gets called when HTMLMediaElement.play()'s Promise is rejected.
To learn more, see [HTMLMediaElement.play()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play) and [exceptions](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play#exceptions)
As a consequence of adding the first async/await in our components (within Video), I started getting the error  `ReferenceError: regeneratorRuntime is not defined Babel 6` while  running tests. To get it fixed, we are adding …
> Video: handle HTMLMediaElement.play() Promise rejection and autoplay blocking, and API improvements

- docs/pages/video.js
- packages/gestalt/src/Video.js
Video: fix on Flow type
The Flowtype provided doesn't match the actual Flowtype for ref in Classes. Moving ref type signature to a manual definition.
> Video: fix on Flow type

- docs/pages/searchfield.js
- docs/pages/textarea.js
- docs/pages/textfield.js
- packages/gestalt/src/SearchField.js
- packages/gestalt/src/TextArea.js
- packages/gestalt/src/TextField.js
In order to make the `label` prop required, we need to provide a `labelDisplay` drop for toggling visibility. This work includes adding the prop to each component and providing documentation updates to each component.
> TextField & TextArea: Added labelDisplay prop

- packages/gestalt/src/TextArea.js
labelDisplay prop was missing the "visible" default value.
> TextArea: Added default value to labelDisplay prop

- packages/gestalt/src/Masonry.js
This PR fixes an issue where we are unable to hydrate a server-rendered flexible grid.
At the moment, when `Masonry` hydrates from a server render it attaches a callbackRef to each of the items being rendered so it can measure each element's heights.  It does this so that in the next pass, it can properly infer the layout from these measurements.
For _flexible_ grids, we don't store the element heights during this initial pass because the assumption is that the height will be incorrect since the server does not have enough information to properly layout a flexible grid.  What this ends up causing is that all the grid items are _removed_ during the second render pass because we don't have any measurements to lay out the grid.  
What this ends up looking like from a user perspective: …
> Masonry: Fix hydration for server rendered flexible grids

- docs/pages/about_us.js
- docs/pages/accessibility.js
- docs/pages/how_to_work_with_us.js
Pinched some links and fixed a typo in the How to work with us page
> Docs: Typo fixes and link shortening

- packages/gestalt-datepicker/src/DatePicker.js
- packages/gestalt-datepicker/src/DatePickerTextField.js
- packages/gestalt/src/Sheet.js
Adding `name` prop which gets passed to the internal TextField component used by DatePicker.
To keep consistent pattern across form fields and enable the consistent use of form-related API such as [formData](https://developer.mozilla.org/en-US/docs/Web/API/FormData)
> DatePicker: add `name` prop

- packages/gestalt/src/Avatar.js
- packages/gestalt/src/__snapshots__/Avatar.test.js.snap
- packages/gestalt/src/__snapshots__/AvatarGroup.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/AvatarPair.test.js.snap
Add a default data test id to allow exclusion of Avatars from contrast checker 
Because we rely on SVG for avatar initials, the aXe contrast checker complains about a lack of content to determine if it is text or not when checking for contrast. Adding this id allows us to exclude Avatars from this check.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4197)
> Avatar: Add data test id for testing

- docs/pages/link.js
- packages/gestalt/src/Link.js
- packages/gestalt/src/Link.test.js
- packages/gestalt/src/__snapshots__/Link.test.js.snap
Link: remove `role` and `accessibilitySelected` props
Both `role` and `accessibilitySelected` props were deprecated and unused
Run codemod to detect instances of prop usage
`yarn codemod detectManualReplacement  ~/path/to/your/code --component=Link --prop=role`
`yarn codemod detectManualReplacement  ~/path/to/your/code --component=Link --prop= accessibilitySelected `
> Link: remove `role` and `accessibilitySelected` props

- docs/pages/icon.js
- packages/gestalt-design-tokens/tokens/color/alias.json
- packages/gestalt/src/Colors.css
- packages/gestalt/src/Colors.css.flow
- packages/gestalt/src/Icon.js
- packages/gestalt/src/__snapshots__/Video.test.js.snap
- packages/gestalt/src/contexts/ColorSchemeProvider.jsdom.test.js
Add option to create info icons (used in Callout, Banner etc.) to avoid contamination with Shopping option
Create separation so we can make updates to either in the future
> Icon: Add info color option

- docs/pages/scrollboundarycontainer.js
- packages/gestalt/src/Contents.js
- packages/gestalt/src/__snapshots__/Controller.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/Dropdown.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/Popover.jsdom.test.js.snap
> Tooltip: minor refactor

- packages/gestalt/src/ComboBox.js
ComboBox: add zIndex prop
Follow pattern supported in other components such as Dropdown
Prevent issues like https://codesandbox.io/s/compassionate-field-32f0oy?file=/example.js
> ComboBox: add zIndex prop

- packages/gestalt/src/Datapoint.js
[context from Slack](https://pinterest.slack.com/archives/C13KLG5P0/p1652206272829709)
It should be no surprise that the same issues that caused us to add `zIndex` to Tooltip mean that we'll need to be able to set that prop where we integrate tooltip into other components, like Datapoint. This PR adds a prop to Datapoint to do just that. (We'll likely need to do the same for IconButton and any other places we integrate Tooltip into other components)
> Datapoint: add prop to set z-index on integrated tooltip

- docs/pages/eslint_plugin.js
- packages/eslint-plugin-gestalt/README.md
- packages/eslint-plugin-gestalt/src/__fixtures__/button-icon-restrictions/invalid/invalid-no-color.js
- packages/eslint-plugin-gestalt/src/__fixtures__/button-icon-restrictions/invalid/invalid-no-size.js
- packages/eslint-plugin-gestalt/src/__fixtures__/button-icon-restrictions/invalid/invalid-renamed.js
- packages/eslint-plugin-gestalt/src/__fixtures__/button-icon-restrictions/invalid/invalid-wrong-color.js
- packages/eslint-plugin-gestalt/src/__fixtures__/button-icon-restrictions/invalid/invalid-wrong-size.js
- packages/eslint-plugin-gestalt/src/button-icon-restrictions.js
- packages/eslint-plugin-gestalt/src/button-icon-restrictions.test.js
Update our guidance to allow any color or size for Buttons with iconEnd="arrow-down"
We no longer have restrictions on the color or size when arrow-down is used
> Eslint: Allow iconEnd buttons to be any color or size

- .eslintrc.json
- cypress/integration/page_header_spec.js
- docs/components/handleCodeSandbox.js
- docs/package.json
- package.json
- packages/gestalt/src/__snapshots__/Avatar.test.js.snap
- packages/gestalt/src/__snapshots__/FormErrorMessage.test.js.snap
- yarn.lock
This PR upgrades Gestalt and the docs site to use React 18. The only change to use any React 18 APIs is in the CodeSandbox handler, where `render` is replaced with `createRoot`. Since no other changes are made (yet), this should continue to be fully backwards-compatible with React 17.
I'm marking this as a `major` change, but don't expect there to be any real breaking changes.
This also introduces some console spam on unit test runs, which I'll address by upgrading a few packages in a follow-up PR.
> Internal: upgrade to React 18

- docs/pages/installation.js
- packages/gestalt-datepicker/src/DatePicker.js
Adds a note to the documentation page for `DatePicker` that this component is installed from a separate package
Update the `Installation` page of the documentation for installation of the DatePicker package
Updated documentation to note that installation of datepicker is separate from the installation of the main gestalt package
It is not immediately clear from the documentation that DatePicker is in a separate package and must be installed separately. This information is noted in the README.md of the repo and appear on the github homepage
> DatePicker: Add note about installing as a separate package

- docs/components/PageHeader.js
- docs/pages/radiobutton.js
- docs/pages/tooltip.js
- packages/gestalt/src/RadioButton.js
- packages/gestalt/src/Tooltip.js
- scripts/generateMetadata.js
Docs: adding slimBanner prop into Docs' PageHeader to display information related to the component. 
##BEFORE
##AFTER
New comms pattern re components
> Docs: adding slimBanner prop into Docs' PageHeader to display information related to the component. 

- docs/pages/_document.js
Adding the Pinterest HTML tag to the 
Adding Pinterest HTML tag to connect the Gestalt Pinterest account  on Pinterest to the https://gestalt.pinterest.systems/ so we can officially claim it.
https://user-images.githubusercontent.com/50343812/171476588-5a994f80-9e90-4b22-9050-c46e15b2051c.png
> Internal: Add Pinterest metadata tag to connect Gestalt Pinterest account w/ Gestalt site

- docs/components/PageHeader.js
- docs/pages/BlogPosts.json
- docs/pages/radiobutton.js
- docs/pages/whats_new.js
Update the What's New page to become a blog page for recent updates
Have a single source of truth to host weekly digests of updates, allowing designers and engineers to find information easily and predictably.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4376)
> Docs: Revamp What's New page into our blog

- packages/gestalt-design-tokens/build.js
- packages/gestalt-design-tokens/config.json
Add an output for Android to support dark-mode colors 
Ensure there's a single file that has every color and the value it should use in dark mode
> Design Tokens: Update android output files

- packages/gestalt/src/Card.js
Card's `active` prop is intended to force the active state of the component. However, it currently can only be used to force the active state "on"; because of the way the logic is rewritten, attempting to force "off" falls through to continue using the hover state.
This PR fixes that logic to always respect the `active` value if passed.
> Card: fix `active` logic to support `false`

- docs/components/CombinationNew.js
- docs/components/MainSectionCard.js
- docs/pages/datapoint.js
- docs/pages/numberfield.js
- docs/pages/status.js
Small cleanups to adjust layout for Best Practices and shade colors for combination color examples
Try to provide an ideal background color when showcasing color example of a component using CombinationNew
> Docs: Cleanup layout and shaded color examples

- packages/gestalt/src/InternalTextField.css
Remove unnecessary spacing from "spacer" div
Align spacing with Textarea and TextField so forms look consistent
> ComboBox: Fix spacing with Tags

- docs/components/ColorPalette.js
- docs/components/TokenExample.js
- docs/pages/box.js
- docs/pages/color_palette.js
- docs/pages/data_visualization_colors.js
- docs/pages/data_visualization_guidelines.js
- docs/pages/design_tokens.js
- docs/pages/how_to_hack_around_gestalt.js
Add multiple links across tokens and color guideline pages to try and add context wherever needed. Also updated "hackign Box" example to use a design token.
As folks start implementing Data Viz colors and design tokens, we want to ensure the best practices and information are easily consumable.
> Design Tokens: Add cross-linking to various pages

- packages/gestalt/src/PageHeader.js
- packages/gestalt/src/PageHeaderComponents.js
the onClick prop of the helperLink prop was unnecessarily required (it's not required on Link), so this switches it to be optional
Avoid unnecessarily strict flow types if onClick is not needed for the link
> PageHeader: Make onClick for helperLink optional

- docs/components/COMPONENT_DATA.js
- docs/pages/table.js
- packages/gestalt/src/TableSortableHeaderCell.js
Current behavior isn't great when de-selecting a sortable header, with the arrow icon lingering due to the header cell having focus after being clicked:
https://user-images.githubusercontent.com/12059539/176942403-ead225fa-e627-4aad-81d3-5c8f5a539792.mov
This PR doesn't adjust the actual focus of the cell, but removes the focus UI state just after click.
> Table: update sortable header cell behavior

- packages/gestalt/src/TableSortableHeaderCell.js
The previous version of this change was too specific, potentially yielding this error if the event had no args:
```
TypeError: Cannot destructure property 'event' of 'undefined' as it is undefined.
```
This PR makes the handler adapt to whatever args it's given.
> Table: fix sortable header cell args bug

- .eslintrc.json
- docs/pages/masonry.js
- packages/gestalt-codemods/59.0.0/masonry-update-flexible-prop.js
- packages/gestalt-codemods/59.0.0/masonry-update-flexible-prop.test.js
- packages/gestalt/src/Masonry.js
Removes the `flexible` boolean prop from Masonry.
Consistency: `layout="flexible"` and `flexible` props do the same thing, so it's confusing what prop to use when
<details>
<summary>Why not use <code>packages/gestalt-codemods/generic-codemods/modifyPropValue.js</code> ?</summary>
We need to throw when the `flexible` prop is set on a layout other than the default, `flexible` or `serverRenderedFlexible`.
</details>
> Masonry: remove boolean flexible prop (Breaking change)

- docs/pages/masonry.js
- packages/gestalt/src/Masonry.js
- packages/gestalt/src/index.js
- packages/gestalt/src/layouts/MasonryLayout.js
- packages/gestalt/src/layouts/UniformRowLayout.js
- packages/gestalt/src/legacyLayoutSymbols.js
1 way to specify masonry layouts: string enums
Masonry has 3 different ways to specify layouts:
1. As a string enum: `'basic' | 'basicCentered' | 'flexible' | 'serverRenderedFlexible' | 'uniformRow'`
2. As a class: `LegacyMasonryLayout | LegacyUniformRowLayout`
3. As a symbol: `typeof DefaultLayoutSymbol | typeof UniformRowLayoutSymbol`
These 3 different ways are confusing and we should stick to 1
In https://github.com/pinterest/gestalt/pull/782 we introduced the option to specify masonry layouts as strings but never completed the conversion:
> Because extra exports are annoying and we already split on what to use, I'd like to update to one true system: strings.
- https://phabricator.pinadmin.com/D906449 - Replaces all deprecated layouts in pinboard/webapp
- #2175 - Replaces `flexible` …
> Masonry: remove deprecated layouts

- docs/components/ExampleCode.js
- docs/components/MainSectionCard.js
- docs/components/PageHeader.js
- docs/components/PageHeaderQualitySummary.js
- docs/components/QualityChecklist.js
- docs/pages/activationcard.js
- docs/pages/avatargroup.js
- docs/pages/badge.js
- docs/pages/button.js
- docs/pages/callout.js
- docs/pages/datepicker.js
- docs/pages/dropdown.js
- docs/pages/fieldset.js
- docs/pages/link.js
- docs/pages/modal.js
- docs/pages/pog.js
- docs/pages/pulsar.js
- docs/pages/radiogroup.js
- docs/pages/selectlist.js
- docs/pages/sheet.js
- docs/pages/switch.js
- docs/pages/tabs.js
- docs/pages/textarea.js
- docs/pages/toast.js
- docs/pages/tooltip.js
- docs/pages/upsell.js
Added the ability to see the code for our top-most header examples on component pages
Also added a way to see the code for Best Practice Do's
Make it easier to see the code behind our examples and learn what to do for best practices
Header Before:
Header After:
Best Practices Before:
Best Practices After:
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4579) and [Jira](https://jira.pinadmin.com/browse/GESTALT-4580)
> Docs: Show code for top example and Do's

- docs/components/DocSearch.js
- docs/components/Header.js
- docs/docs.css
Introduce new top level navigation for key pages
Add top level navigation on desktop web. mWeb implementation will be added in part 2
Also consolidates search at smaller screen widths
- [Figma](https://www.figma.com/file/emykswARRS1tQwpB7ThIPN/Gestalt-2022-Site?node-id=879%3A17764)
> Docs: New top navigation

- packages/gestalt/src/Masonry.js
- packages/gestalt/src/defaultLayout.js
- packages/gestalt/src/fullWidthLayout.js
Fixes 3 flow fixme's and 2 ESLint disables related to `Position` in `Masonry`. These changes are internal only
> Masonry: Fix internal only flow issues

- docs/components/PropTable.js
- docs/components/QualityChecklist.js
- packages/gestalt/src/TableHeader.js
* Add `display` prop to `Table.Header`
* Fix hydration issues on every page which used the `QualityChecklist` component
* Fix `Warning: Expected server HTML to contain a matching <table> in <div>.`
The `QualityChecklist` component renders a `<div />` as a direct descendant of `<thead />` which is not allowed:
It results in the follow hydration error:
* Clone the repro
* Go to `/modal` (or any other page with a `QualityChecklist` component
* Reload the page
* Bug was introduced in #2114 /cc @AlbertCarreras 
* Instead we could wrap `<Text />` in `<Box display="visuallyHidden" />` but that results in unnecessary space and an extra border
> Table.Header: add 'display' prop

- docs/components/Card.js
The height of the top nav increase but we never updated the scroll margin top for the heading.
To repo, go to https://gestalt.pinterest.systems/buttongroup#Props
> Docs: fix heading scroll position

- docs/components/AppLayout.js
The sidebar border should reach the bottom of the page.
> Docs: sidebar border should reach bottom

- docs/pages/box.js
Fix bug in one of the `Box` examples.
Error:
```
Warning: Received `true` for a non-boolean attribute `wsz`.
If you want to write it to the DOM, pass a string instead: wsz="true" or wsz={value.toString()}.
at div
at Box (webpack-internal:///../packages/gestalt/dist/gestalt.es.js:1575:3)
at div
```
#2187 /cc @EduhCosta
By flow typing our doc examples and using Sandpack - #2221
> Docs: fix received 'true' for a non-boolean attribute 'wsz'

- docs/components/buttons/SidebarCategorizationButton.js
Group sidebar radio button toggles.
Revert of a change done in https://github.com/pinterest/gestalt/pull/2185 /cc @AlbertCarreras 
Radio buttons which belong together should have the same `name`:
> [Defining a radio group](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio#defining_a_radio_group)
> A radio group is defined by giving each of radio buttons in the group the same [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-name).
**Repro**
1) Tab to the category radio button
2) Hit the right or left arrow key
**Expected**
Toggle between `Category` and `Alphabetical`
> Docs: group sidebar toggles

- docs/components/ResourcesFooter.js
Fix the `Web repository` link
Previously this link went to a specific PR instead of the main Gestalt repository
https://github.com/pinterest/gestalt/pull/2163
> Docs: fix web repository link

- docs/components/App.js
- docs/components/SandpackExample.js
- docs/components/contexts/LocalFilesProvider.js
- docs/pages/_app.js
- docs/pages/api/localFiles.js
- docs/pages/development.js
- flow-typed/npm/next_v10.x.x.js
Follow up from #2221 - we add the ability to use local Gestalt JS & CSS files instead of the latest Gestalt.
When developing locally, you want to use the Gestalt version which has your local changes, not the latest Gestalt release.
**Why do we not always use the local files?**
This is significantly slower since we
1) load the local JS & CSS through a Next.js API route
2) have to send the local JS & CSS to CodeSandbox
So it's useful when coding locally but we shouldn't use it in other cases.
**How do I use the local Gestalt CSS & JS files?**
Add `localFiles=true` to your URL:
http://localhost:8888/modal?localFiles=true
**Why do you use Next.js page data and not /api routes?**
With page data, the file reads & request only happen once per page load. If we use `/api` routes, we would get …
> Internal: add ability to use local Gestalt CSS & JS files

- docs/components/Combination.js
- docs/components/GeneratedPropTable.js
- docs/components/PropTable.js
- packages/gestalt-datepicker/src/DatePicker.js
This PR cleans up the way we suppress Flow errors to use `// $FlowFixMe` everywhere, as well as some other random cleanup
> Internal: replace flow-lint suppressions with FlowFixMe

- docs/pages/eslint_plugin.js
- packages/eslint-plugin-gestalt/src/__fixtures__/no-workflow-status-icon/invalid/default-size.js
- packages/eslint-plugin-gestalt/src/__fixtures__/no-workflow-status-icon/invalid/match-properties.js
- packages/eslint-plugin-gestalt/src/__fixtures__/no-workflow-status-icon/invalid/renamed-icon.js
- packages/eslint-plugin-gestalt/src/__fixtures__/no-workflow-status-icon/valid/no-match-color.js
- packages/eslint-plugin-gestalt/src/__fixtures__/no-workflow-status-icon/valid/no-match-icon.js
- packages/eslint-plugin-gestalt/src/__fixtures__/no-workflow-status-icon/valid/no-match-size.js
- packages/eslint-plugin-gestalt/src/__fixtures__/no-workflow-status-icon/valid/renamed-icon.js
- packages/eslint-plugin-gestalt/src/index.js
- packages/eslint-plugin-gestalt/src/no-workflow-status-icon.js
- packages/eslint-plugin-gestalt/src/no-workflow-status-icon.test.js
Add a new rule to avoid the following cases on Icon component:
| Implementations disallowed by rule |
| - |
| \<Icon icon="workflow-status-warning" color="warning" /\> |
| \<Icon icon="workflow-status-warning" color="warning"  size={16} /\> |
| \<Icon icon="workflow-status-problem" color="error" /> |
| \<Icon icon="workflow-status-problem" color="error"  size={16} /\> |
| \<Icon icon="workflow-status-ok" color="success" /\> |
| \<Icon icon="workflow-status-ok" color="success"  size={16} \> |
| \<Icon icon="workflow-status-in-progress" color="success" /\> |
| \<Icon icon="workflow-status-in-progress" color="success"  size={16} /\> |
The current good practice is use the [Status Component](https://gestalt.pinterest.systems/status) rather than the previous one list. Like the table bellow:
| …
> Eslint plugin: Avoid "workflow-status-[..]" on Icon

- docs/pages/collage.js
Fix an issue where the collage page was making requests to `/undefined`
It results in multiple calls to `GestaltApp.getInitialProps` which render the `/_error` page
#1662 /cc @dangerismycat
In that PR we fall back to `{}` for `image`, however that is truthy while before it was `undefined` which is falsy
```js
const image = images[index];
// Works as expected
if (image) {
```
```js
// Fails
const image = images[index] || {};
if (image) {
```
> Docs: Fix /_error renders on collage page

- package.json
- yarn.lock
We no longer use `cacache`, so we can remove it from our `resolutions`.
Unused dependencies:
* create a maintenance burden for the team
* result in an increase of the `node_modules` directory
> Internal: remove unused cacache dependency

- .eslintrc.json
- package.json
- yarn.lock
This PR adds a new lint rule from [this package](https://github.com/MananTank/eslint-plugin-validate-jsx-nesting), checking to make sure we don't have invalid nested JSX (e.g. `<p>` within `<p>`). We don't have any errors currently, so this is more about preventing future errors.
> Internal: add eslint-plugin-validate-jsx-nesting

- docs/examples/accessibility/useFocusVisibleExample.js
- docs/examples/accessibility/useReducedMotionExample.js
- docs/pages/foundations/accessibility.js
* Converts https://gestalt.pinterest.systems/foundations/accessibility examples to use Sandpack.
More context in #2221 
Issues found in this diff:
* Lint error: Missing an explicit type attribute for button `eslintreact/button-has-type`
* Broken example: We were still using `color="red"` on `<Box />` which resulted in a broken `useReducedMotion` example.
> Docs: convert accessibility page to Sandpack & fix useReducedMotion example

- docs/examples/sidenavigation/mobileExample.js
- docs/pages/_app.js
- packages/gestalt/src/SideNavigation.js
- packages/gestalt/src/SideNavigationGroup.js
- packages/gestalt/src/SideNavigationGroupContent.js
- packages/gestalt/src/SideNavigationTopItem.js
- packages/gestalt/src/contexts/DeviceTypeProvider.js
The type changing of `DeviceTypes` type would be a major change and was marked as a minor one. When the bumping happening the modification freezing the bumping and made a sensible diff.
The word `phone` is used to identify mobile devices.
Create a big complexity to bumping a minor version of gestalt on pinboard.
> DeviceTypeProvider: Rollback to use `phone` to identify mobile devices

- docs/docs-components/SandpackExample.js
- docs/pages/foundations/accessibility.js
- docs/pages/web/modal.js
- docs/pages/web/pageheader.js
- docs/pages/web/sheet.js
- docs/pages/web/sidenavigation.js
Docs: adjustments to Sandpack code containers
Set default props for Sandpack containers
Variants and all examples except Best practices are open in SideNavigation, PageHeader, Sheet, and Modal
> Docs: adjustments to Sandpack code containers

- docs/pages/web/collage.js
This fixes a bug that was introduced in #2236. Apparently the code editor can't handle optional chaining, so this PR removes it:
> Docs: fix Collage bug

- docs/pages/foundations/color/palette.js
Fixed a link to https://uxdesign.cc/design-tokens-cheatsheet-927fc1404099
> Docs: Fixed broken link in color palette page

- .eslintrc.json
- flow-typed/npm/jest_v26.x.x.js
- package.json
- packages/gestalt-codemods/34.0.0/__tests__/toast-replace-color-variant.test.js
- packages/gestalt-codemods/45.0.0/__tests__/rename-popover-handleKeyDown-to-onKeyDown.test.js
- packages/gestalt-codemods/future-typo-changes/__tests__/replace-typography-sizes.test.js
- packages/gestalt-datepicker/src/DatePicker.jsdom.test.js
- packages/gestalt/src/NumberField.jsdom.test.js
- packages/gestalt/src/TextField.jsdom.test.js
- packages/gestalt/src/contexts/I18nProvider.jsdom.test.js
- scripts/setupJest.js
- yarn.lock
We disallow `console.*` calls such as `console.log` / `console.error` and `console.warn` in our jest tests.
* Clean output when you run tests. No random console message when running the tests
* Find issues: deprecated or incorrect React testing usage / invalid examples
* Make `console.*` calls explicit, so it's intentional & clear when we use them (E.g. codemod runs)
* `Error: Uncaught [Error: Foo translations not available — please add translations to I18nProvider] `
* `Warning: toHaveDescription has been deprecated and will be removed in future updates. Please use toHaveAccessibleDescription.`
* `Warning: An update to InnerPopper inside a test was not wrapped in act(…).`
* Now, if we do find a `console.*` which we can't get rid off, we should mock the `console.*` call. There are a few …
> Internal: disallow console.* calls in tests

- docs/docs-components/SandpackExample.js
- docs/examples/colors/alternativeColorTextExample.js
- docs/examples/colors/alternativeColorTokensExample.js
- docs/examples/colors/alternativeColorsExample.js
- docs/examples/colors/appropriateColorTokensExample.js
- docs/examples/colors/communicateStatusExample.js
- docs/examples/colors/distinctionExample.js
- docs/examples/colors/establishedExample.js
- docs/examples/colors/extendedColorsExample.js
- docs/examples/colors/invalidElevationExample.js
- docs/examples/colors/repurposeExample.js
- docs/examples/colors/soleIndicatorExample.js
- docs/examples/colors/validElevationExample.js
- docs/examples/layouts/layoutsExample.js
- docs/examples/screenSizes/screenSizesAndroid.js
- docs/examples/screenSizes/screenSizesIos.js
- docs/examples/screenSizes/screenSizesWeb.js
- docs/pages/foundations/color/examples.js
- docs/pages/foundations/layouts.js
- docs/pages/foundations/screen_sizes.js
- docs/pages/web/modal.js
- docs/pages/web/pageheader.js
- docs/pages/web/sheet.js
- docs/pages/web/sidenavigation.js
* Converts multiple "foundation" page examples to Sandpack
* Convert `hideControls` prop to `showControls` => makes it consistent with the `showEditor` prop on `SandpackExample`
* Remove t-shirt sizes `sm` and `md` from `SandpackExample`
For more context see #2221 
Flow issues found in this diff:
```
* Cannot create `Table` element because property `accessibilityLabel` is missing in  props [1] but exists in  `Props` [2].Flow(prop-missing)
* Cannot create `Badge` element because property `inline` is missing in  `Props` [1] but exists in  props [2].Flow(prop-missing)
* Cannot create `Image` element because  string [1] is incompatible with  number [2] in property `naturalWidth`.
* Cannot create `TapArea` element because: Either property `color` is missing in  `TapAreaType` [1] but exists in …
```
> Docs: convert multiple "foundation" page examples to Sandpack

- docs/pages/web/heading.js
- packages/gestalt/src/Heading.js
Removing unused prop `justify` of `Heading` component;
The following codemod help you to do the follow table replacement.
To modifyPropValue, please, use
```bash
yarn codemod modifyPropValue ~/path/to/your/code
--component=Heading
--previousProp=align
--previousValue=justify
```
To detect manual changes use
```bash
--component=Heading
--prop=align
--value=justify
```
The value was removed of main file and code;
The value is not used and the design suggest your delete;
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4508)
> Heading: Removing justify value prop

- docs/pages/web/masonry.js
Fixes an issue where we saw the following the docs
```
~~~jsx
~~~Pcard
```
Issue was introduced at https://github.com/pinterest/gestalt/pull/2114/files#diff-3c424fdcf1b7cc45413983af04f026e91c1637527ca1d8c9cd0b74b05fb35054R220
> Docs: fix incorrect code wrapping on Masonry docs

- docs/pages/web/callout.js
- packages/gestalt/src/Callout.js
Add two new variants to Callout:
_success_
_recommendation_
> Callout: add "success", "recommendation" variants

- docs/docs-components/DocSearch.js
- docs/docs-components/Header.js
- docs/docs-components/z-indices.js
This PR improves keyboard interactions for the docs search bar:
- `/` now works to open the search bar even when using the compressed UI, e.g. the icon button
- `esc` blurs the search bar and collapses to the icon button if using the compressed UI
> Docs: improve keyboard interactions for search bar

- .github/workflows/ci.yml
Add Node.js 18 to Github CI's test matrix
Node.js 18 is becoming the LTS version on 2022-10-25 ([releases](https://nodejs.org/en/about/releases/)) so let's make sure Gestalt's tests can run on it.
> Internal: add Node.js 18 to test matrix

- .github/workflows/ci.yml
My [SelectList PR](https://github.com/pinterest/gestalt/pull/2219) has been failing CI due to OOM issues on an unrelated test. Per [this Stack Overflow answer](https://stackoverflow.com/a/38560292/5253702), this PR adds the `--max-old-space-size` option to Node for the CI test run. This gets past the (low) default memory settings for Node, which were causing the OOM issue. (We can tweak this actual value in the future if needed)
> Internal: increase Node memory to solve OOM issue on CI

- .prettierignore
- .stylelintrc.json
- docs/docs.css
- packages/gestalt-datepicker/src/DatePicker.css
- packages/gestalt/src/Badge.css
- packages/gestalt/src/Borders.css
- packages/gestalt/src/Dropdown.css
- packages/gestalt/src/InternalTextField.css
- packages/gestalt/src/SearchField.css
- packages/gestalt/src/SelectList.css
- packages/gestalt/src/Sheet.css
- packages/gestalt/src/TextArea.css
- packages/gestalt/src/Toast.css
- yarn.lock
Use [Prettier](https://prettier.io/) on our CSS files
* Consistent formatting across all of our codebase (JS & md already uses prettier
* We already had [stylelint-config-prettier](https://www.npmjs.com/package/stylelint-config-prettier) installed but never used it.
> Internal: run Prettier on CSS files

- .eslintrc.json
- docs/docs-components/MarkdownPage.js
- docs/docs-components/highlight.js
- docs/pages/[id].js
Flow has two ways to declare an array type: "verbose" (`Array<string>`) or "shorthand" (`string[]`). For consistency, we should stick with one syntax across the repo. This PR adds a couple of [eslint rules](https://github.com/gajus/eslint-plugin-flowtype#array-style-complex-type) to enforce the verbose style, matching Pinboard's settings.
> Internal: lint for array Flow type syntax

- .eslintrc.json
We don't seem to need `flowtype/no-weak-types` — this rule duplicates errors already thrown by Flow, without providing any additional safety that I can tell.
> Internal: remove commented-out lint rule

- .prettierrc.json
This is a fix for the release breaking.
Even though we're ignoring Markdown files, it seems that this portion of the config is necessary to not cause the release step to stop working.
This should fix it.
> Fix: Adding MD Config Back to Prettier

- docs/pages/foundations/color/palette.js
- docs/pages/foundations/color/usage.js
- docs/pages/foundations/data_visualization/palette.js
- docs/pages/foundations/data_visualization/usage.js
- docs/pages/foundations/elevation.js
- docs/pages/foundations/iconography/usage.js
- docs/pages/foundations/messaging/principles.js
- docs/pages/foundations/typography/guidelines.js
Now that gap on Flex can be specified for both directions, we remove some outdated code and update spacing where needed
In some places we used marginBottom to help spacing after wrapping, in other places we just had bad spacing. This alleviates the spacing in many Foundations pages when rendered on Mobile
Before:
After
> Docs: Update mobile spacing with new Flex gap

- packages/gestalt/src/Masonry.js
[This caused a fun bug](https://pinterest.slack.com/archives/C13KLG5P0/p1661293861162029)
We probably need to do more to address this in the future (possibly renaming/capitalizing the prop, adding any other possible checks) but this may help things for now at least.
> Masonry: add note about stable component references

- .eslintrc.json
- docs/docs-components/COMPONENT_DATA.js
- docs/docs-components/MainSectionCard.js
- docs/docs-components/MarkdownPage.js
- docs/docs-components/PropTable.js
- docs/docs-components/ResourcesFooter.js
- docs/docs-components/Toc.js
- docs/docs-components/docgen.js
- docs/docs-components/handleCodeSandbox.js
- docs/docs-components/highlight.js
- docs/docs-components/siteIndex.js
- docs/next.config.js
- docs/pages/[...id].js
- docs/pages/roadmap/whats_new.js
- docs/pages/web/masonry.js
- docs/pages/web/overview.js
- docs/redirects.js
- docs/utils/mdHelper.js
When @jackhsu978 [first implemented read-only arrays in Gestalt](https://github.com/pinterest/gestalt/pull/1321/) a couple of years ago, he specifically didn't include our docs components. I don't see any reason why we wouldn't want to also enforce immutable arrays in those components, so this PR removes that override and fixes all current violations.
_…but why?_
A great explanation from Jack's PR:
> General reasons for using immutable data structures:
> 
> - They are simpler to construct, test, and use
> - They help to avoid temporal coupling
> - Their usage is side-effect free (no defensive copies)
> - Identity mutability problem is avoided
> - They always have failure atomicity
> - They are much easier to cache
> 
> When a prop/argument of a component/function is typed as the mutable …
> Internal: use immutable arrays in docs components

- docs/pages/web/masonry.js
- packages/gestalt/src/Masonry.flowtest.js
- packages/gestalt/src/Masonry.js
The current prop name `comp` on Masonry doesn't make it clear how the prop will be used: is it a function? A function component? A component of any sort? It's not clear.
Renaming this prop to `Item` makes it more clear that the prop will be used as a component. The ultimate goal is to ensure that users know this always needs to be a stable reference, which this barely addresses. However, future work will add a lint rule to ensure that `Item` is always stable, and will possibly rethink how we treat the item component to completely preclude this possibility.
More context in [this Slack thread](https://pinterest.slack.com/archives/C13KLG5P0/p1661293861162029)
```zsh
yarn codemod modifyProp ~/path/to/your/code --component=Masonry --previousProp=comp --nextProp=Item
```
_Notes_
@ponori This …
> Masonry: rename `comp` to `Item`

- docs/pages/web/popover.js
- packages/gestalt/src/Contents.js
- packages/gestalt/src/Controller.js
- packages/gestalt/src/Popover.js
- packages/gestalt/src/__snapshots__/Controller.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/Dropdown.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/Popover.jsdom.test.js.snap
- playwright/accessibility/Popover.spec.mjs
Update Popover (and its inner components) to always include a role and aria-label - a requirement for accessibility. Also allow users to specify an accessibilityLabel for their Popover
We were disabling an a11y check, which caused issues in the main repo. All non-modal dialogs (Popovers) need a role. All items with role = dialog or listbox need a label. So this PR adds defaults for both to ensure every Popover is accessible by default (but also allows users to override the label to be more specific, which is preferred).
- [Jira](https://jira.pinadmin.com/browse/GESTALT-3554)
> Popover: Fix accessibility bug, add option for accessibilityLabel

- docs/docs-components/COMPONENT_DATA.js
Made Tabs available in Component Overview pages for Android and iOS
> Docs: Updated component_data to set Tabs docs ready for Android and iOS

- docs/docs-components/buttons/SidebarPlatformSwitcher.js
When switching b/w platforms, navigate to the Overview page
> Docs: Navigate to overview page with platform switcher

- docs/pages/web/numberfield.js
- docs/pages/web/textfield.js
- packages/gestalt/src/InternalTextField.js
- packages/gestalt/src/NumberField.js
- packages/gestalt/src/NumberField.test.js
- packages/gestalt/src/TextField.js
- packages/gestalt/src/TextField.test.js
- packages/gestalt/src/__snapshots__/NumberField.test.js.snap
- packages/gestalt/src/__snapshots__/TextField.test.js.snap
Textfield, Numberfield: new enterKeyHint prop
As a user, I want better context on my mobile keyboard's action key so I know what will happen when I tap it.
Acceptance criteria:
Implement the [`enterkeyhint` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/enterkeyhint) in the TextField and NumberField components.
Allow the following values based on the spec found at https://html.spec.whatwg.org/multipage/interaction.html#input-modalities:-the-enterkeyhint-attribute
Update the documentation for TextField and NumberField to include descriptions/guidance for each enterkeyhint value from [this spec](https://html.spec.whatwg.org/multipage/interaction.html#input-modalities:-the-enterkeyhint-attribute)
More info found here: …
> Textfield, Numberfield: new enterKeyHint prop

- packages/gestalt/src/Masonry.css
- packages/gestalt/src/Masonry.js
Masonry currently does nothing in response to the user's right-to-left (RTL) settings. This doesn't really matter in full-width, infinite grids, like homefeed; the user isn't likely to even be aware if the first item is in the top left or the top right. However, this _does_ matter when the grid width is constrained, particularly if there are a finite number of items or the user is likely to be aware of the order of the items, e.g. the Homefeed Tuner (pins and topics). 
This PR adds logic to support laying out Masonry items right-to-left according to the computed text direction for the Masonry container. This will typically match the style set on the entire page (typically on `<html>` or `<body>`), but will also respect more "local" settings, since [the `dir` …
> Masonry: add support for RTL text direction

- docs/docs-components/AppLayout.js
- docs/docs-components/SkipToContent.js
- docs/docs-components/z-indices.js
Docs: implement a11y "Skip to content"
For accessibility purposes. 
The skip to content link idea is this - put a link at the top of the page that allows keyboard users to jump over the navigation links and land on the main content of the page. For screen reader users this provides help with the structure of the page - where is the main content - and being able to get there. 
https://www.loom.com/share/beb2cc04d2e7496e998694d9c0287a72
I got logic from `app/packages/ui/SkipToContent.js` with a major code cleanup
For reference see https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160105/G1#maincontent
> Docs: implement a11y "Skip to content"

- docs/pages/foundations/messaging/available_components.js
- docs/pages/web/badge.js
- docs/pages/web/box.js
- docs/pages/web/checkbox.js
- docs/pages/web/image.js
- docs/pages/web/link.js
- docs/pages/web/radiogroup.js
- docs/pages/web/tabs.js
- docs/pages/web/taparea.js
Updates to multiple pages that weren't rendering well on mobile due to missing 'wrap' properties on Flex
Ensure code examples are properly responsive and render well on mobile
> Docs: Fix Flex wrapping in multiple pages

- CHANGELOG.md
- scripts/releaseSteps.js
Internal: add links to PR in Changelog on every release
Facilitate the access to PR urls
> Internal: add links to PR in Changelog on every release

- docs/examples/sidenavigation/badgeExample.js
- docs/examples/sidenavigation/borderExample.js
- docs/examples/sidenavigation/headerExample.js
- docs/examples/sidenavigation/sectionsExample.js
- docs/markdown/android/avatar.md
- docs/markdown/android/icon.md
- docs/markdown/android/textfield.md
- docs/markdown/get_started/developers/development_process.md
- docs/markdown/ios/avatar.md
- docs/markdown/ios/icon.md
- docs/markdown/ios/textfield.md
- docs/markdown/testing/how-to.md
- docs/pages/foundations/color/examples.js
- docs/pages/foundations/elevation.js
- docs/pages/foundations/messaging/available_components.js
- docs/pages/get_started/developers/releases.js
- docs/pages/get_started/how_to_work_with_us.js
- docs/pages/web/combobox.js
- docs/pages/web/link.js
- docs/pages/web/pageheader.js
- docs/pages/web/tag.js
- docs/pages/web/textarea.js
- docs/pages/web/tooltip.js
Docs: clean link urls to only use relative paths for Docs links
> Docs: clean link urls to only use relative paths for Docs links

- docs/pages/web/tabs.js
- packages/gestalt/src/Tabs.js
I heard feedback recently that some folks aren't clear about the `indicator` field on the `tabs` prop — including some who thought the current tab would have the red dot! This PR removes the indicator from most examples, and adds an example to specifically call out its usage.
> Tabs: clarify indicator usage in docs

- docs/pages/BlogPosts.json
- docs/pages/whats_new.js
Add ability to show a summary for each What's New section
Give readers a high-level overview of the content
> Docs: Add summary option for What's New page

- docs/package.json
- yarn.lock
No features I'm particularly excited about, just keeping us up-to-date
https://github.com/vercel/next.js/releases/tag/v12.3.0
> Internal: upgrade Next.js to 12.3.0

- docs/docs-components/DocSearch.js
- docs/docs-components/Header.js
- docs/docs-components/appContext.js
- docs/docs.css
- packages/gestalt/src/Divider.css
- packages/gestalt/src/SideNavigation.css
Fix a few bugs in the header of our docs site
Ensure site settings dropdown always aligns properly, fix search icon in RTL, and Algolia popup in dark mode
[Tracker](https://coda.io/d/Gestalt-Team-Folder_d2LeXkQ1kVX/Gestalt-site-update-bug-tracker_sugaw#Bugs-August-18-Sprint-17_tuH4m/r4)
Before
After
> Docs: Visual fixes to the site header

- docs/docs-components/PageHeader.js
Use multiline comments to enable flow docs
Makes the comments visible to where the props are being used, not just where they are defined.
> Internal: use multiline comments to enable flow docs

- docs/docs-components/siteIndex.js
- docs/markdown/get_started/developers/contributing/creating_and_updating_pages.md
- docs/markdown/get_started/developers/contributing/development_process.md
- docs/redirects.js
- playwright/accessibility/Creating and updating pages.spec.mjs
Add information on how to add, move, or delete a page in our Docs site
Make it easier for contributors to understand the docs site and process
- [TDD](https://paper.dropbox.com/doc/Creating-and-updating-pages-in-Gestalt--BpFMpCRbv5Ytj_HXJvzl3AYTAg-oDNv0d3zNOjkueLwlCDwA)
> Docs: Add developer guide on adding a new page

- docs/pages/web/badge.js
- packages/gestalt/src/Badge.js
Add a Recommendation type for Badge
With the introduction of our recommendation tokens, we needed to add it to Badge as well as our banners
> Badge: Add recommendation type

- docs/examples/slimbanner/responsiveExample.js
- docs/pages/web/slimbanner.js
- packages/gestalt/src/SlimBanner.js
- packages/gestalt/src/__snapshots__/SlimBanner.test.js.snap
Move SlimBanner action down to a new line in mobile viewports
Ensure the text is readable in small viewports. Note: This does not yet address the horizontal alignment of the icon and dismiss button in small viewports
Before:
After:
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4605)
- [Figma](https://www.figma.com/file/MInxIhLJSbGDebM0939W5G/Gestalt-SlimBanner-Hand-off?node-id=213%3A1766)
> SlimBanner: Adjust layout in small viewports

- docs/examples/modal/createBoardExample.js
- docs/pages/visual-test/Checkbox-dark.js
- docs/pages/visual-test/Checkbox.js
- docs/pages/visual-test/Fieldset-dark.js
- docs/pages/visual-test/Fieldset.js
- docs/pages/web/checkbox.js
- docs/pages/web/iconbutton.js
- packages/gestalt/src/Checkbox.js
- packages/gestalt/src/Checkbox.test.js
- packages/gestalt/src/__snapshots__/Checkbox.test.js.snap
Checkbox: standardize helper/error message style with other form/control fields, renamed subtext, deprecated hasError
Form controls: Textfield, TextArea, have the same helperText / errorMessage prop and style. Refactoring Checkbox to match style and API of all form fields.
1st Run 
`yarn codemod modifyProp ~/code/pinboard/webapp
--component=Checkbox
--previousProp=subtext
--nextProp=helperText`
2nd Run 
`yarn codemod modifyProp ~/code/pinboard/webapp --component=Checkbox --previousProp=hasError
`
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4843)
> Checkbox: standardize helper/error message style with other form/control fields, renamed subtext, deprecated hasError

- docs/pages/web/numberfield.js
Came across this blog post today that really nails when a number input should be used instead of a text input:
https://stackoverflow.blog/2022/09/15/why-the-number-input-is-the-worst-input/
> NumberField: add link to useful blog post

- packages/gestalt/src/Contents.js
- packages/gestalt/src/Dropdown.js
- packages/gestalt/src/__snapshots__/Dropdown.jsdom.test.js.snap
This reverts commit [Popover: Add support to handle content that overflows the viewport height ([#2384](https://github.com/pinterest/gestalt/pull/2384))]
This was motivated by:
- https://pinterest.slack.com/archives/GG6T5UG3X/p1663601895689729
- https://pinterest.slack.com/archives/G01GN7CE99S/p1663265961230629
Bug repro: https://www.loom.com/share/50731be953b34c4e82521fc3c18d7f00 & https://www.loom.com/share/dfef5d196be5411caff4eb1b3f7b4f03
> Revert "Popover: Add support to handle content that overflows the viewport height"

- docs/pages/web/radiogroup.js
- packages/gestalt/src/RadioGroupButton.js
RadioGroupButton: standardize helper message style with other form/control fields, renamed subtext
Form controls: Textfield, TextArea, have the same helperText / errorMessage prop and style. Refactoring RadioGroup.Button to match style and API of all form fields.
1st Run 
`yarn codemod modifyProp ~/code/pinboard/webapp
--component=RadioGroup
--subcomponent=RadioButton
--previousProp=subtext
--nextProp=helperText
`
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4843)
> RadioGroupButton: standardize helper message style with other form/control fields, renamed subtext

- packages/gestalt/src/Checkbox.js
- packages/gestalt/src/FormErrorMessage.js
- packages/gestalt/src/FormHelperText.js
- packages/gestalt/src/RadioGroupButton.js
- packages/gestalt/src/__snapshots__/Checkbox.test.js.snap
Checkbox, RadioButton: Implementing a11y pause
It was removed in previous PR  https://github.com/pinterest/gestalt/pull/2392 & https://github.com/pinterest/gestalt/pull/2391
Reimplementing + adding pause in ErrorMessage for Checkbox as well.
> Checkbox, RadioButton: Implementing a11y pause

- packages/gestalt/src/Checkbox.js
- packages/gestalt/src/RadioButton.js
- packages/gestalt/src/RadioGroupButton.js
- packages/gestalt/src/__snapshots__/Checkbox.test.js.snap
- packages/gestalt/src/__snapshots__/Fieldset.test.js.snap
- packages/gestalt/src/__snapshots__/RadioButton.test.js.snap
- packages/gestalt/src/__snapshots__/RadioGroup.test.js.snap
Checkbox, RadioButton, RadioGroupButton: start align input
Checkbox and RadioGroup controls currently are vertically center-aligned with the label (see attached image)
The Checkbox and RadioGroup controls (e.g., the actual checkbox / radio inputs) should be top aligned with the label. So that if/when the label wraps, the position of the checkbox / radio should not change relative to the first line of the label.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4272)
> Checkbox, RadioButton, RadioGroupButton: start align input

- packages/gestalt-datepicker/src/DatePicker.js
- packages/gestalt-datepicker/src/DatePickerTextField.js
DatePicker: standardize error message style and internal cleanup
Standardization in style. Whenever we implement error icons in error messages in textfield, Datepicker will get it for free
Form controls: Textfield, TextArea, have the same helperText / errorMessage prop and style. Refactoring Datepicker to match style
Internal Refactor to use Textfield built-in error and helper message
> DatePicker: standardize error message style and internal cleanup

- CHANGELOG.md
- docs/docs-components/siteIndex.js
- docs/examples/sidenavigation/sectionsExample.js
- docs/pages/get_started/developers/eslint_plugin.js
- docs/pages/get_started/developers/tooling/web.js
- docs/pages/web/button.js
- packages/eslint-plugin-gestalt/package.json
- packages/eslint-plugin-gestalt/src/__fixtures__/button-icon-restrictions/invalid/invalid-wrong-link-role-icon.js
- packages/eslint-plugin-gestalt/src/__fixtures__/button-icon-restrictions/valid/valid-size.js
- packages/eslint-plugin-gestalt/src/button-icon-restrictions.js
- packages/eslint-plugin-gestalt/src/button-icon-restrictions.test.js
- packages/eslint-plugin-gestalt/src/helpers/noBoxDangerousStyleDuplicatesReducer.js
- packages/eslint-plugin-gestalt/src/prefer-box-no-disallowed.js
- playwright/accessibility/Eslint Plugin.spec.mjs
Eslint_plugin: extend gestalt/button-icon-restrictions to cover role=link icon restrictions
Require a specific value when using [Icon](http://localhost:8888/web/icon) with [Button](http://localhost:8888/web/button). Gestalt is more permissive than we recommend internally for adding icons to Buttons, so Buttons using iconEnd must use the "arrow-down" icon and Buttons with link role using iconEnd must use the "visit" icon.
This Eslint rule didn't cover the second restriction, a new best practice that  was recently implemented.
To facilitate the migration, run this codemod to find instances of Button role="link" 
```
--component=Button
--prop=role
--value=link
```
However, the Eslint rule will through an ERROR/WARNING message anyway …
> Eslint plugin: extend gestalt/button-icon-restrictions to cover role=link icon restrictions

- docs/pages/get_started/faq.js
We see frequent confusion on how to work with Gestalt types:
- How to properly use Flow types for a component's props (e.g. when creating a wrapper component that mirrors a Gestalt component's prop type)
- TypeScript support
This PR adds notes to the FAQ page about these two questions. In a future PR I'll add the ability to quickly copy the syntax for a given prop's type to Prop tables.
> Docs: add notes about types to FAQ

- docs/pages/web/selectlist.js
Show an example of how to add an IconButton/Tooltip to the SelectList label using the labelDisplay prop
This a frequent use case, so examples in docs would be helpful
> SelectList: Update labelVisbility example to show tooltip

- docs/docs-components/GeneratedPropTable.js
- docs/docs-components/PropTable.js
- docs/pages/web/button.js
- docs/pages/web/dropdown.js
- docs/pages/web/iconbutton.js
- docs/pages/web/radiogroup.js
- docs/pages/web/sheet.js
- docs/pages/web/sidenavigation.js
- docs/pages/web/sticky.js
- docs/pages/web/tag.js
- docs/pages/web/taparea.js
Building on #2409, this PR adds a button to the Props table to allow for easy copying of the correct Flow syntax to access a component's prop type:
```js
$ElementType<React$ElementConfig<typeof {ComponentName}>, '{propName}'>
```
> Docs: add button to copy Flow type

- docs/pages/web/textarea.js
- docs/pages/web/textfield.js
- packages/gestalt/src/FormHelperText.js
- packages/gestalt/src/FormHelperTextCounter.js
- packages/gestalt/src/InternalTextField.js
- packages/gestalt/src/PageHeader.js
- packages/gestalt/src/TextArea.js
- packages/gestalt/src/TextArea.jsdom.test.js
- packages/gestalt/src/TextArea.test.js
- packages/gestalt/src/TextField.js
- packages/gestalt/src/TextField.jsdom.test.js
- packages/gestalt/src/TextField.test.js
- packages/gestalt/src/__snapshots__/Checkbox.test.js.snap
- packages/gestalt/src/__snapshots__/TextArea.test.js.snap
- packages/gestalt/src/__snapshots__/TextField.test.js.snap
- packages/gestalt/src/utils/testing/expectToThrow.js
Textfield, TextArea: add maxLength prop
As a user, I want to have a visual affordance for how many characters I can add to a TextArea so I can effectively write for the character limit.
Acceptance criteria
- The TextArea and TextField components should have a prop to enforce a maximum character limit.
maximum character limits should not be enforced unless the maxchars prop (or whatever name we give it) is explicitly set.
- The prop should only accept a positive integer.
When the prop is set with a valid number, a counter affordance should be displayed on the right side of TextField/TextArea below the input element (see Figma design link above).
- The counter should update whenever the number of characters within the input changes.
When helperText is displayed:
- The counter's width should …
> Textfield, TextArea: add maxLength prop

- packages/gestalt/src/InternalTextField.js
Under the hood implementation in Textfield: implemented `spellcheck=false` for `type=password` and `type=email`
This config is required to prevent passwords and usernames could be sent to spell-checking servers during login processes. More info here: https://www.androidpolice.com/google-chrome-servers-get-passwords-enhanced-spell-check/
> Textfield: implemented spellcheck=false for type=password or email

- packages/gestalt/src/Checkbox.js
- packages/gestalt/src/RadioButton.js
- packages/gestalt/src/RadioGroupButton.js
- packages/gestalt/src/__snapshots__/Checkbox.test.js.snap
- packages/gestalt/src/__snapshots__/RadioButton.test.js.snap
CheckBox, RadioGroupButton: fix spacing in size='sm'  with custom marginTop
Introduced in https://github.com/pinterest/gestalt/pull/2403
BEFORE
AFTER
> CheckBox, RadioGroupButton: fix spacing in size='sm'  with custom marginTop

- docs/docs-components/AccessibilitySection.js
- docs/docs-components/AppLayout.js
- docs/docs-components/siteIndex.js
- docs/examples/devicetypeprovider/implementation.js
- docs/examples/sidenavigation/mobileExample.js
- docs/examples/sidenavigation/subcomponent.js
- docs/pages/_app.js
- docs/pages/web/sidenavigation.js
- docs/pages/web/utilities/devicetypeprovider.js
- docs/pages/web/utilities/onlinknavigationprovider.js
- packages/gestalt/src/SideNavigation.js
- packages/gestalt/src/SideNavigationGroup.js
- packages/gestalt/src/SideNavigationGroupContent.js
- packages/gestalt/src/SideNavigationTopItem.js
- packages/gestalt/src/contexts/DeviceTypeProvider.js
DeviceTypeProvider: new utility and documentation page
Gestalt components can enable their mobile user interfaces using DeviceTypeProvider.
WARNING: This PR introduces 2 main changes to the previously undocumented DeviceTypeProvider: removes 'tablet' from the Flow type as Gestalt doesn't support tablet UI (and this is not planned to change in the near future) and renames `phone` to `mobile` to follow the standard way of referring to mobile platform. 
Despite the fact that DeviceTypeProvider was an undocumented utility, we are releasing this change as a major version. Use the following codemod to find DeviceTypeProvider in your codebase and make adjustments to upgrade to this version.
`yarn codemod detectManualReplacement ~/path/to/your/code --component=DeviceTypeProvider
`
NOTE: To test …
> DeviceTypeProvider: new utility and documentation page

- docs/pages/web/checkbox.js
Checkbox: new best practice example re vertical alignment
The recent changes in Checkbox https://github.com/pinterest/gestalt/pull/2403 encompass built-in labels, however, in product we still have multiple examples of certered vertical alignments in custom-labeled Checkboxes.
This new best practice aims to cover this new design spec that might be overseeing in designs and engineering implementations.
> Checkbox: new best practice example re vertical alignment

- docs/pages/web/datapoint.js
As noted in [this Slack thread](https://pinterest.slack.com/archives/C014X9LTRCN/p1664488014513369), we need to be more consistent with the casing of abbreviations. This PR updates our examples to be consistent. It specifically does _not_ address adding new guidance around this, as we should work with content design folks to develop that guidance.
> Datapoint: fix casing in docs examples

- docs/docs-components/PageHeaderQualitySummary.js
In preparation for other work, I cleaned up PageHeaderQualitySummary a bit. Most of this is refactoring code and simplifying markup. Visual changes are increased spacing between the rows of items when wrapped, and making the divider element only as tall as the content.
_Before_
_After_
> Docs: cleanup PageHeaderQualitySummary

- docs/docs-components/COMPONENT_DATA.js
- docs/docs-components/PageHeader.js
- docs/pages/web/combobox.js
- docs/pages/web/utilities/colorschemeprovider.js
- docs/pages/web/utilities/devicetypeprovider.js
- docs/pages/web/utilities/onlinknavigationprovider.js
- docs/pages/web/utilities/usefocusvisible.js
- docs/pages/web/utilities/usereducedmotion.js
- packages/gestalt/src/ComboBox.js
Naming is one of the more difficult things we struggle with, and similar components often have different names across the industry. While we need to settle on specific names for sanity's sake, our users may not be accustomed to those names. This PR adds an optional "aliases" section to the docs page header so we can add these other names components are commonly known by. This _should_ get picked up on the next Algolia crawl and improve search results for folks using these other names.
> Docs: add component aliases to page header

- docs/pages/web/text.js
- packages/gestalt/src/Text.js
Removing unused prop `justify` of `Text` component;
The following codemod help you to do the follow table replacement.
To modifyPropValue, please, use
```bash
yarn codemod modifyPropValue ~/path/to/your/code
--component=Text
--previousProp=align
--previousValue=justify
```
To detect manual changes use
```bash
--component=Text
--prop=align
--value=justify
```
The value was removed of main file and code;
The value is not used and the design suggest your delete;
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4794)
> Text: Removing justify value prop

- docs/pages/web/datepicker.js
- packages/gestalt-design-tokens/tokens/color/alias.json
- packages/gestalt/src/contexts/__snapshots__/ColorSchemeProvider.jsdom.test.js.snap
Adjust error token for Text and Icon to have more contrast in dark mode
In order to provide better color contrast in dark mode, $color-text-error and $color-text-icon-error went from $color-red-pushpin-400 to $color-red-pushpin-300
> Tokens: Adjust dark mode error text and icon

- docs/docs-components/CombinationNew.js
- docs/docs-components/TokenExample.js
- docs/pages/foundations/design_tokens.js
- docs/pages/web/box.js
- packages/gestalt-design-tokens/config.json
- packages/gestalt-design-tokens/tokens/opacity/base.json
Add tokens for opacity values
Allow cross platform consistency for opacity on objects (Pins, images, Boards, etc.)
- [Jira](https://jira.pinadmin.com/browse/GESTALT-3661)
- [TDD](https://coda.io/d/Android-opacity-ramp_dQC4S2hCCxU/Opacity-ramp-Phase-1_suIbi)
> Design tokens: Add opacity tokens

- docs/docs-components/PageHeader.js
- docs/docs.css
The new aliases aren't getting picked up by Algolia — probably because I used a div with heading roles instead of an actual `h2`. This PR switches out to use the native element, with a style reset to avoid native browser heading styles.
> Docs: use actual h2 for aliases

- docs/examples/hacking_gestalt/dangerouslySetInlineStyle.js
- docs/examples/hacking_gestalt/ref.js
- docs/examples/hacking_gestalt/wrappingComponents.js
- docs/pages/get_started/developers/hacking_gestalt.js
Of note: the previous ref example was no longer functional (pretty good indicator of why this isn't a great technique! 😅), so I updated to use TextField instead:
> Docs: convert Hacking Gestalt page to use Sandpack

- docs/docs-components/PropTable.js
- packages/gestalt/src/Masonry.js
Adds `virtualBufferFactor` as a prop to Masonry.
The virtual buffer factor impacts when masonry shows items when scrolling. Adding it as a prop enables us to experiment with different values and measure performance / user impact.
* Experiment with different `virtualBufferFactor` values & measure the performance impact
* Consolidate `virtualBoundsBottom`, `virtualBoundsTop` and `virtualBufferFactor` into 1 prop
> Masonry: add virtualBufferFactor prop

- packages/gestalt-datepicker/src/DatePicker.jsdom.test.js
- packages/gestalt/src/contexts/DefaultLabelProvider.js
also removing the Provider from the DatePicker test file for now — we can re-add it when needed
> DefaultLabelProvider: add comments about updating translations

- packages/gestalt-design-tokens/tokens/color/alias.json
- packages/gestalt-design-tokens/tokens/color/base.json
New transparent base token
Support transparent backgrounds and fills cross-platform
> Design Tokens: Add transparent token

- packages/gestalt/src/Flex.js
- packages/gestalt/src/FlexItem.js
This is a common request from folks, and often either results in people using Box instead, or wrapping Flex in an additional Box just to set the id (resulting in DOM bloat).
This could be implemented as a passthrough prop (similar to Box), but I think that's a leaky abstraction. Though it is a passthrough component under the hood, we don't treat Flex as such. And we shouldn't expect our users to know how Flex is implemented. Therefore, I implemented this as an "official" new prop, `dataTestId`. This matches our other non-Box test ids.
I need to update the existing `prefer-flex` lint rule to accommodate this new prop.
I'll also look at ways of finding and refactoring Boxes that wrap Flexes only for the test id.
> Flex: add dataTestId

- docs/pages/web/toast.js
- packages/gestalt/src/Toast.js
Removing prop value thumbnailShape=**rectangular**
Run the following codemode to replace rectangular to square 
```
yarn codemod modifyPropValue ~/path/to/your/code
--component=Toast
--previousProp=thumbnailShape
--previousValue=rectangular
--nextValue=square
```
Run the following codemode to locate  rectangular value for manual change
```
--component=Toast
--prop=thumbnailShape
--value=rectangular
```
Toast: deprecating thumbnailShape=rectangular 
New redesigns deprecate this option. Cleaning up API to facilitate next changes
- [TDD](https://paper.dropbox.com/doc/Gestalt-TDD-Toast--BreAMsHjKfKyzyNISaHmYW_GAg-EC6LAr0uO808c6GrjH9FO)
- [Figma](https://www.figma.com/file/rVnMTnlB64QbKrF5c6KjUl/Gestalt-Toast-Design?node-id=16%3A402)
> Toast: deprecating value thumbnailShape=rectangular 

- docs/examples/buttongroup/defaultExample.js
- docs/examples/card/defaultExample.js
- docs/examples/segmentedcontrol/defaultExample.js
- docs/examples/tag/defaultExample.js
- docs/pages/web/buttongroup.js
- docs/pages/web/card.js
- docs/pages/web/segmentedcontrol.js
- docs/pages/web/tag.js
Add top-of-page example to Tag, Card, SegmentedControl, and ButtonGroup
Ensure folks can see the component at first glance
> Docs: Add top of page examples

- docs/docs-components/PropTable.js
- docs/docs-components/buttons/CopyCodeButton.js
Replace drag and drop icon with copy-to-clipboard icon
Before
After
> Docs: Update to new copy-to-clipboard icon

- docs/examples/defaultlabelprovider/translations.js
- docs/pages/web/button.js
- docs/pages/web/iconbutton.js
- docs/pages/web/link.js
- docs/pages/web/taparea.js
- docs/pages/web/utilities/onlinknavigationprovider.js
- packages/gestalt/src/Button.js
- packages/gestalt/src/Button.jsdom.test.js
- packages/gestalt/src/DropdownLink.jsdom.test.js
- packages/gestalt/src/IconButton.js
- packages/gestalt/src/IconButton.jsdom.test.js
- packages/gestalt/src/Link.js
- packages/gestalt/src/Link.jsdom.test.js
- packages/gestalt/src/NewTabAccessibilityLabel.js
- packages/gestalt/src/OptionItem.js
- packages/gestalt/src/TapArea.js
- packages/gestalt/src/TapArea.jsdom.test.js
- packages/gestalt/src/__snapshots__/ActivationCard.test.js.snap
- packages/gestalt/src/__snapshots__/Callout.test.js.snap
- packages/gestalt/src/__snapshots__/Dropdown.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/Link.test.js.snap
- packages/gestalt/src/__snapshots__/Upsell.test.js.snap
- packages/gestalt/src/__snapshots__/UpsellForm.test.js.snap
- packages/gestalt/src/contexts/DefaultLabelProvider.js
- packages/gestalt/src/contexts/DefaultLabelProvider.jsdom.test.js
Update `DefaultLabelProvider` with new label.
```
Link: {
accessibilityNewTabLabel: myI18nTranslator('Opens a new tab'),
},
```
Link, Button, TapArea, IconButton: implemented default label to target="blank" #2467
Added SlimBanners across the different documentation pages linking components to DefaultLabelProvider.
Note from WebAim — The vast majority of screen readers don't inform users that target= "_blank" links open in new tabs; folks could have a hard time realizing why they can't use the back button to return to the previous page and that they might need to switch back to the last tab to do so. 
We actually can create a label informing users that the link is going to open in a new tab. 
Label suggestion to announce: Opens a new tab
Reference: We must inform your users about this …
> Link, Button, TapArea, IconButton: implemented default label to target="blank"

- docs/docs-components/siteIndex.js
- docs/pages/foundations/iconography/ICON_DATA.json
- docs/pages/foundations/iconography/custom_and_brand_icons.js
- docs/pages/foundations/iconography/library.js
- docs/pages/foundations/iconography/usage.js
- playwright/accessibility/Custom and brand icons.spec.mjs
Update the Icon library page to support better search and categories. Move custom and brand info to own page
Make it easier to find icons by name or by category
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4673)
- [Figma](https://www.figma.com/file/RBlfOYmL123whCtlglXIsG/Iconography-page-redesign?node-id=1%3A2)
> Icons: Update Icon library page

- .eslintrc.json
- docs/docs-components/AccessibilityChecklist.js
- docs/docs-components/Combination.js
- docs/docs-components/CombinationNew.js
- docs/docs-components/MainSectionSubsection.js
- docs/docs-components/Overview.js
- docs/docs-components/OverviewList.js
- docs/docs-components/Page.js
- docs/docs-components/PropTable.js
- docs/docs-components/QualityChecklist.js
- docs/docs-components/useGetSideNavItems.js
- docs/examples/avatarGroup/roleButton.js
- docs/examples/pageheader/multiplePrimaryActionsExample.js
- docs/examples/sidenavigation/footerExample.js
- docs/pages/foundations/data_visualization/usage.js
- docs/pages/foundations/overview.js
- docs/pages/get_started/developers/tooling/web.js
- docs/pages/visual-test/Icon-list-dark.js
- docs/pages/visual-test/Icon-list.js
- docs/pages/visual-test/Table.js
- docs/pages/web/component_status.js
- packages/gestalt/src/AvatarGroup.js
- packages/gestalt/src/ComboBox.js
- packages/gestalt/src/InternalTextField.js
- packages/gestalt/src/Masonry.js
- packages/gestalt/src/ModuleExpandable.js
- packages/gestalt/src/ModuleExpandableItem.js
- packages/gestalt/src/PageHeaderComponents.js
- packages/gestalt/src/SegmentedControl.js
- packages/gestalt/src/TextArea.js
[Rule definition](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md)
[React uses `key` to identify items within arrays and maintain stability as those items change](https://reactjs.org/docs/lists-and-keys.html#keys). But it's generally [a bad idea to use array indices as keys](https://robinpokorny.com/blog/index-as-a-key-is-an-anti-pattern/).
While there are occasionally valid reasons to use indices as keys, in general we want to avoid that practice, so it makes sense to lint against it.
> Internal: turn on `react/no-array-index-key` lint rule

- packages/gestalt/src/behaviors/TrapFocusBehavior.js
No longer scroll jump on `Sheet` and `Modal` pages
It's a very annoying experience for folks using our documentation pages.
* Both `Sheet` and `Modal` use `TrapFocusBehavior`
* `focusFirstChild` is only used within `useEffect`, so it's not necessary to do a `window` check: `typeof window !== 'undefined'`
* Other approaches like preventing the focus or scroll in the parent window did not work
> Docs: Fix page jumps on Sheet & Modal pages

- docs/docs-components/MainSectionSubsection.js
Caused by #2472 - fixes a duplicate key issue on every docs page
Resolves errors in the browser console (happens on every page):
* Require a unique `id` for every `MainSectionSubsection` component
* Use combination of `title` and `description` - I tried this and it looks like we have quite a few places were both are empty
> Docs: fix duplicate key issue

- docs/docs-components/MainSectionCard.js
- docs/docs-components/Overview.js
- docs/docs-components/PropTable.js
- docs/docs-components/utils.js
- docs/pages/foundations/data_visualization/palette.js
- docs/utils/capitalizeFirstLetter.js
From recent survey feedback and my own personal use, the radio buttons at the top of the Component Overview page aren't very obvious. Per design recommendation from @hectoid, this PR swaps out the radio buttons for SegmentedControl.
Note that the "design spec" was a quick mock from [this Slack convo](https://pinterest.slack.com/archives/C014X9LTRCN/p1667346055685839), so pixel specifics were kinda guesses. 😅 
_Design "spec"_
_Implementation at normal widths_
_Implementation at most narrow width (before the side nav is hidden)_
> Docs: use SegmentedControl for component overview sort control

- packages/gestalt/src/contexts/DefaultLabelProvider.js
Attempting to solve [this issue](https://pinterest.slack.com/archives/G01GN7CE99S/p1667574386047009), where the proper mock isn't being used and destructuring throws.
> DefaultLabelProvider: add fallback objects to prevent destructuring errors

- docs/examples/README.md
- docs/removeFlowTypesLoader.js
Removes `import {} from 'react'` from our Sandpack examples
It's unnecessary and confusing for developers
> Docs: fix empty import from 'react'

- packages/gestalt/src/Image.js
- packages/gestalt/src/Image.test.js
- packages/gestalt/src/__snapshots__/Avatar.test.js.snap
- packages/gestalt/src/__snapshots__/AvatarGroup.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/Checkbox.test.js.snap
- packages/gestalt/src/__snapshots__/Image.test.js.snap
- packages/gestalt/src/__snapshots__/RadioButton.test.js.snap
major release - running a generic codemod to replace instances of 'importance' prop and replacing them with 'fetchPriority' 
```bash
yarn codemod modifyProp ~/path/to/your/code
--component=Image
--previousProp=importance
--nextProp=fetchPriority
```
Updating 'importance' prop to 'fetchPriority' . This diff removes the deprecated 'importance' prop and replaces with fetchpriority.
There's an old PR [here](https://github.com/pinterest/gestalt/pull/2012) that aimed to do the same thing - just opening up a new one instead of having to jump through permissions hoops + rebasing troubles.
Now that fetchPriority is stable (at least for chromium-based browsers), we want to start running experiments with it to see if we can optimize Largest Contentful Paint on certain surfaces in order to improve …
> Image: replace `importance` prop with `fetchPriority`

- packages/gestalt/src/Image.js
This was a request from our recent survey, though also makes sense for consistency. By passing along the event, users can easily see which image failed to load and take the appropriate action.
> Image: pass event object through on load and error

- docs/markdown/android/button.md
The accessibility section referenced iOS guidelines for an Android component
> Docs: Fixed accessibility section in Android Button guidelines

- docs/pages/web/table.js
- packages/gestalt/src/Table.css
- packages/gestalt/src/Table.css.flow
- packages/gestalt/src/Table.js
- packages/gestalt/src/TableRowDrawer.js
- packages/gestalt/src/TableRowDrawer.test.js
- packages/gestalt/src/TableRowExpandable.js
- packages/gestalt/src/__snapshots__/TableRowDrawer.test.js.snap
Table: new Table.RowDrawer subcomponent
Also, removed divider between Row and RowExpandable and RowDrawer
New component to support m10n requests. 
New featured (Drawer with SlimBanner) was tested under experimentation presenting good results.
> Table: new Table.RowDrawer subcomponent

- docs/pages/visual-test/Toast-dark.js
- docs/pages/visual-test/Toast.js
- docs/pages/web/toast.js
- packages/gestalt/src/Toast.js
- packages/gestalt/src/Toast.test.js
- packages/gestalt/src/ToastPrimaryAction.js
- packages/gestalt/src/__snapshots__/Toast.test.js.snap
API change. From `button` (Node) to a restricted object `{ accessibilityLabel, href, label, onClick, rel, size, target }
Added a new undocumented prop `_dangerouslySetPrimaryAction`. Use `_dangerouslySetPrimaryAction` as an exception, only for legacy custom buttons components. 
Run the following codemod to detect button props and replace them manually:
```
--component=Toast
--prop=button
```
Toast: refactor 'button' prop to enable upcoming redesign changes
'button' prop doesn't allow to control button sizes. refactoring to 'primaryAction' to enable upcoming redesign changes
> Toast: refactor 'button' prop to 'primaryAction' to enable upcoming redesign changes

- CHANGELOG.md
- docs/pages/web/slimbanner.js
- packages/gestalt/src/SideNavigation/getChildrenToArray.js
- packages/gestalt/src/SlimBanner.js
- packages/gestalt/src/SlimBanner.test.js
- packages/gestalt/src/Text.js
- packages/gestalt/src/__snapshots__/SlimBanner.test.js.snap
SlimBanner: extend "message" prop to accept Text component for rich-styled messages
Supporting Text and string in message prop will solve 2 problems: supporting rich-style messages such as inline bold text within Text and supporting links within Text allowing the correct localization of text with inlined links. helperText cannot be used with that purpose as localization not always follows the same word order in different locales.
- Left: Previously supported
- Center: Previously unsupported
- Right: Previously unsupported
- [Figma]( https://www.figma.com/file/MInxIhLJSbGDebM0939W5G/Gestalt-SlimBanner-Hand-off?node-id=602%3A2520)
> SlimBanner: extend "message" prop to accept Text component for rich-styled messages

- docs/docs-components/PropTable.js
Our current display of complex Flow types, uh, leaves something to be desired. 😅 
However, better formatting has been available all along, just waiting for us to use it! This PR adds `<pre>` tags, allowing us to use the available formatting for much prettier types! 🎉
> Docs: add formatting for prop types

- docs/docs-components/GeneratedPropTable.js
- packages/gestalt/src/Modal.js
- packages/gestalt/src/Module.js
- packages/gestalt/src/ScrollBoundaryContainer.js
- packages/gestalt/src/Text.js
- scripts/templates/ComponentName.js
- Get the "responsive" part of the prop table working again (we don't actually use this currently, but at least it works again in case we decide to bring it back)
- Remove the "href" override and refactor the last few usages of it
- Refactor how we handle overrides for autogen metadata to be more scalable
- Clean up some cruft related to autogen metadata
> Internal: cleanup/refactor how we handle autogen props

- docs/pages/web/toast.js
- packages/gestalt/src/Toast.js
Run the following codemod to list and manually replace those Node elements in `text` prop with Text
--component=Toast
--prop=text
Toast: restricting `text` prop from Node to only string and Text
> Toast: restricting `text` prop from Node to only string and Text

- docs/examples/defaultlabelprovider/translations.js
- docs/examples/popover/defaultExample.js
- docs/pages/web/popover.js
- packages/gestalt/src/InternalDismissButton.js
- packages/gestalt/src/Popover.js
- packages/gestalt/src/contexts/DefaultLabelProvider.js
- packages/gestalt/src/contexts/DefaultLabelProvider.jsdom.test.js
Add a showDismissButton option for Popover to include a dismiss button
To improve accessibility, Popovers should include a dismiss button. This PR adds the option, which we will eventually turn on by default
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4178)
> Popover: Add new option for dismiss button

- docs/docs-components/App.js
- docs/docs-components/PageHeader.js
- docs/docs-components/SlimBannerExperiment.js
- docs/docs-components/appContext.js
- docs/docs-components/contexts/DocsExperimentProvider.js
- docs/pages/web/badge.js
- docs/pages/web/textfield.js
Docs: added cookies to support activation/deactivation of experiments from ExperimentProvidern in Docs
Be able to support SlimBanner's primaryAction to toggle between active/inactive experiments to visualize changes from experiments.
Implemented in Textfield. See https://deploy-preview-2511--gestalt.netlify.app/web/textfield
Next ones:
> Docs: added cookies to support activation/deactivation of experiments from ExperimentProvidern in Docs

- docs/pages/web/text.js
- packages/gestalt/src/Text.js
Text: add forwardRef to component
Accessing the ref can be helpful to detect if the text is being truncated. This can be helpful when the Text component is using text nodes rather than strings. If we detect truncation, we can manually set the title prop.
We need this change to detect truncation inside Toast (which remove the helperLink) and therefore we can stack the helperLink again back at the toast so not to lose functionality.
> Text: add forwardRef to component

- docs/pages/get_started/designers.js
Fixed typo in designer getting started page (donts -> don'ts)
> Docs: Fix typo in designer getting started

- packages/gestalt/src/Tag.css
- packages/gestalt/src/Tag.js
- packages/gestalt/src/__snapshots__/ComboBox.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/Tag.test.js.snap
- packages/gestalt/src/__snapshots__/TextArea.test.js.snap
- packages/gestalt/src/__snapshots__/TextField.test.js.snap
Fix color disparity and update truncated view in dark mode
Before
After
> Tag: fix background color and dark mode

- docs/pages/web/table.js
- packages/gestalt/src/TableRowDrawer.js
Table.Drawer: fix subcomponent so no empty drawer shows no extra space
After dismissing SlimBanner
> Table.Drawer: fix subcomponent so no empty drawer shows no extra space

- docs/pages/foundations/iconography/ICON_DATA.json
- docs/pages/foundations/iconography/library.js
Add a tooltip for descriptions of Icons on the Icon Library page
Give designers and developers an example of when to use each icon
Note: Layla will be adding the rest of the descriptions in a follow up PR 
- [Figma](https://www.figma.com/file/RBlfOYmL123whCtlglXIsG/Iconography-page-redesign?node-id=360%3A3389&t=Ndz6EXOsnEahAIjm-0)
> Docs: Add Icon descriptions to library page

- docs/pages/web/toast.js
- packages/gestalt/src/Toast.css
- packages/gestalt/src/Toast.css.flow
- packages/gestalt/src/Toast.js
Toast: new Toast design adjustments
All changes behind experiments
| change      |  BEFORE | AFTER |
| ----------- | ----------- |  ----------- |
| Width under sm breakpoint: Fix so that below smallest breakpoint, width gets set to "100%"        |   ![Screen Shot 2022-11-28 at 5 12 47 PM](https://user-images.githubusercontent.com/10593890/204391966-46bb6b33-1ef3-4575-a3cd-4bd25c2a6235.png) ![Kapture 2022-11-28 at 11 45 45](https://user-images.githubusercontent.com/10593890/204334256-81ead66e-9fb6-4b45-87aa-d53d1a0e0baf.gif)     |    ![Kapture 2022-11-28 at 11 41 54](https://user-images.githubusercontent.com/10593890/204333199-42756f29-52ae-4072-b095-ea02b6a1da84.gif)    |
| lineClamp={2}       |    ![Screen Shot 2022-11-28 at 5 13 18 …
> Toast: new Toast design adjustments

- docs/pages/foundations/iconography/ICON_DATA.json
I added descriptions inside the tooltips at the icon library page.
To give designers and developers context on when to use each icon
- [Jira](https://jira.pinadmin.com/browse/GESTALT-5117)
- [Figma file](https://www.figma.com/file/RBlfOYmL123whCtlglXIsG/Iconography-page-redesign?node-id=214%3A6768&t=w5prB2kk5VTnVl9x-1)
> Add icon descriptions to library page

- docs/examples/modal/accessibilityExample.js
- docs/examples/modal/createBoardExample.js
- docs/examples/modal/limitActionsExample.js
- docs/examples/modal/preventCloseExample.js
- docs/examples/modal/sizesExample.js
- packages/gestalt/src/Modal.js
- packages/gestalt/src/ModalAlert.js
- packages/gestalt/src/__snapshots__/Modal.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/ModalAlert.jsdom.test.js.snap
We are changing internal padding. To prevent styling inside Modal breaking, we should set padding="default" into all Modals to keep the same style logic as before.
We also have to remove any padding in custom headings
Run the following codemod to locate Modals in the codebase and update them manually
`yarn codemod detectManualReplacement ~/path/to/your/code --component=Modal
`
**Codebase impact magnitude**
app/packages/gestaltExtensions/Modal/DesktopModal.js
app/packages/gestaltExtensions/Modal/MobileModal.js
Modal: add default padding to main content and heading and padding prop
Adding padding = {6} (24 px) in header and main content (footer already had). padding="none" removes padding = {6}  on main content
Style unification between Modal/Sheet
- …
> Modal: add default padding to main content and heading and padding prop

- docs/pages/web/box.js
- docs/pages/web/flex.js
We hide responsive props from the props table to reduce clutter. These recently-added props weren't added to GeneratedPropsTable's `excludeProps`, so this PR does that.
> Box, Flex: remove responsive alignItems props from table

- docs/examples/sidenavigation/counterExample.js
- docs/pages/web/sidenavigation.js
- packages/gestalt/src/SideNavigationGroupContent.js
- packages/gestalt/src/SideNavigationNestedGroup.js
- packages/gestalt/src/SideNavigationNestedItem.js
- packages/gestalt/src/SideNavigationTopItem.js
- packages/gestalt/src/__snapshots__/SideNavigation.test.js.snap
SideNavigation: support counters in all subcomponents
To support use cases like the one below needed in monetization
Best practices for this new feature to come soon.
> SideNavigation: support counter prop in all subcomponents

- .markdownlint.json
While linting markdown files can be useful (and we should fix our existing errors), [some of the rules](https://github.com/DavidAnson/vscode-markdownlint#rules) don't make sense with MDX. This PR adds a config file for `markdownlint` and eases a few rules:
- [MD013](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013) line-length - Line length, not applicable
- [MD033](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md033) no-inline-html - Inline HTML, kinda the whole point of MDX
- [MD034](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md034) no-bare-urls - Causes this error:
> Internal: add markdown lint config file, ease some rules

- docs/markdown/get_started/developers/contributing/development_process.md
- netlify.toml
The typical dev process across the team involves leaving a browser tab open to the dev site constantly, making it annoying to restart the dev server as it launches a new tab that needs to be closed. This PR removes that autolaunch feature.
> Internal: do not autolaunch browser in dev

- docs/examples/popover/a11y.js
- docs/examples/popover/doEducate.js
- docs/examples/popover/dontCaret.js
- docs/examples/popover/dontCritical.js
- docs/examples/popover/main.js
- docs/examples/popover/variantAnchor.js
- docs/examples/popover/variantColorCaret.js
- docs/examples/popover/variantIdealDirection.js
- docs/examples/popover/variantLayer.js
- docs/examples/popover/variantScrollingContainers.js
- docs/examples/popover/variantVisibility.js
- docs/pages/web/popover.js
Also added one new variant about Popover visibility on page load. Didn't modify content of existing examples, just migrated them as-is
> Popover: migrate docs examples to Sandpack

- docs/pages/web/iconbutton.js
Docs: fix manual prop table value on IconButton
> Docs: fix manual prop table value on IconButton 

- yarn.lock
This reverts commit 87d7e903eb45a73b496b55979c2ce80b269f1441.
This apparently broke the default values for autogen props tables?
> Internal: Revert "Bump minimatch from 3.0.4 to 3.0.8 (#2506)"

- packages/gestalt-codemods/generic-codemods/detectManualReplacement.js
- packages/gestalt-codemods/generic-codemods/modifyProp.js
- packages/gestalt-codemods/generic-codemods/modifyPropValue.js
- packages/gestalt-codemods/generic-codemods/renameComponent.js
Make it a bit easier on ourselves when copy-pasting the script examples into the terminal
> Internal: tweak generic codemods for easier copy/paste-ability

- docs/docs-components/GeneratedPropTable.js
- yarn.lock
This _actually_ fixes the broken autogen props defaults, introduced in #2504. This also reverts the revert of a dependabot patch, which wasn't the culprit (#2583).
> Internal: actually fix autogen props default values

- packages/gestalt/src/Contents.js
- packages/gestalt/src/__snapshots__/Controller.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/Dropdown.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/Popover.jsdom.test.js.snap
This change handle and fix the following error, reported to us by [this thread](https://pinterest.slack.com/archives/C13KLG5P0/p1658953735281499):
"When we have more content inner dropdown children than the viewport height supports and the anchor is positioned on second half (bottom half) of screen, the initial elements is not accessible" 
The images below provide you the bug view:
BUG's reproduction: https://codesandbox.io/s/dropdown-size-error-3jo09u
- Popover
- Dropdown
- Content
We fix the max height of children's Popover content to 90% of the viewport's vertical size. If the viewport contains a `ScrollBoundaryContainer` component, we use the height of this component to set the max height of popover content. In other words, the Popover max size is `90%  screen height` or `90% of …
> Popover: Controlled height based on size of contents

- docs/pages/foundations/iconography/ICON_DATA.json
- docs/pages/foundations/iconography/ICON_DATA.json.flow
- docs/pages/foundations/iconography/library.js
This PR uses [this tool](https://github.com/zth/json-to-flowtype-generator) to add Flow types for ICON_DATA.json using a [declaration file](https://flow.org/en/docs/declarations/). This prompted a few changes:
- Changing the `categories` field in the json object to always be an array — mixing types makes dealing with that field needlessly complicated
- Removed type declarations in `library.js`, since those are available from the declarations file
- - Removed output type from `findIconByCategory` helper in `library.js`, since those are available from the declarations file
> Internal: add Flow types to icon data

- docs/pages/RoadmapData.json
- docs/pages/RoadmapData.json.flow
- docs/pages/roadmap.js
This PR uses [this tool](https://github.com/zth/json-to-flowtype-generator) to add Flow types for RoadmapData.json using a [declaration file](https://flow.org/en/docs/declarations/). Additional changes:
- Changed (implied) `platform: string` to `platforms: $ReadOnlyArray<Platform>` for consistent platform names
- Lots of general cleanup and simplification
> Internal: add Flow declaration for roadmap data json

- docs/pages/BlogPosts.json.flow
- docs/pages/whats_new.js
This PR uses [this tool](https://github.com/zth/json-to-flowtype-generator) to add Flow types for RoadmapData.json using a [declaration file](https://flow.org/en/docs/declarations/). Also includes some minor related(ish) cleanup.
> Internal: add Flow declaration for blog posts json

- flow-typed/npm/@testing-library/user-event_v14.x.x.js
- packages/gestalt/src/ComboBox.jsdom.test.js
- packages/gestalt/src/TextArea.jsdom.test.js
- packages/gestalt/src/TextField.jsdom.test.js
`flow-typed` doesn't have a declarations file for our version of `@testing-library/user-event` (v14), but does have types for [the previous version](https://github.com/flow-typed/flow-typed/blob/e420967f1d88dc042409e9e70ac034ffb968a222/definitions/npm/%40testing-library/user-event_v13.x.x/flow_v0.104.x-/user-event_v13.x.x.js). This PR copy/pastes those v13 types into a flow-typed file for v14. This seems mostly correct so far, as it allows us to remove the "untyped-import" suppressions without surfacing any new errors. However, the API is likely slightly different for our version, so we should feel free to update these types in the future as needed if they don't seem to accurately reflect the API.
> Internal: add flow declarations for @testing-library/user-event

- docs/docs-components/YearInReviewBanner.js
- docs/graphics/year-in-review/lottie/discoStars.json.flow
- docs/graphics/year-in-review/lottie/figma.json.flow
- docs/graphics/year-in-review/lottie/pencil.json.flow
- docs/graphics/year-in-review/lottie/steps.json.flow
- docs/graphics/year-in-review/lottie/vibes.json.flow
- docs/pages/year_in_review_2022.js
This PR uses [this tool](https://github.com/zth/json-to-flowtype-generator) to add Flow types for the Lottie animation JSON files using [declaration files](https://flow.org/en/docs/declarations/).
> Internal: add Flow declarations for Lottie JSON animations

- docs/docs-components/contexts/DocsExperimentProvider.js
- docs/pages/web/textfield.js
- packages/gestalt/src/TextField.js
This PR ships the password visibility toggle experiments, ensuring that every `<TextField type="password">` shows a visibility icon button.
This makes for a more accessible and enjoyable UX, as the user confirm what they've entered before submitting the form.
We originally intended to run this as an experiment (in spirit with Project Ignite). Implementation ran into a number of issues with ExperimentProvider, and so never actually launched. However, we also discovered that other teams had implemented hacky versions of this feature on the primary login surfaces, so it's unlikely that we would have seen significant changes in user behavior in our experiment. Therefore we're shipping this feature and will replace the hacky versions as part of bumping the Pinboard version.
Note that this PR …
> TextField: Ship password visibility experiment

- docs/pages/foundations/iconography/ICON_DATA.json
- docs/pages/foundations/iconography/ICON_DATA.json.flow
- docs/pages/foundations/iconography/library.js
Add keywords to make a better search experience for the Icon library page 
Find icons by keywords instead of just exact icon name
- [Jira](https://jira.pinadmin.com/browse/GESTALT-5001)
- [Figma](https://www.figma.com/file/RBlfOYmL123whCtlglXIsG/Iconography-page-redesign?node-id=442%3A3384&t=U2cj3eIDMKoIpsEg-0)
> Icons: Add keywords to icon search page

- packages/gestalt-datepicker/src/DatePicker.js
- packages/gestalt-datepicker/src/DatePickerTextField.js
- packages/gestalt/src/AvatarGroup.js
- packages/gestalt/src/Button.js
- packages/gestalt/src/Checkbox.js
- packages/gestalt/src/ComboBox.js
- packages/gestalt/src/ComboBoxItem.js
- packages/gestalt/src/IconButton.js
- packages/gestalt/src/IconButtonFloating.js
- packages/gestalt/src/InternalDismissButton.js
- packages/gestalt/src/InternalTextField.js
- packages/gestalt/src/NumberField.js
- packages/gestalt/src/OptionItem.js
- packages/gestalt/src/RadioButton.js
- packages/gestalt/src/RadioGroupButton.js
- packages/gestalt/src/SearchField.js
- packages/gestalt/src/TapArea.js
- packages/gestalt/src/TextArea.js
- packages/gestalt/src/TextField.js
Replace usage of `React$AbstractComponent` with react's built in type `AbstractComponent`. 
They are pretty much the same thing 
If you option-click (also called hyber-click?) the AbstractComponent, you would see this:
```
declare export type AbstractComponent<
-Config,
+Instance = mixed,
> = React$AbstractComponent<Config, Instance>;
```
From @dangerismycat 
> The React$SomeType types are considered “internal”, so changes to them aren’t necessarily considered “breaking”. I’ve heard of folks recommending not using them, but I also see them being used everywhere, so functionally I don’t think the React team can make unannounced breaking changes to them without alienating a large part of their users.
Updated 19 files, for example: 
- More future proof to use the react implementation 
- I'm …
> Replace Flow React$AbstractComponent with React wrapper type AbstractComponent

- docs/docs-components/AppLayout.js
- docs/docs-components/Header.js
- docs/docs-components/IllustrationCard.js
- docs/docs-components/IllustrationContainer.js
- docs/docs-components/IllustrationSection.js
- docs/docs-components/Page.js
- docs/docs-components/PageHeader.js
- docs/docs-components/Toc.js
- docs/pages/foundations/iconography/library.js
- docs/pages/home.js
Update layout of Roadmap and Whats New page, fix mobile layout on home screen
Before
After
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4810)
- [Figma](https://www.figma.com/file/ZNDhPw1tHNgpLtaQploUSm/Docs-style-guide?node-id=208%3A11629&t=wNdtShZa74IcNA7x-0)
> Docs: Update site layout

- docs/pages/web/iconbutton.js
- docs/pages/web/pog.js
- packages/gestalt/src/IconButton.js
- packages/gestalt/src/Pog.js
Add an option for `iconColor` on IconButton to represent the Pinterest brand
Currently some IconButtons using the pinterest logo are not rendering the right shade of red
- [Jira](https://jira.pinadmin.com/browse/GESTALT-5175)
> IconButton: Add icon color option for Pinterest brand

- .github/workflows/release.yml
The release workflow previously used @christianvuerings's account, which isn't good. This PR updates the workflow to use the @pinterest-gestalt account that we use for other automated things.
> Internal: update release.yml to use pinterest-gestalt account

- .github/workflows/release.yml
#2603 didn't seem to work. Given these lines in the logs:
_before #2603_
```
remote: Permission to pinterest/gestalt.git denied to christianvuerings.
fatal: unable to access 'https://github.com/pinterest/gestalt/': The requested URL returned error: 403
```
_after #2603_
```
remote: Permission to pinterest/gestalt.git denied to pinterest-gestalt.
fatal: unable to access 'https://github.com/pinterest/gestalt/': The requested URL returned error: 403
```
This may be a permissions error. I know that my account definitely has permissions, so let's see if that works.
> Internal: update release.yml to use dangerismycat account

- packages/gestalt/src/Masonry.js
When testing migration from Flow to Typescript I get an error saying: 
> File: Masonry.ts - Error: Parameter 'props' of public static method from exported class has or is using private name 'T'.
- It seems like the proper way to type Flow Generics is to declare the `private name T` after the function name `getDerivedStateFromProps<Private Name Here>`
- Also I renamed `T` to `K` because I got an eslint error saying that T was already used 
There's an [issue in the Typescript](https://github.com/microsoft/TypeScript/issues/23465#issuecomment-382077840) project that references how to probably type `getDerivedStateFromProps`
> Before the change, the type of props.items for getDerivedStateFromProps must be consistent with the one for componentDidUpdate. After the change, it no longer does? So …
> Masonary: Update getDerivedStateFromProps  Flowtype

- packages/gestalt/src/Table/getChildrenCount.js
- packages/gestalt/src/TableRowDrawer.js
- packages/gestalt/src/TableRowExpandable.js
- packages/gestalt/src/__snapshots__/TableRowDrawer.test.js.snap
Table: fix unresponsive Table.Rowdrawer and Table.RowExpandable to wrapped children in React.Fragment
BEFORE
AFTER
Under the hood, Table uses Children.count to estimate the amount of colSpan + 1 but React.Fragment is evaluated as the only children so Table sets colspan for Drawer to 2 incorrectly.
> Table: fix unresponsive Table.Rowdrawer and Table.RowExpandable to wrapped children in React.Fragment

- docs/pages/visual-test/Masonry.js
- docs/pages/web/masonry.js
- packages/gestalt/src/Collage.js
- packages/gestalt/src/Collection.js
- packages/gestalt/src/Collection.test.js
- packages/gestalt/src/Masonry.flowtest.js
- packages/gestalt/src/Masonry.js
This reverts commit d41bdf7e37c38b8f4de8125880f0016033a8f450, which was accidentally merged without CI and code review
> Revert "Masonry: deprecate Item prop in favor of renderItem prop"

- docs/pages/visual-test/Masonry.js
- docs/pages/web/masonry.js
- packages/gestalt/src/Collage.js
- packages/gestalt/src/Collection.js
- packages/gestalt/src/Collection.test.js
- packages/gestalt/src/Masonry.flowtest.js
- packages/gestalt/src/Masonry.js
This PR adds a prop to the Masonry API. This prop is optional for now, but will eventually become required.
No changes are required now, but if you want to get a head start: run the following codemod to detect Masonry in your code base.
```
--component=Masonry
```
You can also automate the renaming: 
```
yarn codemod modifyProp ~/path/to/your/code
--component=Masonry
--previousProp=Items
--nextProp=renderItems
```
but still need to change the value manually following the steps described below:
In `Masonry`, deprecate the `Item` prop (which is expected to be a React component) in favor of `renderItem`, which can be any function that returns a React Node.
When React renders the `<App />` component here:
```ts
const MyGrid = ({ Item }) …
```
> Masonry: replace the `Item` prop with the `renderItem` prop

- docs/docs-components/PageHeader.js
Our [What's New blog](https://gestalt.pinterest.systems/whats_new) and [changelog](https://github.com/pinterest/gestalt/blob/master/CHANGELOG.md) can be useful, but often users want to see what changes have been made to a given component recently. We can explore more precise methods in the future (possibly using the GitHub API to look at specific file changes), but as a first step this PR adds a link that goes to a list of our releases, filtered by the component name. This isn't perfect — "Button" gets a lot of false hits given the prevalence of the word "button" — but it's a start.
In this example, the link will go to https://github.com/pinterest/gestalt/releases?q=ButtonGroup&expanded=true.
> Docs: add recent changes link to component pages

- docs/pages/integration-test/masonry.js
- docs/public/robots.txt
As a prereq for future integration tests, this PR adds a new route: `/integration-test/masonry`. For now it's a recreation of the simple example we use on the Masonry docs page (converted to a function component, which I'll migrate to the docs page eventually). I'll probably need to tweak this (maybe a lot) in the future — this is just a first step.
This PR also creates a [robots.txt](https://developers.google.com/search/docs/crawling-indexing/robots/create-robots-txt) file to prevent Google (and others) from crawling the visual test and integration test pages. I also disallowed these from the Algolia crawler in that config, which isn't really necessary since they're not linked anywhere.
> Masonry: add route for future integration tests

- docs/examples/defaultlabelprovider/translations.js
- docs/examples/sheet/defaultExample.js
- docs/pages/web/sheet.js
- packages/gestalt/src/InternalSheet.js
- packages/gestalt/src/Sheet.js
- packages/gestalt/src/Sheet.jsdom.test.js
- packages/gestalt/src/SheetConfirmationPopover.js
- packages/gestalt/src/__snapshots__/Sheet.jsdom.test.js.snap
- packages/gestalt/src/contexts/DefaultLabelProvider.js
- packages/gestalt/src/contexts/DefaultLabelProvider.jsdom.test.js
Sheet: implement dismiss confirmation modal and dismissConfirmation prop #2630
It's been a long-time request from eng. Some Sheets have forms in them and dismissing the Sheet leads to losing the information entered. 
There are 6 action point for dismissing Sheet:
1. ESC key >> component controlled
2. Dismiss button >> component controlled
3. Backdrop click >> component controlled
4. onDismissStart render prop (subheading) >> Eng has access and control
5. onDismissStart render prop (content) >> Eng has access and control
6. onDismissStart render prop (footer) >> Eng has access and control
`dismissConfirmation` forces confirmation from user if it tries to dismiss Sheet via 1,2,3 action points.
It renders a Popover that alerts the user and request user action.
- …
> Sheet: implement dismiss confirmation modal and `dismissConfirmation` prop

- docs/docs-components/AppLayout.js
- docs/integration-test-helpers/masonry/ExampleGridItem.js
- docs/integration-test-helpers/masonry/MasonryContainer.js
- docs/integration-test-helpers/masonry/getClassicGridServerStyles.js
- docs/integration-test-helpers/masonry/getFlexibleGridServerStyles.js
- docs/integration-test-helpers/masonry/items-utils.js
- docs/pages/integration-test/masonry.js
- docs/pages/web/masonry.js
The component I'll need for the Masonry integration test route is considerably more complex than the simple one I'd copied over from the docs page. However, I'd also refactored and cleaned up that docs example when I migrated it over, which I don't want to lose.
This PR does two things:
- Replaces the previous `/integration-test/masonry` view with a much more complex one, migrated from Pinboard
- Updates the docs Masonry example with the refactored one
> Internal: improve Masonry a11y test route, refactor docs example

- docs/docs-components/handleCodeSandbox.js
Internal: fix "open in codesandbox" dependencies
Fixes a bug when opening codesandbox from example in Datepicker
> Internal: fix "open in codesandbox" dependencies

- docs/docs-components/COMPONENT_DATA.js
- docs/docs-components/PageHeader.js
Docs: improve 'See recent changes on GitHub" by including previous component names
BEFORE
AFTER
> Docs: improve 'See recent changes on GitHub" by including previous component names

- packages/gestalt/src/List.css
Replaced `padding-inline-start` with `padding-start ` & `padding-left` with RTL logic in CSS files.
BEFORE
AFTER
`padding-inline-start` was first use in List. It seems it was being lost after CSS compilation in Sandpack code editor and pinterest.developers.com
Seems related to https://github.com/csstools/postcss-preset-env/issues/210
> List: fix style issue replacing uncompiling `padding-inline-start` with `padding-right/left`

- packages/gestalt-datepicker/package.json
- packages/gestalt/package.json
We upgraded to React 18 back in #2104, but didn't start using any new features until the introduction of SideNavigation in #2185. While the `react` dependency in `package.json` was correct, the `react` and `react-dom` peer dependencies in `/packages/gestalt/package.json` and `/packages/gestalt-datepicker/package.json` still indicated that React 16 & 17 were supported. We now have multiple components that use React 18-only features, so we need to officially remove 16 & 17 as acceptable peer dependencies.
This PR does not add specific documentation around this, as we don't specifically call out any of our dependencies in the docs. If we keep getting questions about it in the future, we can add documentation as needed.
> Internal: match peer dependencies to actual usage

- packages/gestalt/src/zIndex.js
ZIndex: fix Flow types to prevent Flow error when passing zIndexs from props to CompositeZIndex
> ZIndex: fix Flow types

- docs/pages/integration-test/masonry.js
- package.json
- playwright/masonry/fetch-more.spec.mjs
- playwright/masonry/utils/getServerURL.mjs
- playwright/masonry/utils/resizeWidth.mjs
- playwright/masonry/utils/selectors.mjs
- playwright/masonry/utils/waitForRenderedItems.mjs
Once upon a time there existed a suite of integration tests for Masonry. It first lived in this repo, then was migrated to Pinboard, then was turned off, then was deleted. womp womp.
This PR is the first of many adding this test suite back. The approach is fairly different, using a regular (but unlinked) route on our docs site instead of setting up a bespoke mini-app, and using Playwright instead of Puppeteer.
I started with a test that I thought looked pretty simple, but really had no idea. The test file has two tests. The first test now passes completely. The second test no longer throws any errors, but also times out without passing. I'm still trying to debug what's going on there, but I wanted to get this code checked in to get other 👀 on it, and I'll keep chipping away at the skipped …
> Internal: add first integration test for Masonry

- docs/examples/sidenavigation/localizationExample.js
- docs/examples/sidenavigation/primaryAction.js
- docs/pages/web/sidenavigation.js
- packages/gestalt/src/OptionItem.js
- packages/gestalt/src/SideNavigation.js
- packages/gestalt/src/SideNavigation.jsdom.test.js
- packages/gestalt/src/SideNavigationGroup.js
- packages/gestalt/src/SideNavigationGroupContent.js
- packages/gestalt/src/SideNavigationGroupMobile.js
- packages/gestalt/src/SideNavigationIconButton.js
- packages/gestalt/src/SideNavigationMobile.js
- packages/gestalt/src/SideNavigationTopItem.js
- packages/gestalt/src/__snapshots__/SideNavigation.test.js.snap
SideNavigation: implemented `primaryAction` prop to allow actions on SideNavigation.TopItem and SideNavigation.Group
DESKTOP
MOBILE
DESKTOP VOICEOVER
FOLLOWUP to clean code: alphabetize, dry, etc
Add new features for m10n teams
> SideNavigation: implemented `primaryAction` prop to allow actions on SideNavigation.TopItem and SideNavigation.Group

- docs/docs-components/AppLayout.js
Given it's nearly March, it seems appropriate to remove the 2022 year in review banner.
> Docs: Remove Year in Review banner

- docs/examples/scrollboundarycontainer/autoOverflowExample.js
- docs/examples/scrollboundarycontainer/modalExample.js
- docs/examples/scrollboundarycontainer/popoverExample.js
- docs/examples/scrollboundarycontainer/visibleOverflowExample.js
- docs/pages/web/utilities/scrollboundarycontainer.js
- packages/gestalt/src/ScrollBoundaryContainer.js
- packages/gestalt/src/ScrollBoundaryContainerWithForwardRef.js
ScrollBoundaryContainer: add 'visible' to `overflow` prop type, documented case, and move editor to Sandpack
In some cases, we might want to anchor Popover to a small container that will never overflow/scroll, when the parent container does scroll. Visible allows Popover to not hide within the small container. We've experienced some complex implementations where ScrollBoundaryContainer at higher prents doesn't fix floating issues, so moving ScrollBoundaryContainer closer to Popover is needed.
https://user-images.githubusercontent.com/10593890/220972873-f6aec12d-cd25-42c7-98dd-e280467cec89.mov
> ScrollBoundaryContainer: add 'visible' to `overflow` prop type, documented case, and move editor to Sandpack

- docs/examples/popovereducational/customContent.js
- docs/examples/popovereducational/doEducate.js
- docs/examples/popovereducational/doReference.js
- docs/examples/popovereducational/dontDouble.js
- docs/examples/popovereducational/main.js
- docs/examples/popovereducational/message.js
- docs/examples/popovereducational/primaryAction.js
- docs/examples/popovereducational/size.js
- docs/examples/popovereducational/visibility.js
- docs/pages/web/popovereducational.js
- packages/gestalt/src/PopoverEducational.js
- packages/gestalt/src/__snapshots__/Popover.jsdom.test.js.snap
PopoverEducational: move examples to Sandpack + added `shouldFocus` to props
> PopoverEducational: move examples to Sandpack + added `shouldFocus` to props

- docs/examples/helpbutton/endGuideElement.js
- docs/examples/helpbutton/intermixedBlocks.js
- docs/examples/helpbutton/withLink.js
- docs/examples/helpbutton/withText.js
- docs/pages/web/helpbutton.js
Remove duplicates examples on HelpButton doc page
Our current version of `sandpack` not allowed us to use the development build to test our features, so is requested to test the new page use the `Example` component and after merge we should send a new PR removing these temporary ones.
> HelpButton: Remove duplicated examples on doc page

- docs/integration-test-helpers/masonry/MasonryContainer.js
- docs/pages/integration-test/masonry.js
- playwright/masonry/flexible-resize.spec.mjs
- playwright/masonry/handle-item-updates.spec.mjs
- playwright/masonry/handle-position-update.spec.mjs
- playwright/masonry/utils/getGridItems.mjs
- playwright/masonry/utils/getServerURL.mjs
- Fixed up some Flow types, which uncovered a prop error
- Added support for `flexible` query param to Masonry integration test route
- Pulled out `getGridItems` as a util
- Added `flexible-resize` integration test
> Internal: add Masonry `flexible-resize` integration test

- docs/pages/integration-test/masonry.js
- playwright/masonry/parent-sizing.spec.mjs
- playwright/masonry/utils/getServerURL.mjs
Also adds support for `constrained` and `finiteLength` query params
> Internal: add Masonry `parent-sizing` integration test

- docs/markdown/ios/toast.md
Updated iOS toast images to represent upcoming work and added/fixed text to clarify.
> Toast: Updates to iOS images in Docs

- packages/gestalt/src/Contents.js
- packages/gestalt/src/Controller.js
- packages/gestalt/src/Dropdown.js
- packages/gestalt/src/Popover.js
We add the new property `maxHeight` to Dropdown component to control the size of Popover container and  removing `ScrollBoundaryContainer` calculation when this property is defined.
To understand better, please read the thread: https://pinterest.slack.com/archives/C13KLG5P0/p1676662974832019
https://capture.dropbox.com/tCVVMlf5LTJoLY7q
> Dropdown, Popover: Add `maxHeight` prop

- .eslintrc.json
- packages/gestalt-datepicker/rollup.config.js
- packages/gestalt/rollup.config.js
- packages/gestalt/src/contexts/__mocks__/DefaultLabelProvider.js
This rule is preventing us from keeping our main directory clean by moving child components into directories. Eventually we should add a webpack resolver to allow us to use absolute paths for all imports.
> Internal: turn off `import/no-relative-parent-imports` lint rule

- packages/gestalt/src/Masonry.js
In [a previous PR](https://github.com/pinterest/gestalt/pull/2616), @jackhsu978 introduced `renderItem` to replace Masonry's `Item` prop. Now that we've refactored all usages in Pinboard, this PR removes `Item` and makes `renderItem` required.
** CODEMOD
I recommend manually updating:
```bash
--component=Masonry
```
> Masonry: remove `Item` prop

- .eslintrc.json
This rule doesn't help us with our docs examples, where we want to avoid directing the user off our docs site.
> Internal: turn off `jsx-a11y/anchor-is-valid` for docs examples

- docs/pages/foundations/forms/available_components.js
There was an extra TextField example on the Available components page. It was removed.
Removed TextField2.
It's not needed. Was left over from copy and pasting examples.
> Docs: remove extra TextField on Foundations forms

- docs/examples/toast/success.js
- docs/pages/web/toast.js
a few missed in #2551 because GitHub's UI likes to hide comments from the viewer 😒
> Toast: fix typos in docs

- docs/docs-components/docgen.js
- docs/pages/web/button.js
- packages/gestalt/src/Button.js
- packages/gestalt/src/InternalLink.js
- packages/gestalt/src/ModalAlert.js
- packages/gestalt/src/ModalAlert/ModalAlertAction.js
- packages/gestalt/src/ModalAlert/ModalAlertHeader.js
Adding `dataTestId` to the actions on ModalAlert, which necessitates also adding that prop to Button.
_(note the URL, linking to RTL docs trying to convince people not to use dataTestIds for unit tests)_
Request from a team refactoring a custom modal to use ModalAlert. Needed for integration tests, where we prefer to use stable test ids rather than labels that may change.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-5886)
> ModalAlert, Button: add dataTestId

- packages/gestalt/src/Pog.css
This is a weird one. 
To support RTL languages, we rotate some icons by 180 rather than use a different SVG. On mobile Safari (device only!), this presents a problem:
Apparently this is a known bug on mobile Safari going back to at least 2015 (!) and still not fixed. Actually, it's kind of a combination of two bugs:
- [mobile Safari can't handle rotating SVGs in multiples of 90](https://9to5answer.com/svg-transform-rotate-by-90-180-or-270-degrees-not-working-on-circle-in-safari-ios-10)
- [mobile Safari can't handle rotating SVGs at all](https://stackoverflow.com/a/28617071/5253702)
Though it wouldn't be a shippable solution, I explored the "90° problem" by adjusting our rotation to 179°. The results are…not great:
It turns out the real solution is to add [the CSS property …
> Pog, IconButton: bugfix for rotated icons on iPhone

- packages/gestalt/src/IconButtonFloating.js
This PR is adding a property `disabled` to IconButtonFloating.
[This deprecation ticket](https://jira.pinadmin.com/browse/GESTALT-5478) is changing a Pinboard code based which has the follow behaviour:
1. While the user not select one of pins on organize screen, the IconButtonFloating, on footer of screen, should be disabled;
2. After one of pins is selected the IconButtonFloating should be enabled;
To get more context, please look at [this video](https://capture.dropbox.com/8RzrpABsVStH5XpS)
The video above was sent to @hectoid and @ponori and both of them understanding the `disabled` prop should be present on this component.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-5478)
> IconButtonFloating: Add `disabled` prop

- packages/gestalt/src/IconButtonFloating.js
This PR is adding a property `dangerouslySetSvgPath` to IconButtonFloating.
[This deprecation ticket](https://jira.pinadmin.com/browse/GESTALT-5478) is changing a Pinboard code based which has two icons out of our library but is in review of our Design System team.
The current solution is to keep the icons until their added to our code base;
- [Jira](https://jira.pinadmin.com/browse/GESTALT-5478)
> IconButtonFloating - Add `dangerouslySetSvgPath` prop

- docs/docs-components/COMPONENT_DATA.js
This needs to be replaced with a MobileSheet SVG when we have it
> OverlayPanel: remove from iOS/Android overview pages

- package.json
- yarn.lock
Addressing [this vulnerability](https://github.com/pinterest/gestalt/security/dependabot/73). The [Dependabot PR](https://github.com/pinterest/gestalt/pull/2763) is failing lots of tests, likely due to the `cssnano` major version bump.
Tracing how this sub-sub-sub-dependency is used:
nth-check
- css-select
- svgo
- postcss-svgo
- cssnano-preset-default
- cssnano *
- babel-plugin-inline-react-svg *
* = dependency in package.json
> Internal: Add resolution for `nth-check` to address vulnerability

- docs/docs.css
- docs/pages/get_started/designers.js
Removed references to legacy plugins and added a promo image to highlight the Pinterest Design plugin.
> Docs: Cleaned up our Figma plugins section

- docs/redirects.js
This page was removed in #2762
> Docs: add redirect for "How to work with us" page

- docs/examples/modalalert/doClearCommunicate.js
- docs/examples/modalalert/doExplainWhy.js
- docs/examples/modalalert/doLimitContent.js
- docs/examples/modalalert/doProvideAction.js
- docs/examples/modalalert/dontDoubleOverlay.js
- docs/examples/modalalert/dontHardLanguage.js
- docs/examples/modalalert/dontLeaveOutAction.js
- docs/examples/modalalert/dontLeaveOutExplanation.js
- docs/examples/modalalert/dontLongContent.js
- docs/examples/modalalert/errorMultiAction.js
- docs/examples/modalalert/errorSingleAction.js
- docs/examples/modalalert/main.js
- docs/examples/modalalert/mobileExample.js
- docs/examples/modalalert/multipleActions.js
- docs/examples/modalalert/singleAction.js
- docs/examples/modalalert/warningMultiAction.js
- docs/examples/modalalert/warningSingleAction.js
- docs/examples/modalalert/withCheckbox.js
#2787 introduced changes that caused ModalAlert examples to require user interaction to be visible, degrading the UX. This PR makes sure that the examples are visible as the user scrolls through the page.
> ModalAlert: make sure docs examples are open without user interaction

- docs/examples/iconbuttonfloating/doForScroll.js
- docs/examples/iconbuttonfloating/dontNegative.js
- docs/examples/iconbuttonfloating/dontNotification.js
- docs/examples/iconbuttonfloating/variantsA11y.js
- docs/examples/iconbuttonfloating/variantsWithTooltip.js
- docs/pages/visual-test/IconButtonFloating-dark.js
- docs/pages/visual-test/IconButtonFloating.js
- docs/pages/web/iconbuttonfloating.js
- packages/gestalt/src/IconButtonFloating.js
This PR adds a required `tooltip` prop to IconButtonFloating. The prop value is identical to IconButton's.
For the same reason we added `tooltip` to IconButton: icon meaning is not always obvious to the user, and providing a tooltip gives the user more context so they know what to expect when interacting with the button.
IconButtonFloating usage is still very low (2 instances in Pinboard currently), so jumping straight to a required prop isn't a big lift.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-6028)
> IconButtonFloating: add required `tooltip` prop

- docs/pages/web/table.js
- packages/gestalt/src/Table.css
- packages/gestalt/src/Table.css.flow
- packages/gestalt/src/Table.js
- packages/gestalt/src/TableFooter.js
- packages/gestalt/src/TableHeader.js
- packages/gestalt/src/__snapshots__/TableFooter.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/TableHeader..jsdom.test.js.snap
Table: implemented header/footer borders
Scrolling borders
Fixed borders
- [Jira](https://jira.pinadmin.com/browse/GESTALT-5934)
- [Figma](https://www.figma.com/file/HbBD5AgCNvupMVKBkTgdsH/Table-Enhancements?node-id=611-49291&t=rMa6Dw7RQUHf6B2q-0)
> Table: implemented header/footer borders

- docs/examples/table/controlledExpandable.js
- docs/examples/table/main.js
- docs/examples/table/uncontrolledExpandable.js
- docs/pages/web/table.js
- packages/gestalt/src/TableRowDrawer.js
- packages/gestalt/src/TableRowExpandable.js
Table: implement controlled Table.RowExpanded
So engineers can leave some Table.RowExpanded open based on use case.
> Table: implement controlled Table.RowExpanded with `expanded` prop

- docs/docs.css
Dark mode shows a paragraph highlight.
Changing paragraphs to a transparent background. Didn't find instances of where a fixed bg color was needed. Turns out for most MD pages w/ paragraphs, this seems like an issue.
> Docs: Removing Paragraph BG Color for MD documents

- docs/examples/datepicker/main.js
- docs/examples/datepicker/selectLists.js
- docs/pages/web/datepicker.js
- packages/gestalt-datepicker/package.json
- packages/gestalt-datepicker/src/DatePicker.css
- packages/gestalt-datepicker/src/DatePicker.js
- packages/gestalt-datepicker/src/DatePicker.jsdom.test.js
- packages/gestalt-datepicker/src/DatePickerTextField.js
- yarn.lock
No codemod needed. We are removing virtual keyboard support for DatePicker so they don't conflict with each other. Also, upgrading react-datepicker to 4.0.0
DatePicker: added Year/Month dropdown options + DatePicker:  remove virtual keyboard on mobile
https://user-images.githubusercontent.com/10593890/229939820-76c3a6c0-d38b-477d-96a8-0dfd9f75f889.MP4
Also, 
Upgraded library to 4.0.0. to get latest Popper v2. utils.
DatePicker: add 'inputMode' = none to internal TextField to only show calendar, and don't display …
> DatePicker: added Year/Month dropdown options, removed virtual keyboard, upgraded react-datepicker to 4.0.0

- docs/examples/numberfield/enterKeyHint.js
- packages/gestalt-datepicker/src/DatePickerTextField.js
- packages/gestalt/src/NumberField.js
- packages/gestalt/src/NumberField.test.js
- packages/gestalt/src/TextField.js
- packages/gestalt/src/TextField.test.js
- packages/gestalt/src/TextField/InternalTextField.js
```
yarn codemod modifyProp ~/path/to/your/code
--component=TextField
--previousProp=inputMode
--nextProp=mobileInputMode
```
```
yarn codemod modifyProp ~/path/to/your/code
--component=TextField
--previousProp=enterKeyHint
--nextProp=mobileEnterKeyHint
```
```
yarn codemod modifyProp ~/path/to/your/code
--component=NumberField
--previousProp=enterKeyHint
--nextProp=mobileEnterKeyHint
```
TextField, NumberField: prefix 'mobile' to mobile only props: inputMode & enterKeyHint
Provide clarity to API. These props are only to be used in mobile web experiences.
> TextField, NumberField: prefix 'mobile' to mobile only props: inputMode & enterKeyHint

- docs/docs-components/MarkdownPage.js
- docs/markdown/android/avatar.md
- docs/markdown/android/checkbox.md
- docs/markdown/android/switch.md
- docs/markdown/android/toast.md
- docs/markdown/ios/avatar.md
- docs/markdown/ios/checkbox.md
- docs/markdown/ios/icon.md
- docs/markdown/ios/switch.md
- docs/markdown/ios/toast.md
- docs/pages/BlogPosts.json
- docs/pages/whats_new.js
Change image container so that the darkmode bg is white
Remove padding by default on all images. Can be added again with `addPadding` flag
> Docs: Add white bg to darkmode images, remove padding

- docs/docs-components/SandpackExample.js
- docs/pages/web/modal.js
- docs/pages/web/modalalert.js
- docs/pages/web/sheetmobile.js
- docs/pages/web/sidenavigation.js
Docs: fix mobile examples display
> Docs: fix mobile examples display

- docs/pages/foundations/iconography/ICON_DATA.json
- packages/gestalt/src/icons/briefcase.svg
- packages/gestalt/src/icons/index.js
1. New icon for the m10n interface
Added the briefcase icon for use in ads as a business manager icon.
A new icon for an alpha release.
> Icon: add "briefcase" icon

- package.json
- yarn.lock
Addressing [this security vulnerability](https://github.com/pinterest/gestalt/security/dependabot/74)
We use this package directly, and it's a sub-dependency, so this PR both bumps our version and adds a resolution. Our direct usage is part of parsing SVGs during our build process, so if those appear fine, we should be ok. It's a sub-sub-sub-(etc)-dependency for `netlify-cli`, which we are woefully behind on, so a resolution is the preferred fix.
> Internal: upgrade xml2js to 0.5.0

- packages/eslint-plugin-gestalt/rollup.config.js
- packages/gestalt-datepicker/rollup.config.js
- packages/gestalt/rollup.config.js
Stop generating inline sourcemaps for our dist bundles and generate separate .map files instead.
Our rollup configs are currently configured to generate inline sourcemaps, which means the sourcemap information is added to the generated bundle. This is convenient for development, but horrible for bundle size. Instead, we can change the configuration to generate separate .map files which will still allow consumers to have access to sourcemaps without the bundle size cost
Based on local testing, this should cut down bundle sizes for gestalt and gestalt-datepicker by well over 50%
> Internal: Stop generating inline sourcemaps

- docs/examples/link/accessibilityBoxes.js
- docs/examples/link/accessibilityTiers.js
- docs/examples/link/doClarity.js
- docs/examples/link/doDisplayExternal.js
- docs/examples/link/doMatchStyle.js
- docs/examples/link/doMeaning.js
- docs/examples/link/doUnderline.js
- docs/examples/link/doWeightLists.js
- docs/examples/link/dontGeneric.js
- docs/examples/link/dontMultiple.js
- docs/examples/link/dontOtherIcons.js
- docs/examples/link/dontOveruse.js
- docs/examples/link/dontUnderlineLists.js
- docs/examples/link/dontWeightTexts.js
- docs/examples/link/main.js
- docs/examples/link/variantExternalIcon.js
- docs/examples/link/variantHiddenUnderline.js
- docs/examples/link/variantInlineLink.js
- docs/examples/link/variantInlineOverride.js
- docs/examples/link/variantLinkText.js
- docs/examples/link/variantRel.js
- docs/examples/link/variantStandaloneLink.js
- docs/examples/link/variantTarget.js
- docs/pages/web/link.js
Migrated examples in the docs from the old editor to the sandpack editor for the Link component.
Ensures the editor remains consistent with other components, as part of the current migration efforts.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4874)
- [ N/A ] Added unit and Flow Tests
- [ N/A ] Added documentation + accessibility tests
- [ Yes ] Verified accessibility: keyboard & screen reader interaction
- [ Yes ] Checked dark mode, responsiveness, and right-to-left support
- [ TBD ] Checked stakeholder feedback (e.g. Gestalt designers)
> Link: Convert examples to use Sandpack

- .flowconfig
- package.json
- yarn.lock
[Release notes](https://github.com/facebook/flow/releases/tag/v0.188.2)
This gets us closer to parity with Pinboard. The next few upgrades will be more work — this is as far as we can get without running codemods or making other changes, which we'll address in future PRs.
> Internal: upgrade Flow to 0.188.2

- .eslintrc.js
- docs/docs-components/SandpackExample.js
- docs/docs-components/buttons/CodeExampleDarkModeButton.js
- docs/docs-components/buttons/CodeExampleTextDirectionButton.js
- packages/gestalt/src/Layout.css
- packages/gestalt/src/Layout.css.flow
- packages/gestalt/src/contexts/ColorSchemeProvider.js
- packages/gestalt/src/contexts/ColorSchemeProvider.jsdom.test.js
Sandpack is awesome overall. But unfortunately due to how it renders examples in iframes, we lose the surrounding app context, most noticeably with dark mode and text direction. However, I've never been happy with needing to toggle dark mode or text direction for the entire site just to see how a single example responds — it's very disorienting, particularly text direction. 
This PR adds a couple of buttons to every Sandpack example (that we show any buttons for) to allow the user to toggle dark mode and text direction on a per-example basis. We track these clicks as with any other, so we can monitor usage. The icons used for text direction seem fine to me. The dark mode ones should be considered temporary; it'd be great to use a 🌞 / 🌚  combo as seen on most other sites.
Note that I …
> Docs: add support for dark mode and RTL in Sandpack examples

- docs/docs-components/SandpackExample.js
When the user updates the "global" dark mode or text direction setting, let's update all the examples too.
> Docs: update dark mode and text direction from "global" when changed

- packages/gestalt/src/Box.css
Box, Textfield, TextArea: fixed `visuallyHidden` prop CSS configuration, fixed bug in overflowing `maxLength.errorAccessibilityLabel`
Anything contained within a `visuallyHidden` Box should not overflow, as it creates ghostly empty spaces.
https://jira.pinadmin.com/browse/BUG-158982
> Box, Textfield, TextArea: fixed `visuallyHidden` prop CSS configuration, fixed bug in overflowing `maxLength.errorAccessibilityLabel`

- docs/docs-components/Header.js
Now that we have per-example toggles for dark mode and text direction, we can simplify our "global" toggles in the docs header. This PR removes the dropdown menu and replaces that icon button with one for dark mode, and conditionally adds another icon button for dev mode when in dev mode.
Note: the icon color choice for the dev mode button isn't ideal, but we don't offer a good alternative (and this isn't public-facing). Ideally we'd use green to match the border around the code examples.
_light mode_
_dark mode_
_default dev mode_
_old-style dev mode_
> Docs: update header icon button toggles

- packages/gestalt-datepicker/src/DateField.css
DateField: undoing ._gestalt in DateField.css file as it breaks style
It didn't work as I expected. I tested it but I guess I didn't get the changes right when I did it.
> DateField: undoing ._gestalt in DateField.css file as it breaks style

- docs/docs-components/SandpackExample.js
- docs/examples/text/doMinimalStyle.js
- docs/examples/text/doStartAlign.js
- docs/examples/text/doUseSize.js
- docs/examples/text/doWeight.js
- docs/examples/text/dontCenterAlign.js
- docs/examples/text/dontMixStyles.js
- docs/examples/text/dontUnderline.js
- docs/examples/text/dontUseHierarchy.js
- docs/examples/text/main.js
- docs/examples/text/variantAlignment.js
- docs/examples/text/variantBoxInline.js
- docs/examples/text/variantColors.js
- docs/examples/text/variantOverflowTruncation.js
- docs/examples/text/variantRefs.js
- docs/examples/text/variantSizes.js
- docs/examples/text/variantStyles.js
- docs/examples/text/variantTitle.js
- docs/pages/web/text.js
Migrated examples in the docs from the old editor to the sandpack editor for the Text component.
Ensures the editor remains consistent with other components, as part of the current migration efforts.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4871)
- [ N/A ] Added unit and Flow Tests
- [ N/A ] Added documentation + accessibility tests
- [ Yes ] Verified accessibility: keyboard & screen reader interaction
- [ Yes ] Checked dark mode, responsiveness, and right-to-left support
- [ TBD ] Checked stakeholder feedback (e.g. Gestalt designers)
> Text: convert examples to use Sandpack

- packages/gestalt/src/TextField/InternalTextFieldIconButton.js
TextField includes margin spacing to the right of the icon button that appears on `type="password"`. This margin is included in the tooltip triggering area, which causes the tooltip to be triggered when the user hovers over the area to the right of the icon button. This can interfere with layouts in certain situations. This PR moves the tooltip triggering area to only enclose the icon button and not the margin as well.
_the margin in question_
_before_
_after_
> TextField: fix tooltip triggering on icon button

- docs/docs-components/Overview.js
- docs/pages/foundations/color/examples.js
- docs/pages/foundations/iconography/library.js
- docs/pages/foundations/iconography/usage.js
- docs/pages/web/link.js
- docs/pages/web/sheetmobile.js
- docs/redirects.js
- packages/gestalt/src/TextField.js
found from `3xx` and `4xx` results on Algolia crawls
> Docs: fix outdated/incorrect links

- docs/pages/web/link.js
Fixed the cases where code examples should open vertically but were opened to the side instead.
Some change recently may have changed the default direction of code expanding, thus cases where the direction wasn't explicit were now opening incorrectly.
- [Link docs page](https://gestalt.pinterest.systems/web/link)
- [ N/A ] Added unit and Flow Tests
- [ N/A ] Added documentation + accessibility tests
- [ Yes ] Verified accessibility: keyboard & screen reader interaction
- [ Yes ] Checked dark mode, responsiveness, and right-to-left support
- [ Yes ] Checked stakeholder feedback (e.g. Gestalt designers)
> Link: Fixing code not expanding vertically

- packages/gestalt/src/PopoverEducational.js
accessibilityLabel is now not a required prop in PopoverEducational
It shouldn't have been required, given in many cases there is no context to define an appropriate specific accessibilityLabel, and a default is provided by the component.
> PopoverEducational: changing `accessibilityLabel` prop to optional

- docs/integration-test-helpers/masonry/MasonryContainer.js
- docs/pages/integration-test/masonry.js
- packages/gestalt/src/Masonry.js
- packages/gestalt/src/Masonry/MeasureItems.js
- playwright/masonry/utils/getServerURL.mjs
Currently Masonry measures and paints items sequentially, like
```
measure
paint
measure
paint
measure
paint
```
We're probably going to need to alter this behavior for future 2-col module work. @liuyenwei had the idea to test out that change independent of the modules and algorithm changes, by batching paints. So we'd instead do something like
```
measure
measure
measure
paint
paint
paint
```
in the hope that the browser can batch the paints together, which would be more efficient and performant.
This PR introduces a mechanism to experimentally batch Masonry paints, which we can run immediately to start testing out hypotheses around batching performance.
Preliminary perf output looks promising…
_no batching_
_batching, reading clientHeight and setting immediately_
_batching, also …
> Masonry: add experimental prop to batch paints

- docs/examples/table/main.js
- packages/gestalt/src/NewTabAccessibilityLabel.js
- packages/gestalt/src/__snapshots__/Dropdown.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/Link.test.js.snap
Link, Button, TapArea, IconButton: fix default label to target="blank".
BEFORE
inline block 
vs inline
AFTER
> Link, Button, TapArea, IconButton: fix default label to target="blank".

- docs/pages/web/textarea.js
- packages/gestalt/src/TextArea.js
- packages/gestalt/src/__snapshots__/TextArea.test.js.snap
Set max-height to rows when using Tags with TextArea
Setting the maxHeight and minHeights to be the same in the TagsWrapper, so an overflow appears.
We have an issue with having too many tags, and not wrapping in the TextArea. This causes the div to grow past the given area. There may be a better design, though this adds consistency to the control in respecting the rows prop
- [Jira](https://jira.pinadmin.com/secure/RapidBoard.jspa?rapidView=1936&view=planning&selectedIssue=GESTALT-6019&quickFilter=12031&issueLimit=100)
- [] Verified accessibility: keyboard & screen reader interaction
> TextArea: Add MaxHeight for Rows with Tags

- .flowconfig
- package.json
- yarn.lock
Internal: upgrade to Flow 0.195.2
https://github.com/facebook/flow/releases/tag/v0.194.0
https://github.com/facebook/flow/releases/tag/v0.195.0
> Internal: upgrade to Flow 0.195.2

- .gitignore
- .prettierrc.json
- .vscode/settings.json
- README.md
- docs/pages/get_started/developers/installation.js
- docs/pages/get_started/faq.js
- package.json
- packages/gestalt-datepicker/dist/index.d.ts
- packages/gestalt-datepicker/package.json
- packages/gestalt/dist/index.d.ts
- packages/gestalt/package.json
- scripts/templates/README.md
- tsconfig.json
- yarn.lock
If your app was previously using https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/gestalt or https://www.npmjs.com/package/@types/gestalt, Gestalt now supports TypeScrip declaration files.
They are maintained manually. The types are based on the ones from https://www.npmjs.com/package/@types/gestalt but they were reviewed manually. Many errors were found and they all were corrected.
Please, report if you find any incorrect TypeScript type for any of the components 
Internal:  add TypeScript declaration files
Support Gestalt in apps using TypeScript rather than Flow. 
Internalize ownership of https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/gestalt/index.d.ts for better maintenance
Test 
`yarn tsc` with no issues
alpha release in bextools
> Internal: add TypeScript declaration files

- docs/markdown/android/textfield.md
The goal of this PR is to display design specs to the TextField Android component page to support implementation. 
Design specs (Figma iFrames) + new content added
The new design specs will support code implementation non Android. It is part of Gestalt's OKRs (O3KR2 Android TextField documentation updates) 
- …
> TextField: Update Android docs content and specs 

- packages/gestalt/src/PopoverEducational.js
PopoverEducational: fix unresponsive `zIndex` prop
> PopoverEducational: fix unresponsive `zIndex` prop

- docs/pages/get_started/developers/eslint_plugin.js
- packages/eslint-plugin-gestalt/src/__fixtures__/prefer-list/invalid/no-gestalt-list-ol.js
- packages/eslint-plugin-gestalt/src/__fixtures__/prefer-list/invalid/no-gestalt-list-ul.js
- packages/eslint-plugin-gestalt/src/__fixtures__/prefer-list/valid/valid.js
- packages/eslint-plugin-gestalt/src/index.js
- packages/eslint-plugin-gestalt/src/prefer-list.js
- packages/eslint-plugin-gestalt/src/prefer-list.test.js
Created a ESLint rule which prevents ol/ul tag usage and suggests the List component as replacement.
Improve adpotion of the List component in Pinboard. Deprecation of current ol/ul usage cases still pending.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-5612)
- [ Yes ] Added unit and Flow Tests
- [ Yes ] Added documentation + accessibility tests
- [ N/A ] Verified accessibility: keyboard & screen reader interaction
- [ N/A ] Checked dark mode, responsiveness, and right-to-left support
- [ Yes ] Checked stakeholder feedback (e.g. Gestalt designers)
> Internal: Create ESLint rule to enforce List usage

- docs/markdown/team_support/design_file_hygiene/design_handoff.md
It is only a tiny typo fix on the page Design handoff (under Design file hygiene section). A line was probably copied by accident, and we didn't catch it on the review. 
A line of text was removed.
It was a typo!
- [Jira](N/A)
- [TDD](N/A)
- [Figma](https://www.figma.com/file/tdOhnardSfDs5LI96NIxqv/File-hygiene?type=design&node-id=1205%3A5270&t=dcwIQ7ZcdyhOlpyP-1)
> Docs: Design handoff page typo fix

- .eslintrc.js
- packages/gestalt/src/OverlayPanel.jsdom.test.js
- packages/gestalt/src/animation/AnimationContext.jsdom.test.js
This doesn't make sense given how we often mock imports
> Internal: disable `import/no-namespace` for test files

- packages/gestalt/src/Dropdown.js
- packages/gestalt/src/Dropdown/OptionItem.js
- packages/gestalt/src/OverlayPanel.js
- packages/gestalt/src/OverlayPanel.jsdom.test.js
- packages/gestalt/src/OverlayPanel/ConfirmationPopover.js
- packages/gestalt/src/OverlayPanel/InternalOverlayPanel.js
- packages/gestalt/src/SheetMobile.js
- packages/gestalt/src/SheetMobile.jsdom.test.js
- packages/gestalt/src/SheetMobile/Header.js
- packages/gestalt/src/SheetMobile/PartialPage.js
- packages/gestalt/src/__snapshots__/OverlayPanel.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/SheetMobile.jsdom.test.js.snap
- packages/gestalt/src/animation/AnimationContext.js
- packages/gestalt/src/animation/AnimationContext.jsdom.test.js
- packages/gestalt/src/animation/DismissingElement.js
- packages/gestalt/src/animation/RequestAnimationFrameContext.js
OverlayPanel, SheetMobile: implemented [window.requestAnimationFrame() method](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) in animation in & out 
Detailed explanation here (20min ha): https://capture.dropbox.com/7FDLbkhV2EXbYpOI
This logic is implemented in MobileModal in Pinboard (app/packages/gestaltExtensions/Modal/MobileModal.js). It says "Guarantees that rendering two different states occurs in separate animation frames. Without this, renders are sometimes merged together resulting in no animation. Usecase: Updating CSS for transitions on state change"
To unify logic between Gestalt and Pinboard, I implemented logic into the internal `AnimationProvider` as it's reused in SheetMobile and OverlayPanel.
> SheetMobile, OverlayPanel: implement `window.requestAnimationFrame` method

- packages/gestalt/src/Dropdown/OptionItem.js
Dropdown: changed Dropdown.Link icon from `arrow-up-right` to `visit`
> Dropdown: changed Dropdown.Link icon to "visit"

- docs/markdown/android/avatar.md
- docs/markdown/android/button.md
- docs/markdown/android/checkbox.md
- docs/markdown/android/icon.md
- docs/markdown/android/searchfield.md
- docs/markdown/android/sheet.md
- docs/markdown/android/switch.md
- docs/markdown/android/tabs.md
- docs/markdown/android/text.md
Fixed the layout of a few Android docs pages to create consistency across all pages: Avatar, Button, Checkbox, Icon, SearchField, Sheet, Switch, Tabs, Text
> Docs: Android page layout consistency

- packages/gestalt/src/Backdrop.css
- packages/gestalt/src/Backdrop.css.flow
- packages/gestalt/src/Backdrop.js
- packages/gestalt/src/OverlayPanel/InternalOverlayPanel.js
- packages/gestalt/src/SheetMobile/PartialPage.js
- packages/gestalt/src/animation/AnimationContext.js
- packages/gestalt/src/animation/AnimationContext.jsdom.test.js
- packages/gestalt/src/animation/RequestAnimationFrameContext.js
- packages/gestalt/src/animation/animation.css
- packages/gestalt/src/animation/animation.css.flow
SheetMobile, OverlayPanel: fixes to animation
Rendering component since the beginning, and using CSS to initially hide. 
Rendering null creates issues in tests. 
Improving the animation logic so it always renders children. Not doing so messes up tests in Pinboard. This is a much neater CSS solution
> SheetMobile, OverlayPanel: fixes to animation

- packages/gestalt/src/SheetMobile.js
- packages/gestalt/src/SheetMobile/PartialPage.js
SheetMobile: adding `onOutsideClick` prop 
Mobile Modal in Pinboard does logging/tracking when the user clicks outside the SheetMobile bottom sheet.
This enables getting closer to the functionality in Pinboard.
https://sourcegraph.pinadmin.com/github.com/pinternal/pinboard/-/blob/webapp/app/packages/gestaltExtensions/Modal/MobileModal.js?L123:9&subtree=true&popover=pinned
Next steps
This should be replaced with a InteractionProvider. To unblock adoption of MobileSheet, we are adding this prop, but it will eventually be replaced with Providers passing the logic into the component directly as this events re only needed for "side effects" from user interaction
> SheetMobile: adding `onOutsideClick` prop 

- package.json
When dependencies were updated in #2812 ([package.json link](https://github.com/pinterest/gestalt/pull/2812/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)) they weren't added in alphabetical order, possibly from being added by manually editing the file. Any subsequent updates to dependencies cause these dependencies to be alphabetized, adding changed lines where nothing is actually changed.
This PR alphabetizes the dependencies so they stop appearing as changed lines in other PRs.
> Internal: alphabetize dependencies

- packages/gestalt/src/AvatarGroup.js
Internal: fixes to pass `flow codemod annotate-implicit-instantiations --write --include-widened --annotate-special-function-return .`
Prepping codebase to upgrade to Flow v 0.203.1
Annotate all parameters that are only required to be annotated in LTI.
Annotate declarations to help unbreak type cycles.
Annotate underconstrained react hooks like useState(null).
Annotate underconstrained empty arrays.
Annotate under-constrained type arguments.
Annotate type arguments that might be widened. 
This is a noisy codemod that doesn't always produce what you might want.
Same as above, but it will annotate function returns like 
`array.map((v): T => {...})` instead of `array.map<T, _>(v => {...})`
From https://medium.com/flow-type/local-type-inference-for-flow-aaa65d071347
> Internal: fixes to pass `flow codemod annotate-implicit-instantiations --write --include-widened --annotate-special-function-return .`

- docs/pages/foundations/data_visualization/palette.js
- packages/gestalt-design-tokens/tokens/color/data-visualization/base.json
- packages/gestalt/src/contexts/__snapshots__/ColorSchemeProvider.jsdom.test.js.snap
The 03 Dark mode palette was incorrect, and missing. This adds it as a token value
https://deploy-preview-2933--gestalt.netlify.app/foundations/data_visualization/palette
See 03
BEFORE
AFTER
We need if for TileData
> Internal: Add 03 Dark Value to Data Viz Pallete

- packages/gestalt/src/Masonry/defaultLayout.test.js
Internal: fixes to pass `flow codemod annotate-empty-array --write . `
Prepping codebase to upgrade to Flow v 0.203.1
Annotate all parameters that are only required to be annotated in LTI.
Annotate declarations to help unbreak type cycles.
Annotate underconstrained react hooks like useState(null).
Annotate underconstrained empty arrays.
Annotate under-constrained type arguments.
Annotate type arguments that might be widened. 
This is a noisy codemod that doesn't always produce what you might want.
Same as above, but it will annotate function returns like 
`array.map((v): T => {...})` instead of `array.map<T, _>(v => {...})`
From https://medium.com/flow-type/local-type-inference-for-flow-aaa65d071347
> Internal: fixes to pass `flow codemod annotate-empty-array --write . `

- docs/docs-components/Combination.js
- docs/docs-components/CombinationNew.js
- docs/docs-components/SkipToContent.js
- docs/docs-components/useGetSideNavItems.js
- docs/examples/tag/variantDismissable.js
- packages/gestalt/src/List/getChildrenToArray.js
- packages/gestalt/src/OverlayPanel.jsdom.test.js
- packages/gestalt/src/SideNavigation/getChildrenToArray.js
- packages/gestalt/src/animation/RequestAnimationFrameContext.js
Internal: fixes to pass `flow codemod annotate-cycles --write .`
Prepping codebase to upgrade to Flow v 0.203.1
Annotate all parameters that are only required to be annotated in LTI.
Annotate declarations to help unbreak type cycles.
Annotate underconstrained react hooks like useState(null).
Annotate underconstrained empty arrays.
Annotate under-constrained type arguments.
Annotate type arguments that might be widened. 
This is a noisy codemod that doesn't always produce what you might want.
Same as above, but it will annotate function returns like 
`array.map((v): T => {...})` instead of `array.map<T, _>(v => {...})`
From https://medium.com/flow-type/local-type-inference-for-flow-aaa65d071347
> Internal: fixes to pass `flow codemod annotate-cycles --write .`

- docs/docs-components/Combination.js
- docs/docs-components/CombinationNew.js
- packages/eslint-plugin-gestalt/src/no-box-useless-props.js
- packages/eslint-plugin-gestalt/src/no-workflow-status-icon.js
- packages/eslint-plugin-gestalt/src/prefer-box-inline-style.js
- packages/gestalt-datepicker/src/DateField/InternalDateField.js
- packages/gestalt/src/Collage/Collection.js
- packages/gestalt/src/OverlayPanel/InternalOverlayPanel.js
- packages/gestalt/src/SideNavigationGroup.js
- playwright/masonry/flexible-resize.spec.mjs
- playwright/masonry/shuffle-items.spec.mjs
- playwright/masonry/utils/getGridItems.mjs
Internal: fixes to pass `flow codemod annotate-react-hooks --write .`
Prepping codebase to upgrade to Flow v 0.203.1
Annotate all parameters that are only required to be annotated in LTI.
Annotate declarations to help unbreak type cycles.
Annotate underconstrained react hooks like useState(null).
Annotate underconstrained empty arrays.
Annotate under-constrained type arguments.
Annotate type arguments that might be widened. 
This is a noisy codemod that doesn't always produce what you might want.
Same as above, but it will annotate function returns like 
`array.map((v): T => {...})` instead of `array.map<T, _>(v => {...})`
From https://medium.com/flow-type/local-type-inference-for-flow-aaa65d071347
> Internal: fixes to pass `flow codemod annotate-functions-and-classes --include-lti --write .`

- .flowconfig
- package.json
- packages/gestalt/src/Divider.js
- packages/gestalt/src/debounce.js
- packages/gestalt/src/throttle.js
- yarn.lock
Internal: upgrade to Flow 0.206.0
https://github.com/facebook/flow/releases/tag/v0.205.0
https://github.com/facebook/flow/releases/tag/v0.206.0
> Internal: upgrade to Flow 0.206.0

- docs/docs-components/navigationContext.js
Docs: fix bug in navigation
http://localhost:8888/android/text
Behaviour only on ios and android. It might have to do with the markdown implementation?
[GESTALT-5854](https://jira.pinadmin.com/browse/GESTALT-5854)
> Docs: fix bug in navigation

- docs/examples/table/selected.js
- docs/pages/web/table.js
- packages/gestalt/dist/index.d.ts
- packages/gestalt/src/Table.css
- packages/gestalt/src/Table.css.flow
- packages/gestalt/src/TableRow.js
- packages/gestalt/src/TableRowDrawer.js
- packages/gestalt/src/TableRowExpandable.js
- packages/gestalt/src/__snapshots__/TableFooter.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/TableHeader..jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/TableRow.test.js.snap
- packages/gestalt/src/__snapshots__/TableRowDrawer.test.js.snap
- packages/gestalt/src/__snapshots__/TableRowExpandable.test.js.snap
Table: added "selected"and "hoverStyle" prop to all Table.Row subcomponents
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4697)
- [Figma](https://www.figma.com/file/pGpBsKBAXMwl2bv1dMISfs/Documentation-Table-Selected-Row?type=design&node-id=1%3A1956&t=J4YninrFn7P6Wzyb-1)
> Table: added "selected"and "hoverStyle" prop  to all Table.Row subcomponents

- docs/examples/tiledata/color.js
- docs/examples/tiledata/disabled.js
- docs/examples/tiledata/group.js
- docs/examples/tiledata/main.js
- docs/examples/tiledata/tooltip.js
Fixing TileData examples
BEFORE
AFTER
> Internal: Fix TileData Examples

- docs/examples/callout/accessibilityExample.js
- docs/examples/callout/actionsExample.js
- docs/examples/callout/dismissibleExample.js
- docs/examples/callout/dontStack.js
- docs/examples/callout/dontUseForMarketing.js
- docs/examples/callout/localizationExample.js
- docs/examples/callout/main.js
- docs/examples/callout/placeAtTop.js
- docs/examples/callout/productMessages.js
- docs/examples/callout/variantError.js
- docs/examples/callout/variantInfo.js
- docs/examples/callout/variantRecommendation.js
- docs/examples/callout/variantSuccess.js
- docs/examples/callout/variantWarning.js
- docs/pages/web/callout.js
Migrated examples in the docs from the old editor to the sandpack editor for the Callout component.
Ensures the editor remains consistent with other components, as part of the current migration efforts.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4876)
- [n/a] Verified accessibility: keyboard & screen reader interaction
> Callout: Convert examples to use Sandpack

- docs/pages/web/tiledata.js
- packages/gestalt/dist/index.d.ts
- Adding Typescript Types 
- Remove Controls from Don't examples
> TileData: Add Typescript Types

- docs/examples/table/alignContent.js
- docs/examples/table/avoidOverStylingText.js
- docs/examples/table/bottomCaptionExample.js
- docs/examples/table/dontAddSoMuchContent.js
- docs/examples/table/dontAlignContent.js
- docs/examples/table/dontMixTextAndGraphics.js
- docs/examples/table/dontOverStyleText.js
- docs/examples/table/dontUseExpandForDenseContent.js
- docs/examples/table/drawerRowExample.js
- docs/examples/table/expandRows.js
- docs/examples/table/main.js
- docs/examples/table/makeContentDigestable.js
- docs/examples/table/multipleStickyColumnsExample.js
- docs/examples/table/rowExpandableWithStickyColumns.js
- docs/examples/table/selected.js
- docs/examples/table/separateUnitType.js
- docs/examples/table/sortableHeaderCellsWithStickyColumns.js
- docs/examples/table/sortableTableCells.js
- docs/examples/table/stickyColumnExample.js
- docs/examples/table/stickyHeaderColumnExample.js
- docs/examples/table/stickyHeaderFooterExample.js
- docs/examples/table/topCaptionExample.js
- docs/pages/web/table.js
Migrated examples in the docs from the old editor to the sandpack editor for the Table component.
Migrated examples in the docs from the old editor to the sandpack editor for the Table component.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4873)
- [n/a] Verified accessibility: keyboard & screen reader interaction
- [n/a] Checked stakeholder feedback (e.g. Gestalt designers)
> Table: Convert examples to use Sandpack

- docs/pages/get_started/designers.js
Included a link to the Product Surfaces in the Get Started section and deleted a line with an out-of-date plugin.
To update the Get Started page, and include a link to a new library that can be used by designers.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-5929)
> Docs: Update Designers page

- packages/gestalt/src/Checkbox/InternalCheckbox.css
Looks like relative imports from `./Borders.css` were incorrect.
Didn't notice any snapshot issues, so it went under the radar, since the classes were likely added.
But it could have caused a visual regression.
Actual:
Expected:
> Checkbox: Update InternalCheckbox.css

- .github/workflows/alpha.yml
- scripts/releaseSteps.js
We were doing commits to alpha, and the workflow file also lived on Alpha. 
So a force push, or resetting to master on alpha caused this file to disappear.
Merging this into master should keep the workflow preserved, and resetting alpha to master should still keep the workflow running as expected now.
> Internal: Add Alpha Workflow file

- packages/gestalt/src/Backdrop.js
- packages/gestalt/src/SheetMobile.js
- packages/gestalt/src/SheetMobile/PartialPage.js
SheetMobile: add event to `onOutsideClick`
Needed in Pinboard
> SheetMobile: add event to `onOutsideClick`

- docs/pages/web/tabs.js
The Wrapping section had wording from Button Group. Replaced the wording to be specific to tabs. Added more context on truncation Best practices: horizontal scrolling for mobile, wrapping for desktop.
Replaced the wording under Wrapping to be pertinent to tabs. Clarified behavior for truncation in Best Practices
Wrapping guidance was incorrect. Best practices were confusing to designers and needed clarification.
- [[Jira](https://jira.pinadmin.com/browse/GESTALT-XXXX](https://jira.pinadmin.com/browse/GESTALT-6230))
> Tabs: Update wrap and best practices docs verbiage

- docs/pages/web/tiledata.js
- packages/gestalt/src/TileData.js
Noticed an extraneous `a` in TileData's header description. Took a quick pass of copyediting while looking at that file
> TileData: fix typo + copyediting

- docs/pages/whats_new.js
> Docs: fix max width for blog post titles

- packages/gestalt-core/build.js
- packages/gestalt/package.json
When rollup is run watch mode (our development version), the outputted css will also include the full classname to make it easier for debugging in the inspect tab.
**Why?**
When building components, it's hard to track the minified css or know which class to modify. This can also encourage behavior to to write new classes instead of extending current ones. The code may write the style class like this `styles.button`, but when debugging, it's up to the developer to associate that with `DUt` as a className
What changed:
Classnames when in development are run as `fullClassName___minifiedClassName`
**BEFORE**
**AFTER**
> Internal: Unminify classname when developing

- docs/pages/foundations/data_visualization/color/usage.js
- docs/pages/foundations/design_tokens.js
- docs/pages/web/tiledata.js
- docs/redirects.js
These links were broken by #2980.
This PR adds redirects for the two data viz pages that were moved in the referenced PR. It also updates references to those old URLs on a few other docs pages.
These broken links were found using [the Algolia crawler](https://crawler.algolia.com/admin/crawlers/1b084526-6b1b-4fe6-be0e-c4de54b9f65c/monitoring/details?reason=http_not_found&url=https%3A%2F%2Fgestalt.pinterest.systems%2Ffoundations%2Fdata_visualization%2Fpalette).
> Docs: fix broken links

- packages/gestalt/src/Masonry.js
- packages/gestalt/src/Masonry/README.md
Add a README file explaining how Masonry works. I'll probably add to / update this in the future after knowledge share sessions.
> Internal: add README explaining Masonry

- docs/docs-components/AppLayout.js
- docs/docs-components/DevelopmentEditor.js
- docs/docs-components/Header.js
- docs/markdown/get_started/developers/contributing/development_process.md
- scripts/releaseSteps.js
Sometimes we need to explicitly remind people to turn on DevExample Mode. 
This makes it a query param.
So you can say `<deployurl>/web/tiledata?devexample=true`
And have the previews run everywhere. Since we anticipate future PRs to utilize this, this well help us make sharing links easier for review.
One thing to note, passing this param once will probably always enable devmode for people in the deployment versions (probably okay) since I believe this state is actually preserved in localstorage. But also, every deploy url is different.
> Internal: Add Url Param to toggle Dev Example Mode

- docs/pages/foundations/data_visualization/available_components.js
- docs/pages/foundations/data_visualization/charts_and_graphs.js
- docs/pages/foundations/data_visualization/micro_visualizations.js
For better or for worse, we treat "data point" as a single word for the casing of our component ([Datapoint](https://gestalt.pinterest.systems/web/datapoint)). This PR fixes non-standard casing in a few usages introduced recently.
> Docs: fix non-standard Datapoint casing

- docs/examples/datepicker/controlled.js
- docs/examples/datepicker/disable.js
- docs/examples/datepicker/disableSelected.js
- docs/examples/datepicker/disabled.js
- docs/examples/datepicker/error.js
- docs/examples/datepicker/helperText.js
- docs/examples/datepicker/preselected.js
- docs/examples/datepicker/range.js
- docs/pages/web/datepicker.js
- packages/gestalt-datepicker/dist/index.d.ts
- packages/gestalt-datepicker/src/DatePicker.js
- packages/gestalt-datepicker/src/DatePicker.jsdom.test.js
- packages/gestalt-datepicker/src/DatePicker/InternalDatePicker.js
Run codemod to detect DatePicker. Also, Flow|TypeScript complains could help fixing this.
```
--component=DatePicker
```
DatePicker returns "Date" objects and "null", "null" value was not in the type. 
Major breaking change as it might affect useState value when implementing the upgrade
Flow errors
> DatePicker: fixes in Flow|TypeScript types

- docs/docs-components/PageHeader.js
The existing `aliases` check in the docs PageHeader is too simple — we don't just care if `aliases` is defined, but also if it has length
_before_
_after_
> Docs: fix empty aliases bug

- packages/gestalt/src/Toast.css
Toast: CSS fix in width
Before
After
> Toast: CSS fix in width

- scripts/generateMetadata.js
When we run `yarn start` we usually see a bunch of errors from docgen.
We were logging the entire stacktrace, and this made the terminal log output larger.  This updates the logging method to give more details on the filepath with missing docgen and the issue.
Before:
After:
> Internal: Cleaner Logging for DocGen Errors

- docs/docs-components/COMPONENT_DATA.js
- docs/examples/datavisualization/desktopgraphExample.js
- docs/examples/datavisualization/graphtotableExample.js
- docs/examples/datavisualization/mobilegraphExample.js
- docs/pages/foundations/data_visualization/charts_and_graphs.js
Data visualization clean up.
Updated videos to be larger and of higher quality. Added a better description for the Data visualization link on the Foundations overview page.
Videos were blurring before. This makes them sharper. We only had a description under the Data visualization heading and graphic that said "Data visualization". This provides a more descriptive sentence to match other Foundations docs.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-6311)
> Docs: Data visualization videos

- .markdownlint.json
- docs/markdown/foundations/content_standards/resources.md
Created by Hartley after the Content Design layoffs. This PR also includes linting the existing markdown file.
> Docs: add link to UX Writing Cheat Sheet

- docs/pages/get_started/developers/tooling/web.js
Docs: adds a new metric statsboards to web/tooling page
> Docs: adds a new metric statsboards to web/tooling page

- packages/gestalt/src/Image.js
Fixing this hydration error:
Warning: Extra attributes from the server: elementtiming
at img
If no element timing prop is passed, use the src as a value.
This causes a hydration issue. I'm guessing the server adds the attribute, but the browser removes it because it is empty. This causes a mismatch in HTML, throwing a hydration error.
> Image: web - conditionally add imagetiming attribute

- docs/docs-components/data/components-new.js
- docs/docs-components/data/types.js
- docs/docs-components/data/utils/getByCategory.js
- docs/docs-components/data/utils/getByCategory.test.js
- docs/docs-components/data/utils/getByPlatform.js
- docs/docs-components/data/utils/getByPlatform.test.js
- docs/docs-components/data/utils/test-fixtures.js
This PR implements the new component data structure proposed in #3005. I modified the data structure slightly — whereas previously each field required an object that took values for each platform, the entire data structure is now split by platform. This seemed to make things a bit easier to deal with. 
I also added a couple of helpers to get components by platform and by platform+category, with tests.
Note that this PR doesn't actually switch to _consume_ the new component data. I wanted to merge this change and let other folks double-check the data to make sure it's correct (I'm pretty confident the web data is fine, but less so on Android/iOS, and much less so for Figma). So this doesn't represent any changes that would be visible in the docs yet.
> Internal: implement new component data type (w/helpers)

- docs/examples/callout/variantMessage.js
- docs/pages/web/callout.js
- packages/gestalt/src/Callout.js
- packages/gestalt/src/Callout.test.js
- packages/gestalt/src/__snapshots__/Callout.test.js.snap
Based on a slack convo with a customer.
Adding support for Rich Text Type in a Callout. message E.g. Bold, italics.
Before
After
Slimbanner supports a text prop for the message, but callout does not. Seems like it would be a consistency thing among the two message props. Pending design review. 
> Callout: Support Text Type in Callout

- docs/integration-test-helpers/masonry/MasonryContainer.js
- docs/pages/integration-test/masonry.js
- packages/gestalt/src/Masonry.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.js
- playwright/masonry/utils/getServerURL.mjs
In preparation for the upcoming 2-col module experiment, we need to know how much whitespace is present above 2-col modules. This will inform the effort we put into implementing pin leveling, either for the initial launch of the experiment or at all.
This PR adds hook into the 2-col layout function to log this whitespace, via an experimental prop. We can hook this up to Statsboard in Pinboard to log real-world values. The PR also updates the existing integration test route to test out this logging.
> Masonry: add hook to log whitespace above 2-col modules

- packages/gestalt/src/Masonry.js
We're not using this field yet and it's breaking types in Pinboard
> Masonry: remove unused `heightAdjustment` field

- .flowconfig
- docs/integration-test-helpers/masonry/MasonryContainer.js
- package.json
- yarn.lock
I'd like to be able to use some of Flow's [nifty new utility types](https://flow.org/en/docs/types/utilities/#toc-exclude)
> Internal: upgrade Flow to 0.209.0

- .flowconfig
- package.json
- yarn.lock
I still want those nifty utility types I'd referenced in #3053. The Flow docs claim they were available in `≥0.209.0`, which seems to be a lie. Upgrading to the latest version to try to get `$Exclude`!
> Internal: upgrade Flow to 0.210.2

- docs/examples/box/as.js
- packages/gestalt/src/Box.js
- packages/gestalt/src/boxTypes.js
The [`<p>` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p) is useful for semantic text. We should support it!
> Box: add support for `<p>` in `as`

- docs/docs-components/OverviewList.js
- docs/docs-components/data/components.js
- docs/docs-components/data/types.js
- docs/docs-components/data/utils/test-fixtures.js
- docs/pages/web/component_status.js
A lil bit of cleanup after #3054 
- Remove the outdated types that were exported from `/data/components.js` in favor of the current ones in `/data/types.js`
- Remove the `figmaOnly` field from platform types — this is unnecessary, as it can be derived by a component only having data for the `figma` platform
> Internal: clean up component data types

- docs/docs-components/data/componentStatusMessaging.js
- docs/docs-components/siteIndex.js
- docs/pages/android/component_status.js
- docs/pages/ios/component_status.js
- docs/pages/web/component_status.js
- playwright/accessibility/android__component_status.spec.mjs
- playwright/accessibility/ios__component_status.spec.mjs
Since [`/web/component_status`](https://gestalt.pinterest.systems/web/component_status) now only covers web components, we're no longer surfacing component status for iOS and Android. This PR adds Component Status pages for both platforms.
This doesn't address Figma-only components, which will need to be surfaced elsewhere. There isn't an obvious place in the docs for those components, so that will need design 👀.
> Docs: add Component Status pages for iOS and Android

- docs/pages/foundations/design_tokens.js
- packages/gestalt-design-tokens/tokens/color/alias.json
- packages/gestalt/src/contexts/__snapshots__/ColorSchemeProvider.jsdom.test.js.snap
Tokens: added undocumented $color-text-disabled & $color-text-icon-disabled tokens #3068
Before allowing use in Pinterest web, we need to figure out Axe color contrast issues.
Original PR https://github.com/pinterest/gestalt/pull/3019
> Tokens: added undocumented `$color-text-disabled` & `$color-text-icon-disabled` tokens

- docs/pages/foundations/data_visualization/overview.js
Fixed typo.
Changed intro sentence to Visualizing Data in Product Dashboards to "the layout should be structured starting with the most significant and ending with the least significant details" per user feedback.
https://pinterest.slack.com/archives/C0HUV5J93/p1689360990683139
Incorrect phrasing.
> Docs: Fix typo in overview

- docs/examples/table/sortableTableCells.js
- docs/pages/web/table.js
- packages/gestalt/dist/index.d.ts
- packages/gestalt/src/TableSortableHeaderCell.js
- packages/gestalt/src/TableSortableHeaderCell.test.js
- packages/gestalt/src/__snapshots__/TableSortableHeaderCell.test.js.snap
Enabling the SortableHeaderCell to align to the right as expected. Previously, the arrow was in the way for 
Adding an `align= start | end` and moving the icon when end-aligned. 
The end property also reverses the order so that the text is the last thing to appear.
We have a few [customers](https://jira.pinadmin.com/secure/RapidBoard.jspa?rapidView=1936&view=planning&selectedIssue=GESTALT-5154&quickFilter=12031&issueLimit=100) that ran into issues with this.
Before:
The icon would go away, and the alignment looks poor
After:
LTR
RTL
- [Jira](https://jira.pinadmin.com/secure/RapidBoard.jspa?rapidView=1936&view=planning&selectedIssue=GESTALT-5154&quickFilter=12031&issueLimit=100)
- [Figma](https://www.figma.com/file/HbBD5AgCNvupMVKBkTgdsH/Table-Enhancements?type=design&node-id=603-45434&mode …
> Table: Add SortableHeaderCell End align

- docs/pages/web/button.js
- packages/gestalt/dist/index.d.ts
- packages/gestalt/src/Button.flowtest.js
- packages/gestalt/src/Button.js
Breaking change because before you could pass name to Button role="link" which was dead code. Now you cant.
```
--component=Button
--prop=name
```
We can use the above codemod to detect Button with name used on them and see if they are also role="link" but it's much faster to rely on Flow complaining.
Button: fixes ` name` prop documentation and Flow
Previously missing
> Button: fixes ` name` prop documentation and Flow

- packages/gestalt/src/PopoverEducational.js
PopoverEducational: removing flex null spacing
> PopoverEducational: removing flex null spacing

- docs/pages/home.js
Re-animate the Hero graphic on the home page (turned off during Year-in-review)
I miss the animations 
(you know, when I reference the site 5 times a day 😅)
(( Miss you all ❤️ ))
> Docs: Re-add hero animation on home page

- docs/docs-components/Header.js
Docs: development mode switch shown when activated from url
Because sometimes I find myself in dev mode and can't toggle it off as it's set in locale storage.
It's bothered me about 2-3 times already. Removing the switch doesn't really provide a better experience over all. 
> Docs: development mode switch shown when activated from url

- docs/markdown/android/switch.md
- docs/markdown/ios/switch.md
Cleaning up the iOS Switch documentation, making sure the information is correct, and adding specs and variants so the mobile platforms can align.
Added new sections to the iOS Switch docs, including Anatomy, Design tokens, and more variants. Also a rearrangement of sections and correction of typo. 
Change made so we make sure the docs are correct, …
> Switch: iOS mobile doc clean up

- flow-typed/npm/@mui/material_vx.x.x.js
- flow-typed/npm/@mui/x-date-pickers_vx.x.x.js
- packages/gestalt-datepicker/src/DateField/InternalDateField.js
Not sure what the impact of the namespace import here could be.
We take the code from localeData, and make it so that we can get it from the MUI locales object, and pass it in to `localeText`. A light transformation is needed between the two.
For birthday picking, translations are an issue.
Before:
After:
> DateField: Add locale format translations

- packages/gestalt/src/Icon.js
- packages/gestalt/src/Video/__snapshots__/Controls.test.js.snap
- packages/gestalt/src/__snapshots__/Video.test.js.snap
Icon: support rtl to "mute" icon
https://jira.pinadmin.com/browse/BUG-161879
> Icon: support rtl to "mute" icon

- docs/examples/text/cjkText.js
- docs/pages/web/text.js
- packages/gestalt/src/Text.css
Adding CJK support to wrap `Text`.
Introduces a css rule:
```
*:lang(zh) .Text,
*:lang(ko) .Text,
*:lang(ja) .Text {
word-break: keep-all;
}
```
CJK languages should use a `keep-all` word-break to preserve the words. 
See the #Word-Breaks-and-CJK-languages section.
We noticed that in small width containers the text was not getting wrapped as expected. This creates a poor user experience.
Before:
After:
We still need to verify the downstream changes and verify if these changes break surfaces
> Text: Add CJK wrapping to Text

- docs/examples/table/sortableTableCells.js
- packages/gestalt/src/TableSortableHeaderCell.js
- packages/gestalt/src/__snapshots__/TableSortableHeaderCell.test.js.snap
Bug fix:
Changes the header cell to take the full width, so end-align works as expected.
Adding width 100%.
Getting rid of row-reverse since it's not accessible, and replacing with Icon rendering.
Before:
After:
> Table: Headercell take full width

- docs/docs-components/CombinationNew.js
- docs/docs-components/MainSectionCard.js
- docs/docs-components/MainSectionSubsection.js
- docs/pages/web/buttonlink.js
- docs/pages/web/datefield.js
- docs/pages/web/datepicker.js
- docs/pages/web/daterange.js
- docs/pages/web/iconbutton.js
- docs/pages/web/link.js
- docs/pages/web/taparea.js
- docs/pages/web/utilities/globaleventshandlerprovider.js
- packages/gestalt-datepicker/src/DateField.js
- packages/gestalt-datepicker/src/DateField/InternalDateField.js
- packages/gestalt-datepicker/src/DatePicker.js
- packages/gestalt-datepicker/src/DateRange.js
- packages/gestalt/src/contexts/GlobalEventsHandlerProvider.js
- packages/gestalt/src/index.js
GlobalEventsHandlerProvider, DatePicker, DateRange, DateField: add `onMount` handlers
Documented GlobalEventsHandlerProvider (external handlers) in some components pages
Enable impression logging tests
> GlobalEventsHandlerProvider, DatePicker, DateRange, DateField: add `onMount` handlers

- packages/gestalt/src/TableOfContents.js
- packages/gestalt/src/__snapshots__/TableOfContents.test.js.snap
Added default accessibilty label for TableOfContents.
- [n/a] Verified accessibility: keyboard & screen reader interaction
- [n/a] Checked dark mode, responsiveness, and right-to-left support
- [n/a] Checked stakeholder feedback (e.g. Gestalt designers)
> TableOfContents: Add default label

- docs/examples/tableofcontents/dontPlaceFarAway.js
- docs/examples/tableofcontents/main.js
- docs/examples/tableofcontents/nestedItemsExample.js
- docs/examples/tableofcontents/topAlignWithContentTitle.js
- docs/examples/tableofcontents/withHeaderExample.js
TableOfContents should have a fixed position on a page. Examples in the docs were updated accordingly.
> Docs: Fix layout of TableOfContents examples

- docs/docs-components/Toc.js
Replaced custom table of contents component with the new `TableOfContents` component in docs site `ToC`.
BEFORE:
AFTER:
- [Jira](https://jira.pinadmin.com/browse/GESTALT-6267)
> Docs: Use TableOfContents component in ToC 

- docs/docs-components/DocsSideNavigation.js
- docs/examples/devicetypeprovider/implementation.js
- docs/examples/sidenavigation/mobileExample.js
- packages/gestalt/dist/index.d.ts
- packages/gestalt/src/SideNavigation.js
- packages/gestalt/src/SideNavigation/Mobile.js
Renamed `title` prop of SideNavigation to `mobileTitle` because the title of SideNavigation appears only for mobile.
The old icon needs to be replaced with custom SVG component manually. Run the following codemod to locate the usages:
```bash
yarn codemod modifyProp . --component=SideNavigation --previousProp=title --nextProp=mobileTitle
```
- [Jira](https://jira.pinadmin.com/browse/GESTALT-6239)
- [n/a] Verified accessibility: keyboard & screen reader interaction
- [n/a] Checked dark mode, responsiveness, and right-to-left support
- [n/a] Checked stakeholder feedback (e.g. Gestalt designers)
> SideNavigation: Rename `title` prop to `mobileTitle`

- docs/pages/get_started/developers/tooling/web.js
Docs: removed outdated stats from table in tooling
> Docs: removed outdated stats from table in tooling

- packages/gestalt/src/Module/ExpandableItem.js
- packages/gestalt/src/Module/__snapshots__/ExpandableItem.test.js.snap
- packages/gestalt/src/__snapshots__/ModuleExpandable.test.js.snap
Adding items-center and a maxheight to the wrapper at the end.
See this thread:
https://pinterest.slack.com/archives/C13KLG5P0/p1692124542365889
Icon was not centered
Before:
After:
> Module: Center the collapse/expand icon 

- packages/gestalt/src/SideNavigation/PrimaryActionIconButton.js
Moving to 
Tweaking the SideNavigation to use `MaybeTooltip` and turning off the tooltip completely when the dropdown menu is open.
Without this fix, the tooltip can't be seen if the dropdown is open, and the primary action has already been pressed.
https://github.com/pinterest/gestalt/assets/5509813/219947a3-130e-4d65-93f2-b1c314e58e85
[See example here](https://gestalt.pinterest.systems/web/sidenavigation#Primary-action)
- [Slack](https://pinterest.slack.com/archives/C13KLG5P0/p1691794954357239)
> SideNavigation: Remove Tooltip on dropdown open

- docs/markdown/android/button.md
Changed from 48dp to 44dp to reflect the button in code.
What is the purpose of this PR? Please include the context around these changes for Future Us. In addition to _what_ is changing, we need to know _why_ these changes are needed. …
> Button: Update Android button docs

- docs/examples/text/variantOverflowTruncation.js
- packages/gestalt/src/Typography.css
Use CSS property of `word-wrap` instead of `word-break` for word break. This is how it was before.
Our old word-break property and the new one seems to create a difference.  Likely this case: [Read here](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap). It's hard to catch these cases since we don't know the width of where text is used. Rather not break things
This breaks TileData. It happens on a case-by-case basis. Likely due to width of container that could be handled differently:
The usage of `Text` is the same.
```
<Text size={size === 'lg' ? '500' : '400'} weight="bold" color={textColor}>
{value}
<AccessibilityPause />
</Text>
```
Swapping to the previous seems to work
- [Figma](link to …
> Text: Swap word-break property

- packages/gestalt/src/ComboBox.js
Re-draw the combobox popover when the number of items change
Before:
After:
[Fixes this customer bug](https://jira.pinadmin.com/browse/GESTALT-6876)
> ComboBox: Fix Bottom Rendering

- packages/gestalt/src/ActivationCard.js
- packages/gestalt/src/Module.js
- packages/gestalt/src/ModuleExpandable.js
- packages/gestalt/src/Upsell.js
- packages/gestalt/src/__snapshots__/ActivationCard.test.js.snap
- packages/gestalt/src/__snapshots__/Module.test.js.snap
- packages/gestalt/src/__snapshots__/ModuleExpandable.test.js.snap
- packages/gestalt/src/__snapshots__/Upsell.test.js.snap
Changing:
- Module, ModuleExpandable
- Upsell,
- ActivationCard
These use `elevationRaised` in light mode. But the bg is `transparent` and this causes the bg color to take place. In most cases, we want "white". In dark mode, we do want the elevationRaised as expected.
Before:
After:
[See thread](https://pinterest.slack.com/archives/C13KLG5P0/p1693241098556749)
We may change elevationRaised in the future
> Upsell: Update default backgrounds for elevationRaised

- docs/docs-components/Toc.js
- packages/gestalt/src/TableOfContents/TableOfContentsAnchor.js
- packages/gestalt/src/__snapshots__/TableOfContents.test.js.snap
Removed logic for displaying marker when `TableOfContents.Item` is focused without active or hovered state.
`TableOfContents.Item` should have marker only in active or hovered state.
Before:
After:
> TableOfContents: Show maker only for active or hovered item

- docs/docs-components/Toc.js
Fixed a bug caused by previous change. Overflow rule for ToC component was set wrong.
> Docs: Fix ToC overflow

- docs/pages/web/taparea.js
- packages/gestalt/dist/index.d.ts
- packages/gestalt/src/TapArea.js
TapArea: support to new  `dataTestId` prop
Prevent instances like:
> TapArea: support to new  `dataTestId` prop

- docs/docs-components/SandpackExample.js
- docs/examples/video/autoplayAndErrorDetectionExample.js
- docs/examples/video/captionsExample.js
- docs/examples/video/controlsExample.js
- docs/examples/video/mainExample.js
- docs/examples/video/multipleSourcesExample.js
- docs/examples/video/updatesExample.js
- docs/examples/video/withChildrenExample.js
- packages/gestalt/src/Video/Playhead.js
- packages/gestalt/src/Video/__snapshots__/Controls.test.js.snap
- packages/gestalt/src/Video/__snapshots__/Playhead.test.js.snap
- packages/gestalt/src/__snapshots__/Video.test.js.snap
In RTL language context the scrubber of Video component was moving from left to right (instead of right to left).
**Also** I updated the RTL preview of Sandpack examples, so that examples responds to `html[dir="rtl"]` CSS selector (not to container div's `dir` attribute).
- Removed redundant html elements and styles to render Playhead component.
- Added logic to Playhead, so that 
- it can detect text direction and respond to RTL language layout.
- it correctly reacts to `seek()` when clicked.
- Fixed unreponsive Video component examples. The controls were not working at all.
- [Jira](https://jira.pinadmin.com/browse/BUG-169925)
> Video: Support RTL layout in scrubber

- docs/pages/get_started/designers.js
Fixed one broken link to the Pinterest Assets plugin
> Docs: Fix broken link in Get started/Designers section

- docs/docs-components/Toc.js
Removed accessibility attributes from the wrapper ToC for TableOfContents in docs-components.
It was causing duplicated labels appear for screen readers.
Before
After
> Docs: Fix duplicated ToC accessibility label

- packages/gestalt/dist/index.d.ts
Fix toast typescript type to match [props table](https://gestalt.pinterest.systems/web/toast)
prop "variant" changed to prop "type"
> Toast: Fix toast prop "variant" to "type"

- docs/integration-test-helpers/masonry/MasonryContainer.js
- docs/pages/integration-test/masonry.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.js
This PR fixes a bug with using an externally managed position store where heights are incorrectly initialized to 0 when remounting a grid. The end result is that after the initial mount, the new pages are rendered starting at 0 which causes overlap in the grid
I also updated the Masonry test page so that we can test mount/unmount with an external position cache
In https://github.com/pinterest/gestalt/pull/3146, we added support for the position cache to be externally managed for multi-column grids. This was meant to reduce the overhead when remounting a grid, however it resulted in the bug described above.
> Masonry: Fix height initialization when reusing cached positions for multi-column pins

- packages/gestalt/src/SideNavigation/PrimaryActionIconButton.js
- packages/gestalt/src/Tooltip.js
- packages/gestalt/src/Tooltip/InternalTooltip.js
- packages/gestalt/src/__snapshots__/TagData.test.js.snap
- packages/gestalt/src/__snapshots__/TileData.test.js.snap
- packages/gestalt/src/utils/MaybeTooltip.js
Sidenavigation primary action dropdown is not positioned correctly. This is due to `MaybeTooltip` re-rendering the children when the tooltip should be disabled.
This is a broken change introduced in this [PR](https://github.com/pinterest/gestalt/pull/3134). The TapArea is the innerRef, but when the tooltip is disabled, the dropdown placement is initially messed up because the TapArea is re-rendered. TapArea uses `useId` and the ref likely changes on every render.
~~This moves the `MaybeTooltip` to inside the tap area, so the outer ref for the dropdown is not changed.~~
This change does two things:
- Moves tooltip to `InternalTooltip`, and adds a new disabled prop. When disabled, the tooltip will never open.
-  `MaybeTooltip` will override set the tooltip behavior to be "disabled" 
See …
> Tooltip: Move to Internal Tooltip with a disabled state

- packages/gestalt/src/Icon.css
- packages/gestalt/src/Video.css
This PR fixes a bug that is present only in iOS browsers (mobile Safari and Chrome). Apparently, rotated SVGs on top of video element causes the video element appear on top. Sometimes, it causes SVG and its container to flicker then disappear (or to partially render).
This bug was caught in RTL mode because in RTL some of the icons are flipped.
`rotateY(180deg)` CSS rule was replaced by `scale(-1, 1)` as it seems to be more stable/reliable.
Original bug was reported here https://jira.pinadmin.com/browse/BUG-170571
- [Jira](https://jira.pinadmin.com/browse/BUG-171048)
> Video: Fix flickering video controls on iOS browsers

- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.js
This PR fixes an oversight from https://github.com/pinterest/gestalt/pull/3201. 
Atm when we restore heights, we also factor in two column items. Unfortunately, I had a bug in the previous PR where, instead of appending the height, I would reset it.
This should fix the remaining overlap we're still seeing
> Masonry: Fix bug with height restoration + two column module items

- packages/gestalt/src/WashAnimated.css
Spacing tokens that were in the animate field and this caused weird behavior in Wash Animated on hover:
Before:
After:
It seems like our visual tests didn't catch this, even though the page was visibly different. Something for us to investigate
> WashAnimated: Remove space tokens 

- packages/gestalt/dist/index.d.ts
- packages/gestalt/src/TapArea.js
TapArea: fix in TapArea child Flow type
`TapArea fullWidth fullHeight` technically doesn't need children 
> TapArea: fix in TapArea child Flow type

- docs/examples/taparea/fullSpace.js
- docs/pages/web/taparea.js
TapArea: full space with no children example in Docs
> TapArea: full space with no children example in Docs

- packages/gestalt/src/List.css
Fixing some List spacing tokens that were not correct for condensed items
> List: Update Condensed List Spacing Tokens

- packages/gestalt/src/Tooltip.js
- packages/gestalt/src/Tooltip/InternalTooltip.js
- packages/gestalt/src/__snapshots__/TagData.test.js.snap
- packages/gestalt/src/__snapshots__/TileData.test.js.snap
- packages/gestalt/src/utils/MaybeTooltip.js
Moving to an internal tooltip. Original change description is in #3187.  It was reverted in #3209 due to failing tests.
This fixes extra rendering that kept getting called in the useEffect 
Before:
```
useEffect(() => {
dispatch({ type: 'hoverOutIcon', disabled });
}, [disabled]);
```
This would dispatch the event every time on first render. So when a lot of conditional renders were happening, this would cause a `too many renders` issue.
E.g. in something like
```
{text && <Tooltip> <Child> </Tooltip}
```
Every time text would change, the element would fall into re-rendering.
Now:
```
useEffect(() => {
if(disabled === true){
dispatch({ type: 'hoverOutIcon', disabled });
}
}, [disabled]);
```
This only dispatches the disabled action if the item in the disabled prop is true.
Also, added …
> Tooltip: Move to Internal Tooltip

- packages/gestalt/src/IconButton.js
IconButton: reenabling tooltip when disabled  as there are use cases of disabled button tooltip messages
> IconButton: reenabling tooltip when disabled 

- packages/gestalt/dist/index.d.ts
SideNav AbstactEventHandle syntax error, and toast has a typo
Missing comma on SideNavigationTopItem,
Addional comma on SideNavigationNestedItem
Toast dismiss attribute has a typo
> Toast, SideNavigation: typo and syntax error

- packages/gestalt-design-tokens/tokens/color/alias.json
- packages/gestalt/src/contexts/__snapshots__/ColorSchemeProvider.jsdom.test.js.snap
Updated dark mode for $color-border-container to use roboflow 500 (#767676)
BEFORE
AFTER
The previous color was very hard to see and wasn't perceptually on-par with the light mode color
- [Jira](https://jira.pinadmin.com/browse/GESTALT-6973)
> Tokens: Updated dark mode $color-border-container

- packages/gestalt/dist/index.d.ts
- packages/gestalt/src/TableRowExpandable.js
- packages/gestalt/src/TableRowExpandable.jsdom.test.js
Table: fix Flow and TS types for Table.RowExpandable
> Table: fix Flow and TS types for Table.RowExpandable

- scripts/test.sh
Visual tests were not always running locally as expected. This updates old Bash script.
The old git diff command was paginating, and the grep command was not always finding instances.
This adds a `--name-only` flag to the git diff so we get a complete list of the files, and greps everything at once. 
It also wraps the function an if else statement to continue executing due to `set -euo pipefail` requirements
> Internal: Update local test check

- docs/docs-components/AccessibilityChecklist.js
- docs/docs-components/InternalDocumentationSection.js
- docs/docs-components/PageHeader.js
- docs/pages/get_started/developers/tooling/web.js
- docs/pages/web/avatar.js
- docs/pages/web/box.js
- docs/pages/web/button.js
- docs/pages/web/buttonlink.js
- docs/pages/web/datefield.js
- docs/pages/web/datepicker.js
- docs/pages/web/daterange.js
- docs/pages/web/flex.js
- docs/pages/web/iconbutton.js
- docs/pages/web/iconbuttonlink.js
- docs/pages/web/link.js
- docs/pages/web/masonry.js
- docs/pages/web/modal.js
- docs/pages/web/pageheader.js
- docs/pages/web/sheetmobile.js
- docs/pages/web/taparea.js
- docs/pages/web/taparealink.js
- docs/pages/web/toast.js
- docs/pages/web/utilities/colorschemeprovider.js
- docs/pages/web/utilities/defaultlabelprovider.js
- docs/pages/web/utilities/devicetypeprovider.js
- docs/pages/web/utilities/globaleventshandlerprovider.js
- docs/pages/web/video.js
Docs: integrate PDocs in web component docs #3241
Pinterest web is our main customer for web components. 
We have internal documentation around wrappers and Pinterest-specific implementations. 
This sections aims to provide more visibility to this critical docs  for engineers.
> Docs: integrate PDocs in web component docs

- docs/examples/tagdata/tooltip.js
- docs/examples/tiledata/tooltip.js
- docs/pages/web/tagdata.js
- docs/pages/web/tiledata.js
- packages/gestalt/dist/index.d.ts
- packages/gestalt/src/TagData.js
- packages/gestalt/src/TileData.js
- packages/gestalt/src/Tooltip/InternalTooltip.js
- packages/gestalt/src/utils/MaybeTooltip.js
Making tooltips more rich for dataviz components. This enables rich text.
Continuing to build on Internal Tooltip. This adds support for the `string[]` element to enable paragraphs and more spacing.
The m1On teams needs this to enable denser views and add more clarity around these elements.
- [Original thread](https://pinterest.slack.com/archives/C13KLG5P0/p1694560363775429?thread_ts=1674168008.120529&cid=C13KLG5P0)
- [Design Discussion](https://pinterest.slack.com/archives/GD6AMGH9C/p1694562105160289)
> TagData, TileData: Multi-line Tooltips

- docs/docs-components/data/components.js
- docs/examples/chartgraph/biaxial.js
- packages/gestalt-charts/src/ChartGraph.js
- packages/gestalt-charts/src/ChartGraph/renderAxis.js
- packages/gestalt-charts/src/ChartGraph/useDefaultLegend.js
- packages/gestalt-charts/src/ChartGraph/useDefaultTooltip.js
> ChartGraph: support to RTL

- packages/gestalt-datepicker/dist/index.d.ts
- packages/gestalt-datepicker/src/DateField.css
- packages/gestalt-datepicker/src/DateField.css.flow
- packages/gestalt-datepicker/src/DateField.js
- packages/gestalt-datepicker/src/DateField/InternalDateField.js
DateField: add `size` prop to match input field pattern and fix border color
BEFORE <> AFTER
https://jira.pinadmin.com/browse/GESTALT-6113
> DateField: add `size` prop to match input field pattern and fix border color

- packages/gestalt/src/Divider.css
This adds a set border-color to also tweak the vertical divider to match our standard border color. [Context here](https://pinterest.slack.com/archives/C0HUV5J93/p1697478365506619)
Before:
After:
> Divider: make vertical border lightgray

- docs/pages/foundations/data_visualization/charts_and_graphs/general_guidelines.js
- playwright/accessibility/foundations__data_visualization__charts_and_graphs__general_guidelines.spec.mjs
Fixed formatting in Chart use case paragraph of General guidelines for Charts and graphs.
/data_visualization/charts_and_graphs/general_guidelines#Chart-use-cases
Wasn't formatted properly in the merge:
> Docs: fixed paragraph typo

- docs/examples/status/textAdditionsExample1.js
- docs/pages/foundations/iconography/ICON_DATA.json
- packages/gestalt/src/Status.js
Added locked status to the Status component
Added a locked status:
Requested by m10n, as that is another workflow state.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-7032)
> Status: Add locked status

- packages/gestalt/src/RadioGroup.js
Broken cyclical import causing build issues. It was importing `gestalt` in the src directory
Changed the import to source
> Internal: Fix eventhandler import

- docs/docs-components/data/components.js
- packages/gestalt/src/Tag.js
Updated description for Tag
Changed from "Tags are objects that hold text and have a delete icon to remove them." to something that better describes what they are for: "
Better user comprehension. The original description is too vague and generic; we have a number of components that are objects that hold text and are dismissible.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-6988)
> Docs: updated Tag description

- docs/markdown/android/buttongroup.md
- docs/markdown/android/textarea.md
- docs/markdown/ios/button.md
- docs/markdown/ios/iconbutton.md
- docs/markdown/ios/sheet.md
- docs/markdown/ios/textarea.md
Updated heading inconsistencies
Changed "Mobile best practices" to "Best practices" in iOS and Android docs: Button, IconButton and Button Group.
Content design inconsistency.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-6916)
> Docs: Update best practices headings

- packages/gestalt/src/Video.js
- packages/gestalt/src/Video/Controls.js
- packages/gestalt/src/Video/Playhead.js
- packages/gestalt/src/Video/Playhead.jsdom.test.js
- packages/gestalt/src/Video/__snapshots__/Controls.test.js.snap
- packages/gestalt/src/Video/__snapshots__/Playhead.test.js.snap
- packages/gestalt/src/__snapshots__/Video.test.js.snap
Video: fix scrubber issue in mobile when mouse events don't work
onmouse events don't get trigger properly on mobile, specifically `onMouseMove`. implementing ontouch events so that scrubber works, particularly, `onTouchMove`. 
Bug:
Repro steps
In mWEb - Go to video pin https://www.pinterest.com/pin/52846995621056822/
When it starts to play, try to use the scrubber to move forward or backward
The scrubber does not move, but tapping on anywhere in the progress bar, the scrubber jumps to that position.
Tapping makes the scrubber move, not smooth sliding on it.
EXPECTED: The scrubber should move smoothly on the progress bar.
ACTUAL: Only on Video pins, the scrubber does not move smoothly, tapping on it makes it to jump.
eg: https://www.pinterest.com/pin/32228953576256499/ …
> Video: fix scrubber issue in mobile when mouse events don't work BUG-175963

- packages/gestalt/src/Video/Playhead.js
Video: preventDefault fix for mouse events
The original intention was to check passive events in touch events not mouse ones. 
Original PR: Video: fix scrubber issue in mobile when mouse events don't work BUG-175963 (https://github.com/pinterest/gestalt/pull/3310) - [Preview link](https://deploy-preview-3310--gestalt.netlify.app/?devexample=true)
In the Docs I don't see this issue, but in Pinboard I see a new focus ring that might come from not preventing the event and propagating.
BEFORE #3310
AFTER #3310
> Video: preventDefault fix for mouse events

- docs/docs-components/SandpackExample.js
- docs/docs-components/contexts/DocsExperimentProvider.js
- docs/examples/popover/localizationLabels.js
Sandpack examples are now wrapped with `ExperimentProvider` so that they will have also experiments which are enabled in Docs.
Recent Popover experiments were not working after the PR was merged.
> Docs: Add ExperimentProvider to Sandpack examples

- packages/gestalt/src/PopoverEducational.js
PopoverEducational should always be rendered near its anchor, not outside the root through portal.
When `disablePortal` is not set, Popover is rendered through portal and `zIndex` prop of PopoverEducational will have no effect.
> PopoverEducational: Add `disablePortal`

- packages/gestalt/src/Toast.css
Toast: reduce side margins from 32 to 16 px
Designs need more Toast space in mobile devices and small screens.
> Toast: reduce side margins from 32 to 16 px

- docs/docs-components/data/components.js
Quick edit to wording here:
to: "Accordion is a container that can be expanded and collapsed to show content about a single subject."
> Docs: update description of Accordion

- docs/docs-components/MainSectionSubsection.js
Updated `scroll-margin-top` for `MainSubSection` so that the title is visible on scrollsnap. 
Before:
After:
> Docs: Fix subsection scroll-magin-top

- docs/examples/taparea/mouseCursor.js
- docs/pages/web/taparea.js
Add descriptions for each type of cursor and when to use
> TapArea: Add cursor doc changes

- .vscode/settings.json
- docs/examples/list/fontSize.js
- docs/pages/web/list.js
- packages/gestalt/src/List.js
- packages/gestalt/src/List/InternalList.js
- packages/gestalt/src/List/Message.js
- packages/gestalt/src/ListItem.js
- packages/gestalt/src/__snapshots__/List.test.js.snap
- packages/gestalt/src/contexts/ListProvider.js
Add multiple sizes for list sizing.
We support the 'Text' Element in List, but not different font sizes. This adds more font sizing support to List to align with `Text` and passes it to the rest of the children.
Before:
AFter:
Adding support for a `size` prop to for varying and uniform font-sizes
List is used alongside paragraphs and other sets of text. Since it is primarily a text element, aligning with a text sizing here seems good.
> List: Add Sizing to List

- docs/examples/banneroverlay/avatar.js
- docs/examples/banneroverlay/desktop.js
- docs/examples/banneroverlay/doConcise.js
- docs/examples/banneroverlay/doEducate.js
- docs/examples/banneroverlay/doNavigate.js
- docs/examples/banneroverlay/dontCritical.js
- docs/examples/banneroverlay/icon.js
- docs/examples/banneroverlay/image.js
- docs/examples/banneroverlay/main.js
- docs/examples/banneroverlay/mobile.js
Fixed BannerOverlay examples where trailing space was omitted before links.
React Live added those during development, and Sandpack didn't, so the examples ended up looking wrong on release of the component.
> BannerOverlay: fixing trailing space in link examples

- docs/docs-components/PageHeader.js
- docs/docs-components/contexts/DocsExperimentProvider.js
- docs/pages/web/combobox.js
- docs/pages/web/dropdown.js
- docs/pages/web/helpbutton.js
- docs/pages/web/overlaypanel.js
- docs/pages/web/popover.js
- docs/pages/web/popovereducational.js
- docs/pages/web/tooltip.js
- packages/gestalt/src/Tooltip/InternalTooltip.js
Tooltip and Tooltip based components now can be switched between old and new implementation of Popover using ExperimentProvider by providing the experiment names:
- web_gestalt_popover_v2_tooltip
- mweb_gestalt_popover_v2_tooltip
Also, added `slimBannerExperiment` prop to `PageHeader` in docs-components. Because there is now a use case where 2 slimbanners needs to be displayed.
Tooltip component experiements can be toggled in the docs site to try them out.
Before:
After:
This is for the 3rd phase of releasing Popover based components. The experiments are not ramped-up in Helium and this PR 
> Tooltip: Add experiment hooks for using Popover v2

- .github/labeler.yml
- .github/workflows/pr-labeler.yml
- .github/workflows/semver.yml
Automatically add a "docs-update" label for non-docs changes. This will automatically skip package versioning.
As per #3334 this should skip the PR
[Github ](https://github.com/actions/labeler)ships a labeler workflow, and we can use that to auto label issues based on file changes. 
Adding a labeler workflow
Trying to avoid unused versions and only keep package related changes in npm
> Docs: Add a docs-update label to non-package related changes

- docs/docs-components/Markdown.js
Fix extra space in Markdown Links on Docs Pages
Removing an extra space
> Docs: Remove extra space link

- docs/pages/web/banneroverlay.js
- packages/gestalt/src/BannerOverlay.js
- packages/gestalt/src/__snapshots__/BannerOverlay.test.js.snap
This is a follow-up to BannerOverlay component creation, fixing issues with small screens on desktop not being responsive as intended.
On small desktop screens, the banner is going to mantain margins against the edges of the screen even if it becomes smaller than 900px, and on small breakpoints, the mobile variant is going to be used for desktop.
To prevent issues with rendering the CTAs on small desktop viewports.
> BannerOverlay: Fixing responsiveness and margin for small desktop viewports

- docs/pages/web/dropdown.js
- docs/pages/web/sheetmobile.js
- packages/gestalt/src/DropdownLink.js
Found a few stray references to Netlify preview deploys instead of our actual domain
> Docs: remove preview deploy links

- docs/docs-components/Header.js
Before:
After:
Removed old logic that controlled stickiness of the header based on window height. Replaced it with device type check.
The old logic was introduced here #1074 
Since the reasoning behind that change is no longer relevant, it is now removed.
> Docs: Make header always sticky for desktop

- docs/pages/year_in_review_2023.js
Fixed a couple of typos.
typescript to TypeScript
Iit to "It"
Typos needed to be fixed.
> Docs: Update year_in_review_2023.js

- docs/markdown/team_support/contributions.md
Fixed typos
fixed two typos: "contribuite" to "contribute" and "contribuition" to "contribution"
Typos. done in the browser.
> Docs: Update contributions.md

- package.json
- yarn.lock
Addressing [this](https://github.com/pinterest/gestalt/security/dependabot/83) high severity Dependabot alert
We need to upgrade to the latest version of `netlify-cli`, if possible
> Internal: upgrade netlify-cli to 3.39.4

- package.json
- yarn.lock
Addressing [this](https://github.com/pinterest/gestalt/security/dependabot/83) high severity Dependabot alert
We need to upgrade to the latest version of `netlify-cli`, if possible
Previous upgrades:
2.x.x --> 3.x.x: #3362
3.x.x --> 4.x.x: #3364
> Internal: upgrade netlify-cli to 6.15.0

- package.json
- yarn.lock
Addressing [this](https://github.com/pinterest/gestalt/security/dependabot/83) high severity Dependabot alert
We need to upgrade to the latest version of `netlify-cli`, if possible
Previous upgrades:
2.x.x --> 3.x.x: #3362
3.x.x --> 4.x.x: #3364
4.x.x --> 6.x.x: #3366
> Internal: upgrade netlify-cli to 7.1.0

- package.json
- packages/gestalt-core/build.js
- yarn.lock
(Apparently I've [tried this before](https://github.com/pinterest/gestalt/pull/2768). 🤞 this time goes better 😬)
Our current version of `cssnano` uses an older version of `postcss` which has a [security vulnerability](https://github.com/pinterest/gestalt/security/dependabot/82). I tried simply adding a resolution, but that ran into [changed API issues](https://github.com/pinterest/gestalt/actions/runs/7576463054/job/20635344707?pr=3367). I'm attempting to upgrade our `cssnano` version to obviate those issues.
> Internal: upgrade cssnano to 5.1.15

- .eslintrc.js
- docs/pages/foundations/international_design/icon_localization.js
- docs/pages/foundations/international_design/rtl_guidelines/iconography.js
- docs/pages/foundations/international_design/rtl_guidelines/layout_and_text_direction.js
- docs/pages/foundations/international_design/rtl_guidelines/typography.js
- packages/eslint-plugin-gestalt/src/button-icon-restrictions.js
- packages/eslint-plugin-gestalt/src/no-box-marginleft-marginright.js
- packages/eslint-plugin-gestalt/src/no-medium-formfields.js
- packages/eslint-plugin-gestalt/src/no-role-link-components.js
- packages/gestalt-charts/src/ChartGraph/LegendIcon.js
- packages/gestalt-charts/src/ChartGraph/renderGraphPoint.js
- packages/gestalt-charts/src/ChartGraph/useDefaultLegend.js
- packages/gestalt-datepicker/src/DateField/InternalDateField.js
A number of `no-unused-vars` suppressions had crept into the codebase. They almost all fell into a couple of buckets:
- copypasta on mobile docs pages
- unused keys when mapping over `Object.entries`
I tweaked the lint rule config to better support the latter of these, making two changes:
- `'args': 'after-used'`: for functions with positional arguments, unused args _before_ used args are ignored. Only unused args _after_ the used args will throw an error. See the [eslint docs](https://eslint.org/docs/latest/rules/no-unused-vars#args-after-used) for more details.
- `'argsIgnorePattern': '^_'`: Unfortunately the previous change doesn't help with most of our existing issues (the `Object.entries` errors). For code like
```js
([key, value]) => value && value.name && value.name.name === 'size' …
```
> Internal: fixes for no-unused-vars suppressions

- .github/pull_request_template.md
There has been some confusion about semver labels, so added a note about that (with examples of valid changes for each). Also some general cleanup and copyediting.
> Internal: update pull_request_template to include semver info

- packages/gestalt/src/Tooltip/InternalTooltip.js
Experiment name was not set correctly in #3333.
Updated the names to match the experiments in Helium and Pinboard.
> Tooltip: Fix v2 experiment name

- docs/pages/foundations/international_design/pluralization.js
end-aligned RLT languages inside tables on the page.
> Docs: end-align P10n table

- docs/docs-components/ColorPalette.js
- docs/docs-components/ColorTile.js
- docs/pages/foundations/color/palette.js
- docs/pages/foundations/design_tokens.js
Tokens: update color token documentation to include transparent and improve how base colors are explain and linked to concepts such as extended palette and semantic tokens.
BEFORE
AFTER
> Tokens: update color token documentation

- packages/gestalt-design-tokens/CHANGELOG.md
- packages/gestalt-design-tokens/tokens/color/alias.json
- packages/gestalt/src/contexts/__snapshots__/ColorSchemeProvider.jsdom.test.js.snap
Changelog: [packages/gestalt-design-tokens/CHANGELOG](https://github.com/pinterest/gestalt/blob/master/packages/gestalt-design-tokens/CHANGELOG.md)
| name                   | old value                     | new value                     |
| ---------------------- | ----------------------------- | ----------------------------- |
| color-text-subtle      | color.gray.roboflow.550.value | color.gray.roboflow.500.value |
| color-text-icon-subtle | color.gray.roboflow.550.value | color.gray.roboflow.500.value |
Before 
After
Reconcile with Figma values
It might break visual snapshots
> Tokens: change color-text-subtle &  color-text-icon-subtle  value to match Figma + Token changelog

- packages/gestalt/src/Avatar/Foundation.js
Before:
After:
Changing the icon used for `addCollaborators` prop on AvatarGroup
Changing the icon for add-collaborators.
Improved user comprehension
> AvatarGroup: Update addCollaborators icon from 'add' to 'add-person'

- docs/docs-components/MarkdownPage.js
- docs/docs-components/PageHeader.js
- docs/pages/[...id].js
Way back in #3054, I introduced a bug where the `alias` field was hardcoded to use web component metadata. It appeared to work for most mobile components by accident — but was broken for any mobile component that didn't have a web counterpart.
This PR parses the platform for Markdown pages (e.g. all mobile docs) and passes it through to ensure we're using component metadata for the correct platform.
> Docs: fix alias section on mobile pages

- docs/examples/radiogroup/addingABadgeExample.js
- docs/pages/web/radiogroup.js
- packages/gestalt/src/RadioGroupButton.js
- packages/gestalt/src/__snapshots__/RadioGroup.test.js.snap
RadioGroup now has a prop to add a Badge next to the label.
To satisfy the use case where users need both a Badge and a helperText with a RadioGroup.RadioButton option, as described in the component request: https://jira.pinadmin.com/browse/GESTALT-7505
- [Jira](https://jira.pinadmin.com/browse/GESTALT-7505)
> RadioGroup: Add Badge prop

- packages/gestalt/src/Tag.js
- packages/gestalt/src/__snapshots__/ComboBox.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/Tag.test.js.snap
- packages/gestalt/src/__snapshots__/TextArea.test.js.snap
- packages/gestalt/src/__snapshots__/TextField.test.js.snap
Tag uses `break-word` by default. But tags don't have to be full sentences. So things like ids and other important data gets cut off after the first word that can fit, leaving a lot of unfilled room.
Before:
After:
> Tag: Change tag contents to break-all

- docs/examples/buttonlink/colors.js
- docs/examples/buttonlink/washColors.js
- docs/pages/web/buttonlink.js
- packages/gestalt/src/BannerUpsell.js
- packages/gestalt/src/Button.css
- packages/gestalt/src/ButtonLink.js
ButtonLink: fix on darkmode colors + more documentation
> ButtonLink: fix on darkmode colors + more documentation

- docs/pages/foundations/design_tokens/component_tokens.js
- docs/pages/foundations/iconography/library.js
- packages/gestalt-design-tokens/CHANGELOG.md
- packages/gestalt-design-tokens/tokens/color/component.json
- packages/gestalt/dist/index.d.ts
- packages/gestalt/src/BannerOverlay.css
- packages/gestalt/src/IconButton.css
- packages/gestalt/src/RadioButton.css
- packages/gestalt/src/SearchField.css
- packages/gestalt/src/SearchField.js
- packages/gestalt/src/contexts/__snapshots__/ColorSchemeProvider.jsdom.test.js.snap
- packages/gestalt/src/shared/FormElement.css
Run
```
--component=SearchField
--prop=onChange
```
or
```
--component=SearchField
--prop=onFocus
```
`onChange: ({   value: string,   syntheticEvent: SyntheticEvent<HTMLInputElement>, }) => void
`
to 
`onChange: ({   value: string,   event: SyntheticEvent<HTMLInputElement | HTMLButtonElement>, }) => void
`
```
onFocus?: ({
syntheticEvent: SyntheticKeyboardEvent<HTMLInputElement>,
value: string,
}) => void
```
to 
```
onFocus?: ({
event: SyntheticKeyboardEvent<HTMLInputElement>,
value: string,
}) => void
```
Textfield:   implement background color tokens in form fields and some code cleanups 
NEW
| name                                | light   | dark    |
| …
> Textfield, RadioGroup, SearchField:   implement background color tokens in form fields and some code cleanups 

- docs/markdown/team_support/contributions.md
- packages/gestalt-datepicker/src/DatePicker.css
- packages/gestalt-design-tokens/CHANGELOG.md
- packages/gestalt-design-tokens/tokens/color/alias.json
- packages/gestalt-design-tokens/tokens/color/component.json
- packages/gestalt-design-tokens/tokens/elevation/component.json
- packages/gestalt-design-tokens/tokens/rounding/component.json
- packages/gestalt/src/contexts/__snapshots__/ColorSchemeProvider.jsdom.test.js.snap
DatePicker: tokenize colors and other internal styles #3438
NEW
| name                                        | light                                                 | dark                             |
| ------------------------------------------- | ----------------------------------------------------- | -------------------------------- |
| color-background-datepicker-container       | #fff                                                  | #212121                          |
| color-background-datepicker-button-default  | #fff                                                  | #212121                          |
| color-background-datepicker-button-hover    | rgba(0, 0, 0, 0.06)                                   | rgba(250, 250, 250, 0.5)         |
| …
> DatePicker: tokenize colors and other internal styles 

- packages/gestalt/src/ComboBox.js
- packages/gestalt/src/Dropdown.js
- packages/gestalt/src/HelpButton.js
- packages/gestalt/src/OverlayPanel/ConfirmationPopover.js
Popover v2 has built-in portalling feature. But it doesn't support z-index yet.
ComboBox, Dropdown and HelpButton control portalling themselves with Layer which supports z-index.
Basically here we were having 2 nested React.Portals. (Floating UI) Popover's internal portal is conflicting with Gestalt Layer and rendering itself outside of Layer (which leaves Layer empty and useless). That's why Layer's zIndex prop has no effect on the rendered Popover, as it would be in a different Portal.
This confusion will be eliminated as soon as the legacy Popover code is removed. The purpose of introducing internal Portal for Popover was to deprecate using Layer + Popover combination for internal usages.
Bug was reported in [Slack](https://pinterest.slack.com/archives/C13KLG5P0/p1708465918425379)
- …
> ComboBox, Dropdown, HelpButton: Disable internal Popover portal

- docs/docs-components/contexts/DocsExperimentProvider.js
- packages/gestalt/src/Popover.js
- packages/gestalt/src/Popover/Contents.js
- packages/gestalt/src/Popover/Controller.js
- packages/gestalt/src/Popover/InternalPopover.js
- packages/gestalt/src/PopoverEducational.js
- packages/gestalt/src/Tooltip/InternalTooltip.js
- packages/gestalt/src/__snapshots__/Popover.jsdom.test.js.snap
- packages/gestalt/src/__snapshots__/PopoverEducational.jsdom.test.js.snap
There was an overlooked case during Floating-UI integration. Tooltip didn't need FloatingFocusManager. Tooltip is not an accessible component.
Default values of new props `hideWhenReferenceHidden` and `disableFocusTrap` are now passed at the component props level. Previously the defaults set at `Contents` component level. This change makes it more obvious how the components behave. The default value now also displayed in the docs.
For the context, this is the table of components classified by accessiblity features:
> Popover, Dropdown, ComboBox, Tooltip: Disable focus trap for Tooltip + fixed a11y in Dropdown, ComboBox

- packages/gestalt/dist/index.d.ts
- packages/gestalt/src/TextField.js
- packages/gestalt/src/TextField/InternalTextField.js
Added a dataTestId prop to TextField. Used #2726 as a model.
To allow for deprecating the Sterling TextField component, that implements their own as a Box around the TextField.
- [Jira]https://jira.pinadmin.com/browse/GESTALT-7558
> TextField: Add dataTestId prop

- packages/gestalt/dist/index.d.ts
- packages/gestalt/src/Accordion.js
- packages/gestalt/src/Accordion/ExpandableItem.js
- packages/gestalt/src/Accordion/Title.js
- packages/gestalt/src/AccordionExpandable.js
- packages/gestalt/src/Datapoint.js
- packages/gestalt/src/Datapoint/InternalDatapoint.js
- packages/gestalt/src/Dropdown/OptionItem.js
- packages/gestalt/src/DropdownItem.js
- packages/gestalt/src/DropdownLink.js
- packages/gestalt/src/RadioGroupButton.js
Adding dynamic types to hardcoded versions of BadgeType across Gestalt.
Adding more types to Badge would not be reflected on the BadgeType for these components.
- [Slack](https://pinterest.slack.com/archives/C13KLG5P0/p1708713858987789?thread_ts=1705437845.356239&cid=C13KLG5P0)
> RadioGroup, Accordion, Datapoint, Dropdown: Fixing badge type

- docs/examples/selectlist/main.js
- packages/gestalt/src/SelectList.js
- packages/gestalt/src/__snapshots__/SelectList.test.js.snap
- packages/gestalt/src/shared/FormElement.css
- packages/gestalt/src/shared/FormElement.css.flow
Fix.
BEFORE
AFTER with BUG
AFTER with FIX
We need move the background color below the Icon position so it's visible again.
> SelectList: fix for hidden arrow-down Icon

- packages/gestalt/src/Dropdown.js
- packages/gestalt/src/Popover/InternalPopover.js
Auto focusing dismiss button when Popover is mounted causing the content jump. 
When Popover is mounted, it is not yet positioned correctly and it is at `top: 0; left: 0`. That's why focusing it scrolls the page up.
Focusing the dismiss button is actually redundant and `FloatingFocusManager` takes care of focusing the 1st focusable element inside floating element, i.e. Popover.
Also, for Dropdown `shouldFocus={false}` was set to Popover becasue Dropdown's item always gets the focus. That's why focusing on Popover itself is redundant.
- [Bug in Jira](https://jira.pinadmin.com/browse/BUG-180930)
> Popover: Remove autofocusing dismiss button

- packages/gestalt-design-tokens/build.js
- packages/gestalt-design-tokens/config.json
Adding token original references to tokens
https://amzn.github.io/style-dictionary/#/formats?id=androidresources
> Tokens: set `outputReferences": true` for android/resources

- packages/gestalt/src/Masonry.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.test.js
This PR addresses two issues with Masonry when `_twoColItems` is enabled:
- `defaultTwoColumnModuleLayout` does not return the full set of item positions when there is a two column module (e.g. if we pass in 50 items, we currently do not get 50 positions back). This is because we currently early a subset of positions depending on where we end up placing the two column module. This PR addresses the issue by ensuring that we also return the positions for the remaining items as well.
- When hydrating from a server rendering, `itemsToRender` will initially be empty because we are rendering items which already have positions (in the two column case) vs items that have measurements. This was previously necessary because of the above mentioned issue. This PR addresses this by just being …
> Masonry: Fix initial flash for two-column mode

- packages/gestalt/src/TagData.js
- packages/gestalt/src/__snapshots__/TagData.test.js.snap
Changing Breakword to BreakAll:
To align with Tag Behavior as in https://github.com/pinterest/gestalt/pull/3435
> TagData: Move to BreakAll

- docs/docs-components/MarkdownPage.js
- docs/markdown/team_support/contributions.md
The previous max width for text was defined globally. This adds it per element and wraps text to always to be 664px or less.
Before:
After:
Wrapping 
This was creating inconsistencies in the docs site between markdown pages and js pages
> Docs: Fix md page width

- docs/integration-test-helpers/masonry/MasonryContainer.js
- packages/gestalt/src/Masonry.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.test.js
- playwright/masonry/two-module.spec.mjs
This PR fixes an issue where the page would freeze trying to calculate the position of a two column module when there are many items that have the height already measured but not the position. This is required to enable the use of a two column module on the first page (with the items comming from the server).
When Masonry is first rendered it measures the heights of all the items at the same time, after that it calculates the positions. This was not a problem for one column items because the process to calculate the positions is very fast, but for two column items this is really hard because it has to create the graph for all the items not limited to the batch size, depending on the amount of items this can freeze the page completely. 
To fix it we can force the batch size when there is a …
> Masonry: Enable two column module on secod batch

- docs/pages/get_started/developers/eslint_plugin.js
- packages/eslint-plugin-gestalt/README.md
- packages/eslint-plugin-gestalt/rollup.config.js
- packages/eslint-plugin-gestalt/src/__fixtures__/only-valid-tokens/invalid/dangerouslySetInlineStyle-input.js
- packages/eslint-plugin-gestalt/src/__fixtures__/only-valid-tokens/invalid/dangerouslySetInlineStyle-output.js
- packages/eslint-plugin-gestalt/src/__fixtures__/only-valid-tokens/invalid/inline-input.js
- packages/eslint-plugin-gestalt/src/__fixtures__/only-valid-tokens/invalid/inline-output.js
- packages/eslint-plugin-gestalt/src/__fixtures__/only-valid-tokens/invalid/unsafeCss-input.js
- packages/eslint-plugin-gestalt/src/__fixtures__/only-valid-tokens/invalid/unsafeCss-output.js
- packages/eslint-plugin-gestalt/src/__fixtures__/only-valid-tokens/invalid/variable-input.js
- packages/eslint-plugin-gestalt/src/__fixtures__/only-valid-tokens/invalid/variable-output.js
- packages/eslint-plugin-gestalt/src/__fixtures__/only-valid-tokens/valid/valid.js
- packages/eslint-plugin-gestalt/src/index.js
- packages/eslint-plugin-gestalt/src/only-valid-tokens.js
- packages/eslint-plugin-gestalt/src/only-valid-tokens.test.js
ESLint plugin: only-valid-tokens
It includes FIX
ERROR
FIX
MESSAGING:
Examples:
> ESLint plugin: `only-valid-tokens`

- packages/gestalt/src/Masonry.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.test.js
To enable the use of a two column module on Masonry using SSR we need to:
- Identify on CSS and early scripts if an item is two column. This PR adds a new attribute to the ssr structure called `data-column-span` that can hold the column span value of the item.
- Add logic to set the correct witdh for n column modules when rendered for mearurements
- Change the logic of the split index on large batches so tcm can be moved to the first position when applicable
> Masonry: Adds a data attribute for two column module on ssr

- playwright/masonry/scroll-performance.spec.mjs
This PR updates the implementation of the Masonry scroll performance test (first introduced in https://github.com/pinterest/gestalt/pull/3388) to improve the accuracy of the calculations
I was looking into comparing data from the scroll performance test against previous runs. Before doing so, I wanted to validate the accuracy of our existing scroll performance test. 
After running the existing test locally, I noticed two things:
- the average FPS numbers seemed consistently high (e.g. 80, 90)
- if i artificially slow down the render (e.g. by rendering a very deep component), the average FPS drops but is still much higher than it should be (50+)  
The current implementation captures `Tracing` events via the chrome devtools protocol and specifically uses the delta between …
> Masonry: Update scroll performance test

- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.test.js
This PR reverts the change to splitIndex that was made in https://github.com/pinterest/gestalt/pull/3482. This ensures that we don't reposition two column items when server rendering
> Masonry: Revert splitIndex change

- docs/examples/popovereducational/zIndex.js
- docs/pages/web/popovereducational.js
- packages/gestalt/src/LegacyContents.js
- packages/gestalt/src/LegacyController.js
- packages/gestalt/src/Popover/LegacyInternalPopover.js
- packages/gestalt/src/PopoverEducational.js
- packages/gestalt/src/__snapshots__/LegacyController.jsdom.test.js.snap
PopoverEducational: fix zIndex bug + add example
Zindex was not properly working. Zindex was not being applied to absolute positioned Contents component. Removed unnecessary Box.
BEFORE
AFTER
> PopoverEducational: fix zIndex bug + add example

- packages/gestalt/src/Masonry/MeasurementStore.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.test.js
When we render the items of the first row if there is a two column item on the last spot of the row we have to replace it with another one column item, we can handle that on ssr but when hydration happens this item can swap places with other item since it is part of the graph of the two column item.
This PR handles this taking advantage of the concepts of pre items (items to be rendered before the two column module) and introducing a new array `graphBatch` this two represent what comes before the two column item and what is used to create the graph to position the two column item.
We can change the `splitIndex` so we can have more items on the `pre` depending on if the two column module fits or not and have a consistent experience with ssr. 
So the original position of the two column item …
> Masonry: Positions tcm correctly for last item on first row

- docs/integration-test-helpers/masonry/MasonryContainer.js
- docs/integration-test-helpers/masonry/items-utils/generateExampleItems.js
- docs/integration-test-helpers/masonry/items-utils/generateRealisticExampleItems.js
- docs/pages/integration-test/masonry.js
Masonry integration tests now have randomized values that are deterministic from one test run to the next due to the addition of a custom pseudo random number generator that accepts a seed value.
This allows us to write integration tests to assert things like "this two column element should be rendered on the third row, which is the optimal position given these item sizes".
- [Jira](https://jira.pinadmin.com/browse/GESTALT-7638)
> Masonry: seeded random values for deterministic integration tests

- packages/gestalt/src/SideNavigation.css
SideNavigation had `overflow: scroll` which makes the scrollbar always be displayed. It is now changed to `overflow: auto` so that scrollbar appears only when content overflows.
**BEFORE**
**AFTER**
> SideNavigation: Display scrollbar only when content overflows

- packages/gestalt/src/Masonry.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.test.js
When the position for items on the first row are calculated with a multi column item and the batch is small the correct postition was not set correctly because we returned `0` as split index although we have to maintain al least the position of the elements on the first row.
To fix this intead of returning 0 we return the number of available slots on first row to fill them correctly. This means that the multi column item will have less items to calculate the optimal position but in my testing is not that bad and we need to keep the items on the first row.
Unit test added
- We were incorrectly passing batches of only 5 elements to the layout
- We can change `columnCount` with `availableSlotsOnFirstRow` to calculate split index since that is more accuarate
> Masonry: Multi column feature, fix first row items position when batch is small

- docs/docs-components/ExampleCode.js
- docs/examples/sidenavigation/collapsibleExample.js
- docs/examples/sidenavigation/collapsibleHeaderExample.js
- docs/examples/sidenavigation/collapsibleWithMixedIconsExample.js
- docs/examples/sidenavigation/collapsibleWithoutIconsExample.js
- docs/pages/web/sidenavigation.js
- packages/gestalt/src/Layout.css
- packages/gestalt/src/Layout.css.flow
- packages/gestalt/src/SideNavigation.css
- packages/gestalt/src/SideNavigation/NavigationContent.js
- packages/gestalt/src/__snapshots__/SideNavigation.test.js.snap
When SideNavigation content overflowed, the scrollbar was appearing on top of the items. Because the wrapper responsible for scrolling had a static width. I separated the wrapper into 2:
- 1st one is responsible for scrolling
- 2nd is for preserving the width
This way the scrolling wrapper doesn't take up the space preserved only for SideNavigation content.
However, it was not enough. Now that the outermost wrapper has a dynamic width, when SideNavigation is expanded AS OVERLAY, it pushed the page content like it does in expanded state (which it shouldn't).
That's why, with the power of JavaScript, the "calculated" width (by browser) of the SidaNavigation is recorded just before it is exapanded as overlay. Then it is set as a static width to it, so that 
1. Sidenavigation doesn't push the …
> SideNavigation: Fix scrollbar clipping in collapsed state

- docs/docs-components/contexts/DocsExperimentProvider.js
- docs/pages/web/overlaypanel.js
- packages/gestalt/src/OverlayPanel/ConfirmationPopover.js
- packages/gestalt/src/__snapshots__/OverlayPanel.jsdom.test.js.snap
Removed all the experiment related code from ConfirmationPopover of OverlayPanel.
- [Jira](https://jira.pinadmin.com/browse/GWEB-67)
> OverlayPanel: Use ConfirmationPopover v2 #3501

- docs/markdown/team_support/design_contributions/design_contributions_overview.md
- playwright/accessibility/team_support__design_contributions__process_deep_dive.spec.mjs
Added a new overview image.
New image.
To make the new page more exciting, less drab with just a screenshot of Slack.
> Docs: Update contributions image

- docs/redirects.js
Added redirect to new Typography url
A redirect
Brand site is linking to an old url, and there wasn't a redirect.
- [Jira](https://pinterest.slack.com/archives/C06L0DR2KML/p1712147316786669)
> Docs: Update redirects.js

- docs/markdown/team_support/design_contributions/design_contributions_overview.md
- docs/markdown/team_support/design_contributions/process_deep_dive.md
Fixed broken urls
URL to Contribution types and criteria on the overview page. URL to the same on the Process deep dive page.
URLs were wrong and leading to 404 pages.
> Docs: Contributions

- packages/gestalt/src/PageHeader/components.js
- packages/gestalt/src/__snapshots__/PageHeader.test.js.snap
Moving to `BreakAll` for PageHeader title to solve this [issue](https://pinterest.slack.com/archives/C13KLG5P0/p1710181944469399) 
BEFORE 
AFTER
To test use 
`        title="Pinterest_app_Pinterest _app_Pinterest_app_Pinterest_app_Pinterest_app_Pinterest_app_Pinterest_app_Pinterest_app_Pinterest_app_Pinterest_app"
`
This fixes text wrapping on really long titles.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-7698)
> PageHeader: update heading to BreakAll to split on long titles

- docs/docs-components/contexts/DocsExperimentProvider.js
- docs/pages/web/combobox.js
- packages/gestalt/src/ComboBox.js
Reverts pinterest/gestalt#3512
Reverting to unblock newer bumps as the v2 release caused some test to fail in Pinboard (which will take a while to fix).
> Revert "ComboBox: Use Popover v2"

- packages/gestalt/src/Masonry/Graph.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.test.js
Currently to determine the optimal position of a two column item we create a graph that stores a certain combination of one column items and the whitespace that it has, we saw that in fact this was not the case because sometimes the two column item was positioned on very strange places.
The problem was that on the graph the node that was being returned as winner was not the one with the lowest whitespace but the parent of that node. This pr fixes that going through all the edges to find the lowest score and return the edge node, not the current node.
With this change I found one test that didn't have an optimal solution, the whitespace on the previous test was 3px, while with this fix the whitespace is in fact 0px.
Before fix
After fix
> Masonry: Fix incorrect node to solve graph positioning for two column items

- packages/gestalt/dist/index.d.ts
The Accordion component [size type props](https://github.com/pinterest/gestalt/blob/master/packages/gestalt/src/Accordion.js#L54) and [its default behavior](https://github.com/pinterest/gestalt/blob/master/packages/gestalt/src/Accordion.js#L80) indicates the prop is an optional prop, but the `dist/index.d.ts` file has it defined as mandatory causing an inconsistency.
The following PR change fixes it
> Accordion: Fix size type inconsistency with the Accordion component

- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.test.js
Tho determine the best position for the two column item the current behavior creates all the possible combinations of items on the graphBatch and then looks for the one with the minimum whitespace, although this works is very inneficient since we could have a good enough answer. To improve it this PR implements a new feature to exit early the algorithm when a certain whitespace threshold is found. 
Manual tests showed a really awesome improvement using a threshold of gutter*2 px, reducing the number of iterationr from 326 to ~4* (limited manual tests)
Unit test added
- To enable this a `whitespaceThreshold` must be set, but this PR doesn't set one, that would be on another pr to determine the best threshold
- The future of this feature is very related to the implementation of a dynamic …
> Masonry: Implement graph early bailout feature

- packages/gestalt/dist/index.d.ts
The [SideNavigation props](https://github.com/pinterest/gestalt/blob/master/packages/gestalt/dist/index.d.ts#L1841) in the index.d.ts file has missing types that are declared in the [component](https://github.com/pinterest/gestalt/blob/master/packages/gestalt/src/SideNavigation.js#L47) causing inconsistency
The missing props are:
- collapsed
- onCollapse
- onPreview
The following PR change fixes it
> SideNavigation: add type fixes based on component prop definition

- packages/gestalt/src/MasonryV2.js
This PR applies two more optimizations to MasonryV2: scroll throttle and memoizing each masonry item that we render
I realized that one change I did not carry over from current Masonry is throttling the callback of the scroll event listener, which means that we're currently triggering a render _every_ time scroll position changes (which is a lot). This PR reintroduces the same throttle that was currently use in control Masonry.
I was doing some investigation into React's startTransition API and noticed that it actually causes React to render _more_. A github thread I came across which was particularly interesting was : https://github.com/facebook/react/issues/24269. Based on this, one recommendation to reduce the impact from rendering more was to memoize the component that is expected to …
> Masonry: Scroll throttle + memo component (MasonryV2)

- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.test.js
We didn't have support for multiple multi column items on one pass of the layout logic, the impact is that in the case of multiple multi column items only the first one has the correct width since all others are treated as one col items.
The solution on this PR checks if there are more than one multi column item, in that case trim the items to position so we position the next multi column item on the next round.
- Previously there were discussions of not skiping items on the layout logic because that means an extra render to position the items, in this case I think is not so bad because: 1 - is a strange case, 2 - Is possible that we don't have enough items to have a good position of the second multi column item, this gives us a chance to have more
- In my testing if the multi column …
> Masonry: Enable multiple multi column items on layout logic

- packages/gestalt/src/MasonryV2.js
There is currently a bug with MasonryV2 where the element width is not re-calculated during a manually reflow. This PR addresses it by adding a `updateElementWidth` fucntion which is triggered on reflow.
Followup:
Ideally we should be able to leverage ResizeObserver to achieve this. will followup on that once we ship v2.
> Masonry: Update element height on reflow (MasonryV2)

- packages/gestalt-datepicker/package.json
- packages/gestalt-datepicker/src/DatePicker.css
- packages/gestalt-datepicker/src/DatePicker/InternalDatePicker.js
- yarn.lock
DatePicker: upgraded react-datepicker to 6.9.0
With this upgrade we get first day of week based in local 
With this change, DatePicker is now using Floating UI instead of Popper. This aligns with our own Popover.
> DatePicker: upgraded react-datepicker to 6.9.0

- packages/gestalt/dist/index.d.ts
- packages/gestalt/src/Accordion.js
- packages/gestalt/src/AccordionExpandable.js
Accordion, support borderStyles prop
They supports requests like
> Accordion: support borderStyles prop

- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.test.js
This PR fixes an issue introduced by https://github.com/pinterest/gestalt/pull/3544 that was causing overlapping positions in the `defaultTwoColumnModuleLayout` when a multi column item was rendered towards the end of the first page. 
The overlap happens in the situation when `initializeHeightsArray` is called and the following is true:
- there is a two column item
- the two column item is positioned _before_ single column items that come after it in the array
i.e.
[A, B, C, D, E, F, G] - assuming E is the multi column item and the layout looks like:
|  A  |  B  | C |
|  D  |  F  | G |
|  _   | E  |  E |
In this scenario, the current logic will think that the column height for column 1, 2 are B + E and C + E respectively. 
This PR fixes this scenario by simplifying the logic. Ultimately, …
> Masonry: Fix heights init

- packages/gestalt/src/Tag.css
Tag: fix padding in mobile browsers in button tag
BEFORE
AFTER
BUG: https://jira.pinadmin.com/browse/BUG-179079
On mobile browsers, button tag has a default padding. We reset it in Button but we didn't on Tag
> Tag: fix padding in mobile browsers in button tag

- docs/docs-components/data/components.js
Update component data to reflect the latest Android gestalt component code status
Mark all component listed in https://gestalt.pinterest.systems/android/component_status as Ready
The components list wasn't reflecting the real world status
- [Jira](https://jira.pinadmin.com/browse/ANDX-19589)
> Docs: Update Android component status to reflect the latest

- .github/workflows/alpha.yml
- .github/workflows/ci.yml
- .github/workflows/playwright.yml
- .github/workflows/release.yml
Updates GitHub actions to the latest version
1. Security & reliability of the Gestalt CI pipeline
2. Unblock https://github.com/pinterest/gestalt/pull/3560/
> Internal: Upgrade GitHub actions to v4

- packages/gestalt/src/SideNavigation/NavigationContent.js
- packages/gestalt/src/contexts/SideNavigationProvider.js
Replaced `setTimeout` logic with `transitionend` event. So that the transition duration is independent from JS code.
This also ensures that `transitioning` is set to `true` only when the transition is indeed ended (not when the timer signals so).
So that the transition duration is kept only in the CSS code.
> SideNavigation: Use TransitionEvent

- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.js
- packages/gestalt/src/MasonryV2.js
This PR addresses two issues I noticed with the multi-column layout, specifically on MasonryV2
In https://github.com/pinterest/gestalt/pull/3530/, we updated the measure batch size for multi-column to be `MULTI_COL_ITEMS_MEASURE_BATCH_SIZE` + 1 for `Masonry` but did not apply the same change to V2. This was causing multi-column positioning to be different between the two
I also noticed that https://github.com/pinterest/gestalt/pull/3545 introduced a scenario where the layout function can return _more_ positions than items, depending on what's already in the position cache. 
This is not a big deal for Masonry but it does affect V2 since we assume that if there are no items in the positionCache, we fall back to position by index. This PR addresses the issue by filtering out items that are …
> Masonry: Fix multi-column issues

- packages/gestalt/src/Popover/Contents.js
- packages/gestalt/src/Popover/usePopover.js
Popover is getting flipped before it can shift as much as it can. Popover needs to "shift" itself relative to the anchor to stay in the viewport. However, Popover is getting "flipped" to other direction because "flip" calculation is done BEFORE "shift". 
That's why "flip" middleware needs to be put after "shift". So that Popover can stay in the initial direction as long as possible before it flips.
> Popover: Flip direction after shifting

- .eslintignore
- .gitignore
- .prettierignore
- .stylelintignore
- package.json
Add temporary files to ignore list:
- `coverage/`
- `.rollup.cache/`
- `*.tsbuildinfo`
These files get auto-generated when we run CI commands (or `tsc` for TypeScript type checking) locally, and we should generally ignore these files (when we lint, format, commit, ...etc)
> Internal: add temporary files to ignore lists

- .github/workflows/playwright.yml
Change the OS which the playwright tests run on from MacOS 12 (Mac) to Ubuntu (Linux).
In [TypeScript migration](https://github.com/pinterest/gestalt/pull/3567), `yarn build` in CI consistently finished, but not in Playwright. The `yarn build` for playwright sometimes get stuck. After some investigation, I realized that this is not independent to which tests we run, and only depends on which OS the `yarn build` runs on. Regardlessly if it's Playwright workflow (`playwright.yml`) or CI workflow (`ci.yml`), the build would get stuck MacOS 12 and MacOS 14 but consistently finish in Ubuntu.
To unblock TypeScript migration, I'd like to change the OS which Playwright tests run on from MacOS to Ubuntu.
> Internal: change runs-on from macos-12 to ubuntu-latest

- docs/examples/masonry/align.js
- docs/pages/web/masonry.js
- packages/gestalt/src/Masonry.js
- packages/gestalt/src/Masonry/defaultLayout.js
- packages/gestalt/src/Masonry/defaultLayout.test.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.js
- packages/gestalt/src/Masonry/defaultTwoColumnModuleLayout.test.js
- packages/gestalt/src/Masonry/getLayoutAlgorithm.js
- packages/gestalt/src/Masonry/types.js
- packages/gestalt/src/MasonryV2.js
When layout is set to `basic`, the docs state that the grid will be "Left-aligned, fixed-column-width masonry layout." This wasn't the case, due to `gutterWidth` pushing the items away from the left side. When `gutterWidth` is set to `0`, it is appropriately left aligned, but then you have no gutter spacing between pins. 
Additionally, center alignment was miscalculated due to the inclusion of an extra gutter (e.g. when you have 4 columns, you should only calculate 3 `gutterWidths` for the `contentWidth`)
I've introduced a new optional prop `justify` which controls the horizontal alignment of items within the Masonry grid.
This change affects both Masonry and MasonryV2
Center alignment was slightly off, due to an extra `gutter` being calculated
| Before | After |
|--------|--------|
| …
> Masonry: Bug fix, "basic" layout not left aligning 

- playwright/accessibility/expectAccessiblePage.ts
- playwright/masonry/fetch-more.spec.ts
- playwright/masonry/flexible-resize.spec.ts
- playwright/masonry/handle-item-updates.spec.ts
- playwright/masonry/parent-sizing.spec.ts
- playwright/masonry/reflow-item-prop-changes.spec.ts
- playwright/masonry/render-height.spec.ts
- playwright/masonry/scroll-performance.spec.ts
- playwright/masonry/server-render-layout.spec.ts
- playwright/masonry/shuffle-items.spec.ts
- playwright/masonry/utils/clickButton.ts
- playwright/masonry/utils/countColumns.ts
- playwright/masonry/utils/getGridItems.ts
- playwright/masonry/utils/getServerURL.ts
- playwright/masonry/utils/getStaticGridItems.ts
- playwright/masonry/utils/resizeWidth.ts
- playwright/masonry/utils/selectors.ts
- playwright/masonry/utils/tracingEvents.ts
- playwright/masonry/utils/waitForRenderedItems.ts
This is a fix-up for https://github.com/pinterest/gestalt/pull/3580. The PR converts [Flow comment types](https://flow.org/en/docs/types/comments/) in Playwright tests to TypeScript types.
With the additional type coverage, this PR also removes some unused error suppressions and adds a few type-level fixes (e.g. adding optional chaining).
The Flow comment types are not handled in migration codemod, so we have to manually convert them to TypeScript types.
> Internal: playwright TypeScript types fixup

- docs/markdown/team_support/design_contributions/design_contributions_overview.md
Updated link on the Design Contributions page.
Fixed a broken Slack link—can't link to Slack workflows via the browser; linked to our design channel instead.
Link was broken
- [Jira](https://jira.pinadmin.com/browse/GESTALT-8005)
> Docs: Update design_contributions_overview.md

- docs/docs-components/contexts/DocsExperimentProvider.tsx
- docs/pages/web/dropdown.tsx
- packages/gestalt/src/Dropdown.tsx
- packages/gestalt/src/__snapshots__/Dropdown.jsdom.test.tsx.snap
Thanks for creating a PR! 🎉
- Please follow this template and delete items/sections that are not relevant to your changes, _including these instructions_.
- Make sure your [PR title](https://github.com/pinterest/gestalt/#releasing) matches our format: `{ComponentName}: Description (mention platform if relevant)`. If there are changes to multiple components, use `{ComponentName}, {OtherComponentName}: Description (mention platform if relevant)`.
- Each PR needs a [label](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels) indicating which [semantic version](https://semver.org/) should be applied:
- _Major_: Breaking changes to existing components (e.g. removing a prop, removing a prop value, removing a component).
- _Minor_: New components, …
> Dropdown: Remove experiment for alpha release

- packages/gestalt/src/Image.tsx
`<Image />` accepts an `onLoad` callback which ends up being attached to the native `img` element's `load` event handler and is triggered once the image resource has finished loading. 
The problem with this approach is that the `onLoad` handler does not get triggered if the image resource has already finished loading _before_ the `<Image />` component is rendered. The most common scenario of this happening is server-side rendering since the image request will be kicked off via the server-rendered HTML and, very likely, be completed by the time client hydration happens.
This PR introduces a fix for this by attached a ref callback to the native `img` callback which will do the following:
- check that `_fixCompletedOnLoad` is true, the [img complete …
> Image: Address onLoad not being called for SSR images

- packages/gestalt/src/TableOfContents/TableOfContentsAnchor.css
- packages/gestalt/src/TableOfContents/TableOfContentsAnchor.tsx
- packages/gestalt/src/__snapshots__/TableOfContents.test.tsx.snap
TableOfContents: Fix padding-inline-start padding-inline-end issues with PostCSS
All rtl CSS have the html in the CSS build:
Fixing but worth investigating why.
> TableOfContents: Fix padding-inline-start padding-inline-end issues with PostCSS

- docs/examples/pageheader/titleExample.tsx
- docs/pages/visual-test/PageHeader-thumbnail-badge-iconButton.tsx
- packages/gestalt/src/PageHeader.tsx
- packages/gestalt/src/PageHeader/components.tsx
first
```
yarn codemod modifyProp ~/path/to/your/code
--component=PageHeader
--previousProp=tooltipText
--nextProp=tooltip
```
PageHeader: standardize tooltip prop
> PageHeader: standardize tooltip prop

- docs/examples/badge/variantsType.tsx
- docs/pages/web/badge.tsx
- packages/gestalt/src/Badge.css
- packages/gestalt/src/Badge.tsx
Badge: add interactive icon to all types
BEFORE
AFTER
> Badge: add interactive icon to all types

- docs/examples/sidenavigation/primaryAction.tsx
- packages/gestalt/src/SideNavigationNestedGroup.tsx
- packages/gestalt/src/SideNavigationNestedItem.tsx
Now all the subcomponents of SideNavigation can have `primaryAction`.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-8031)
- [Figma](https://www.figma.com/design/vjhfBsOtHw0wVg67vqwz1v/branch/V3zxGsrUf68qHDFNmD7rKw/Gestalt-for-Web?m=auto&node-id=35045-2125&t=aAacqGW7EWFWfDga-1)
> SideNavigation: Add `primaryAction` prop to all nested subcomponents

- packages/gestalt/src/Video.test.tsx
- packages/gestalt/src/Video.tsx
- packages/gestalt/src/__snapshots__/Video.test.tsx.snap
- Add an optional `dataTestId` prop to Video
- Better compatibility with react testing library by allowing us to use `screen.queryByTestId` rather than `container.querySelector('video')`
> Video: Add `dataTestId` prop

- docs/markdown/android/searchguide.md
- docs/markdown/ios/searchguide.md
Changed embedded links from Figma and added more variants to the component's documentation.
Links were broken and SearchGuide has three new variants.
- [Jira]([GESTALT-7991](https://jira.pinadmin.com/browse/GESTALT-7991))
> SearchGuide: docs on mobile (iOS/Android)

- packages/gestalt/src/Masonry.tsx
- packages/gestalt/src/Masonry/fullWidthLayout.test.ts
- packages/gestalt/src/Masonry/fullWidthLayout.ts
- packages/gestalt/src/Masonry/getLayoutAlgorithm.ts
- packages/gestalt/src/MasonryV2.tsx
Removed the `_legacyFlexibleGutterLogic` prop for masonry full width layout.
When we enabled multi column items on the flexible layout we found that there was a bug on the logic to calculate the height position, it was not used to calculate the new col height so the vertical gutter was ignored. To keep the same behavior we added a flag to keep the old logic, the proble is that this only works when not using the multi column modules logic. To be able to unify the logic we need to get rid of the legacy logic.
I did an investigation inside pinboard and the vast mayority of cases don't use a gutter so are not affected, a couple have 2px, 4px and 6px gutters, this was not too impactful.
There are some components that have 16px or higher but was not able to test them, in case we find issues we …
> Masonry: Remove legacy flexible gutter logic

- docs/docs-components/GeneratedPropTable.tsx
- docs/docs-components/TokenTable.tsx
- docs/pages/foundations/design_tokens/component_tokens.tsx
- docs/pages/foundations/design_tokens/overview.tsx
- package.json
- packages/gestalt-charts/src/ChartGraph/useDefaultLegend.tsx
- packages/gestalt-charts/src/ChartGraph/useDefaultTooltip.tsx
- packages/gestalt/src/Datapoint/InternalDatapoint.tsx
- packages/gestalt/src/Popover.tsx
- packages/gestalt/src/TextField/InternalTextFieldIconButton.tsx
- scripts/ts/removeUnusedTsExpectErrorComments.ts
- scripts/ts/tsRemoveUnusedTsExpectErrors.sh
- yarn.lock
Upgrade to TypeScript 5.5. See https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/
Also add the command `yarn ts:removeUnusedTsExpectErrors` to remove unused `@ts-expect-error`.
- Stay current
- v5.5 is the biggest TypeScript release, which includes an awesome feature: Inferred Type Predicates
What is Inferred Type Predicates? Basically, it adds type narrowing in array filtering.
So instead of writing the overly complex form
```ts
// reduce instead of filter to appease type checker
myArray.reduce<Array<Item>>(
(arr, item) =>
arr.concat(shouldInclude(item) ? [item] : []),
[],
)
```
You can just write:
```ts
myArray.filter((item) => shouldInclude(item))
```
> Internal: Upgrade TypeScript to 5.5

- docs/integration-test-helpers/masonry/MasonryContainer.tsx
- packages/gestalt/src/Masonry.tsx
- packages/gestalt/src/Masonry/defaultLayout.test.ts
- packages/gestalt/src/Masonry/defaultLayout.ts
- packages/gestalt/src/Masonry/fullWidthLayout.test.ts
- packages/gestalt/src/Masonry/fullWidthLayout.ts
- packages/gestalt/src/Masonry/getLayoutAlgorithm.ts
- packages/gestalt/src/Masonry/multiColumnLayout.test.ts
- packages/gestalt/src/Masonry/multiColumnLayout.ts
- packages/gestalt/src/MasonryV2.tsx
This PR builds on Masonry's multi-column module support and adds support for _responsive_ grid modules
**Note: ** This is a breaking change since it removes support for Masonry's experimental `_twoColItems` prop in favor of `_getColumnSpanConfig`
At a high level, how N-column Masonry currently works:
- Modules can declare their column span via a static columnSpan property, which can span 1 - N columns, where N is the maximum number of columns in the grid
- Modules are positioned to optimize for reducing whitespace in the grid. We do this by generating a directed acyclic graph (DAG) of different layouts and picking the one with the least amount of whitespace. This means that we do not guarantee exact item positioning but can guarantee the general area (e.g. Pin 20 will not show up in the …
> Masonry: Responsive grid modules

- docs/pages/web/avatargroup.tsx
- packages/gestalt/src/AvatarGroup.tsx
AvatarGroup: enable actions in smaller sizes
BEFORE counter and addCollaborators were only available to md.
AFTER counter and addCollaborators are available to xs, sm, & md.
> AvatarGroup: enable actions in smaller sizes

- docs/pages/web/avatargroup.tsx
- packages/gestalt/src/AvatarGroup.tsx
AvatarGroup: fix, remove xs from actions
Follow up to https://github.com/pinterest/gestalt/pull/3646 as per design changes
> AvatarGroup: fix, remove xs from actions

- packages/gestalt/src/SelectList.tsx
- Added onBlur Prop: This prop allows developers to provide custom callback functions that are triggered when the element loses focus.
- Added onFocus Prop: This prop allows for custom callback functions to be provided, which are triggered when the element gains focus.
Standardized Prop Availability: Ensures consistency across Gestalt components by providing a standardized set of props (onBlur and onFocus) for handling focus events.
- [Jira](https://jira.pinadmin.com/browse/CPW-6880)
- [TDD](https://docs.google.com/document/d/1KxDV6YoKpeq-6Vff1TPu6E1bFdgzSY-sTz9qCcyCBIU/edit#heading=h.qvamkklezmc7)
> SelectList: Added onBlur/onFocus props

- packages/gestalt/src/SearchField.tsx
- packages/gestalt/src/SelectList.tsx
- packages/gestalt/src/TextArea.tsx
- packages/gestalt/src/TextField/InternalTextField.css
- packages/gestalt/src/TextField/InternalTextField.tsx
- packages/gestalt/src/__snapshots__/BannerUpsell.test.tsx.snap
- packages/gestalt/src/__snapshots__/BannerUpsellForm.test.tsx.snap
- packages/gestalt/src/__snapshots__/ComboBox.jsdom.test.tsx.snap
- packages/gestalt/src/__snapshots__/NumberField.test.tsx.snap
- packages/gestalt/src/__snapshots__/TextField.test.tsx.snap
- packages/gestalt/src/sharedSubcomponents/FormElement.css
TextField, SearchField, TextArea, SelectList: fix Label implementation consistency
MD (TextArea only LG)
- SelectList rounding
LG
- Label spacing
MD  (TextArea only LG)
LG
Inconsistencies
> TextField, SearchField, TextArea, SelectList: fix Label implementation consistency

- packages/eslint-plugin-gestalt/package.json
- packages/gestalt-charts/package.json
- packages/gestalt-datepicker/package.json
- packages/gestalt-design-tokens/package.json
- packages/gestalt/package.json
Looks like the release pipeline step is failing because of a tag clash. This updates package.json to bump the other versions.
> Docs: fixing release pipeline

- docs/docs-components/CombinationNew.tsx
- docs/pages/web/iconbutton.tsx
- docs/pages/web/pog.tsx
- packages/gestalt/src/IconButton.tsx
- packages/gestalt/src/Pog.css
- packages/gestalt/src/Pog.tsx
Added the washLight color to IconButton background options, It uses the same background color as Button semi-transparent white.
The same was added to Pog, for consistency.
To comply with a component update request @ https://pinterest.slack.com/archives/D060Y91C4D9/p1719955590973859
- [Jira](https://jira.pinadmin.com/browse/CPW-7039)
- [Figma](https://www.figma.com/design/n5FTA5WAunEJmbIPsMBkcR/Leading-icon-to-Button%3A-Gestalt-classic-component-updates?node-id=64-1688&t=Uz5vAftxjqVy3yrj-0)
> IconButton, Pog: New background for classic IconButton

- docs/pages/foundations/design_tokens/component_tokens.tsx
People are getting this error when visiting:
https://gestalt.pinterest.systems/foundations/design_tokens/component_tokens
Netlify has a limit of 62KB on a page. The imported tokens file is 61KB.
This moves the large import of classic tokens to a server-side-prop to see if it works
> Tokens: Move Component_Tokens to getStaticProps

- packages/gestalt/src/SideNavigation/ItemContent.tsx
- packages/gestalt/src/__snapshots__/SideNavigation.test.tsx.snap
Border width affects the content width of an element. That's why it was causing `SideNavigation.GroupItem` to squeeze its contents when it has border.
Using box-shadow as border solves the problem as box-shadow doesn't affect the width of its element.
**BEFORE**
**AFTER**
> SideNavigation: Use outline as border

- docs/pages/visual-test/Masonry-renderLoadingItems-flexible.tsx
- docs/pages/visual-test/Masonry-renderLoadingItems-uniformRow.tsx
- packages/gestalt/src/Masonry.tsx
- packages/gestalt/src/Masonry/fullWidthLayout.test.ts
- packages/gestalt/src/Masonry/fullWidthLayout.ts
- packages/gestalt/src/Masonry/uniformRowLayout.test.ts
- packages/gestalt/src/Masonry/uniformRowLayout.ts
- Support the `flexible` and `uniformRow` layouts for rendering loading state items
- Add Masonry-renderLoadingItems-flexible visual test page
- Add Masonry-renderLoadingItems-uniformRow visual test page
- Allows us to use the shimmering skeleton loading state for all layouts now
> Masonry: Support flexible and uniformRow layouts for rendering loading state items

- docs/examples/defaultlabelprovider/translations.tsx
- docs/pages/web/utilities/defaultlabelprovider.tsx
- packages/gestalt/src/contexts/DefaultLabelProvider.jsdom.test.tsx
- packages/gestalt/src/contexts/DefaultLabelProvider.tsx
- packages/gestalt/src/sharedSubcomponents/thumbnailSubcomponents.tsx
Changed default accessibility label for Toast to 'dismiss message' instead of 'dismiss toast'. Also changed VR color for the success icon to 'default', as a special case for Toast.
https://pinterest.slack.com/archives/C014X9LTRCN/p1722364602407439?thread_ts=1721244858.309079&cid=C014X9LTRCN
> Toast: VR implementation changes

- docs/examples/textarea/tags.tsx
- docs/examples/textfield/tags.tsx
- docs/pages/web/textarea.tsx
- docs/pages/web/textfield.tsx
- packages/gestalt/src/TagArea/TagArea.css
- packages/gestalt/src/TagArea/TagArea.tsx
- packages/gestalt/src/TextArea.tsx
- packages/gestalt/src/TextField.tsx
TextArea, TextField: Add support for Tags with internal TagArea #3710
Both are the same for TextField and TextArea
> TextArea, TextField: Add support for Tags with internal TagArea #3710

- packages/gestalt/src/ComboBox.tsx
ComboBox: undoing breaking change in `id` set in #3712
> ComboBox: undoing breaking change in `id` set in #3712

- packages/gestalt/src/Masonry/multiColumnLayout.ts
This PR fixes an issue where setting the multi-column module width to `Infinity` causes the browser to freeze by updating `calculateActualColumnSpan` to  return the _minimum_ of `columnCount` or the computed value of `getColumnSpanConfig`. 
This is accurate since an item can never span more columns than supported by the grid.  In the case of `Infinity`, this was previously causing an infinite loop since the value of `calculateActualColumnSpan` was being use to initialize the item heights array.
> Masonry: Fix full-width module support

- packages/gestalt/src/Masonry.tsx
- packages/gestalt/src/Masonry/defaultLayout.ts
- packages/gestalt/src/Masonry/fullWidthLayout.ts
- packages/gestalt/src/Masonry/getLayoutAlgorithm.ts
- packages/gestalt/src/Masonry/multiColumnLayout.ts
- packages/gestalt/src/MasonryV2.tsx
We plan to add whitespace metrics to helium, for this we wanted to have a more robust insight on how the whitespace behaves and that means to add not just one number but all the gaps for modules that have 3 or more columns.
- All the references of the log whitespace function are changed from `number` to `ReadOnlyArray<number>`
- Removed the whitespace metric from `getGraphPositions` and instead use `getMultiColItemPosition` (This because on the later we have the info of all the whitespaces not just the node score)
- Changed the logic for whitespace to return the array with the corresponding whitespaces
- Also removed all the typescript suppression errors from `multiColumnLayout.ts`
> Masonry: Change whitespace logging from one number to an array

- packages/gestalt/src/Accordion.test.tsx
- packages/gestalt/src/Accordion.tsx
- packages/gestalt/src/Accordion/Title.tsx
- packages/gestalt/src/Badge.test.tsx
- packages/gestalt/src/Badge.tsx
- packages/gestalt/src/Icon.test.tsx
- packages/gestalt/src/Icon.tsx
- packages/gestalt/src/Text.test.tsx
- packages/gestalt/src/Text.tsx
- packages/gestalt/src/Tooltip.jsdom.test.tsx
- packages/gestalt/src/Tooltip.tsx
- packages/gestalt/src/Tooltip/InternalTooltip.tsx
Adding data test id for Accordion, Badge, Icon, Tooltip and Text Gestalt components
New prop dataTestId for Accordion and its sub components Gestalt components
Adding a new prop for some Gestalt components
To improve integration testing speed and accuracy
> Accordion, Badge, Icon, Text, Tooltip: Adding data test id

- docs/pages/foundations/accessibility.tsx
Add promotion to accessibility training
Updated Pinternal resource links
There are new accessibility training courses available we want to promote. We also want to remove the deprecated courses from the resource section.
- [Jira](https://jira.pinadmin.com/browse/A11Y-90)
> Docs: Add promotion to accessibility training and update Pinternal resources

- packages/gestalt/src/Masonry/defaultLayout.test.ts
- packages/gestalt/src/Masonry/defaultLayout.ts
- packages/gestalt/src/Masonry/fullWidthLayout.test.ts
- packages/gestalt/src/Masonry/fullWidthLayout.ts
- packages/gestalt/src/Masonry/layoutHelpers.ts
- packages/gestalt/src/Masonry/multiColumnLayout.test.ts
- packages/gestalt/src/Masonry/multiColumnLayout.ts
This PR updates Masonry to ensure that items with zero height do not actually occupy any space
At the moment, if Masonry renders a component with zero height (i.e. an item that returns `null`), it could still end up occupying space since we still add the `gutter` to the position. This results in subsequent items in the column being pushed down.
This PR addresses this by updating the `heightAndGutter` logic to only return height + gutter if height > 0. I also took the opportunity to clean up the code a tad
> Masonry: Ensure zero height items dont have a gutter

- package.json
- packages/gestalt/src/AvatarGroup/PositioningWrapper.tsx
- yarn.lock
Upgrade TypeScript from v5.5 to v5.6.
See https://devblogs.microsoft.com/typescript/announcing-typescript-5-6/ for the v5.6 release notes.
See also the previous v5.5 upgrade PR: https://github.com/pinterest/gestalt/pull/3643
Stay current
> Internal: Upgrade TypeScript to 5.6

- packages/gestalt/src/Sticky.tsx
We've gotten flagged for the following issue:
```
./node_modules/.pnpm/gestalt@159.0.0_react-dom@18.3.1+react@18.3.1/node_modules/gestalt/dist/Sticky.d.ts:43:27
Type error: Property 'bottom' does not exist on type 'Props'.
```
This is causing issues with ITP upgrades. It seems like we have TS suppressions to overcome this. This replaces the missing type options with a `never` and always ensures the property type is defined.
Adding missing types for properties that previously were unset.
ITP and other TS repos are unable to upgrade
> Sticky: Updating Types to avoid Prop Issues

- docs/examples/textfield/main.tsx
- packages/gestalt/src/ButtonToggle.tsx
ButtonToggle: adopted TextUI
|---|---|---|
| classic  |  ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/0ca02a20-46ca-46d9-84b6-8f9d08a4e5b4)   |  ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/7ae3543e-0f47-46e1-99a3-020de20111e9) |  
|  VR  |  ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/d1cdcfbd-cc1c-408e-956c-a42e8f4218dd)  |  ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/da245ff6-c12a-4f2b-a4a0-b3e1fe3f330a) |
> ButtonToggle: adopted TextUI

- packages/gestalt/src/Accordion/__snapshots__/ExpandableItem.test.tsx.snap
- packages/gestalt/src/IconButton.tsx
- packages/gestalt/src/__snapshots__/Accordion.test.tsx.snap
- packages/gestalt/src/__snapshots__/ActivationCard.test.tsx.snap
- packages/gestalt/src/__snapshots__/BannerCallout.test.tsx.snap
- packages/gestalt/src/__snapshots__/BannerSlim.test.tsx.snap
- packages/gestalt/src/__snapshots__/BannerUpsell.test.tsx.snap
- packages/gestalt/src/__snapshots__/IconButton.jsdom.test.tsx.snap
- packages/gestalt/src/__snapshots__/ModalAlert.jsdom.test.tsx.snap
- packages/gestalt/src/__snapshots__/PageHeader.test.tsx.snap
- packages/gestalt/src/__snapshots__/TableRowExpandable.test.tsx.snap
The wrapping flex around IconButton now renders conditionally
To reduce the number of snapshot changes necessary on Pinboard when bumping #3720
> IconButton: refactor to prevent snapshot change

- packages/gestalt/src/Tabs.css
Tabs: fix padding
Padding needed to position the underline border
> Tabs: fix padding

- docs/examples/taparea/focus.tsx
- docs/pages/web/taparea.tsx
- packages/gestalt/src/ButtonToggle.css
- packages/gestalt/src/ButtonToggle.tsx
- packages/gestalt/src/Focus.css
- packages/gestalt/src/TapArea.tsx
TapArea: support to VR visible focus style
> TapArea: support to VR visible focus style

- packages/gestalt/src/IconButton/InternalIconButton.tsx
- packages/gestalt/src/IconButtonFloating.tsx
IconButtonFloating: reverting circle to squircle as per Gestalt design request
AFTER Classic
BEFORE Classic
AFTER VR
BEFORE VR
> IconButtonFloating: reverting circle to squircle 

- docs/examples/taparealink/focus.tsx
- docs/pages/web/taparealink.tsx
- packages/gestalt/src/Link/InternalLink.tsx
- packages/gestalt/src/TapAreaLink.tsx
TapAreaLink: support to VR visible focus style
> TapAreaLink: support to VR visible focus style

- packages/gestalt/src/Focus.css
- packages/gestalt/src/Text.css
TapArea: fix focus token to support built-in darkmode### Checklist
> TapArea: fix focus token to support built-in darkmode

- packages/gestalt/src/Text.css
Icon: vertical-align unset (overriding vertical-align middle set by default in icons) when within Text
> Icon: vertical-align unset when within Text

- docs/examples/datepicker/mobile.tsx
- docs/examples/defaultlabelprovider/translations.tsx
- docs/pages/web/datepicker.tsx
- packages/gestalt-datepicker/src/DatePicker.jsdom.test.tsx
- packages/gestalt-datepicker/src/DatePicker.tsx
- packages/gestalt-datepicker/src/DatePicker/DateInput.tsx
- packages/gestalt-datepicker/src/DatePicker/InternalDatePicker.tsx
- packages/gestalt-datepicker/src/__snapshots__/DatePicker.jsdom.test.tsx.snap
- packages/gestalt/src/contexts/DefaultLabelProvider.jsdom.test.tsx
- packages/gestalt/src/contexts/DefaultLabelProvider.tsx
DatePicker: support SheetMobile for mobile
> DatePicker: support SheetMobile for mobile

- docs/examples/daterange/secondaryErrorMessages.tsx
- docs/pages/web/daterange.tsx
- packages/gestalt-datepicker/src/DateRange.tsx
DateRange: add example for secondary date errors (web) #3806
> DateRange: add example for secondary date errors (web)

- packages/gestalt/src/ButtonToggle.tsx
Reverted accidentally deleted lin of code that broke tap animation.
Reference: https://github.com/pinterest/gestalt/pull/3738/files#diff-687777f0ffbee69afb9f560b2c8602d3f68cb4844558ef9b76c5f159450285f2L223
**BEFORE**
**AFTER**
> ButtonToggle: Fix VR scale animation

- packages/gestalt/src/PopoverEducational.tsx
This PR adds an experimental prop to the component PopoverEducational so we can test out using it for notification purposes on web. This simply changes the background color of the current component.
Approved contribution doc: https://docs.google.com/document/d/1uhpW2DmYsMWXMba0J0xkJrUyg8YnPrUdLTyNN2eergs/edit 
Added prop: _experimentalVariant?: 'notification' | 'education'
If _experimentalVariant set to 'notification', set bgColor to be 'darkGray', otherwise default to 'blue'.
In August 2024, the Social Growth team shipped [this experiment ](https://helium.pinadmin.com/sg_dweb_app_start_msg_notif/)to show users a notification message on dWeb app start if they have unread messages and saw overall success on messaging engagement. At that time, we used a component that is not standard to …
> PopoverEducational: Add Experimental Prop for Notification (background color change)

- packages/gestalt/src/Masonry.tsx
- packages/gestalt/src/Masonry/defaultLayout.ts
- packages/gestalt/src/Masonry/fullWidthLayout.ts
- packages/gestalt/src/Masonry/getLayoutAlgorithm.ts
- packages/gestalt/src/Masonry/multiColumnLayout.ts
- packages/gestalt/src/Masonry/types.ts
- packages/gestalt/src/MasonryV2.tsx
We want to add Masonry metrics to Statsboard. We want to have insights on how many iterations we make each time we position a multicolumn module.
- logWhitespace now includes number of iterations to be used when logging
- Changed getGraphPositions to return winningNode and this new metric
https://github.com/user-attachments/assets/30b69a3c-3620-4337-9268-3053133abf27
Added the columnspan so we can use it as a tag when logging and potentially segment the data.
Enabling whitespace threshold to 16:
https://github.com/user-attachments/assets/62c2efd5-6add-47d4-95d9-6bf6a1c612dc
> Masonry: Log number of iterations it takes to find optimal whitespace

- packages/gestalt/src/Masonry/getLayoutAlgorithm.ts
- packages/gestalt/src/MasonryV2.tsx
This PR adds support for the experimental `_loadingItems` and `_renderLoadingItems` API to MasonryV2 
We originally excluded MasonryV2 since it was unclear whether this would ship. Given the likelihood that this will ship soon-ish, we need to support in V2
> Masonry: Add support for loading states to v2

- packages/gestalt/src/Masonry.tsx
- packages/gestalt/src/Masonry/getLayoutAlgorithm.ts
- packages/gestalt/src/MasonryV2.tsx
We are enabling whitespace threshold so it can be used to position multicolumn modules without excessive work to find an optimal whitespace.
This is a follow-up to https://github.com/pinterest/gestalt/pull/3817.
> Masonry: Enable whitespaceThreshold prop

- packages/gestalt/src/ButtonGroup.tsx
Implemented changes to ButtonGroup in VR. Specifically, the spacing between buttons was reduced by 2px.
Classic:
VR:
To conform to new VR designs.
- [Jira](https://jira.pinadmin.com/browse/CPW-7193)
- [Figma](https://www.figma.com/design/vjhfBsOtHw0wVg67vqwz1v/Gestalt-for-Web?node-id=2508-17905&node-type=canvas&m=dev)
> ButtonGroup: VR Implementation

- packages/gestalt/src/Masonry.tsx
- packages/gestalt/src/Masonry/defaultLayout.ts
- packages/gestalt/src/Masonry/fullWidthLayout.ts
- packages/gestalt/src/Masonry/getLayoutAlgorithm.ts
- packages/gestalt/src/Masonry/multiColumnLayout.test.ts
- packages/gestalt/src/Masonry/multiColumnLayout.ts
- packages/gestalt/src/MasonryV2.tsx
After experimenting, we decided on two different values for early bailout. This PR exposes a prop to enable this functionality.
- Removes whitespaceThreshold (We won't allow this value to be set from the outside)
- Adds earlyBailout prop
> Masonry: Add fixed early bailout depending on column span

- packages/gestalt/src/Masonry.tsx
- packages/gestalt/src/Masonry/defaultLayout.ts
- packages/gestalt/src/Masonry/fullWidthLayout.ts
- packages/gestalt/src/Masonry/getLayoutAlgorithm.ts
- packages/gestalt/src/Masonry/multiColumnLayout.test.ts
- packages/gestalt/src/Masonry/multiColumnLayout.ts
- packages/gestalt/src/MasonryV2.tsx
Change earblyBailout prop to receive a function to define value using column span.
- Changes earlyBailout from number to function
> Masonry: Add early bailout to be configurable from the outside

- docs/examples/daterange/readOnly.tsx
- docs/pages/web/daterange.tsx
- packages/gestalt-datepicker/src/DateRange.jsdom.test.tsx
- packages/gestalt-datepicker/src/DateRange.tsx
This PR introduces the `readOnly` prop, which makes all date inputs read-only. 
https://github.com/user-attachments/assets/5cbf187e-24f6-4008-ba41-ea09f4ed1ac5
There are some scenarios where you don't want to let the user introduce dates via typing into the date inputs since they could introduce invalid dates, this can be fixed by making them read only.
- [ABC-3856](https://jira.pinadmin.com/browse/ABC-3856)
> DateRange: add readonly optinal prop to DateRange component (web)

- packages/gestalt/src/Masonry.tsx
- packages/gestalt/src/Masonry/getLayoutAlgorithm.ts
- packages/gestalt/src/Masonry/types.ts
- packages/gestalt/src/Masonry/uniformRowLayout.test.ts
- packages/gestalt/src/Masonry/uniformRowLayout.ts
This PR enables flexible width columns for the `uniformRow` layout on Masonry
As part of the fluid grid experiment on desktop, we got some reports of uneven columns on the board page. This is because the board page is currently being opted into the default Masonry layout when it should be using the `uniformRow` layout since we always want even rows. 
-  Update layout prop to accept `uniformRowFlexible`
-  Update uniformRowLayout.ts to support flexible width columns
-  Update Masonry to use `getLayoutAlgorithm` to consolidate logic.
Note: While making this change, it occurred to me that `flexible` should likely just be an attribute on Masonry vs a separate layout. I'll make that change in a followup PR
> Masonry: Support flexible for uniformRow layout

- packages/gestalt/src/MasonryV2.tsx
This PR fixes a bug with Masonry V2 which can cause a delay in items being rendered when unmounting/restoring scroll position.
Currently, we initialize the `containerHeight` and `containerOffset` values during the initial render and then, subsequently, trigger async updates. However, this results in a delay during the initial render because `scrollContainer` is not set, which results in the order of operations being:
- render
- set containerHeight, containerOffset
- set scrollContainer
- (async) update containerHeight and containerOffset
Because of this, we can sometimes see a delay in pins being rendered when navigating back and forth in related pins.
This PR addresses the issue by "forcing" a measurement of `containerHeight` and `containerOffset` whenever we detect any change to …
> Masonry: Update container measurement logic for V2

- packages/gestalt/src/Masonry/fullWidthLayout.ts
- playwright/masonry/flexible-resize.spec.ts
Currently, when calculating column widths via `fullWidthLayout`, the values of the column widths are rounded down via Math.floor. 
Because we rely on CSS (specifically `calc`) for the initial server render, this can actually cause slight layout shifts when going from server render -> client render due to the slight difference in widths
While visually, this is not an issue (due to the shift being so tiny), this can actually result in LCP regressions since this results in a repaint.
This PR addresses the issue by removing the Math.floor. After this change, the column width will stay consistent between server and client render
> Masonry: Update fullWidthLayout to not floor column widths

- packages/gestalt-design-tokens/src/transformers/transformGroups.js
- packages/gestalt-design-tokens/src/transformers/transforms.js
- packages/gestalt-design-tokens/tests/__snapshots__/android.test.js.snap
This changes the value of the Android circle rounding output from `50%` to `0.5`. No actual token values have been updated.
> Tokens: Remove percents from Android rounding

- packages/gestalt/src/Masonry/fullWidthLayout.ts
- playwright/masonry/flexible-resize.spec.ts
Reverts pinterest/gestalt#3874
apparently having floating point column widths breaks pinboard
> Revert "Masonry: Update fullWidthLayout to not floor column widths"

- packages/gestalt/src/Spinner.css
This is a hypothesis for Spinner not showing when a delay is added. 
It removes the opacity variable that is then used to animate when spinning. Sometimes this transition fails and the spinner doesn't appear.
A similar problem also happened here. So removing the usage of tokens because we didn't change anything otherwise:
https://github.com/pinterest/gestalt/pull/3213/files
> Spinner: Remove Opacity Token

- packages/gestalt/src/Spinner.css
Spinner with `delay=true` doesn't appear on the screen even after the delay has passed. This was because `opacity: 1` rule in the animation keyframes were not being applied correctly. Weirdly enough, it is applied only after mouse is moved, clicked, or inspected from DevTools. And it's only specific to Chrome, other browsers didn't have that bug.
The bug is fixed by "forcing" Chrome to apply the rules specified in animation keyframes. For that, `animation-composition: add` or `animation-composition: accumulate` rule needs to be added.
Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/animation-composition
Even when the default value is explicity set (`animation-composition: replace`), the bug remains. That could mean there is a rendering bug in Chrome with this rule and …
> Spinner: Opacity animation bug in Chrome

- packages/gestalt/src/BannerCallout/DismissButton.tsx
- packages/gestalt/src/BannerCallout/HeaderSection.tsx
- packages/gestalt/src/IconButton/InternalIconCompactButton.tsx
- packages/gestalt/src/Pog/InternalPogCompact.tsx
Only in VR BannerCallout: implement internal IconCompactButton for dismiss button #3893
BEFORE
AFTER
> BannerCallout: implement internal IconCompactButton for dismiss button (VR only)

- packages/gestalt/src/Checkbox/VRInternalCheckbox.tsx
Checkbox: VR adjustments
Adding one side padding rather than paddingX, so it doesn't add spacing on the edge of the label
> Checkbox: VR adjustments

- packages/gestalt/src/HelpButton.tsx
HelpButton: VR adjusments
https://www.figma.com/design/vjhfBsOtHw0wVg67vqwz1v/Gestalt-for-Web?node-id=41743-1239&node-type=instance&m=dev
> HelpButton: VR adjusments

- packages/gestalt/src/BannerCallout.tsx
BannerCallout: Remove Children.only logic prone to break if message is undefined in runtime
BEFORE
AFTER
> BannerCallout: Remove Children.only logic prone to break if message is undefined in runtime

- packages/gestalt/src/Masonry/fullWidthLayout.ts
- packages/gestalt/src/Masonry/multiColumnLayout.test.ts
- packages/gestalt/src/Masonry/multiColumnLayout.ts
- playwright/masonry/flexible-resize.spec.ts
This PR re-lands the change originally introduced in https://github.com/pinterest/gestalt/pull/3874 (which updates `fullWidthLayout` column widths to not be floored) and addresses the bug that caused it to be reverted.
This previous change was reverted after it was reported that pins were "stacking" . After doing some debugging, I was able to trace the issue down to the `initializeHeightsArray` function, which is called during multi-column layout. Currently, it has some logic to determine `column` based on a combination of `position.left` + `columnWidthAndGutter` - when column widths are floating point numbers, this ends up breaking since the calculated `column` is no longer an integer.
This PR fixes the above issue by ensuring that the above calculation is rounded to the nearest integer. …
> Masonry: Update fluid grid to not floor column width (take two)

- packages/gestalt-datepicker/src/DateRange.css
- packages/gestalt-datepicker/src/DateRange.tsx
Remove overflow prop and apply border radius with css instead, this will fix a visual bug on pinboard when the component is wrapped in a Popover.
The prop `overflow=hidden` is causing a small gap at the bottom of the component when wrapped inside a Popover.
- [ABC-3889](https://jira.pinadmin.com/browse/ABC-3889)
> DateRange: Remove overflow prop and apply border radius with css instead (web)

- docs/pages/web/iconbuttonlink.tsx
- packages/gestalt/src/IconButtonLink.tsx
- packages/gestalt/src/Link/InternalLink.tsx
Remove prop active=section from all IconButtonLink.
Some of our link components tried to implement aria-selected and role=tab. This is actually an incorrect implementation. Links cannot have aria-selected and role=tab. For example, more info https://www.stefanjudis.com/blog/aria-selected-and-when-to-use-it
This issue was raising some accessibility bugs requesting a parent with role=tablist but it was not possible to fix.
This PR removes internal usage of aria-selected and role=tab in links. It doesn't fix APIs completely but it allows unsilencing integration tests. 
The links are announced as links but they are not presented as tabs. It's an improvement that it requires changes Out of Scope for this PR which aimee d to fix the bug.
Errors are gone:
> SideNavigation: patch for accessibility aria-selected bug

- package.json
- packages/gestalt-datepicker/package.json
- packages/gestalt-datepicker/src/DatePicker.css
- packages/gestalt-datepicker/src/DatePicker.tsx
- packages/gestalt-datepicker/src/DatePicker/InternalDatePicker.tsx
- packages/gestalt-datepicker/src/DateRange/InternalDatePicker.tsx
- packages/gestalt-datepicker/src/__snapshots__/DatePicker.jsdom.test.tsx.snap
- yarn.lock
https://github.com/Hacker0x01/react-datepicker/releases
Side benefit: Remove usages of react-onclickoutside to support React 19 by @hamidrezahanafi in https://github.com/Hacker0x01/react-datepicker/pull/4979
> DatePicker: upgraded package to latest 7.5.0

- packages/gestalt-datepicker/src/DatePicker.jsdom.test.tsx
- packages/gestalt-datepicker/src/DatePicker/DateInput.tsx
- packages/gestalt/src/TextField.tsx
- packages/gestalt/src/TextField/InternalTextField.tsx
- packages/gestalt/src/TextField/VRInternalTextField.tsx
DatePicker, TextField: 1. fix open behavior, 2. support to onClick
When we upgraded react-datepicker to 6.9.0  https://github.com/pinterest/gestalt/pull/3551/files, some internal logic in Datepicker changed. Datepicker requires to call an internal onFocus and onClick events injected in the custom input to open the container and they were both called at the same onFocus event in TextField. With this upgrade, the focus event was being called twice not letting the picker to stay closed, making the Datepicker popper to reopen.
To fix this, we've supported onClick in Textfield, and extended it to Datepicker so we can properly trigger this event on the custom input in Datepicker and avoid event conflicts.
> DatePicker, TextField: 1. fix open behavior, 2. support to onClick

- packages/gestalt-datepicker/src/DateRange.tsx
- packages/gestalt-datepicker/src/DateRange/InternalDatePicker.tsx
- packages/gestalt/src/ButtonGroup.tsx
Internal: remove internal circular dependencies
> Internal: remove internal circular dependencies

- packages/gestalt/src/contexts/ColorSchemeProvider.tsx
ColorSchemeProvider: support to classic partial exclusions
We have to support partial exclusions of Visual Refresh which requires adding a second CSS file but targeting the root to targeted classname.
> ColorSchemeProvider: support to classic partial exclusions

- packages/gestalt/src/AvatarGroup.tsx
AvatarGroup: fix VR default size bug
This change was causing
> AvatarGroup: fix VR default size bug

- package.json
- yarn.lock
[#5816 Package 'libasound2' has no installation candidate on Ubuntu 24.04](https://github.com/cypress-io/cypress-documentation/issues/5816) 
reading through https://github.com/microsoft/playwright/issues/30368 - seems like if you bump playwright to 1.49 it might fix it
> Internal: upgrade  "@playwright/test" to 1.49

- packages/gestalt/src/HelpButton.css
- packages/gestalt/src/HelpButton.tsx
HelpButton: general fixes and VR fixes 
General fixes
before
after
VR fix
> HelpButton: general fixes and VR fixes 

- packages/gestalt-datepicker/src/DateRange.css
- packages/gestalt-datepicker/src/DateRange.tsx
Fix small visual bug in DateRange component, the top left border radius is only applied if there is no radio group.
Previously, the border was applied even if the radio group was present, making the DateRange to look weird.
- [Jira](https://jira.pinadmin.com/browse/RI-2835)
| Before | After |
|--------|------|
| <img width="342" alt="Screenshot 2025-01-20 at 12 21 45 p m" src="https://github.com/user-attachments/assets/7d32f0fc-a1cb-46b8-af42-00030fd0c1ae" /> | <img width="351" alt="Screenshot 2025-01-20 at 12 21 53 p m" src="https://github.com/user-attachments/assets/83daa3d7-83ef-4061-a579-070034206f73" /> |
> DateRange: fix date input border radius when radio group is present (web)

- packages/gestalt-datepicker/src/DateRange.tsx
Automatically select primary range if the secondaryDateValues goes undefined.
If you disable or make secondaryDateValues undefined, the DateRange will not let you select new dates since the secondary range is still selected inside the component.
- [Jira](https://jira.pinadmin.com/browse/RI-2836)
| Before | After |
|--------|------|
| <video src=https://github.com/user-attachments/assets/814ed538-b1f1-4489-b3dc-6342b3e57908> | <video src=https://github.com/user-attachments/assets/e3b5d8ac-709a-4138-b0e3-5ac17beca588> |
> DateRange: fix date selection bug when you disable secondary range

- babel.config.js
- packages/gestalt-charts/package.json
- packages/gestalt-charts/rollup.config.js
- packages/gestalt-core/build.js
- packages/gestalt-datepicker/package.json
- packages/gestalt-datepicker/rollup.config.js
- packages/gestalt/rollup.config.js
This imports the JSX runtime from the react library instead of compiling it inline as part of the CJS.
When upgrading to React 19, this variation among the JSX runtime causes incompatible build outputs between both. Until we start using React 19 features, this should keep the library working for both
Added `react/jsx-runtime` and `react-dom/client` as external dependencies. See [SO](https://stackoverflow.com/questions/76135802/how-do-i-make-my-react-package-use-an-external-jsx-runtime) question
Also, changing `@babel/react` to `@babel/preset-react` (which seemed to be the correct package name).
> Internal: Change React 19 Build

- packages/gestalt/src/Flex.tsx
- packages/gestalt/src/utils/wrapWithComponent.tsx
Fix key prop error on Flex Component for React 19
Separate key from props in `wrapWithComponent`
Fixing upgrade to React 19
> Internal: Fix key prop error on Flex Component for React 19

- packages/gestalt/src/Masonry/multiColumnLayout.test.ts
- packages/gestalt/src/Masonry/multiColumnLayout.ts
This PR adds on Masonry's multi-column module new experimental breakpoints for grid size. 
For original Masonry's responsive modules please refer to: https://github.com/pinterest/gestalt/pull/3636
Current grid size breakpoints: 
- sm: 2 columns
- md: 3-4 columns
- lg: 5-8 columns
- xl: 9+ columns
New experimental breakpoints: 
- sm: 2 columns
- md: 3-4 columns
- _lg1: 5-6 columns (New)
- lg: 5-8 columns (Existing)
- xl: 9+ columns
This change also adds logic for retro compatibility, to avoid breaking current configurations. 
In cases where `_lg1` is not configured, it would fallback to use existing `lg`
Unit test has been updated. 
Also tested locally: 
Using following configuration, verified multicolumn module size for different grid sizes: 
```
_getColumnSpanConfig = () => {
return { …
```
> Masonry: Experimental breakpoints for gridSize

- docs/examples/dropdown/avatar.tsx
- docs/pages/web/dropdown.tsx
- packages/gestalt/src/Dropdown/OptionItem.tsx
- packages/gestalt/src/DropdownItem.jsdom.test.tsx
- packages/gestalt/src/DropdownItem.tsx
- packages/gestalt/src/DropdownLink.jsdom.test.tsx
- packages/gestalt/src/DropdownLink.tsx
> Dropdown: support to `avatar`

- docs/integration-test-helpers/masonry/MasonryContainer.tsx
- packages/gestalt/src/Masonry.tsx
- packages/gestalt/src/Masonry/ScrollContainer.ts
- packages/gestalt/src/Masonry/scrollUtils.ts
- packages/gestalt/src/MasonryV2.tsx
This PR adds `Window` type to Masonry's scroll container. This is already allowed, but we are explicitly adding it to avoid TS error suppressions
> Masonry: Adding Window type to scroll container

- packages/gestalt/src/Masonry/scrollUtils.ts
Adding missing type check on Masonry's scroll util from previous PR: https://github.com/pinterest/gestalt/pull/3977
> Masonry: Fixing type bug

- docs/examples/animation/useExample.tsx
- docs/examples/video/autoplayAndErrorDetectionExample.tsx
- docs/examples/video/controlsExample.tsx
- docs/examples/video/localizationLabels.tsx
- docs/examples/video/mainExample.tsx
- docs/examples/video/updatesExample.tsx
- docs/examples/video/withChildrenExample.tsx
Change the video asset URL from `v.pinimg.com` to `v1.pinimg.com`
`v.pinimg.com` is being retired, and we have to use `v1.pinimg.com` instead of `v.pinimg.com`.
> Internal: change v.pinimg.com to v1.pinimg.com

- packages/gestalt/src/__snapshots__/Dropdown.jsdom.test.tsx.snap
- packages/gestalt/src/__snapshots__/Link.test.tsx.snap
- packages/gestalt/src/accessibility/AccessibilityLinkActionIcon.tsx
Refactor how we prepend ", " to the svg title of `<AccessibilityLinkActionIcon />`.
When we render
```tsx
<title>, {titleLabel}</title>
```
React throws the following warning:
> Warning: A title element received an array with more than 1 element as children. In browsers title Elements can only have Text Nodes as children. If the children being rendered output more than a single text node in aggregate the browser will display markup and comments as text in the title and hydration will likely fail and fall back to client rendering
This is because React treats `, {titleLabel}` as two children nodes: `[', ', titleLabel]`.
To fix, reassign `titleLabel` as `, ${titleLabel}`.
> Link: fix a warning from accessibility pause in AccessibilityLinkActionIcon

- packages/gestalt-datepicker/src/DatePicker.tsx
- packages/gestalt-datepicker/src/DatePicker/InternalDatePicker.tsx
DatePicker: add private prop _overrideRangeDateFix to enable correct logic in date ranges     
This component contains logic that made the component uncontrolled and causes unexpected behavior when trying to define min an max dates. We need to deprecate when all instances of DatePicker set _overrideRangeDateFix to true
> DatePicker: add private prop _overrideRangeDateFix to enable correct logic in date ranges

- packages/gestalt/src/SearchGuide.css
- packages/gestalt/src/SearchGuide.tsx
```
border-end-start-radius: var(--rounding-400);
border-start-start-radius: var(--rounding-400);
```
arent supported in Pinboard, replacing with border-radius
> SearchGuide: fix border radius in VR image variant 

- packages/gestalt/src/SearchGuide.css
- packages/gestalt/src/SearchGuide.tsx
SearchGuide: fix stacking context bug with isolation='isolate'
> SearchGuide: fix stacking context bug with isolation='isolate'

- packages/gestalt/src/Masonry/dynamicHeightsV2Utils.ts
This PR addresses an issue where middle elements overlap when the item being resized has at least one item in between a multi-column element, and the height change exceeds the height of the middle elements.
The bug was caused by how positions were determined for repositioning items. Previously, updated positions were used, which neglected to account for items that moved past the multi-column item, leading to the overlap. With this update, original positions are taken into account for determining overlap prevention, while new positions are used for recalculating item placement.
---
- Current state
https://github.com/user-attachments/assets/fce45e08-f967-4cd4-bd51-c09978155746
- Fixed change
https://github.com/user-attachments/assets/a667225e-1013-472e-a9b8-b1ac7c2ab2a9
---
- Current state …
> Masonry: Fix bug on edge case while using dynamicHeightsV2

- docs/pages/web/button.tsx
- docs/pages/web/buttonlink.tsx
- packages/gestalt/src/Button.css
- packages/gestalt/src/Button.tsx
- packages/gestalt/src/Link/InternalLink.tsx
Before:
SM
MD
LG
After:
SM
MD
LG
> Button: Fixing VR height 

- packages/gestalt-datepicker/package.json
- yarn.lock
\DateField, DateRange: upgrade @mui/x-date-pickers to 7.27.2 #4019
Latest seem to not have findDOMNode in [react-transition-group](https://github.com/reactjs/react-transition-group)
https://github.com/reactjs/react-transition-group/releases?q=findDOMNode&expanded=true
> DateField, DateRange: upgrade @mui/x-date-pickers to 7.27.2

- packages/gestalt/src/Image.tsx
- packages/gestalt/src/Video.tsx
If the src is empty in img or track inside the Image and Video component, then it sets it to undefined.
We are getting many errors like this one when upgrading to React 19: `An empty string ("") was passed to the src attribute`. I tested this on my devapp and this fixes this errors.
> Image, Video: if image or track `src` is empty string "" then set as undefined

- packages/gestalt-datepicker/package.json
- yarn.lock
Upgrading @mui/material library to version [5.16.12](https://github.com/mui/material-ui/releases/tag/v5.16.12)
For upgrading pinboard to React 19, this is the version of mui/material that is now compatible with React 19
> Internal: Upgrade mui-material

- packages/gestalt/src/Link/InternalLink.jsdom.test.tsx
- packages/gestalt/src/Link/InternalLink.test.tsx
- packages/gestalt/src/Link/InternalLink.tsx
- packages/gestalt/src/Link/__snapshots__/InternalLink.test.tsx.snap
- packages/gestalt/src/TapAreaLink.jsdom.test.tsx
- packages/gestalt/src/TapAreaLink.tsx
TapAreaLink: support to title prop #4022
Problem description
[TDD](https://docs.google.com/document/d/1tNdL_CSLc3DhCDa-qF1hs-3hEaY3CcrD8p2rS-9BWGk/edit?tab=t.0)
Currently TapAreaLink doesn’t have support for a title global attribute ([mdn link](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title)) on the anchor element <a/>. This attribute is useful for SEO purposes as it provides additional associated text with the link that can help SEO crawlers gather more context around links on a page. In addition, it commonly displays a tooltip with the title that can provide users with more information about the destination page as well. Though aria-label ([mdn link](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label)) may seem similar to …
> TapAreaLink: support to `title` prop

- packages/gestalt/src/BannerCallout/Footer.tsx
- packages/gestalt/src/BannerCallout/VRBannerCallout.tsx
BannerCallout: Revert BannerCallout: message width adjustments (#4007) - Preview link #4024
> BannerCallout: Revert  BannerCallout: message width adjustments (#4007)

- packages/gestalt-charts/package.json
- packages/gestalt-charts/src/ChartGraph/renderAxis.tsx
- packages/gestalt-charts/src/ChartGraph/renderElements.tsx
- yarn.lock
Upgrade recharts library
Current version is having issues when upgrading to React 19, Upgrading to version [2.13.0](https://github.com/recharts/recharts/releases/tag/v2.13.0) which according to the release should be compatible with React 19
> ChartGraph: Upgrade recharts for ChartGraph to support React 19

- docs/docs-components/SandpackExample.tsx
Docs: adds DesignTokensProvider to Sandpack code editor
> Docs: adds DesignTokensProvider to Sandpack code editor

- packages/gestalt/src/sharedSubcomponents/thumbnailSubcomponents.tsx
> Toast: Compact icons

- docs/next.config.js
Enhancement: Add support for dynamic basePath and trailingSlash in Next.js config
Read BASE_PATH from build-time env and apply it only when present.
Tie trailingSlash: false to the same condition so trailing slash behavior changes only alongside the base path.
`docs/next.config.js` now expects `BASE_PATH` to contain the leading / (e.g. /v1); omit the variable to run at /.
If `BASE_PATH` is set, remember to update any absolute URLs, redirects, and asset prefixes to include it.
New Gesalt proyect will have the existing docs v1 site under "/v1"
> Internal: Add support for dynamic basePath and trailingSlash in Next.js config
