- packages/gestalt/src/DropdownItem.js
- packages/gestalt/src/DropdownLink.js
- packages/gestalt/src/OptionItem.js
Dropdown: cleanup dead code
(Probably became dead code after splitting Dropdown and ComboBox internals)
> Dropdown: cleanup dead code

- packages/gestalt/src/Masonry.js
- packages/gestalt/src/ScrollFetch.js
- packages/gestalt/src/debounce.js
- packages/gestalt/src/throttle.js
Fixes 10 `$FlowFixMe`s in Gestalt
> Internal: flow type debounce and throttle methods

- docs/components/App.js
- docs/components/AppLayout.js
- docs/components/DocSearch.js
- docs/components/Footer.js
- docs/components/Header.js
- docs/components/ResourcesFooter.js
Update Footer based on feedback and change color on non-home pages. 
Simplify Resources links and adjust color for pages outside the home page. Also added tracking to the footer links.
- [Figma](https://www.figma.com/file/emykswARRS1tQwpB7ThIPN/Gestalt-2022-Site)
> Docs: Updates to Resources and Footer

- packages/gestalt/src/ActivationCard.js
- packages/gestalt/src/Callout.js
these are currently broken, whoops
> Docs: fix some OnLinkNavigationProvider links

- docs/components/ResourcesFooter.js
Fix Eng Slack link in Resource footer
> Docs: Fix Resource Slack eng link

- docs/components/PageHeaderQualitySummary.js
Component status: quick link fix
> Component status: quick link fix

- docs/components/Footer.js
- docs/components/HeaderMenu.js
- docs/components/ResourcesFooter.js
- docs/pages/tooling.js
> Docs: updated Gestalt Sandbox

- docs/pages/BlogPosts.json
- docs/pages/module.js
> Docs: Blog update for 7/01

- docs/pages/BlogPosts.json
Blog post updates for the week of 07/08
> Docs: Blog posts for week of 07/08

- docs/components/Header.js
Change logo back to default color
> Docs: Header tweak

- .github/workflows/playwright.yml
- docs/components/Navigation.js
- packages/gestalt/src/SideNavigation.js
- packages/gestalt/src/__snapshots__/SideNavigation.test.js.snap
- playwright/visual-test/SideNavigation-dark.spec.mjs
- playwright/visual-test/SideNavigation-light.spec.mjs
Docs: Implement SideNavigation
> Docs: Implement SideNavigation

- docs/pages/link.js
Link: design guidance copy updates
> Link: design guidance copy updates

- docs/pages/BlogPosts.json
Revert last commit for 7/15 update
> Revert "7/15 what's new update"

- packages/gestalt-design-tokens/tokens/color/alias.json
- packages/gestalt/src/Video.js
Fix typos for design tokens and video props table
> Docs: Fix typos

- docs/pages/BlogPosts.json
Published what's new for the week of 7-15
> Docs: 7-15 update

- docs/components/AppLayout.js
- docs/components/Navigation.js
- docs/components/PropTable.js
- docs/pages/sidenavigation.js
- packages/gestalt/src/SideNavigation.css
- packages/gestalt/src/SideNavigation.js
- packages/gestalt/src/SideNavigationGroup.js
- packages/gestalt/src/SideNavigationNestedGroup.js
- packages/gestalt/src/SideNavigationNestedItem.js
- packages/gestalt/src/SideNavigationSection.js
- packages/gestalt/src/SideNavigationTopItem.js
- packages/gestalt/src/__snapshots__/SideNavigation.test.js.snap
SideNavigation: implement guidelines
> SideNavigation: implement guidelines

- docs/pages/sidenavigation.js
SideNavigation: quick fix docs
> SideNavigation: quick fix docs

- docs/pages/BlogPosts.json
> Docs: What's new 7-22 update

- docs/pages/iconography.js
Added an Iconography component to our list and fixed a link
> Docs: Tweaks and fixes to Iconography guidelines

- docs/components/AppLayout.js
- docs/components/DocsSideNavigation.js
- docs/components/Header.js
- docs/components/contexts/DocsDeviceTypeProvider.js
- docs/pages/_app.js
- docs/pages/sidenavigation.js
- packages/gestalt/src/SideNavigation.js
- packages/gestalt/src/SideNavigationGroup.js
- packages/gestalt/src/SideNavigationGroupContent.js
- packages/gestalt/src/SideNavigationGroupMobile.js
- packages/gestalt/src/SideNavigationMobile.js
- packages/gestalt/src/SideNavigationTopItem.js
- packages/gestalt/src/__snapshots__/SideNavigation.test.js.snap
- packages/gestalt/src/contexts/DeviceTypeProvider.js
- packages/gestalt/src/contexts/SideNavigationProvider.js
SideNavigation: V3 (mobile) 
+ Implementation in Docs
(to see open Developer tools and set mobile view)
- [Figma](https://www.figma.com/file/kK9TSF41utPLF2CIRoGLhX/Gestalt-SideNav-Component?node-id=285%3A4844)
> SideNavigation: V3 (mobile)

- docs/docs-components/Header.js
- docs/docs-components/SandpackExample.js
- docs/examples/sidenavigation/activeItemExample.js
- docs/examples/sidenavigation/badgeExample.js
- docs/examples/sidenavigation/borderExample.js
- docs/examples/sidenavigation/correctGroupingExample.js
- docs/examples/sidenavigation/correctHeadingExample.js
- docs/examples/sidenavigation/correctIconExample.js
- docs/examples/sidenavigation/correctLengthExample.js
- docs/examples/sidenavigation/counterExample.js
- docs/examples/sidenavigation/customIconsExample.js
- docs/examples/sidenavigation/footerExample.js
- docs/examples/sidenavigation/headerExample.js
- docs/examples/sidenavigation/iconsExample.js
- docs/examples/sidenavigation/incorrectGroupingExample.js
- docs/examples/sidenavigation/incorrectHeadingExample.js
- docs/examples/sidenavigation/incorrectIconExample.js
- docs/examples/sidenavigation/incorrectLengthExample.js
- docs/examples/sidenavigation/localizationExample.js
- docs/examples/sidenavigation/mainExample.js
- docs/examples/sidenavigation/mobileExample.js
- docs/examples/sidenavigation/nestedExample.js
- docs/examples/sidenavigation/notificationsExample.js
- docs/examples/sidenavigation/sectionsExample.js
- docs/pages/web/modal.js
- docs/pages/web/sidenavigation.js
SideNavigation: implement Sandpack live code examples
> SideNavigation: implement Sandpack live code examples

- docs/docs-components/siteIndex.js
- docs/pages/get_started/developers/development_process.js
- playwright/accessibility/Development Process.spec.mjs
Add the Development page under Developers, rename it Development process
> Docs: Add development process page

- docs/next.config.js
- docs/redirects.js
We need to make sure users hitting the previous URL paths are redirected properly
> Docs: add redirects for old paths

- docs/docs-components/DocsSideNavigation.js
- docs/docs-components/navigationContext.js
- docs/docs-components/useGetSideNavItems.js
Docs: implement Tabs into Gestalt Documentation's SideNavigation for mobile
> Docs: implement Tabs into Gestalt Documentation's SideNavigation for mobile

- docs/docs-components/SandpackExample.js
- docs/examples/pageheader/complimentaryItemsExample.js
- docs/examples/pageheader/dontOverloadExample.js
- docs/examples/pageheader/minimumButtonsExample.js
- docs/examples/pageheader/responsiveExample.js
- docs/examples/pageheader/titleExample.js
- docs/pages/web/pageheader.js
PageHeader: improved Docs with examples and improved descriptions
[GESTALT-4594](https://jira.pinadmin.com/browse/GESTALT-4594)
> PageHeader: improved Docs with examples and descriptions

- docs/docs-components/useGetSideNavItems.js
- packages/gestalt/src/SideNavigation.js
- packages/gestalt/src/SideNavigationGroup.js
- packages/gestalt/src/SideNavigationGroupMobile.js
- packages/gestalt/src/SideNavigationMobile.js
- packages/gestalt/src/SideNavigationNestedGroup.js
- packages/gestalt/src/contexts/SideNavigationProvider.js
- packages/gestalt/src/getChildrenToArray.js
SideNavigation: add self-opening group on active items
Manual test: https://www.loom.com/share/2a68167305854a00a0aa55b632a3dd46
> SideNavigation: add self-opening group on active items

- packages/gestalt/src/Contents.js
- packages/gestalt/src/Controller.js
- packages/gestalt/src/behaviors/TrapFocusBehavior.js
- packages/gestalt/src/utils/positioningUtils.js
@christianvuerings I'd love your 👀 on this. Removing one `*` Flow type led to a lot of downstream type adjustments and I'd love a second set of eyes to make sure I didn't flub anything 😅
> Internal: fix Flow issues with positioning utils

- docs/pages/roadmap/RoadmapData.json
- docs/pages/roadmap/overview.js
Given we're dropping some work from our 2022 goals, our roadmap should reflect that. There's now an "Abandoned" section in our roadmap
> Docs: Roadmap - Added an "Abandoned" section

- docs/pages/roadmap/BlogPosts.json
> Docs: 8-12 update

- docs/docs-components/COMPONENT_DATA.js
- docs/docs-components/IllustrationCard.js
- docs/pages/home.js
- docs/pages/web/overview.js
Component overview: updated as per redesign
- [Figma](https://www.figma.com/file/a2ar8cqq2nhoz9IssecW8y/Components-overview-updates?node-id=5%3A298file)
> Component overview: updated per redesign

- packages/gestalt/src/Video.js
Noticed this while looking through the Algolia logs:
> Video: fix docs link for disableRemotePlayback

- packages/gestalt-codemods/next_IconButton/__testfixtures__/iconButton-defaut-iconColor-change-renamed.input.js
- packages/gestalt-codemods/next_IconButton/__testfixtures__/iconButton-defaut-iconColor-change-renamed.output.js
- packages/gestalt-codemods/next_IconButton/__testfixtures__/iconButton-defaut-iconColor-change.input.js
- packages/gestalt-codemods/next_IconButton/__testfixtures__/iconButton-defaut-iconColor-change.output.js
- packages/gestalt-codemods/next_IconButton/__tests__/iconButton-defaut-iconColor-change.test.js
- packages/gestalt-codemods/next_IconButton/iconButton-defaut-iconColor-change.js
Created codemod for upcoming default iconColor value changes in IconButton
This codemod comes ahead of implementing the breaking changes in IconButton to prevent a blocking PR. This codemod will be run twice, pre major release and when bumping major release to detect any new changes.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-2501)
> IconButton: codemod for upcoming default iconColor value changes

- .eslintrc.json
Migrating more Flow lint rules over from Pinboard
> Internal: more Flow lint rules

- docs/pages/roadmap/BlogPosts.json
Fixed reference of SlimBanner to Callout
> Docs: 8/19 blog post update

- .github/pull_request_template.md
Adding platform to component PR titles
> Docs: update PR template with new title format

- docs/docs-components/COMPONENT_DATA.js
Quick fix for some broken links on the component overview page
> Docs: Fix links on overview page

- packages/gestalt-codemods/68.0.0/__testfixtures__/iconButton-defaut-size-change-renamed.input.js
- packages/gestalt-codemods/68.0.0/__testfixtures__/iconButton-defaut-size-change-renamed.output.js
- packages/gestalt-codemods/68.0.0/__testfixtures__/iconButton-defaut-size-change.input.js
- packages/gestalt-codemods/68.0.0/__testfixtures__/iconButton-defaut-size-change.output.js
- packages/gestalt-codemods/68.0.0/__tests__/iconButton-defaut-size-change.test.js
- packages/gestalt-codemods/68.0.0/iconButton-defaut-size-change.js
Created codemod for upcoming default `size` value changes in IconButton
This codemod comes ahead of implementing the breaking changes in IconButton to prevent a blocking PR. This codemod will be run twice, pre major release and when bumping major release to detect any new changes.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-2501)
> IconButton: codemod for upcoming default `size` changes

- docs/pages/web/link.js
- docs/pages/web/table.js
> Docs: fix broken examples

- netlify.toml
whoops, forgot to include [the splat!](https://docs.netlify.com/routing/redirects/redirect-options/#splats)
> Docs: add redirect from old domain to new one, now with splat!

- docs/pages/web/modal.js
- docs/pages/web/sheet.js
Update Sheet and Modal displays to have more height
> Docs: Update example sizes in Modal and Sheet

- docs/examples/avatar/containerExample.js
- docs/examples/avatar/ideasExample.js
- docs/examples/avatar/mainExample.js
- docs/examples/avatar/nameExample.js
- docs/examples/avatar/noEmojiExample.js
- docs/examples/avatar/noImageSourceExample.js
- docs/examples/avatar/overExample.js
- docs/examples/avatar/personExample.js
- docs/examples/avatar/shapeExample.js
- docs/examples/avatar/sizingExample.js
- docs/examples/avatar/verifiedExample.js
- docs/pages/web/avatar.js
Avatar: implement Sandpack code editors
> Avatar: implement Sandpack code editors

- docs/pages/roadmap/RoadmapData.json
Updated status of the team's work
> Docs: Updated roadmap for August

- docs/pages/web/dropdown.js
- packages/gestalt/src/Dropdown.js
- packages/gestalt/src/Dropdown.jsdom.test.js
- packages/gestalt/src/__snapshots__/Dropdown.jsdom.test.js.snap
Dropdown: support conditional children wrapped in Fragment #2354
Dropdown is a composable / modular component which requires using its own subcomponents ( Dropdown.Item, Dropdown.Link, Dropdown.Section ) to build an instance of Dropdown. Subcomponents are passed as children.
The logic to render Dropdown's children can be complex and based on different conditions. Dropdown relies internally in recognizing each Dropdown subcomponent's display name. When rendering conditionally, Dropdown children must be wrapped in React.Fragment if it contains multiple items. In order to support conditional rendering, Dropdown needs to recognize React.Fragment and set its children in the children array, otherwise, it fails to render them.
Furthermore, Dropdown now supports consecutive arrays of arrays of …
> Dropdown: support conditional children wrapped in Fragment

- docs/pages/web/dropdown.js
> Dropdown: typos in Docs

- CHANGELOG.md
- scripts/releaseSteps.js
Internal: Add preview link to changelog to facilitate debugging across multiple history PRs
> Internal: Add preview link to changelog

- docs/pages/roadmap/BlogPosts.json
- docs/pages/roadmap/whats_new.js
This PR adds support for our monthly eng newsletter to "What's New", as well as the content for the first (August) newsletter.
> Docs: add support for monthly eng newsletter + the Aug newsletter

- scripts/releaseSteps.js
> Internal: tweak preview link

- docs/pages/roadmap/BlogPosts.json
Blog posts for week of Sept 02, 2022
> Docs: Add updates for week of Sept 2

- docs/examples/combobox/controlled.js
- docs/examples/combobox/error.js
- docs/examples/combobox/labels.js
- docs/examples/combobox/localization.js
- docs/examples/combobox/main.js
- docs/examples/combobox/programmatic.js
- docs/examples/combobox/ref.js
- docs/examples/combobox/subtext.js
- docs/examples/combobox/tags.js
- docs/examples/combobox/uncontrolled.js
- docs/pages/web/combobox.js
ComboBox: implement Sandpack code editors
> ComboBox: implement Sandpack code editors

- docs/examples/avatarGroup/accessibility.js
- docs/examples/avatarGroup/ideas.js
- docs/examples/avatarGroup/main.js
- docs/examples/avatarGroup/noEmoji.js
- docs/examples/avatarGroup/noImageSource.js
- docs/examples/avatarGroup/person.js
- docs/examples/avatarGroup/roleButton.js
- docs/examples/avatarGroup/roleLink.js
- docs/examples/avatarGroup/sizing.js
- docs/pages/web/avatar.js
- docs/pages/web/avatargroup.js
AvatarGroup: implement Sandpack code editors
> AvatarGroup: implement Sandpack code editors

- docs/markdown/get_started/developers/development_process.md
- docs/pages/get_started/faq.js
Docs: added link references to Pinterest's Web platform documentation about Gestalt
> Docs: added link references to Pinterest's Web platform documentation about Gestalt

- docs/pages/_app.js
- flow-typed/npm/test_ua-parser-js_vx.x.x.js
Docs: implement ua-parser-js to detect device in our docs site
To test changes, use https://deploy-preview-2371--gestalt.netlify.app/ in your mobile browser
> Internal: implement ua-parser-js to detect device type in docs site

- docs/docs-components/useGetSideNavItems.js
- docs/pages/web/sidenavigation.js
- packages/gestalt/src/SideNavigation.css
- packages/gestalt/src/SideNavigation.css.flow
- packages/gestalt/src/SideNavigationSection.js
- packages/gestalt/src/__snapshots__/SideNavigation.test.js.snap
- packages/gestalt/src/getChildrenToArray.js
SideNavigation: logic cleanup and conditional rendering improvements
Cleanup some logic to explicitly support React.Fragment as well as other conditional rendering of subcomponents.
> SideNavigation: conditional rendering improvements

- docs/markdown/android/sheet.md
- docs/markdown/ios/sheet.md
- docs/pages/BlogPosts.json
- docs/pages/foundations/color/palette.js
- docs/pages/foundations/design_tokens.js
- docs/pages/web/box.js
- docs/pages/web/utilities/onlinknavigationprovider.js
- docs/redirects.js
Found some more broken links from the latest crawler run
> Internal: fix more broken links

- package.json
- yarn.lock
No new features I'm particularly interested in, just keeping us up-to-date
https://github.com/eslint/eslint/releases/tag/v8.23.0
> Internal: upgrade eslint to 8.23.0

- docs/examples/avatar/sizingExample.js
- docs/pages/web/avatar.js
Avatar: fix Sandpack code editor view in Docs
> Avatar: fix Sandpack code editor view in Docs

- docs/examples/flex/flexBasis.js
- docs/examples/flex/flexItem.js
- docs/examples/flex/gap.js
- docs/examples/flex/main.js
- docs/examples/flex/menu.js
- docs/examples/flex/overflowing.js
- docs/pages/web/flex.js
Flex: implement Sandpack code editor examples
> Flex: implement Sandpack code editor examples

- packages/gestalt/src/SlimBanner.js
- packages/gestalt/src/__snapshots__/SlimBanner.test.js.snap
Fix alignment at smaller screens when text is short
> SlimBanner: Fix alignment

- docs/pages/web/button.js
Button: change iconEnd from `arrow-up-right` to `visit` icon
> Button: change iconEnd from `arrow-up-right` to `visit` icon in Docs

- docs/examples/combobox/helperText.js
- docs/pages/web/combobox.js
- packages/gestalt/src/ComboBox.js
ComboBox: add helperText variant in Docs
> ComboBox: add helperText variant in Docs

- docs/pages/web/utilities/usereducedmotion.js
Example was hidden due to incorrect Box color, updated box color to new value
> Docs: fix useReducedMotion example

- docs/examples/iconbutton/aria.js
- docs/examples/iconbutton/customIcon.js
- docs/examples/iconbutton/gestaltIcon.js
- docs/examples/iconbutton/grouping.js
- docs/examples/iconbutton/highActions.js
- docs/examples/iconbutton/image.js
- docs/examples/iconbutton/keyboard.js
- docs/examples/iconbutton/lowActions.js
- docs/examples/iconbutton/main.js
- docs/examples/iconbutton/noGrouping.js
- docs/examples/iconbutton/roleButton.js
- docs/examples/iconbutton/roleLink.js
- docs/examples/iconbutton/selectedState.js
- docs/examples/iconbutton/tooltip.js
- docs/examples/iconbutton/tooltipVariant.js
- docs/pages/web/iconbutton.js
IconButton: implement Sandpack code editor examples
> IconButton: implement Sandpack code editor examples

- docs/pages/get_started/faq.js
> Docs: remove IE11 section from FAQ

- docs/examples/button/accessibilityDropdownExample.js
- docs/examples/button/buttonPopoverExample.js
- docs/examples/button/defaultStateExample.js
- docs/examples/button/disabledStateExample.js
- docs/examples/button/iconEndExample.js
- docs/examples/button/iconTooltipToExplainDo.js
- docs/examples/button/iconTooltipToExplainDont.js
- docs/examples/button/keepSimpleTextDo.js
- docs/examples/button/keepSimpleTextDont.js
- docs/examples/button/main.js
- docs/examples/button/placePrimaryButtonDo.js
- docs/examples/button/placePrimaryButtonDont.js
- docs/examples/button/relAndTargetExample.js
- docs/examples/button/roleButtonExample.js
- docs/examples/button/roleLinkExample.js
- docs/examples/button/selectedStateExample.js
- docs/examples/button/semiTransparentWhiteButtonExample.js
- docs/examples/button/showFullTextDo.js
- docs/examples/button/showFullTextDont.js
- docs/examples/button/whiteButtonExample.js
- docs/pages/web/button.js
Button: implement Sandpack code editor examples
> Button: Implement Sandpack code editor examples

- docs/examples/button/relAndTargetExample.js
- docs/pages/web/button.js
Fix nits of this PR: https://github.com/pinterest/gestalt/pull/2414
> Button: Fix nits of PR 2414

- docs/pages/web/link.js
Made the main Link example more clear that it was a Link example
> Docs: Updated main Link example

- docs/docs-components/COMPONENT_DATA.js
- docs/docs-components/PageHeader.js
From our suggestions on Slack and a quick audit of other design systems, and a few from my own head
> Docs: add aliases for many components

- docs/examples/README.md
- docs/examples/numberfield/bestPractices-do-errorMessage.js
- docs/examples/numberfield/bestPractices-do-helperText.js
- docs/examples/numberfield/bestPractices-do-label.js
- docs/examples/numberfield/bestPractices-do-related.js
- docs/examples/numberfield/bestPractices-do-required.js
- docs/examples/numberfield/bestPractices-dont-errorMessage.js
- docs/examples/numberfield/bestPractices-dont-label.js
- docs/examples/numberfield/bestPractices-dont-placeholder.js
- docs/examples/numberfield/bestPractices-dont-related.js
- docs/examples/numberfield/bestPractices-dont-required.js
- docs/examples/numberfield/disabled.js
- docs/examples/numberfield/enterKeyHint.js
- docs/examples/numberfield/errorMessage.js
- docs/examples/numberfield/helperText.js
- docs/examples/numberfield/main.js
- docs/examples/numberfield/minMaxStep.js
- docs/examples/numberfield/ref.js
- docs/pages/web/numberfield.js
Errors found:
- old colors set on Box
- stacked example that was supposed to be side-by-side
> Docs: convert NumberField to use Sandpack

- docs/pages/foundations/typography/guidelines.js
Fix typos and incorrect sizes for size 600
> Typography guidelines: fix typos

- packages/gestalt/src/ModalAlert.js
Check for value before checking for href and onclick
> ModalAlert: Fix validation bug

- docs/docs-components/MainSectionSubsection.js
- docs/markdown/get_started/developers/contributing/development_process.md
- docs/pages/get_started/how_to_work_with_us.js
> Docs: update Slack channel name

- docs/pages/web/link.js
Links: updated documentation re external links
As a designer (and engineer), I want to clearly understand how to deal with external links and visual indicators (visit icon). 
The updates below will help clarify opening a new tab behavior, and visit icon usage considering a11y. 
Link web doc content update
Minor update under "Usage guidelines": Add period to all sentences (bullet points) for consistency
Update Best Practices - Do and Don't 4th row examples (copy update + adding new examples)
Update Accessibility / External links (copy update)
Update Variants / externalLink and rel (copy update)
Send PR for design review before publishing (Cintia)
> Links: updated documentation re external links

- docs/pages/foundations/iconography/library.js
> Docs: Fix Icon heading

- docs/markdown/android/textfield.md
Updating android TextFIeld images following a design decision. No text changes needed.
> TextField - Android: Update docs images

- docs/markdown/ios/textfield.md
Updating TextFIeld images based on recent design decision
> TextField - iOS: Update docs images

- docs/examples/tabs/backgroundColor.js
- docs/examples/tabs/doAboveTarget.js
- docs/examples/tabs/doBeConcise.js
- docs/examples/tabs/doOrderByRelevance.js
- docs/examples/tabs/dontFilterContent.js
- docs/examples/tabs/dontHide.js
- docs/examples/tabs/dontTruncateLabels.js
- docs/examples/tabs/indicator.js
- docs/examples/tabs/mainExample.js
- docs/examples/tabs/wrapping.js
- docs/pages/web/tabs.js
Tabs: convert Tabs Docs to use Sandpack editor
> Tabs: convert Tabs Docs to use Sandpack editor

- docs/examples/icon/builtInIcon.js
- docs/examples/icon/customIcon.js
- docs/examples/icon/doClarity.js
- docs/examples/icon/doIntentional.js
- docs/examples/icon/dontInteractive.js
- docs/examples/icon/dontRepurpose.js
- docs/examples/icon/main.js
- docs/pages/web/button.js
- docs/pages/web/icon.js
Icon: convert Tabs Docs to use Sandpack editor
> Icon: convert Tabs Docs to use Sandpack editor

- docs/docs-components/Header.js
- docs/docs-components/Overview.js
- docs/docs-components/Toc.js
- docs/pages/_app.js
- docs/pages/_document.js
- docs/pages/foundations/design_tokens.js
- docs/pages/web/masonry.js
- docs/utils/mdHelper.js
- flow-typed/npm/universal-cookie_vx.x.x.js
Fixes 10 out of 16 flow fixme in `/docs/`
Improve flow coverage
> Docs: fix 10 out of 16 flow fixme's

- docs/pages/foundations/messaging/overview.js
updated image dimensions to fit in iOS safari
> Docs: updated image dimensions for messaging guidelines

- docs/docs-components/GeneratedPropTable.js
- docs/pages/web/pageheader.js
- docs/pages/web/slimbanner.js
Docs: fix GeneratedPropTable regex
> Docs: fix GeneratedPropTable regex

- docs/pages/foundations/brand_expression/guidelines.js
Ensure images are container in space provided
> Docs: Brand guidelines tweaks

- docs/docs-components/contexts/DocsExperimentProvider.js
- docs/pages/web/toast.js
- packages/gestalt/src/Toast.js
- packages/gestalt/src/ToastPrimaryAction.js
- packages/gestalt/src/__snapshots__/Toast.test.js.snap
Toast: implementation new Toast design behind experiment
| BEFORE      | AFTER |
| ----------- | ----------- |
| ![Screen Shot 2022-11-18 at 11 43 10 AM](https://user-images.githubusercontent.com/10593890/202757078-e1c766ee-1f5d-4e4f-9190-587508d52849.png) |  ![Screen Shot 2022-11-18 at 11 42 42 AM](https://user-images.githubusercontent.com/10593890/202757769-6ae77619-d2cb-4633-8026-390157b94160.png) |
| ![Screen Shot 2022-11-18 at 11 44 59 AM](https://user-images.githubusercontent.com/10593890/202757597-5f5589d8-ef57-4034-a428-970b9ab8211f.png) | ![Screen Shot 2022-11-18 at 11 44 46 AM](https://user-images.githubusercontent.com/10593890/202757648-9d74e6a6-d204-4c0f-a606-9fded8447d6b.png) |
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4028)
- …
> Toast: new experimental Toast redesign

- package.json
- yarn.lock
Internal: upgrade @netlify/plugin-nextjs to 4.29.2
> Internal: upgrade @netlify/plugin-nextjs to 4.29.2

- docs/pages/foundations/messaging/available_components.js
Docs: minor fix in Toast example in _foundations/messaging/available_components#What-component-should-I-use_ page
> Docs: fix in Toast

- docs/pages/foundations/iconography/ICON_DATA.json
- docs/pages/foundations/iconography/library.js
Ensure alphabetical order is applied in icon library page, add a few missing icons
> Docs: Update alphabetical order in icon library

- docs/pages/web/popover.js
Show editor and controls
Add new dismiss button to a few more examples, remove old Box prop color
> Popover: Update docs examples

- docs/pages/foundations/iconography/ICON_DATA.json
I added descriptions for a few icons that were pending.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-5158)
> Icons: Add more descriptions

- scripts/generateComponent.js
- scripts/templates/lowercasecomponentname.js
Updated output folder in web and paths
Fixed error in replacing component name
> Internal: fixes in scaffolding script

- scripts/templates/lowercasecomponentname.js
Use generatedDocGen for component name
> Internal: quick fix scaffolding

- docs/examples/spinner/doLocation.js
- docs/examples/spinner/doOverlay.js
- docs/examples/spinner/doWait.js
- docs/examples/spinner/dontLabel.js
- docs/examples/spinner/dontMultiple.js
- docs/examples/spinner/dontWait.js
- docs/pages/web/spinner.js
Add Best Practices and Localization sections
- [Jira](https://jira.pinadmin.com/browse/GESTALT-5146)
- [TDD](https://paper.dropbox.com/doc/Gestalt-doc-Spinner--BueSwLMDuUI2U2rw0nNGGwVpAg-Jlkajzd19bBpqelFSJMia)
> Spinner: add Best Practices and Localization sections

- docs/markdown/get_started/developers/contributing/development_process.md
- package.json
Internal: change in visual diff command to be able to run vis diff tests locally
> Internal: change in visual diff command to be able to run vis diff tests locally

- packages/gestalt/src/Layer.js
- packages/gestalt/src/ScrollBoundaryContainer.js
- packages/gestalt/src/Spinner.js
- packages/gestalt/src/Sticky.js
- packages/gestalt/src/TapArea.js
ScrollBoundaryContainer, Layer, Sticky, TapArea, Spinner:  add SVG to Flow description
> ScrollBoundaryContainer, Layer, Sticky, TapArea, Spinner:  add SVG to Flow description

- docs/examples/dropdown/customItem.js
- docs/pages/web/dropdown.js
Update example for custom item content to be more realistic
Add to a11y section about custom item content
Ensure accessibility is taken into account when creating dropdown items with custom content
- [Jira](https://jira.pinadmin.com/browse/GESTALT-4880)
> Dropdown: Update custom item example

- docs/markdown/foundations/content/guidelines.md
Please also make sure your [PR title](https://github.com/pinterest/gestalt/#releasing) matches our format: `{ComponentName}-{platform}: Description`
Adding Content Design Guidelines (v1—changes will come!) to Gestalt
> Bt content guidelines

- packages/gestalt-codemods/README.md
This does fix some lint errors, but mostly is a stronger kick to get the releases working again (hopefully 🤞)
NOT A REAL MAJOR RELEASE, NO BREAKING CHANGES
> Internal: NO BREAKING CHANGES - fix lint errors in codemod readme.md

- docs/docs-components/siteIndex.js
Data visualization menu item should be sentence case
> Updated Data visualization menu item to be sentence case

- packages/gestalt/src/ModalAlert.js
- packages/gestalt/src/VideoControls.js
- packages/gestalt/src/boxTransforms.js
- packages/gestalt/src/style.js
- packages/gestalt/src/transforms.js
- packages/gestalt/src/useFocusVisible.js
- packages/gestalt/src/utils/matchMedia.js
- packages/gestalt/src/utils/positioningUtils.js
- packages/gestalt/src/utils/wrapWithComponent.js
This addresses some of our FlowFixMe's. Some are fixed. Others are converted to FlowExpectedError, where there is not a workaround to make Flow happy. There shouldn't be any runtime changes — potential areas are called out in comments.
> Internal: Flow fixes

- docs/pages/BlogPosts.json
> Docs: Jan 13 weekly digest

- docs/pages/BlogPosts.json
Weekly Gestalt updates added to What's new page
> Docs: 1/20 weekly digest

- docs/pages/BlogPosts.json
- docs/pages/BlogPosts.json.flow
- docs/pages/whats_new.js
- scripts/generateSlackBlockKitPost.js
Also some tweaks to the blog post JSON and script to support multiple years. I left some TODOs for myself to improve the script in the near-ish future to better support both eng and design needs, as well as making the dates more friendly to programmatic munging.
> Docs: January newsletter

- package.json
- yarn.lock
Internal: upgrade @playwright/test to 1.30.0 #2637
> Internal: upgrade @playwright/test to 1.30.0

- docs/pages/web/badge.js
Docs: tiny bug on code Editor in Badge
> Docs: tiny bug on code Editor in Badge

- docs/pages/RoadmapData.json
> Updated roadmap to match H1 2023 goals

- docs/docs-components/MarkdownPage.js
- docs/markdown/android/icon.md
> Docs: linting + copyediting for Android icon page

- docs/docs-components/MarkdownPage.js
We've got some missing bullet points. I have a suspicion…that I guess we have to test in prod? 😅 
_Deploy preview_
_Prod_ 😬
> Docs: fix MDX Do/Dont rendering

- playwright/masonry/handle-position-update.spec.mjs
> Internal: add `handle-position-update` Masonry integration test

- docs/markdown/android/icon.md
Followup to #2668 
This isn't quite it:
Making another attempt.
> Docs: fix MDX Do/Dont rendering, take two

- scripts/generateComponent.js
- scripts/templates/ComponentName.svg
- scripts/templates/ComponentName.test.js
- scripts/templates/README.md
- scripts/templates/lowercasecomponentname.js
- scripts/templates/main.js
Internal: update scripts/generateComponent.js
> Internal: update scripts/generateComponent.js

- docs/pages/BlogPosts.json
> Docs: Weekly update for March 3, 2023

- packages/gestalt/src/Collection.js
- packages/gestalt/src/index.js
Run 
```
--component=Collection
```
Collection: deprecation from index file
This was a little Easter egg. This component is internal and should have been removed a long time ago.
> Collection: deprecation from index file

- docs/markdown/android/toast.md
Updated Android toast images to reflect upcoming work and added/fixed text for clarity.
> Toast: Updates to Android images

- docs/docs-components/PropTable.js
The release script is in a weird state after merging #2707, claiming that the version already exists. Merging this off as a BS "major version" to give the release script a kick and hopefully get it back in a good state.
> Internal: tiny Flow type change to give release script a kick

- docs/examples/toast/avatar.js
- docs/examples/toast/dismissable.js
- docs/examples/toast/doConcise.js
- docs/examples/toast/doDismiss.js
- docs/examples/toast/doInteraction.js
- docs/examples/toast/doOne.js
- docs/examples/toast/dontMultiple.js
- docs/examples/toast/dontPermanent.js
- docs/examples/toast/dontRequest.js
- docs/examples/toast/dontWordy.js
- docs/examples/toast/error.js
- docs/examples/toast/helperLink.js
- docs/examples/toast/howto.js
- docs/examples/toast/icon.js
- docs/examples/toast/image.js
- docs/examples/toast/main.js
- docs/examples/toast/message.js
- docs/examples/toast/primaryAction.js
- docs/examples/toast/processing.js
- docs/examples/toast/richMessage.js
- docs/examples/toast/success.js
- docs/examples/toast/textOnly.js
- docs/markdown/android/toast.md
- docs/markdown/ios/toast.md
- docs/pages/web/toast.js
- packages/gestalt/src/Toast.js
- packages/gestalt/src/Toast/PrimaryAction.js
Toast: new Docs for redesign Toast
- [Jira](https://jira.pinadmin.com/browse/GESTALT-3680)
- [TDD](https://paper.dropbox.com/doc/Toasts--BucHcRauMuq0blMaS8d6EDZRAg-P84oIViyqAZYbRLSA0cpg)
- [Figma](https://www.figma.com/file/rVnMTnlB64QbKrF5c6KjUl/Gestalt-Toast-Design?node-id=2%3A114)
> Toast: new Docs for redesign Toast

- package.json
- yarn.lock
Internal: added @khanacademy/flow-to-ts to devDependencies to test TS
> Internal: added @khanacademy/flow-to-ts to devDependencies to test TS

- docs/graphics/home-page/HeroGraphic.js
Internal: fix in HeroGraphic
Fix error in build
> Internal: fix in HeroGraphic

- packages/gestalt/src/useReducedMotion.js
useReducedMotion: fix undefined error
After seeing in some tests in Pinboard.
> useReducedMotion: fix "undefined" error

- packages/gestalt/src/TextField/InternalTextField.css
Textfield: fix in CSS reference
> Textfield: fix in CSS reference

- docs/markdown/get_started/developers/contributing/development_process.md
Docs: add more context to Playwright visual diff snapshot tests section
> Docs: add more context to Playwright visual diff snapshot tests section

- docs/docs-components/SandpackExample.js
> Internal: fix Sandpack not enabled in prod

- docs/docs-components/DevelopmentEditor.js
- docs/docs-components/ExampleCode.js
- docs/docs-components/Header.js
- docs/docs-components/SandpackExample.js
- docs/docs-components/appContext.js
- docs/docs-components/contexts/DocsConfigProvider.js
Docs: final improvements to development view: cleanup/refactor
> Docs: final improvements to development view: cleanup/refactor

- docs/pages/RoadmapData.json
Status updates to the H1 2023 roadmap
> Docs: Roadmap updates

- docs/examples/colorschemeprovider/variantsColorScheme.js
- docs/examples/onlinknavigationprovider/examplesCalloutUpsell.js
- docs/examples/onlinknavigationprovider/examplesDropdown.js
- docs/examples/onlinknavigationprovider/examplesLinkButton.js
- docs/examples/usefocusvisible/exampleButtons.js
- docs/examples/usereducedmotion/example.js
- docs/pages/web/utilities/colorschemeprovider.js
- docs/pages/web/utilities/onlinknavigationprovider.js
- docs/pages/web/utilities/usefocusvisible.js
- docs/pages/web/utilities/usereducedmotion.js
- docs/removeFlowTypesLoader.js
also adds logic to filter out $FlowFixMe comments
> ColorSchemeProvider, OnLinkNavigationProvider, useFocusVisible, useReducedMotion: convert examples to Sandpack

- docs/docs-components/Header.js
- docs/markdown/team_support/contributions.md
- docs/pages/team_support/overview.js
> Docs: Fixing capitalization

- docs/docs-components/DocsSideNavigation.js
Docs: Add Team support to mobile siden nav
> Docs: Add Team support to mobile siden nav 

- docs/markdown/android/toast.md
Added Figma embeds for design specs in Android Toast documentation
> Toast: Add specs to Android docs page

- packages/gestalt/src/Icon.js
removing references to outdated, previously deprecated colors
adding notes about ARIA attributes
> Icon: update docs for color and other props

- docs/markdown/blog/2023_q1_newsletter.md
PJ never misses a chance to screw up on content.
> Docs: Q1 newsletter fix

- docs/markdown/get_started/developers/contributing/development_process.md
> Docs: lint development_process.md

- docs/docs-components/COMPONENT_DATA.js
- docs/docs-components/siteIndex.js
- docs/markdown/android/text.md
- playwright/accessibility/android__text.spec.mjs
Added a new page for the Android Text component
To add design guidelines when using the Text component, since we're developing this component.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-5941)
- [Coda](https://coda.io/d/Gestalt-Team-Folder_d2LeXkQ1kVX/Text-Android_su0QZ)
- [Figma](https://www.figma.com/file/REw1COFYAktmVWrUBh3Ov8/Gestalt-for-A …
> Text: Android component specs and guidelines

- package.json
- yarn.lock
Current version is `2.6.0`. This PR upgrades to the last `1.x.x` version, in preparation for making the major version upgrade.
> Internal: upgrade @codesandbox/sandpack-react to 1.20.9

- package.json
- yarn.lock
Upgrading to [2.6.0](https://github.com/codesandbox/sandpack/releases/tag/v2.6.0)
> Internal: upgrade @codesandbox/sandpack-react to 2.6.0

- docs/docs-components/COMPONENT_DATA.js
- docs/docs-components/siteIndex.js
- docs/markdown/android/searchfield.md
- docs/markdown/android/textarea.md
- docs/markdown/android/textfield.md
- playwright/accessibility/android__textarea.spec.mjs
Added a TextArea page for Android
Added TextArea page to Android
- …
> TextArea: Add Android guidelines and specs

- docs/pages/web/sheetmobile.js
Added more information for context and clarification around headers and footers.
> SheetMobile: Added additional header and footer context

- docs/pages/get_started/developers/releases.js
Docs: additional information re releases: codemod outputs and alpha released
> Docs: additional information about releases: codemod outputs in csv and alpha release process

- docs/docs-components/SandpackExample.js
- docs/examples/datefield/disabled.js
- docs/examples/datefield/error.js
- docs/examples/datefield/main.js
- docs/examples/datefield/states.js
- docs/pages/web/datefield.js
- packages/gestalt-datepicker/src/DateField/InternalDateField.js
DateField: fixed responsiveness issue & added disableRange example
Also, fixed editor heights
> DateField: fixed responsiveness issue & added disableRange example

- .flowconfig
- package.json
- yarn.lock
Internal: update Flow to v0.190.1
https://github.com/facebook/flow/releases/tag/v0.190.0
https://github.com/facebook/flow/releases/tag/v0.190.1
> Internal: update Flow to v0.190.1

- .flowconfig
- docs/docs-components/Overview.js
- docs/integration-test-helpers/masonry/MasonryContainer.js
- docs/pages/integration-test/masonry.js
- docs/removeFlowTypesLoader.js
- package.json
- packages/eslint-plugin-gestalt/src/helpers/styleValidators.js
- packages/eslint-plugin-gestalt/src/no-workflow-status-icon.js
- packages/gestalt-datepicker/src/DateField.js
- packages/gestalt-datepicker/src/DateField/InternalDateField.js
- packages/gestalt/src/PageHeader.js
- packages/gestalt/src/Video.js
- packages/gestalt/src/getRoundingClassName.js
- packages/gestalt/src/style.js
- packages/gestalt/src/utils/keyboardNavigation.js
- playwright/masonry/load-more.spec.mjs
- playwright/masonry/optimized-remount.spec.mjs
- playwright/masonry/utils/countColumns.mjs
- yarn.lock
Internal: upgrade to Flow 0.191.0
https://github.com/facebook/flow/releases/tag/v0.191.0
> Internal: upgrade to Flow 0.191.0

- .flowconfig
- docs/docs-components/clipboardCopy.js
- package.json
- yarn.lock
Internal: upgrade to Flow 0.192.0
> Internal: upgrade to Flow 0.192.0 

- docs/pages/web/textarea.js
Internal: fix master after missing id in example
Introduced in https://github.com/pinterest/gestalt/pull/2869
All new examples should be in Sandpack
No PRs should be merge if the PR shows integration tests failing
> Internal: fix master after missing id in example (introduced in #2869)

- docs/docs-components/Overview.js
Docs: Fix broken Overview page
> Docs: Fix broken web Overview page

- .flowconfig
- package.json
- yarn.lock
Internal: upgrade to Flow 0.193.0
> Internal: upgrade to Flow 0.193.0

- .flowconfig
- docs/docs-components/MarkdownPage.js
- package.json
- packages/eslint-plugin-gestalt/src/no-box-marginleft-marginright.js
- packages/eslint-plugin-gestalt/src/no-medium-formfields.js
- packages/eslint-plugin-gestalt/src/no-role-link-components.js
- yarn.lock
Internal: upgrade to Flow 0.196.2
https://github.com/facebook/flow/releases/tag/v0.196.0
> Internal: upgrade to Flow 0.196.2

- .flowconfig
- package.json
- packages/gestalt/src/AvatarGroup.js
- yarn.lock
Internal: upgrade to Flow 0.198.2
https://github.com/facebook/flow/releases/tag/v0.197.0
https://github.com/facebook/flow/releases/tag/v0.198.0
> Internal: upgrade to Flow 0.198.2

- .flowconfig
- package.json
- packages/gestalt/src/Avatar/DefaultAvatar.js
- packages/gestalt/src/Tabs.js
- yarn.lock
Internal: upgrade to Flow 0.201.0 
https://github.com/facebook/flow/releases/tag/v0.199.0 
https://github.com/facebook/flow/releases/tag/v0.200.0
https://github.com/facebook/flow/releases/tag/v0.201.0
> Internal: upgrade to Flow 0.201.0

- .flowconfig
- package.json
- yarn.lock
Internal: upgrade to Flow v0.202.0 
https://github.com/facebook/flow/releases/tag/v0.202.0
> Internal: upgrade to Flow v0.202.0 

- docs/examples/dropdown/action.js
- docs/examples/dropdown/badges.js
- docs/examples/dropdown/composability.js
- docs/examples/dropdown/customHeader.js
- docs/examples/dropdown/customItem.js
- docs/examples/dropdown/doFeatures.js
- docs/examples/dropdown/doIcons.js
- docs/examples/dropdown/doOrder.js
- docs/examples/dropdown/dontCustom.js
- docs/examples/dropdown/dontSelectList.js
- docs/examples/dropdown/dontTooltips.js
- docs/examples/dropdown/link.js
- docs/examples/dropdown/main.js
- docs/examples/dropdown/mobile.js
- docs/examples/dropdown/sections.js
- docs/examples/dropdown/subtext.js
- docs/examples/dropdown/truncation.js
- docs/pages/web/dropdown.js
- packages/gestalt/dist/index.d.ts
- packages/gestalt/src/Dropdown.js
- packages/gestalt/src/Dropdown/Context.js
- packages/gestalt/src/Dropdown/OptionItem.js
- packages/gestalt/src/DropdownItem.js
- packages/gestalt/src/DropdownLink.js
- packages/gestalt/src/SheetMobile.js
- packages/gestalt/src/SheetMobile/PartialPage.js
Dropdown: implement adaptive Dropdown with SheetMobile for mobile devices
> Dropdown: implement adaptive Dropdown with SheetMobile for mobile devices

- docs/docs-components/DevelopmentEditor.js
- docs/examples/onlinknavigationprovider/dangerouslyDisableOnNavigation.js
- docs/pages/web/utilities/onlinknavigationprovider.js
OnLinkNavigationProvider: added "disabling provider" variant
> OnLinkNavigationProvider: added "disabling provider" variant

- docs/docs-components/DevelopmentEditor.js
- docs/examples/onlinknavigationprovider/dangerouslyDisableOnNavigation.js
OnLinkNavigationProvider: example fix
> OnLinkNavigationProvider: example fix

- docs/markdown/android/avatar.md
Avatar: (Android) correcting measurement units `px` to `dp`
> Avatar: correcting measurement units for Android

- .flowconfig
- flow-typed/npm/@testing-library/react_v10.x.x.js
- flow-typed/npm/@testing-library/react_vx.x.x.js
- flow-typed/npm/classnames_v2.x.x.js
- flow-typed/npm/jest_v26.x.x.js
- flow-typed/npm/react-datepicker_v2.x.x.js
- package.json
- packages/gestalt-datepicker/src/DatePicker/TextField.js
- packages/gestalt/src/Masonry.js
- yarn.lock
Internal: upgrade to Flow 0.204.1
https://github.com/facebook/flow/releases/tag/v0.204.0
> Internal: upgrade to Flow 0.204.1

- docs/pages/BlogPosts.json
> Docs: May 19, 2023 update

- README.md
Adding a troubleshooting section here that links to our development FAQ
> Internal: Add Troubleshooting section to Readme

- scripts/generateMetadata.js
> Tagdata: Add tagdata alpha

- docs/docs-components/COMPONENT_DATA.js
- docs/docs-components/siteIndex.js
- docs/examples/datavisualization/desktopgraphExample.js
- docs/examples/datavisualization/graphtotableExample.js
- docs/examples/datavisualization/mobilegraphExample.js
- docs/pages/foundations/data_visualization/available_components.js
- docs/pages/foundations/data_visualization/charts_and_graphs.js
- docs/pages/foundations/data_visualization/color/palette.js
- docs/pages/foundations/data_visualization/color/usage.js
- docs/pages/foundations/data_visualization/micro_visualizations.js
- docs/pages/foundations/data_visualization/overview.js
- docs/redirects.js
- playwright/accessibility/foundations__data_visualization__available_components.spec.mjs
- playwright/accessibility/foundations__data_visualization__charts_and_graphs.spec.mjs
- playwright/accessibility/foundations__data_visualization__color__palette.spec.mjs
- playwright/accessibility/foundations__data_visualization__color__usage.spec.mjs
- playwright/accessibility/foundations__data_visualization__micro_visualizations.spec.mjs
- playwright/accessibility/foundations__data_visualization__overview.spec.mjs
Added data visualization guidelines to Foundations
Added Overview, Charts and Graphs, Micro-visualization and Available components to Data Viz. Grouped Palette and usage under a Sub folder Color.
We need more data visualization design guidelines.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-6233)
- [TDD](https://coda.io/d/_dqIC9SDPsU9/Data-visualization_suKXH)
> Docs: Added data visualization guidelines

- docs/docs-components/siteIndex.js
- docs/markdown/android/iconbuttonfloating.md
- playwright/accessibility/android__iconbuttonfloating.spec.mjs
Docs: Added IconButtonFloating Android docs #2979
> Docs: Added IconButtonFloating Android docs

- docs/pages/foundations/data_visualization/available_components.js
In the coming next section, I removed "TileData" since that is already released. I replaced with TagData.
> Docs: Fix info on Available components page

- packages/gestalt/dist/index.d.ts
Internal: fix TS declaration file
> Internal: fix TS declaration file

- packages/eslint-plugin-gestalt/README.md
> Internal: Update eslint-plugin-gestalt README

- docs/docs-components/DevelopmentEditor.js
- docs/docs-components/Example.js
- docs/docs-components/MainSectionCard.js
- docs/docs-components/handleCodeSandbox.js
- scripts/templates/ComponentName.js
- scripts/templates/lowercasecomponentname.js
Internal: fixes to gestalt-datepicker and templates
> Internal: fixes to gestalt-datepicker in editors and templates

- packages/gestalt-datepicker/src/DateField.js
- packages/gestalt-datepicker/src/DateField/InternalDateField.js
DateField: refactor InternalDateField logic
Make a real internal component
> DateField: refactor InternalDateField logic

- packages/gestalt/src/TileData.js
Found using Algolia crawler monitoring
> Docs: fix outdated link

- docs/markdown/team_support/contributions.md
mostly just needing to merge a PR
> Internal: lint contributions.md

- packages/eslint-plugin-gestalt/package.json
- packages/gestalt-datepicker/package.json
- packages/gestalt-design-tokens/package.json
- packages/gestalt/package.json
mostly just kicking off another release
> Internal: update package.json keywords

- docs/markdown/android/iconbutton.md
was going to use this for debugging the release script but that's fixed now. not worth throwing away this work though
> Internal: lint android/iconbutton.md

- docs/markdown/android/icon.md
- docs/markdown/android/text.md
- docs/markdown/ios/icon.md
- docs/markdown/ios/text.md
> Docs: fix `allowfullscreen` bug

- docs/markdown/android/avatar.md
- docs/markdown/android/icon.md
- docs/markdown/android/searchfield.md
- docs/markdown/android/switch.md
- docs/markdown/android/toast.md
Updated Figma links that were pointing to the incorrect content
> Docs: Fix Android Figma links

- docs/docs-components/AccessibilitySection.js
- docs/docs-components/Card.js
- docs/docs-components/MainSectionCard.js
- docs/docs-components/MainSectionSubsection.js
- docs/docs-components/MarkdownPage.js
- docs/docs-components/consts.js
- docs/pages/foundations/animation/guidelines.js
- docs/pages/foundations/animation/implementation.js
- docs/pages/foundations/data_visualization/charts_and_graphs.js
- docs/pages/foundations/iconography/usage.js
- docs/pages/foundations/typography/guidelines.js
- docs/pages/get_started/developers/tooling/web.js
wow this was hardcoded everywhere 😬
> Internal: use const for docs copy max width

- docs/examples/pageheader/centerAlignedExample.js
- docs/examples/pageheader/complimentaryItemsExample.js
- docs/examples/pageheader/defaultExample.js
- docs/examples/pageheader/dontOverloadExample.js
- docs/examples/pageheader/includeImageExample.js
- docs/examples/pageheader/includeProfilePictureExample.js
- docs/examples/pageheader/localizationExample.js
- docs/examples/pageheader/maxWidthExample.js
- docs/examples/pageheader/minimumButtonsExample.js
- docs/examples/pageheader/multiplePrimaryActionsExample.js
- docs/examples/pageheader/onePrimaryActionExample.js
- docs/examples/pageheader/subtextExample.js
- docs/examples/pageheader/titleExample.js
Docs: PageHeader example fixes
> Docs: PageHeader example fixes

- docs/docs-components/QualityChecklist.js
- docs/docs-components/data/components.js
- docs/docs-components/data/types.js
- docs/pages/web/text.js
Docs: Added Issues section for Text, Heading within Component quality checklist
To communicate known issues and having a formal way of tracking issues for the tean
> Docs: Added Issues section for Text, Heading within Component quality checklist

- docs/markdown/android/sheet.md
Fixed images, fixed misspellings, and adjusted Figma graphics.
What is the purpose of this PR? Please include the context around these changes for Future Us. In addition to _what_ is changing, we need to know _why_ these changes are …
> Docs: cleaned up Android sheet docs

- docs/docs-components/Page.js
- docs/pages/[...id].js
The "Edit page on GitHub" link is broken
> Docs: Page Source Links

- docs/docs-components/data/components.js
- docs/docs-components/siteIndex.js
- docs/markdown/android/badge.md
- playwright/accessibility/android__badge.spec.mjs
Docs: Added Android Badge docs #3083
> Docs: Added Android Badge docs

- .github/workflows/pr-title-checker.yml
Internal: test skip-title-checker
> Internal: test skip-title-checker tag in github workflow

- .github/pr-title-checker-config.json
- .github/workflows/pr-title-checker.yml
Internal: test 'skip-title-checker' 2 #3087
> Internal: test 'skip-title-checker' 2

- .github/pr-title-checker-config.json
Internal: revert tests 'skip-title-checker'
> Internal: revert tests 'skip-title-checker'

- docs/pages/BlogPosts.json
> Docs: 2023-07-21 weekly update

- docs/pages/RoadmapData.json
> Docs: 2023 H2 roadmap

- docs/pages/RoadmapData.json
Finalized the list of iOS components and added to the H2 roadmap
> Docs: Added iOS components to the H2 roadmap

- docs/examples/datepicker/main.js
- docs/examples/datepicker/preselected.js
- docs/examples/datepicker/selectLists.js
- docs/pages/web/datefield.js
- docs/pages/web/datepicker.js
- packages/gestalt-datepicker/src/DatePicker/InternalDatePicker.js
DatePicker: support controlled/uncontrolled component
DatePicker was neither a fully controlled/uncontrolled component
https://jira.pinadmin.com/browse/BUG-154540?jql=project%20%3D%20BUG%20AND%20resolution%20%3D%20Unresolved%20AND%20component%20%3D%20Gestalt%20%20ORDER%20BY%20%20priority%20DESC%2C%20updated%20DESC
> DatePicker: support controlled/uncontrolled component

- docs/pages/BlogPosts.json
> Docs: newsletter July

- docs/pages/web/datefield.js
- packages/gestalt-datepicker/package.json
- packages/gestalt-datepicker/src/DateField.jsdom.test.js
- packages/gestalt-datepicker/src/DateField/InternalDateField.js
- yarn.lock
DateField: fix locales in MM/DD/YYYY format, upgraded package, added unit tests
Assessment: https://coda.io/d/_d2LeXkQ1kVX/DateField_sukKr#_luoyc
BEFORE
AFTER
> DateField: fix locales in MM/DD/YYYY format, upgraded package, added unit tests

- docs/pages/get_started/developers/tooling/web.js
What is the purpose of this PR? Please include the context around these changes for Future Us. In addition to _what_ is changing, we need to know _why_ these changes are needed. Imagine someone is looking at these changes a year from now …
> Docs: removed outdated stats from table in tooling

- docs/docs-components/data/components.js
DatePicker: new documented issue
> DatePicker: new documented issue

- docs/docs-components/data/components.js
adding Table component to component status list for Android
adding Table component to component status list for Android
adding Table component to component status list for Android
adding planned component to list
n/a
> Component Status: Update components.js

- .github/workflows/release.yml
Internal: move gestalt-charts to end of release list
> Internal: move gestalt-charts to end of release list

- .github/workflows/alpha.yml
- .github/workflows/release.yml
Internal: updated NPM personal token
> Internal: updated github personal token

- docs/docs-components/DocSearch.js
> Internal: fix npm publishing

- docs/markdown/android/sheet.md
- docs/markdown/ios/sheet.md
What is the purpose of this PR? Please include the context around these changes for Future Us. In addition to _what_ is changing, we need to know _why_ these changes are needed. Imagine someone is looking at these changes a year from now …
> Docs: update ios &aos sheet docs

- docs/markdown/android/checkbox.md
- docs/markdown/ios/checkbox.md
Replaced example images from iOS and Android docs.
Changes made because the previous images had the wrong design.
> Checkbox: iOS/Android update example images 

- README.md
Docs: updated Readme after removing Issues support in GitHub
> Docs: updated Readme after removing Issues support in github

- docs/pages/BlogPosts.json
Docs: Newsletter Eng August 2023
> Docs: Newsletter Eng August 2023

- docs/pages/BlogPosts.json
Docs: 9/8 weekly digest
Merging https://github.com/pinterest/gestalt/pull/3188
> Docs: 9/8 weekly digest

- docs/markdown/ios/checkbox.md
Checkbox header image for iOS was incorrect
What is the purpose of this PR? Please include the context around these changes for Future Us. In addition to _what_ is changing, we need to know _why_ these changes are needed. Imagine someone …
> Docs: update iOS checkbox header image

- docs/pages/BlogPosts.json
Updating Gestalt digest (two last weeks)
Gestalt digest (blog post json file) update
We added the latest updates from Gestalt regarding the two last weeks (September 11-22)
This is a weekly or a bi-weekly team process. 
- [TDD](not applicable)
- [Figma](https://www.figma.com/file/96JCeZSHWiQcsp78k3mFnH/What's-new---Gestalt-latest-updates?type=whiteb …
> Docs: 9/22 weekly digest 

- docs/pages/BlogPosts.json
Docs: Newsletter Eng September 2023
> Docs: Newsletter Eng September 2023

- docs/pages/BlogPosts.json
Docs: remove internal section from Sept eng newsletter
> Docs: remove internal section from Sept eng newsletter

- packages/gestalt/dist/index.d.ts
- packages/gestalt/src/Link.js
- packages/gestalt/src/Link.jsdom.test.js
Link: added  `dataTestId` prop
> Link: added  `dataTestId` prop

- packages/gestalt/dist/index.d.ts
> Internal: fix in TS file

- docs/pages/web/activationcard.js
- docs/pages/web/button.js
- docs/pages/web/callout.js
- docs/pages/web/dropdown.js
- docs/pages/web/iconbutton.js
- docs/pages/web/link.js
- docs/pages/web/taparea.js
- docs/pages/web/upsell.js
- docs/pages/web/utilities/globaleventshandlerprovider.js
> Docs: cleanup

- docs/markdown/android/listaction.md
- docs/markdown/android/tabs.md
- docs/markdown/android/toast.md
- docs/markdown/ios/listaction.md
- docs/markdown/ios/tabs.md
- docs/markdown/ios/toast.md
Docs: Updates to toast and tabs #3242
> Docs: Updates to Toast and Tabs in Android and iOS

- docs/markdown/android/textfield.md
- docs/markdown/ios/textfield.md
What is the purpose of this PR? Please include the context around these changes for Future Us. In addition to _what_ is changing, we need to know _why_ these changes are needed. Imagine someone is looking at these changes a year from now …
> Docs: TextField - Updated ios & android

- docs/docs-components/siteIndex.js
- docs/markdown/ios/searchfield.md
- playwright/accessibility/ios__searchfield.spec.mjs
What is the purpose of this PR? Please include the context around these changes for Future Us. In addition to _what_ is changing, we need to know _why_ these changes are needed. Imagine someone is looking at these changes a year from now …
> Docs: SearchField - Update Android and Add iOS

- .flowconfig
- docs/utils/mdHelper.js
- package.json
- yarn.lock
Internal: update Flow from v0.210.2 to v0.216.1
> Internal: update Flow from v0.210.2 to v0.216.1

- docs/docs-components/siteIndex.js
- docs/markdown/blog/2023_q3_newsletter.md
- playwright/accessibility/blog__2023_q3_newsletter.spec.mjs
Published Q3 newsletter to blog.
New newsletter
We publish one every quarter.
- [TDD](https://coda.io/d/Gestalt-Team-Folder_d2LeXkQ1kVX/Gestalt-2023-Q3-newsletter_sudsg#_luyFn)
> Docs: Q3 Newsletter

- README.md
> Docs: Update README.md with email

- docs/markdown/blog/2023_q3_newsletter.md
fixed typo
First heading, changed to "Q3"
Wrong quarter
> Docs: Update 2023_q3_newsletter.md

- packages/gestalt-design-tokens/tokens/color/alias.json
- packages/gestalt/src/contexts/__snapshots__/ColorSchemeProvider.jsdom.test.js.snap
Adding $color-background-neutral token
> Tokens: Added $color-background-neutral

- docs/markdown/android/iconbutton.md
- docs/markdown/ios/iconbutton.md
I've updated the documentation for IconButton iOS and Android, adding Figma embedded links, extra information and fixing errors.
Pages were not updated for a while and documentation info has changed.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-6448)
> IconButton: iOS/Android documentation cleanup

- docs/markdown/android/listaction.md
- docs/markdown/ios/listaction.md
Docs: Clarifying updates to ListAction docs #3278
> Docs: Clarifying updates to ListAction docs

- docs/docs-components/data/components.js
- docs/docs-components/siteIndex.js
- docs/markdown/ios/badge.md
- playwright/accessibility/ios__badge.spec.mjs
> Docs: Add iOS Badge docs

- docs/docs-components/data/components.js
- docs/docs-components/siteIndex.js
- docs/markdown/android/textarea.md
- docs/markdown/ios/textarea.md
- playwright/accessibility/ios__textarea.spec.mjs
Published the docs for iOS TextArea. I also used this PR to fix mistakes under the Android TextArea docs.
> TextArea: iOS Publishing docs 

- docs/docs-components/Markdown.js
- docs/docs-components/MarkdownPage.js
- docs/markdown/android/checkbox.md
- docs/markdown/android/sheet.md
- docs/pages/foundations/data_visualization/charts_and_graphs/bar_graphs.js
- docs/pages/foundations/data_visualization/charts_and_graphs/combo_graphs.js
- docs/pages/foundations/data_visualization/charts_and_graphs/general_guidelines.js
- docs/pages/foundations/data_visualization/charts_and_graphs/line_graphs.js
Docs: fixes in Markdown and links
> Docs: fixes in Markdown links and links

- packages/gestalt/dist/index.d.ts
- packages/gestalt/src/NumberField.js
NumberField: added `labelDisplay` prop matching TextField
> NumberField: added `labelDisplay` prop

- docs/docs-components/CombinationNew.js
- docs/docs-components/SandpackExample.js
- docs/docs-components/appContext.js
Docs: implement `?helixbot=boolean` in the url to enable a site without code examples to facilitate the crawling of the helix-bot to integrate AI
> Docs: implement `?helixbot=boolean` in the url to enable a site without code examples to facilitate the crawling of the helix-bot to integrate AI

- packages/gestalt/dist/index.d.ts
Internal: Fixed TypeScript declaration file
> Internal: Fixed TypeScript declaration file

- packages/gestalt/dist/index.d.ts
> Internal: fix

- docs/markdown/android/avatar.md
Docs: Updated px to dp on avatar.md
> Docs: Updated px to dp on avatar.md

- docs/markdown/android/sheet.md
- docs/markdown/ios/sheet.md
Docs: Updates to sheet language
> Docs: Updates to sheet language

- packages/gestalt/dist/index.d.ts
> SideNavigation: TS fix

- docs/docs-components/App.js
- packages/gestalt/src/contexts/ColorSchemeProvider.js
ColorSchemeProvider: fix in docs and better documentation
> ColorSchemeProvider: fix in docs and better documentation

- docs/docs-components/App.js
- docs/pages/_document.js
> Docs: fix GA4 property

- packages/gestalt/dist/index.d.ts
> Internal: ts typo fix

- docs/docs-components/PropTable.js
It's been a while. Just verifying that I remember our processes 😅
> Internal: fix Flow suppressions in docs PropTable

- packages/gestalt/dist/index.d.ts
Internal: fixes to .ts files
Added "scissors" icon + formatting
> Internal: fixes to .ts files

- docs/docs-components/siteIndex.js
- docs/pages/foundations/international_design/number_localization.js
- playwright/accessibility/foundations__international_design__number_localization.spec.mjs
Creation of a new doc page, Number localization, under Foundations -> International design
Added a new page. 
- [Jira](https://jira.pinadmin.com/browse/GESTALT-7211)
- [Coda](https://coda.io/d/Gestalt-X-Team-Collaboration_dqIC9SDPsU9/Number-localization_suWsF#_luoaE))
> Docs: Number Localization page

- .vscode/settings.json
- docs/docs-components/siteIndex.js
- docs/pages/foundations/international_design/pluralization.js
- playwright/accessibility/foundations__international_design__pluralization.spec.mjs
Creation of a new doc page, Pluralization, under Foundations -> International design
Added a new page. 
- [Jira](https://jira.pinadmin.com/browse/GESTALT-7211)
- [Coda](https://coda.io/d/Gestalt-X-Team-Collaboration_dqIC9SDPsU9/Pluralization_sumbG#_luHrK)
> Docs: Pluralization page

- packages/gestalt/dist/index.d.ts
Internal: fix TS declaration for SlimBanner's primaryAction type
> Internal: fix TS declaration for SlimBanner's primaryAction type

- docs/docs-components/siteIndex.js
- docs/pages/foundations/international_design/number_localization.js
- docs/pages/foundations/international_design/pluralization.js
- Updated internal and external links, changed URLS into Pinch and added Link component to a few URLs when possible. 
Pinch added to avoid external visitation into private links; better clarification of external links. Reordered the side navigation to follow alphabetical order.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-7377)
> Docs: Small fixes to i18n docs

- docs/pages/BlogPosts.json
> Docs: Newsletter Jan 2024

- packages/gestalt/src/Colors.css
Internal: remove blue color replaced with education
> Internal: remove blue color replaced with color-background-education

- docs/pages/web/button.js
Button: documenting Color contrast in disabled state
> Button: documenting Color contrast in disabled state

- docs/docs-components/PatternBarFill.js
- docs/docs-components/PatternLineMarker.js
- packages/gestalt-charts/src/ChartGraph/LegendIcon.js
- packages/gestalt-charts/src/ChartGraph/usePatterns.js
ChartGraph: fix bug from #3411 still consuming from ColorSchemeProvider 
ChartGraph: fix bug from #3411 still consuming from ColorSchemeProvider
> ChartGraph: fix bug from #3411 still consuming from ColorSchemeProvider 

- packages/gestalt-design-tokens/CHANGELOG.md
- packages/gestalt-design-tokens/tokens/color/component.json
- packages/gestalt/src/Colors.css
- packages/gestalt/src/Modal.css
- packages/gestalt/src/OverlayPanel.css
- packages/gestalt/src/SheetMobile.css
- packages/gestalt/src/contexts/__snapshots__/ColorSchemeProvider.jsdom.test.js.snap
Tokens: fix token bug from #3421
RENAME
| old-name                                  | new-name                 |
| ----------------------------------------- | ------------------------ |
| color-background-overlay-color-background | color-background-overlay |
> Tokens: fix `color-background-overlay` token bug introduced in #3421

- docs/markdown/android/buttontoggle.md
- docs/markdown/android/searchguide.md
- docs/markdown/ios/buttontoggle.md
Docs: Fixed ButtonToggle & SearchGuide information for clarity #3429
> Docs: Fixed ButtonToggle & SearchGuide information for clarity in Android/iOS

- packages/gestalt/src/SearchField.css
- packages/gestalt/src/SelectList.css
SelectList, SearchField: fix token
> SelectList, SearchField: fix token

- docs/pages/BlogPosts.json
> Docs: Newsletter Feb 2024

- packages/gestalt/src/Button.js
- packages/gestalt/src/ButtonLink.js
- packages/gestalt/src/__snapshots__/BannerSlim.test.js.snap
- packages/gestalt/src/__snapshots__/Toast.test.js.snap
Updating small `size=sm` to have a fontSize of 200 for both ButtonLink and Button
> Button: Fix Font Sizing

- docs/docs-components/PageHeader.js
Internal: testing data-id for HelixBot to detect page title 
HelixBox ingests HTML disabling JS.
> Internal: testing data-id for HelixBot to detect page title 

- docs/markdown/ios/avatar.md
- docs/markdown/ios/avatargroup.md
- docs/markdown/ios/textfield.md
Relinking Figma embeds for iOS Avatar, AvatarGroup and Textfield
> Docs: Figma embed fixes

- docs/docs-components/contexts/DocsExperimentProvider.js
- docs/pages/web/popovereducational.js
- packages/gestalt/src/PopoverEducational.js
Removed all the experiment related code from Popover-based components. PopoverEducational is now officially at v2! 🎉
- [Jira](https://jira.pinadmin.com/browse/GWEB-64)
> PopoverEducational: Release v2

- .eslintignore
- .eslintrc.js
- docs/docs-components/ColorPalette.js
- docs/docs-components/ColorTile.js
- docs/docs-components/IllustrationCard.js
- docs/docs-components/MainSectionCard.js
- docs/docs-components/MarkdownPage.js
- docs/docs-components/OverviewList.js
- docs/markdown/android/sheet.md
- docs/markdown/android/tabs.md
- docs/markdown/ios/sheet.md
- docs/markdown/ios/tabs.md
- docs/pages/BlogPosts.json
- docs/pages/foundations/color/palette.js
- docs/pages/foundations/color/usage.js
- docs/pages/foundations/data_visualization/color/palette.js
- docs/pages/foundations/data_visualization/color/usage.js
- docs/pages/foundations/overview.js
- docs/pages/home.js
- docs/pages/team_support/overview.js
- docs/pages/whats_new.js
- package.json
Internal: replace interpolated strings with design tokens constants.
> Internal: replace interpolated strings with design tokens constants.

- docs/pages/BlogPosts.json
> Docs: Newsletter March

- docs/docs-components/data/components.js
- rfcs/rfcs/2023-05-globalEventsHandlersProvider-new-component/README.md
- rfcs/rfcs/2023-07-globalEventsHandlersProvider-providerAuxData/README.md
Docs: updated broken links to drive links
> Docs: updated broken/deprecated links to drive links

- docs/pages/foundations/international_design/rtl_guidelines/iconography.js
Updated RTL icons guidelines
Updated the icon request link to our new Slack workflow
We have a new form and the old link doesn't work anymore.
> Docs: RTL icons update

- docs/docs-components/data/components.js
Update component data to reflect the latest iOS gestalt component code status 
- Mark all component listed in https://gestalt.pinterest.systems/ios/component_status as `Ready`
> Docs: Update iOS component status to reflect the latest 

- packages/gestalt/dist/index.d.ts
Dropdown: fix ts file bug as reported
> Dropdown: fix ts file bug

- package.json
- yarn.lock
Internal: remove dead dev dependency
> Internal: remove dead dev dependency

- packages/gestalt-design-tokens/build.js
- packages/gestalt-design-tokens/package.json
- packages/gestalt/package.json
Tokens: add declaration file for constant tokens
> Tokens: add declaration file for constant tokens

- docs/pages/get_started/developers/releases.tsx
- docs/pages/get_started/faq.tsx
Docs: updates re Flow and codemods
> Docs: updates re Flow and codemods

- docs/pages/foundations/motion/guidelines.tsx
GIF for Lateral easing had a wrong link. It has the correct link now.
> Docs: Fix Motion Guidelines Lateral easing GIF

- .github/workflows/release.yml
- packages/stylelint-plugin-gestalt/README.md
- packages/stylelint-plugin-gestalt/package.json
- scripts/publish.js
Internal: add stylelint-plugin-gestalt to the npm release schedule
> Internal: add stylelint-plugin-gestalt to the npm release schedule

- docs/docs-components/AccessibilitySection.tsx
- docs/docs-components/PageHeaderQualitySummary.tsx
- docs/pages/web/pageheader.tsx
Docs: removed Accessibility checklist module and badge
> Docs: removed Accessibility checklist module and badge

- docs/docs-components/contexts/DocsExperimentProvider.tsx
- docs/pages/web/dropdown.tsx
- packages/gestalt/src/Dropdown.jsdom.test.tsx
- packages/gestalt/src/Dropdown.tsx
- packages/gestalt/src/OverlayPanel.jsdom.test.tsx
- packages/gestalt/src/Popover.tsx
- packages/gestalt/src/PopoverEducational.jsdom.test.tsx
- packages/gestalt/src/__snapshots__/Dropdown.jsdom.test.tsx.snap
Removed all the Popover v2 experiment related code from ComboBox.
- [Jira](https://jira.pinadmin.com/browse/GWEB-69)
> Dropdown: Use Popover v2

- .eslintrc.js
- package.json
- packages/gestalt/src/MasonryV2.tsx
- packages/gestalt/src/ScrollBoundaryContainer.jsdom.test.tsx
- packages/gestalt/src/behaviors/TrapFocusBehavior.tsx
- yarn.lock
Adding [eslint-plugin-react-compiler](https://www.npmjs.com/package/eslint-plugin-react-compiler)
This checks for issues, and protects against new issues we might have when we use the react compiler. 
We would like to test out react complier soon. It [automatically optimizes](https://react.dev/learn/react-compiler#what-does-the-compiler-do) react code at build time.
- https://www.npmjs.com/package/eslint-plugin-react-compiler
> Internal: adding react-compiler plugin and rule

- packages/gestalt/src/Flex.tsx
- scripts/generateMetadata.js
> Docs: fix Flex page

- packages/eslint-plugin-gestalt/package.json
- packages/gestalt-charts/package.json
- packages/gestalt-datepicker/package.json
- packages/gestalt-design-tokens/package.json
- packages/gestalt/package.json
- packages/stylelint-plugin-gestalt/package.json
> Internal: fix releases

- .github/workflows/alpha.yml
- .github/workflows/release.yml
Internal: fixing workflow updating secrets
https://github.com/pinterest/gestalt/pull/2605/files
> Internal: update release.yml to use active account #2605

- docs/examples/link/colors.tsx
- packages/gestalt/src/Link.tsx
- packages/gestalt/src/Text.css
- packages/gestalt/src/__snapshots__/BannerOverlay.test.tsx.snap
- packages/gestalt/src/__snapshots__/BannerSlim.test.tsx.snap
- packages/gestalt/src/__snapshots__/Dropdown.jsdom.test.tsx.snap
- packages/gestalt/src/__snapshots__/Link.test.tsx.snap
- packages/gestalt/src/__snapshots__/PageHeader.test.tsx.snap
- packages/gestalt/src/__snapshots__/Status.test.tsx.snap
- packages/gestalt/src/__snapshots__/Toast.test.tsx.snap
https://www.figma.com/design/vjhfBsOtHw0wVg67vqwz1v/Gestalt-for-Web?node-id=36080-1012&m=dev
> Link: enabling VR design

- packages/gestalt/src/MasonryV2.tsx
This PR fixes a bug I encountered, specifically around `containerOffset` not being updated which could explain some of the metrics drops we're seeing for the unauth experiment
Masonry uses a `containerOffset` to determine how much distance there is between the top of the grid and the top of the scroll container. This is important to help with virtualization and fetch bounds during scrolling.
Currently, the `containerOffset` is calculated inside a `useLayoufEffect` and only recalculated if either the `gridWrapper` or `scrollContainer` elements change. This was initially done to avoid having to recalculate but it becomes problematic if the grid is actually pushed down (or up) as a result of external dom changes.  
As a result, we can see that if the grid is pushed down and containerOffset …
> Masonry: Update logic around updating containerOffset + containerHeight (MasonryV2)

- packages/gestalt/src/Box.tsx
- packages/gestalt/src/Masonry/defaultLayout.ts
> Internal: fixes

- docs/examples/textarea/disabled.tsx
- docs/examples/textarea/doAsAffordance.tsx
- docs/examples/textarea/doHelper.tsx
- docs/examples/textarea/doLabel.tsx
- docs/examples/textarea/doRows.tsx
- docs/examples/textarea/dontPlaceholder.tsx
- docs/examples/textarea/dontPlaceholderLabel.tsx
- docs/examples/textarea/dontRows.tsx
- docs/examples/textarea/dontSingleText.tsx
- docs/examples/textarea/enabled.tsx
- docs/examples/textarea/error.tsx
- docs/examples/textarea/helperText.tsx
- docs/examples/textarea/hiddenLabel.tsx
- docs/examples/textarea/label.tsx
- docs/examples/textarea/labelled.tsx
- docs/examples/textarea/maximumLengthEnabled.tsx
- docs/examples/textarea/maximumLengthError.tsx
- docs/examples/textarea/readOnly.tsx
- docs/examples/textarea/rows.tsx
- docs/examples/textarea/tags.tsx
- docs/pages/web/textarea.tsx
- packages/gestalt/src/TextArea.tsx
- packages/gestalt/src/TextArea/VRTextArea.css
- packages/gestalt/src/TextArea/VRTextArea.tsx
- packages/gestalt/src/TextField/VRInternalTextField.css
- packages/gestalt/src/TextField/VRInternalTextField.tsx
- packages/gestalt/src/sharedSubcomponents/FormErrorMessage.css
>  TextArea: VR Implementation

- packages/gestalt-icons-android/dist/classic/index.d.ts
- packages/gestalt-icons-android/dist/vr-theme/index.d.ts
Internal: run yarn tsc to fix formatting in declaration files
> Internal: run yarn tsc to fix formatting in declaration files

- packages/gestalt/src/ComboBox.tsx
- packages/gestalt/src/__snapshots__/ComboBox.jsdom.test.tsx.snap
ComboBox: undoing breaking change in id set in #3712
>  ComboBox: undoing breaking change in id set in #3712 in classic code

- packages/gestalt/src/Switch.css
- packages/gestalt/src/Switch.tsx
**BEFORE**
**AFTER**
- [Jira](https://jira.pinadmin.com/browse/GESTALT-8364)
- [TDD](https://docs.google.com/document/d/1J6QYhY81mnpZRc0e7wTW7EelUNW7i_u5C8iQsRO6soo/edit?usp=sharing)
- [Figma](https://www.figma.com/design/pMibC8csfCbNMU4jgLVUJh/Motion-Pilot-specs?node-id=2050-174&t=0UQYUBlkwqdzmzCQ-1)
> Switch: Add toggle motion

- docs/pages/web/banneroverlay.tsx
- packages/gestalt/src/BannerOverlay.test.tsx
- packages/gestalt/src/BannerOverlay.tsx
- packages/gestalt/src/__snapshots__/BannerOverlay.test.tsx.snap
BannerOverlay: enabled `reverseOffset` in `offset` for custom positioining
> BannerOverlay: enabled `reverseOffset` in `offset` for custom positioining

- packages/gestalt/src/SelectList/VRSelectList.css
- packages/gestalt/src/SelectList/VRSelectList.tsx
SelectList: adopted TextUI
|---|---|---|
| classic  |  ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/41c810db-c2b2-460f-97eb-8388be2ae815) |  ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/155d2d35-9b69-4d04-be9a-0844a21c6e11) |
|  VR  | ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/e0158d8b-71da-4ed2-baf3-627d9687d6a5) | ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/612db06a-cbcf-4914-9ee5-2efc6888f5bc) |
> SelectList: adopted TextUI

- packages/gestalt/src/Button.tsx
Badge: adopted TextUI 
|---|---|---|
| classic  | ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/98e73cfc-d309-478b-9b15-bc6ffca4f39a) | ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/dc24d2d1-1f97-4b12-8b49-eba6e91da17c) |
|  VR  | ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/ec1e1d66-a90f-46de-985a-abaf360c16ab)  |  ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/a335fb71-d8d6-49d1-9724-57bded93f92f) |
> Button: adopted TextUI

- packages/gestalt/src/TextField/VRInternalTextField.css
- packages/gestalt/src/TextField/VRInternalTextField.tsx
- packages/gestalt/src/TextUI.tsx
TextField, ComboBox: adopted TextUI
|---|---|---|
| classic  |![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/4994c403-42e8-4a6a-928a-1ca7d2cbc6a5) | ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/894f91f6-51cd-4ebb-be57-9ad6124165a1) |
|  VR  | ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/12f3bb34-3d5a-49c1-9e6c-7fda1ce9f114)  | ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/9e86ddda-6c83-4eaf-a718-28ba756edd57) |
> TextField, ComboBox: adopted TextUI

- packages/gestalt/src/TextArea/VRTextArea.css
- packages/gestalt/src/TextArea/VRTextArea.tsx
TextArea: adopted TextUI
|---|---|---|
| classic  |![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/c71de0d6-b847-4c3f-9ee5-941d7fad3743) | ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/e581aca4-087e-400f-8137-97c7bc134006) |
|  VR  | ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/4fc17b50-109a-4679-8e9c-5b3682546885) |![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/c397418e-c41b-46bd-9dcb-b07946a99458) |
> TextArea: adopted TextUI

- packages/gestalt/src/TagArea/TagArea.css
- packages/gestalt/src/TagArea/TagArea.tsx
TextField, TextArea, ComboBox: adopted TextUI in TagArea
|---|---|---|
| classic  | ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/3e31082c-973b-4a51-9a57-a660656d28aa) | ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/3f548275-302d-4594-9ad3-e934e2ea854e) |
|  VR  | ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/4728a63d-1e6e-4cc4-99d7-dfaecae7e8eb) | ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/3e2e3e12-f6ae-4a02-9343-cdc1b99dc535) |
> TextField, TextArea, ComboBox: adopted TextUI in TagArea

- packages/gestalt/src/SelectList/VRSelectList.css
- packages/gestalt/src/TagArea/TagArea.css
- packages/gestalt/src/TagArea/TagArea.tsx
- packages/gestalt/src/TextArea/VRTextArea.css
- packages/gestalt/src/TextField/VRInternalTextField.css
TextArea, TextField, SelectList: adopted TextBody
|---|---|---|
| classic |  ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/f2edc0e6-8391-4764-a9bb-4dc2c0af963d) |  ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/c7c070d3-1802-4ccc-8e99-4828ccb41257) | 
VR |  ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/ba0aec11-4681-4cae-9c7f-d498a143cc7d)  |   ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/9d2248e5-1069-471a-b09f-e7e0c2ae7637)  |
|---|---|---|
| classic    |   |   |
|  VR          | ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/f92f5ec9-842f-4d47-8ff6-3861688dc214) |  ![Screenshot by Dropbox …
> TextArea, TextField, SelectList: adopted TextBody

- docs/examples/searchfield/accessibilityExample.tsx
- docs/examples/searchfield/dontAddCriticalInfoToPlaceholder.tsx
- docs/examples/searchfield/dontTruncateText.tsx
- docs/examples/searchfield/errorExample.tsx
- docs/examples/searchfield/localizationExample.tsx
- docs/examples/searchfield/mainExample.tsx
- docs/examples/searchfield/makePlaceholderSpecific.tsx
- docs/examples/searchfield/makeSearchFieldWide.tsx
- docs/examples/searchfield/placeAboveContent.tsx
- docs/examples/searchfield/sizesExample.tsx
- docs/examples/searchfield/variantsExample.tsx
- packages/gestalt/src/Pog.css
- packages/gestalt/src/SearchField.tsx
- packages/gestalt/src/SearchField/VRSearchField.css
- packages/gestalt/src/SearchField/VRSearchField.tsx
SearchField: VR implementation changes
|   |  classic | VR  |
|---|---|---|
| enabled | ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/9f19de0b-2d14-428f-b72d-e7a52dfe5654) |![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/5a453fc8-0813-4c8f-bbf3-dc55baba02d6)  ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/3f940a63-1beb-4dfd-b304-268f80c46610)  |
| error | ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/82bb3328-446e-435a-8897-8e848dc3883d) |  ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/bb402860-b775-4d96-800f-8f4c2adb12e7)   ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/c5357ff3-335d-4957-bf6a-ee5da1b1f3e9) |
> SearchField: VR implementation changes

- packages/gestalt/src/Popover/Contents.tsx
- packages/gestalt/src/Popover/Controller.tsx
- packages/gestalt/src/Tooltip/InternalTooltip.tsx
Tooltip: implement VR changes
| classic | VR  |
|---|---|
| ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/517798cb-dacc-48ef-bc86-e0630211f68f)  ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/1ff636ae-5c91-49e5-bcf7-035b4fee90b9) |  ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/23b6fb95-30b6-4667-b411-dbcee34739f9) ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/3499d801-7b5a-4233-9549-ca8e990a6598)
> Tooltip: implement VR changes

- packages/gestalt-design-tokens/build.js
- packages/gestalt-design-tokens/tests/__snapshots__/web.test.js.snap
Tokens: removed TOKEN_ prefix from vr tokens in JS
> Tokens: removed TOKEN_ prefix from vr tokens in JS

- packages/gestalt-icons-android/dist/classic/index.d.ts
- packages/gestalt-icons-android/dist/vr-theme/index.d.ts
Internal: updates icon declaration file
> Internal: updates icon declaration file

- docs/pages/web/iconbutton.tsx
- docs/pages/web/iconbuttonlink.tsx
Docs: removed hidden examples for VR
> Docs: removed hidden examples for VR

- packages/gestalt-datepicker/src/DatePicker/VRDateInput.css
- packages/gestalt-datepicker/src/DatePicker/VRDateInput.tsx
- packages/gestalt/src/ComboBox.tsx
- packages/gestalt/src/SelectList/IconEnd.tsx
- packages/gestalt/src/SelectList/VRSelectList.css
- packages/gestalt/src/TextField.tsx
- packages/gestalt/src/TextField/IconButtonEnd.tsx
TextField, DateField, DatePicker: center iconEnd in VR
|            | BEFORE | AFTER |
|------------|--------|-------|
| Textfield  |   ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/7f1e144d-ac28-4e63-9d19-db5e1d9ef3be)     |     ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/b160582d-5042-4cb2-b4a5-2e2f495259cc)  |
| ComboBox   |  ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/697589e7-d93b-4580-b4a0-2604887b4a43)      |   ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/c0685855-29dc-4853-889a-73e7e2424522)     |
| SelectList |    ![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/e351fd0f-efe4-45fe-9316-7a6d44c5bd96)    |    ![Screenshot by Dropbox …
> TextField, SelectList, DateField, DatePicker: center iconEnd in VR

- docs/examples/avatar/colorExample.tsx
- packages/gestalt/src/Avatar/InternalAvatar.tsx
- packages/gestalt/src/__snapshots__/Avatar.test.tsx.snap
- packages/gestalt/src/__snapshots__/AvatarGroup.jsdom.test.tsx.snap
Fix for broken default sizing and color example
> Avatar/AvatarGroup: Fix for broken default sizing on VR

- packages/gestalt/src/SelectList.css
- packages/gestalt/src/SelectList.tsx
- packages/gestalt/src/SelectList/SelectListOption.tsx
- packages/gestalt/src/SelectList/VRSelectList.css
- packages/gestalt/src/SelectList/VRSelectList.tsx
- packages/gestalt/src/__snapshots__/SelectList.test.tsx.snap
SelectList: fix placeholder color
BEFORE
AFTER
BEFORE
AFTER
> SelectList: fix placeholder color

- docs/docs-components/MarkdownPage.tsx
- docs/next-env.d.ts
- docs/package.json
- yarn.lock
This reverts commit 50e68d2fd523eaba4648cebb144fdb4eca8b53c7.
We are encountering issues in production build when navigating.
> Internal: Revert "Internal: Bump next from 12.3.0 to 14.2.10 #3803 (#3807)"

- packages/gestalt/src/PopoverEducational.css
- packages/gestalt/src/PopoverEducational.tsx
- packages/gestalt/src/__snapshots__/PopoverEducational.jsdom.test.tsx.snap
PopoverEducational: fix to color text
> PopoverEducational: fix to color text

- packages/gestalt/src/TextCompact.tsx
- packages/gestalt/src/TextUI.tsx
Docs: updated TextUI TextCompact descriptions
> Docs: updated TextUI TextCompact descriptions

- packages/gestalt/src/Link/InternalLink.tsx
Link: fix aria-selected values for accessibility
> Link: fix aria-selected values for accessibility

- packages/gestalt-datepicker/src/__snapshots__/DatePicker.jsdom.test.tsx.snap
- packages/gestalt/src/Accordion/__snapshots__/ExpandableItem.test.tsx.snap
- packages/gestalt/src/Video/__snapshots__/Controls.test.tsx.snap
- packages/gestalt/src/Video/__snapshots__/Playhead.test.tsx.snap
- packages/gestalt/src/__snapshots__/Accordion.test.tsx.snap
- packages/gestalt/src/__snapshots__/AccordionExpandable.test.tsx.snap
- packages/gestalt/src/__snapshots__/ActivationCard.test.tsx.snap
- packages/gestalt/src/__snapshots__/BannerCallout.test.tsx.snap
- packages/gestalt/src/__snapshots__/BannerOverlay.test.tsx.snap
- packages/gestalt/src/__snapshots__/BannerSlim.test.tsx.snap
- packages/gestalt/src/__snapshots__/BannerUpsell.test.tsx.snap
- packages/gestalt/src/__snapshots__/Box.test.tsx.snap
- packages/gestalt/src/__snapshots__/ComboBox.jsdom.test.tsx.snap
- packages/gestalt/src/__snapshots__/Dropdown.jsdom.test.tsx.snap
- packages/gestalt/src/__snapshots__/SelectList.test.tsx.snap
- packages/gestalt/src/__snapshots__/SheetMobile.jsdom.test.tsx.snap
- packages/gestalt/src/__snapshots__/SideNavigation.test.tsx.snap
- packages/gestalt/src/__snapshots__/Table.test.tsx.snap
- packages/gestalt/src/__snapshots__/TableOfContents.test.tsx.snap
- packages/gestalt/src/__snapshots__/TableRowDrawer.test.tsx.snap
- packages/gestalt/src/__snapshots__/Tabs.test.tsx.snap
- packages/gestalt/src/__snapshots__/Tag.test.tsx.snap
- packages/gestalt/src/__snapshots__/TagData.test.tsx.snap
- packages/gestalt/src/__snapshots__/TextArea.test.tsx.snap
- packages/gestalt/src/__snapshots__/TextField.test.tsx.snap
- packages/gestalt/src/__snapshots__/TileData.test.tsx.snap
- packages/gestalt/src/__snapshots__/Toast.test.tsx.snap
- packages/gestalt/src/__snapshots__/Video.test.tsx.snap
- packages/gestalt/src/boxTransforms.ts
- packages/gestalt/src/transforms.ts
Box: fix rounding bug introduced in #3822
> Box: fix rounding bug introduced in #3822

- packages/gestalt/src/Text.css
> Link: fix link token for Link

- packages/gestalt/src/TextField/VRInternalTextField.css
TextField: TextField VR adjustments\
> TextField: TextField VR adjusments

- docs/examples/selectlist/disabled.tsx
- docs/examples/selectlist/enabled.tsx
- docs/examples/selectlist/error.tsx
- docs/examples/selectlist/helperText.tsx
- docs/examples/selectlist/labelVisible.tsx
- docs/examples/selectlist/labelled.tsx
- packages/gestalt/src/SelectList/IconEnd.tsx
- packages/gestalt/src/SelectList/VRSelectList.css
- packages/gestalt/src/SelectList/VRSelectList.tsx
> SelectList: fixes VR

- docs/examples/searchfield/errorExample.tsx
- docs/examples/searchfield/sizesExample.tsx
- packages/gestalt/src/SearchField/VRSearchField.css
- packages/gestalt/src/SearchField/VRSearchField.tsx
- packages/gestalt/src/sharedSubcomponents/FormErrorMessage.tsx
> SearchField: fix VR issues

- docs/examples/combobox/helperText.tsx
- docs/examples/combobox/subtext.tsx
ComboBox: completed examples for testing
> ComboBox: completed examples for testing

- docs/examples/datefield/main.tsx
- docs/examples/datefield/sizes.tsx
- packages/gestalt-datepicker/src/DateField/VRInternalDateField.css
- packages/gestalt-datepicker/src/DateField/VRInternalDateField.tsx
> DateField: VR fixes

- docs/examples/datepicker/error.tsx
- docs/examples/datepicker/size.tsx
- docs/pages/web/datepicker.tsx
- packages/gestalt-datepicker/src/DatePicker.tsx
- packages/gestalt-datepicker/src/DatePicker/DateInput.tsx
- packages/gestalt-datepicker/src/DatePicker/InternalDatePicker.tsx
- packages/gestalt-datepicker/src/DatePicker/VRDateInput.css
- packages/gestalt-datepicker/src/DatePicker/VRDateInput.tsx
- packages/gestalt-datepicker/src/subcomponents/HelperText.tsx
> DatePicker: VR fixes

- packages/gestalt-datepicker/src/DateField/VRInternalDateField.css
- packages/gestalt-datepicker/src/DatePicker/VRDateInput.css
- packages/gestalt/src/SearchField/VRSearchField.css
SelectList, DatePicker, DateField: fix min heights in VR
> SelectList, DatePicker, DateField: fix min heights in VR

- packages/gestalt/src/Tabs.tsx
Tabs: fixes VR
removing spacing between tabs
> Tabs: fixes VR

- packages/gestalt-icons-android/dist/classic/index.d.ts
- packages/gestalt-icons-android/dist/vr-theme/index.d.ts
> Icon: Update android dist files

- packages/gestalt/src/TextField.tsx
- packages/gestalt/src/TextField/IconButtonEnd.tsx
- packages/gestalt/src/TextField/InternalTextField.css
- packages/gestalt/src/TextField/VRIconButtonEnd.tsx
- packages/gestalt/src/TextField/VRInternalTextField.css
- packages/gestalt/src/TextField/VRInternalTextField.tsx
- packages/gestalt/src/sharedSubcomponents/FormHelperText.css
Textfield: VR layout adjusments
> TextField: VR layout adjusments

- packages/gestalt/src/SelectList/IconEnd.tsx
- packages/gestalt/src/SelectList/VRSelectList.css
- packages/gestalt/src/SelectList/VRSelectList.tsx
- packages/gestalt/src/TextField/VRInternalTextField.css
SelectList: VR fixes to standardize form fields and match them to Figma spacing
BEFORE
AFTER
> SelectList: VR fixes to standardize form fields and match them to Figma spacing

- packages/gestalt/src/SearchField/VRSearchField.css
- packages/gestalt/src/SearchField/VRSearchField.tsx
- packages/gestalt/src/sharedSubcomponents/FormErrorMessage.tsx
SearchField: VR fixes to standardize form fields and match them to Figma spacing
> SearchField: VR fixes to standardize form fields and match them to Figma spacing

- docs/examples/avatar/colorExample.tsx
- docs/examples/avatar/mainExample.tsx
- docs/examples/avatar/noEmojiExample.tsx
- docs/examples/avatar/noImageSourceExample.tsx
- docs/examples/avatarGroup/noEmoji.tsx
- docs/pages/web/avatargroup.tsx
- packages/gestalt/src/Avatar.tsx
- packages/gestalt/src/Avatar/DefaultAvatar.tsx
- packages/gestalt/src/Avatar/Foundation.tsx
- packages/gestalt/src/Avatar/InternalAvatar.tsx
- packages/gestalt/src/Avatar/getAvatarColorToken.ts
- packages/gestalt/src/AvatarGroup.tsx
- packages/gestalt/src/AvatarGroup/CollaboratorAvatar.tsx
BREAKING GHANGE
```
yarn codemod modifyPropValue ~/path/to/your/code
--component=Avatar
--previousProp=color
--previousValue='01'
--nextValue=1
```
```
--component=AvatarGroup
--prop=collaborators
```
From string to numbers:
from 
```color | '01' | '02' | '03' | '04' | '05' | '06' | '07' | '08' | '09' | '10'```
to
```color | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10```
> Avatar,AvatarGroup: Update typing on color prop

- packages/gestalt-datepicker/src/DatePicker/VRDateInput.css
- packages/gestalt-datepicker/src/DatePicker/VRDateInput.tsx
- packages/gestalt-datepicker/src/subcomponents/HelperText.css
- packages/gestalt-datepicker/src/subcomponents/HelperText.tsx
DatePicker: VR fixes to standardize form fields and match them to Figma spacing
> DatePicker: VR fixes to standardize form fields and match them to Figma spacing

- packages/gestalt-datepicker/src/DateField/VRInternalDateField.css
- packages/gestalt-datepicker/src/DateField/VRInternalDateField.tsx
DateField: VR fixes to standardize form fields and match them to Figma spacing
> DateField: VR fixes to standardize form fields and match them to Figma spacing

- docs/examples/buttontoggle/disabled.tsx
- docs/pages/web/buttontoggle.tsx
- packages/gestalt/src/ButtonToggle.css
- packages/gestalt/src/ButtonToggle.tsx
Implemented the fixes requested by Jalena in https://jira.pinadmin.com/browse/GESTALT-8429
To certify the VR implementation for ButtonToggle
- [Jira](https://jira.pinadmin.com/browse/CPW-7487)
- [Figma](https://www.figma.com/design/vjhfBsOtHw0wVg67vqwz1v/Gestalt-for-Web?node-id=33745-3269&m=dev)
> ButtonToggle: VR Certification Fixes

- packages/gestalt/src/ComboBox/Item.tsx
ComboBox: fix in padding after https://github.com/pinterest/gestalt/pull/3822
> ComboBox: fix in padding after  https://github.com/pinterest/gestalt/pull/3822

- packages/gestalt-datepicker/package.json
- packages/gestalt-datepicker/src/DatePicker/InternalDatePicker.tsx
DatePicker: fix for position at the edge
BEFORE
AFTER
> DatePicker: fix for position at the edge

- yarn.lock
> Internal: updated yarn

- packages/gestalt-datepicker/src/DateRange.tsx
DateRange: replace width with minWidth in filter section
> DateRange: replace width with minWidth in filter section

- packages/gestalt/src/Badge.tsx
> Badge: fix VR size icon

- docs/examples/banneroverlay/dismissButton.tsx
- docs/examples/banneroverlay/message.tsx
- docs/pages/web/banneroverlay.tsx
- packages/gestalt/src/BannerOverlay.tsx
- packages/gestalt/src/__snapshots__/BannerOverlay.test.tsx.snap
- packages/gestalt/src/sharedSubcomponents/thumbnailSubcomponents.tsx
BannerOverlay: VR Certification Fixes
> BannerOverlay: VR Certification Fixes

- packages/gestalt/src/BannerCallout/Footer.tsx
- packages/gestalt/src/BannerCallout/HeaderSection.tsx
- packages/gestalt/src/BannerCallout/VRBannerCallout.tsx
- packages/gestalt/src/BannerCallout/useIsWrappedContainer.ts
BannerCallout: responsiveness fixes
BEFORE
AFTER
BEFORE
AFTER
BEFORE
AFTER
> BannerCallout: responsiveness fixes

- docs/examples/searchguide/avatar.tsx
- docs/examples/searchguide/avatargroup.tsx
- docs/examples/searchguide/expandable.tsx
- docs/examples/searchguide/expandableVariants.tsx
- docs/examples/searchguide/icon.tsx
- docs/examples/searchguide/image.tsx
- packages/gestalt/src/SearchGuide.css
- packages/gestalt/src/SearchGuide.tsx
Implemented the fixes requested by Aaron in https://jira.pinadmin.com/browse/GESTALT-8426
To certify the VR implementation for SearchGuide
- [Jira](https://jira.pinadmin.com/browse/CPW-7546)
- [Figma](https://www.figma.com/design/vjhfBsOtHw0wVg67vqwz1v/Gestalt-for-Web?node-id=33915-1282&m=dev)
> SearchGuide: VR certification Fixes

- packages/gestalt/src/Link/InternalLink.tsx
Link: role tab for aria-current === section
> Link: role tab for aria-current === section

- packages/gestalt/src/Divider.css
- packages/gestalt/src/Divider.tsx
- packages/gestalt/src/__snapshots__/AccordionExpandable.test.tsx.snap
- packages/gestalt/src/__snapshots__/Divider.test.tsx.snap
- packages/gestalt/src/__snapshots__/SideNavigation.test.tsx.snap
> Divider: VR adjusments

- packages/gestalt/src/Spinner/VRSpinner.css
- packages/gestalt/src/Spinner/VRSpinner.tsx
- Simplified SVG
- Increased delay between ellipses in intro animation
- [Jira](https://jira.pinadmin.com/browse/GESTALT-8664)
- [Figma](https://www.figma.com/design/pMibC8csfCbNMU4jgLVUJh/Motion-Pilot-specs?node-id=2118-2350&m=dev)
> Spinner: Intro animation refinements

- packages/gestalt/src/List/Message.tsx
- packages/gestalt/src/__snapshots__/List.test.tsx.snap
List: remove color override in Text node
> List: remove color override in Text node

- packages/gestalt/src/BannerSlim.tsx
> BannerSlim: VR

- packages/gestalt/src/TextField/InternalTextField.tsx
ComboBox: fix ref bug issue with tags
> ComboBox: fix ref bug issue with tags

- packages/gestalt-datepicker/src/DatePicker/InternalDatePicker.tsx
Datepicker: fix in onChange event
> DatePicker: fix in onChange event

- packages/gestalt/src/ButtonLink.tsx
- packages/gestalt/src/Link.test.tsx
- packages/gestalt/src/Link.tsx
- packages/gestalt/src/Link/InternalLink.test.tsx
- packages/gestalt/src/Link/InternalLink.tsx
- packages/gestalt/src/Link/__snapshots__/InternalLink.test.tsx.snap
- packages/gestalt/src/__snapshots__/Link.test.tsx.snap
Link/ButtonLink: support for download
> Link/ButtonLink: support for download

- packages/gestalt/src/BannerSlim.tsx
- packages/gestalt/src/BannerSlim/useIsParagraph.ts
- packages/gestalt/src/__snapshots__/BannerSlim.test.tsx.snap
- packages/gestalt/src/__snapshots__/TableRowDrawer.test.tsx.snap
BannerSlim: VR fixes
BEFORE
AFTER
> BannerSlim: VR fixes

- packages/gestalt/src/BannerSlim.tsx
- packages/gestalt/src/__snapshots__/BannerSlim.test.tsx.snap
- packages/gestalt/src/__snapshots__/TableRowDrawer.test.tsx.snap
BannerSlim: VR fixes when message isnt string 
https://capture.dropbox.com/kqK9TwPn9nuKUnmM
> BannerSlim: VR fixes when message isnt string

- packages/gestalt/src/Button.tsx
- packages/gestalt/src/__snapshots__/BannerUpsell.test.tsx.snap
- packages/gestalt/src/__snapshots__/BannerUpsellForm.test.tsx.snap
Button: Fix VR in type=submit
BEFORE
AFTER
> Button: Fix VR in type=submit

- packages/gestalt-charts/package.json
- packages/gestalt-datepicker/package.json
- packages/gestalt/package.json
Upgrading React Version to 19
We need to upgrade Gestalt to be compatible with React 19 in order to be able to upgrade webapp to React 19
- [TDD](https://docs.google.com/document/d/1mOWmj8FAwJ__JL7SoQVli6Ck_0yrVqDN7DUS6j8xYis/edit?tab=t.0#heading=h.qvamkklezmc7)
> Internal: Upgrade React to 19

- packages/gestalt/src/BannerSlim.tsx
- packages/gestalt/src/__snapshots__/BannerSlim.test.tsx.snap
- packages/gestalt/src/__snapshots__/TableRowDrawer.test.tsx.snap
BannerSlim: fix bug with list of children
> BannerSlim: fix bug with list of children

- packages/gestalt/src/BannerSlim.tsx
- packages/gestalt/src/__snapshots__/BannerSlim.test.tsx.snap
- packages/gestalt/src/__snapshots__/TableRowDrawer.test.tsx.snap
> BannerSlim: fix

- packages/gestalt/src/Dropdown/OptionItem.tsx
- packages/gestalt/src/__snapshots__/Dropdown.jsdom.test.tsx.snap
Dropdown: add space to selected check icon
BEFORE
AFTER
> Dropdown: add marginStart to selected check icon

- packages/gestalt/src/Icon/RTLIconList.tsx
Add redo and undo to the RTL icon list
> Icon: Add Re-do and Undo to RTL

- docs/examples/defaultlabelprovider/translations.tsx
- packages/gestalt/src/SearchField.tsx
- packages/gestalt/src/contexts/DefaultLabelProvider.jsdom.test.tsx
- packages/gestalt/src/contexts/DefaultLabelProvider.tsx
SearchField, DefaultLabelProvider: add default accessibility label for clean input button
> SearchField, DefaultLabelProvider: add default accessibility label for clean input button

- packages/gestalt/src/SearchField.tsx
- packages/gestalt/src/SearchField/VRSearchField.tsx
SearchField: support onClear prop
> SearchField: support onClear prop

- packages/gestalt/src/Dropdown.css
- packages/gestalt/src/Dropdown.tsx
- packages/gestalt/src/Dropdown/OptionItem.tsx
- packages/gestalt/src/DropdownSection.tsx
Dropdown: VR changes 1/2
BEFORE
AFTER
> Dropdown: VR changes 1/2

- packages/gestalt/src/BannerSlim.tsx
- packages/gestalt/src/__snapshots__/BannerSlim.test.tsx.snap
- packages/gestalt/src/__snapshots__/TableRowDrawer.test.tsx.snap
> BannerSlim: adjustments

- docs/examples/tabs/icons.tsx
- docs/pages/web/tabs.tsx
- packages/gestalt/src/Tabs.tsx
- packages/gestalt/src/Tabs/Tab.tsx
- packages/gestalt/src/__snapshots__/Tabs.test.tsx.snap
Tabs: support new icon prop #3972
> Tabs: support new icon prop #3972

- docs/examples/banneroverlay/desktop.tsx
- docs/examples/banneroverlay/doEducate.tsx
- docs/examples/banneroverlay/doNavigate.tsx
- docs/examples/banneroverlay/dontStack.tsx
- docs/examples/banneroverlay/main.tsx
- docs/examples/banneroverlay/message.tsx
- docs/examples/banneroverlay/mobile.tsx
BannerOverlay: fix examples with logo
> BannerOverlay: fix examples with logo

- packages/gestalt/src/Checkbox/VRInternalCheckbox.tsx
Checkbox: background fix on VR
> Checkbox: background fix on VR

- packages/gestalt/src/SearchField.tsx
- packages/gestalt/src/SearchField/VRSearchField.tsx
> SearchField: support readOnly

- packages/gestalt/src/SearchField.tsx
- packages/gestalt/src/SearchField/VRSearchField.tsx
> SearchField: support tabIndex

- docs/examples/searchguide/gradient.tsx
- docs/examples/searchguide/main.tsx
- docs/examples/searchguidelink/gradient.tsx
- docs/examples/searchguidelink/main.tsx
- docs/pages/web/searchguide.tsx
- docs/pages/web/searchguidelink.tsx
- packages/gestalt/src/Link/InternalLink.tsx
- packages/gestalt/src/SearchGuide.css
- packages/gestalt/src/SearchGuide.tsx
- packages/gestalt/src/SearchGuideLink.tsx
SearchGuide: support to gradient background + overall fixes
> SearchGuide: support to gradient background + overall fixes

- packages/gestalt/src/SearchField.tsx
- packages/gestalt/src/SearchField/VRSearchField.tsx
> SearchField: VR API fixes

- packages/gestalt/src/TapAreaLink.tsx
TapAreaLink: fix duplication in aria label for target blank
https://jira.pinadmin.com/browse/CPW-7795
> TapAreaLink: fix duplication in aria label for target blank

- docs/examples/combobox/tags.tsx
- packages/gestalt/src/TagArea/TagArea.tsx
ComboBox: fix placeholder width when Tags are used
> ComboBox: fix placeholder width when Tags are used

- packages/gestalt/src/SearchGuide.css
SearchGuides: fix border radius in VR image variant
> SearchGuide: fix border radius in VR image variant

- docs/examples/button/lineclamp.tsx
- docs/examples/buttonlink/lineclamp.tsx
- docs/pages/web/button.tsx
- docs/pages/web/buttonlink.tsx
- packages/gestalt/src/Button.tsx
- packages/gestalt/src/ButtonLink.tsx
- packages/gestalt/src/__snapshots__/ActivationCard.test.tsx.snap
- packages/gestalt/src/__snapshots__/BannerCallout.test.tsx.snap
- packages/gestalt/src/__snapshots__/BannerUpsell.test.tsx.snap
- packages/gestalt/src/__snapshots__/ButtonLink.test.tsx.snap
Button, ButtonLink: support lineClamp
> Button, ButtonLink: support lineClamp

- packages/gestalt/src/SearchGuide.css
- packages/gestalt/src/SearchGuide.tsx
SearchGuides: adjust selected state in Classic
BEFORE
AFTER
> SearchGuide: adjust selected state in Classic

- packages/gestalt/src/IconButtonLink.tsx
IconButton: fix focus ring on visible in VR
> IconButton: fix focus ring on visible in VR

- packages/gestalt-datepicker/package.json
- yarn.lock
> DateField: upgrade dependency

- packages/gestalt/src/Contents.css
- packages/gestalt/src/Popover/Contents.tsx
- packages/gestalt/src/Popover/Controller.tsx
- packages/gestalt/src/Popover/InternalPopover.tsx
- packages/gestalt/src/Tooltip/InternalTooltip.tsx
- packages/gestalt/src/__snapshots__/Dropdown.jsdom.test.tsx.snap
- packages/gestalt/src/__snapshots__/OverlayPanel.jsdom.test.tsx.snap
- packages/gestalt/src/__snapshots__/Popover.jsdom.test.tsx.snap
- packages/gestalt/src/__snapshots__/PopoverEducational.jsdom.test.tsx.snap
Popover: remove border options
> Popover: remove border options

- packages/gestalt/src/ButtonToggle/ColorPicker.tsx
ButtonToggle: color picker supports custom colors
> ButtonToggle: color picker supports custom colors

- docs/examples/chartgraph/doColor.tsx
- docs/examples/chartgraph/doLimit.tsx
- docs/examples/chartgraph/doSameColor.tsx
- docs/examples/chartgraph/dontLimit.tsx
- docs/examples/chartgraph/main.tsx
- packages/gestalt-charts/src/ChartGraph/renderAxis.tsx
- packages/gestalt-charts/src/ChartGraph/renderElements.tsx
ChartGraph: padding adjustments + example fixes
> ChartGraph: padding adjusments + example fixes

- docs/examples/chartgraph/barColumn.tsx
- docs/examples/chartgraph/customLabelBarColumn.tsx
- docs/examples/chartgraph/customLabelBarHorizontal.tsx
- docs/examples/chartgraph/labelBarColumn.tsx
- docs/examples/chartgraph/labelBarHorizontal.tsx
- docs/pages/web/chartgraph.tsx
- packages/gestalt-charts/src/ChartGraph.tsx
- packages/gestalt-charts/src/ChartGraph/BarLabel.tsx
- packages/gestalt-charts/src/ChartGraph/InlineStyle.tsx
- packages/gestalt-charts/src/ChartGraph/renderElements.tsx
ChartGraph: added support to custom labels in bars + new ChartGraph.Label
> ChartGraph: added support to custom labels in bars + new ChartGraph.Label

- docs/examples/avatar/ideasExample.tsx
- docs/examples/avatar/mainExample.tsx
- docs/examples/avatar/nameExample.tsx
- docs/examples/avatar/noEmojiExample.tsx
- docs/examples/avatar/noImageSourceExample.tsx
- docs/examples/avatar/overExample.tsx
- docs/examples/avatar/personExample.tsx
- docs/examples/avatar/shapeExample.tsx
- docs/examples/avatar/sizingExample.tsx
- docs/examples/avatar/verifiedExample.tsx
- packages/gestalt/src/Avatar/InternalAvatar.tsx
- packages/gestalt/src/__snapshots__/Avatar.test.tsx.snap
Avatar: updates to verified icon
https://www.figma.com/design/UqLry0iu1M2sbPjk3Ujfhg/Avatar-and-AvatarGroup?node-id=4-653&m=dev
> Avatar: updates to verified icon

- packages/gestalt/src/TileData.css
- packages/gestalt/src/TileData.tsx
- packages/gestalt/src/__snapshots__/TileData.test.tsx.snap
TileData: removed width and max width definitions
> TileData: removed width and max width definitions

- packages/gestalt/src/RadioGroupButton.css
RadioGroup: fix in CSS file for width
> RadioGroup: fix in CSS file for width

- package.json
- packages/gestalt-codemods/generic-codemods/entry.sh
- packages/gestalt-codemods/generic-codemods/modifyPropValue.ts
- packages/gestalt-codemods/generic-codemods/utils.ts
- yarn.lock
Internal: fixing codemods. they were broke after TS upgrade
> Internal: fixing codemods

- docs/pages/web/buttonsocial.tsx
- packages/gestalt/src/ButtonSocial.tsx
> Button: Fixing docs
