pinterest/gestalt

src/Button/Button.doc.js
src/Checkbox/Checkbox.doc.js
src/Link/Link.doc.js

Currently in the live docs there are a few syntax errors that area stopping the examples from showing up:

Fixes syntax errors in a few live examples

---

src/ExperimentalMasonry/Masonry.js
test/containers/ExperimentalMasonryExample.js

This PR updates Masonry so that it always references `measurementStore` from props instead of `this.measurementStore`.  
Currently the measurementStore is bound to the instance in the constructor.  Because of this, if a new measurementStore is passed in during `componentWillReceiveProps`, we actually end up referencing the wrong measurementStore.

ExperimentalMasonry: Reference measurementStore from props instead of instance

---

package.json
scripts/ghpages.sh

Updating our `package.json` so Netlify can run `yarn run build_docs` instead of the custom webpack command.

Netlify: Live preview with every PR

---

src/Flyout/Flyout.js
src/FlyoutUtils/Contents.js
src/FlyoutUtils/Controller.js

Sometimes design specifications could require the Flyout to extend pass the five standardized sizes. Because the flyout has no method for extending beyond the size, this PR adds a width property to the Flyout component in order to allow the flyout to have custom sizes for when the Flyout must be a different size other than the standardized sizes.
_Pros_
- allows for flexibility in designing components that use the fly-out
- avoids having to add extra sizes for larger fly-outs (i.e. xxl, xxxl, xxxxl)
_Cons_
- less consistency in fly-outs if developers and engineers choose not to use the standardized sizes

Create custom width property for flyout

---

src/Sticky/Sticky.doc.js
src/Sticky/Sticky.js
src/Sticky/__tests__/__snapshots__/Sticky.test.js.snap

Currently, if any element that appears after `Sticky` sets a `position` attribute, it will be stacked on top.  This makes `Sticky` somewhat useless since, most of the time, it will be followed by some sort of scrollable content.  
This PR updates `Sticky` so that, by default, it sets a z-index of 1.  This should handle the 99% case where elements that appear after Sticky set a position attribute, but no z-index.  For the other 1% case where we might have to set a z-index, I've added a `dangerouslySetZIndex` prop.  
cc @PFarejowicz

Sticky: Add zIndex support

---

CHANGELOG.md

- Follows a convention of http://keepachangelog.com/en/1.0.0
- Makes `Unreleased` collapsable: https://github.com/facebook/react/blob/master/CHANGELOG.md
- Add links to docs per release

Internal: Add changelog.md file

---

CHANGELOG.md
src/TextField/TextField.js

We are currently setting state for errorIsOpen in bot handleChange and
componentWillReceiveProps.  This caused the element to render
unnecessarily and lose the cursor location.
Before:
After:

Textfield- Remove duplicate logic opening the error flyout

---

CHANGELOG.md
src/Flyout/Flyout.doc.js

We added this in #16 but didn't update our docs.

Flyout: update docs with correct flowtypes

---

src/TextArea/TextArea.doc.js
src/TextField/TextField.doc.js

I had questions why `TextArea` and `TextField` didn't have `onSubmit` or `autofocus` in the past. Rather than keeping the answers to those questions myself, I figured I'd add it to the docs.

Added explanations for autofocus and onSubmit to TextField/TextArea

---

CHANGELOG.md
docs/src/Box.doc.js
docs/src/Column.doc.js
docs/src/Container.doc.js
docs/src/Flyout.doc.js
docs/src/Heading.doc.js
docs/src/Icon.doc.js
docs/src/Image.doc.js
docs/src/Label.doc.js
docs/src/Letterbox.doc.js
docs/src/Link.doc.js
docs/src/Mask.doc.js
docs/src/Modal.doc.js
docs/src/Text.doc.js
docs/src/Tooltip.doc.js
docs/src/Touchable.doc.js
packages/gestalt/src/Box/Box.js
packages/gestalt/src/Column/Column.js
packages/gestalt/src/Container/Container.js
packages/gestalt/src/Heading/Heading.js
packages/gestalt/src/Image/Image.js
packages/gestalt/src/Label/Label.js
packages/gestalt/src/Letterbox/Letterbox.js
packages/gestalt/src/Link/Link.js
packages/gestalt/src/Mask/Mask.js
packages/gestalt/src/Modal/Modal.js
packages/gestalt/src/Text/Text.js
packages/gestalt/src/Tooltip/Tooltip.js
packages/gestalt/src/Touchable/Touchable.js

Since we upgraded our Flow version, we can now change all these to be the correct Flow type for anything React can render. Also noticed that `<Icon />` doesn't have a `children` prop in the source code so I killed it in the docs as well.

Fix the Flow typing in component and docs for all React children props

---

CHANGELOG.md
packages/gestalt/src/ErrorFlyout/ErrorFlyout.js
packages/gestalt/src/Icon/Icon.js
packages/gestalt/src/Label/Label.js
packages/gestalt/src/Letterbox/Letterbox.js
packages/gestalt/src/Pulsar/Pulsar.js
packages/gestalt/src/Text/Text.js
packages/gestalt/src/Toast/Toast.js
packages/gestalt/src/Tooltip/Tooltip.js

I noticed a few components were missing the same React Proptyping that every other component had so I added those in here.
This change also moves `<Text />` Flow types to a separate `Props` type declaration so it is easier to read.
Lastly, `<Label />` had a mismatch between its Flow types and React Proptypes so I changed the Proptype to match the Flow type

Add React proptying to components that were missing it

---

CHANGELOG.md
packages/gestalt/src/Image/Image.css

Image: Don't show  text when loading the image in Firefox

---

CHANGELOG.md

Realized my `CHANGELOG.md` change was in the wrong place, or it was a bad merge conflict with the reverts yesterday, either way fixing now.

Fix changelog placement for Tabs change

---

CHANGELOG.md
docs/src/index.js

I'm working with this awesome project but because it's using BrowserRouter every time I want to open the docs of a component on a different tab or when I refresh a page that is not the Home I get redirected to https://engineering.pinterest.com/.
Changing the BrowserRouter to  HashRouter will fix this problem.
Thanks for everything!

BrowserRouter -> HashRouter

---

CHANGELOG.md
README.md
scripts/publish.js

Updating the publish script to reflect changes after separation of Gestalt into its own package.

Update publish script for Gestalt

---

packages/gestalt/src/ExperimentalMasonry/Masonry.js
packages/gestalt/src/Masonry/Masonry.js

Currently, Masonry mounts all of the items its going to measure in the top left corner of the grid.  This is totally fine and works, but has the downside that unless a user scroll down, all the items being mounted to the grid are immediately considered to be in the viewport.  
This PR moves the measurement items into a separate div that is rendered below the grid.  Since Masonry measures items one row at a time, this means that as newly measured items get rendered, the "measurement" div will naturally be pushed further down.  
Tested this on mobile + desktop and everything looks 👌

Masonry: Perform measurements "offscreen"

---

CHANGELOG.md
packages/gestalt/src/GroupAvatar/GroupAvatar.js
packages/gestalt/src/GroupAvatar/__tests__/GroupAvatar.test.js
packages/gestalt/src/GroupAvatar/__tests__/__snapshots__/GroupAvatar.test.js.snap

Fix GroupAvatar when there are zero collaborators present.
Looks like:
Fixes #43

A GroupAvatar for nobody

---

CHANGELOG.md
docs/src/components/Navigation.js
docs/src/index.js

In order to fix routing in new tabs we need to use the `history.createHref` function because we chose not to use the `Link` components from `react-router`. The issue was that the href set on the `<a/>` tag did not have the `#` symbol since it was not aware it was inside of a `HashRouter` (which the `history` props knows).
See this for more info: https://github.com/ReactTraining/history/blob/9ff690785f02d5c2554b860ff1a39a6527d18aa1/modules/createHashHistory.js#L176
Solves issue #113

Use createHref from history to make routes and fix navigation in new tabs

---

CHANGELOG.md
docs/src/Masonry.doc.js

I noticed the Masonry docs for the "comp" param were a little misleading, so I provided additional information.

Updated Masonry docs’ “comp” definition.

---

CHANGELOG.md
packages/gestalt/src/Masonry/Masonry.js
packages/gestalt/src/debounce.js
packages/gestalt/src/throttle.js

This PR makes the following changes:
1. I added comments to throttle.
2. I fixed a tiny bug in throttle that was causing longer than intended delays on throttled calls. If a function is throttled to 5 seconds, the first call should happen immediately and another call at 4 seconds should be executed at the 5 second mark. Our throttle function was executing the first one immediately and then starting a new threshold timer at the 4 second mark, so the second call wasn't being executed until 9 seconds (4 + 5).
3. I fixed a subtle bug in Masonry where `handleResize` could be executed after unmount because its timeout wasn't being cleared. I did this by adding a `clearTimeout` method to the function returned by `throttle`.
4. I created `debounce` and switched a couple Masonry methods to use it. …

Made some throttle changes and added debounce

---

CHANGELOG.md
packages/gestalt/src/Switch/Switch.css

**Before**
**After**
Note: I edited the DOM text to force the shrink issue...it doesn't normally sound that dumb...

Disallow flex shrinking for Switch

---

CHANGELOG.md
docs/src/Masonry.doc.js
packages/gestalt/src/ExperimentalMasonry/Masonry.js
packages/gestalt/src/Masonry/Masonry.js
test/containers/ExperimentalMasonryExample.js
test/containers/MasonryExample.js

More cleanup on Masonry. I found an unused prop.

Removed unused “serverRender” prop from Masonry

---

CHANGELOG.md
packages/gestalt/src/FlyoutUtils/Contents.js

IE11 doesn't support `scrollX` and `scrollY` on window which we used when `positionRelativeToAnchor` was set to `false`.
We're using the same patch as React & React Router + made it pass flow:
https://github.com/facebook/react/blob/5d3b12bb3bd6a092cf00ede07b8255a8399c2e58/src/vendor/core/dom/getUnboundedScrollPosition.js#L28
https://github.com/ReactTraining/react-router/pull/607
*Before*
*After*

Flyout: make IE11 compatible

---

CHANGELOG.md
docs/src/Video.doc.js
packages/gestalt/src/Video/Video.js
packages/gestalt/src/Video/VideoControls.js
packages/gestalt/src/Video/__tests__/__snapshots__/VideoControls.test.js.snap

In the initial implementation, `aspectRatio` was hardcoded to 16:9 in the render because that is the industry standard widescreen size. Instead of doing this, we should open this option up to developers to all them to pass in a custom ratio for the placeholder, and only then default to the 16:9 number. This aspect ratio is really only used as a placeholder, similar to `Image` to hold the height while the video loads and we fully know the real width and height.
Also, the fullscreen toggle button should not be exposed if the browser document cannot support the fullscreen API. Instead of doing that check in the callback, we can move the check to the render of the button and hide if for unsupported browsers. One small not here, is this bad for SSR @chrislloyd since document does not exist on …

Adds aspectRatio to Video and hides fullscreen button for unsupported browsers

---

CHANGELOG.md
docs/src/Tooltip.doc.js
docs/src/Touchable.doc.js
packages/gestalt/src/Box/Box.js
packages/gestalt/src/Button/Button.js
packages/gestalt/src/IconButton/IconButton.js
packages/gestalt/src/Touchable/Touchable.js

Noticed that removing these linter suppressions still appeases the linter so they are no longer needed.

Remove unused linter suppressions

---

.eslintrc
CHANGELOG.md
package.json
packages/gestalt/src/Flyout/__tests__/Flyout.test.js
packages/gestalt/src/FlyoutUtils/__tests__/Controller.test.js
packages/gestalt/src/Sticky/__tests__/Sticky.test.js
packages/gestalt/src/Sticky/__tests__/__snapshots__/Sticky.test.js.snap
packages/gestalt/src/TextArea/__tests__/TextArea.test.js
packages/gestalt/src/TextField/__tests__/TextField.test.js
yarn.lock

Adds the [eslint-plugin-jest](https://github.com/jest-community/eslint-plugin-jest) to gestalt and turns on the recommended settings. Puts the jest globals into the environment and fixes any errors from these settings.

Add eslint-plugin-jest with recommended settings

---

CHANGELOG.md
packages/gestalt/src/Masonry/Masonry.js
packages/gestalt/src/Masonry/__integration__/virtualBoundsVisibility.ghost.js
packages/gestalt/src/Masonry/__integration__/virtualBoundsVisibilityWithScrollContainer.ghost.js
test/utils/renderConfig.js

Today we use virtualization to enable a more performant scrolling experience for our masonry users. Unfortunately this does not translate into a good experience for bots. We have seen that virtualization severely limits the number of components a bot can crawl due to removing the components from the DOM. Masonry supports a non-virtualized grid but it stills attempts to hide the component by setting the style to `display: none`. This "faux-virtualization" also severely limits bot crawls and this PR proposes removing this functionality.
This PR will enabled bot crawls on masonry and deliver a truly non-virtual masonry.

Remove faux virtualization (display none on non-visible components)

---

.buildkite/pipeline.yml
.buildkite/steps/test.sh
CHANGELOG.md
package.json
scripts/test.sh
yarn.lock

Jest 22 includes some really interesting change around multi-project running (eslint etc.). This change updates Jest and gets our tests using the multi-project runner.
~~It also upgrades `react-scripts` to the latest version (which I don't think will be a long term change) but latest fixes an issue that conflicted with the parent Jest version. The latest version of `react-scripts` also requires a strict eslint version and seeing as it's a minor it seems fine to downgrade.~~
We don't need up change `react-scripts` anymore because I peg the version we're on seeing as we don't run tests via. `create-react-app` anyway.

Jest 22.4.3

---

.eslintrc
CHANGELOG.md

This change turns on the following rules that are already being followed:
- [import/no-absolute-path](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-absolute-path.md)
- [import/no-duplicates](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md)
- [import/no-named-as-default](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-named-as-default.md)
- [import/no-named-as-default-member](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-named-as-default-member.md)
- [import/no-webpack-loader-syntax](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-webpack-loader-syntax.md)

Turn on linter rules already being followed

---

.eslintrc
CHANGELOG.md
docs/src/components/Example.js

We already list [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react) as a dependency for our package and subscribe to most of the rules. This change turns on the recommended config from that plugin and fixes the one error that arises from doing so. Our settings already turn off the 3 rules we do not follow so this change causes no other errors.

Turn on all recommended react linters

---

CHANGELOG.md
docs/package.json
package.json
packages/gestalt/package.json
test/package.json
yarn.lock

This updates Gestalt to use 16.3.2 and also drops support for React 15 so we can start working with new-style context, portals etc.

React 16.3.2

---

CHANGELOG.md
packages/gestalt/src/Video/Video.css

Previously in fullscreen, the `Video` background would look like this:
With this change, the background is black so that the controls show:

Fix background color for fullscreen video

---

.eslintrc
CHANGELOG.md
dangerfile.js
package.json
yarn.lock

Adds the [eslint-comments](https://github.com/mysticatea/eslint-plugin-eslint-comments) linter as a new plugin for gestalt. This only raised one error in our repo which was fixed by adding an `enable` comment in the file.

Add eslint-plugin-eslint-comments with recommended settings

---

CHANGELOG.md
docs/src/Video.doc.js
packages/gestalt/src/Video/Video.js
packages/gestalt/src/Video/__tests__/Video.test.js
packages/gestalt/src/Video/__tests__/__snapshots__/Video.test.js.snap

Setting `paddingBottom` using the DOM element was causing weird glitches with math operations that set the value to `NaN%`. This change makes the `aspectRatio` required and not defaulted.
@chrislloyd I'm only introducing the required `aspectRatio` here instead of `aspectRatio`, `width`, and `height` so we can keep the resizing fluid for now.

Fix Video sizing with required aspectRatio

---

CHANGELOG.md
packages/gestalt/src/Video/Video.js
packages/gestalt/src/Video/__tests__/Video.test.js

Since the `src` prop on `Video` can be either an array or a string, the shallow `===` check does not work. We need to do a deep comparison of the array contents to verify if the video should indeed be loaded.
This fixes the issue where the video was replaying from the start on interactions.

Fix src check on Video to work for arrays and strings

---

CHANGELOG.md
docs/src/Avatar.doc.js
docs/src/TextField.doc.js

These React example components are not being used in the docs so they can be removed.

Remove dead example code from docs

---

CHANGELOG.md
docs/src/components/App.js
docs/src/components/Link.js

`App` does not need `withRouter` anymore because `Navigation` does not use it. Likewise, `Link` was the only package using `react-router` instead of `react-router-dom` so we can switch those out since the import is the same.

Fix react router dependencies

---

.flowconfig
CHANGELOG.md
docs/package.json
docs/src/Box.doc.js
docs/src/components/PropTable.js

This change fixes all the remaining Flow relate errors with gestalt:
1. Finishes cleaning up the `docs` Flow errors
2. Removes all the Flow ignore folders as they are good to go now
3. Removes `esproposal.class_instance_fields=enable` and `esproposal.class_static_fields=enable` from the config as Flow already defaults to these [values](https://flow.org/en/docs/config/options/#toc-esproposal-class-instance-fields-enable-ignore-warn)
4. Fixes our `NODE_ENV` check in `PropTable` to the correct string

[Flow] Fix Flow errors in docs directory (part 2)

---

CHANGELOG.md
docs/src/Avatar.doc.js
docs/src/Box.doc.js
docs/src/Button.doc.js
docs/src/Card.doc.js
docs/src/Checkbox.doc.js
docs/src/Container.doc.js
docs/src/Divider.doc.js
docs/src/ErrorFlyout.doc.js
docs/src/Flyout.doc.js
docs/src/GroupAvatar.doc.js
docs/src/Heading.doc.js
docs/src/Icon.doc.js
docs/src/IconButton.doc.js
docs/src/Image.doc.js
docs/src/Label.doc.js
docs/src/Link.doc.js
docs/src/Mask.doc.js
docs/src/Pog.doc.js
docs/src/Pulsar.doc.js
docs/src/RadioButton.doc.js
docs/src/Sticky.doc.js
docs/src/Switch.doc.js
docs/src/Tabs.doc.js
docs/src/Text.doc.js
docs/src/TextArea.doc.js
docs/src/TextField.doc.js
docs/src/Toast.doc.js
docs/src/Tooltip.doc.js
docs/src/Touchable.doc.js

Currently the indentation on the code examples in the gestalt docs is off. Examples in the preview look like this:
This change fixes all these collapsed indentations in the docs.

Fix indentation on gestalt doc example code

---

CHANGELOG.md
packages/gestalt/src/ScrollFetch/ScrollContainer.js

Part of #216 
This use case of `componentWillReceiveProps` more closely aligns with https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#reading-dom-properties-before-an-update or https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#side-effects-on-props-change

React async compatible ScrollContainer

---

CHANGELOG.md
packages/gestalt/src/Video/Video.js
packages/gestalt/src/Video/__tests__/__snapshots__/Video.test.js.snap

The `playing` prop covers flipping the video back and forth between being played and being paused, but it breaks on SSR because the browser expects the user to interact with the DOM before the video can play. This means that if for example a user lands on Closeup of a video Pin and `playing` was defaulted to `true`, the video would not actually play until the user starts to click around and clicks play manually (which can lead to inconsistent state issues). By making the `autoPlay` attribute on `video` mirror the `playing` prop on `Video` we can achieve the effect we need of **all** video closeups playing from the get-go regardless of whether they are client navigated from a feed or via a URL.

Fix Video autoplay on SSR on initial render

---

CHANGELOG.md
packages/gestalt/src/Masonry/Masonry.js

Part of #216 followed the state mirroring paradigm talked about here https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#updating-state-based-on-props
Did some testing on both the docs pages and the Masonry playground and both seem to work as expected.

React async compatible Masonry

---

CHANGELOG.md
docs/src/SegmentedControl.doc.js
packages/gestalt/src/SegmentedControl/SegmentedControl.js
packages/gestalt/src/SegmentedControl/__tests__/SegmentedControl.test.js
packages/gestalt/src/SegmentedControl/__tests__/__snapshots__/SegmentedControl.test.js.snap

Even with type `string`, we can still put components in the items array, and it just works.  
In this change, I split the string type and component types.

Change flow type of item in SegmentedControl to support React.Node

---

CHANGELOG.md
package.json
packages/gestalt/src/Video/__tests__/VideoControls.jsdom.test.js

Sets up test files named `*.jsdom.test.js` to only be run in the jsdom environment. Regular `.test.js` files will still be run in both jsdom and node environments.

Add jsdom specific tests for VideoControls

---

CHANGELOG.md
package.json
yarn.lock

Upgrades Stylelint and all its plugins/configs to the latest version. Looks like no breaking changes and no new errors in our codebase https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md

Upgrade stylelint to 9.2.1

---

CHANGELOG.md
README.md

Adds the code coverage badge to the top of the README.md file

Add codecov badge to README

---

CHANGELOG.md
packages/gestalt/src/Card/Card.css
packages/gestalt/src/Layout.css

Fixes https://github.com/pinterest/gestalt/issues/234
Card implicitly uses content-box, but breaks if someone is using * { box-sizing: border-box } for all elements. 
Note: We use content-box to transform: scale with pixels rather than a multiple.

Make Card explicitely use box-sizing: content-box

---

CHANGELOG.md
packages/gestalt/src/Video/Video.js

If server rendered, `onDurationChange` and `onCanPlay` were not being fired off by the native `video` element. By moving the initial setup calls like `setVolume` `setPlaybackRate` and `play` to `componentDidMount` we can make them mirror the other `componentDidUpdate` calls which do similar things since `componentDidMount` is not called on the server. This adds a `video.load()` call in that method as well in order to trigger those missing events on the client which are needed.

Fix server swallowing video events on server render

---

packages/gestalt/src/Masonry/Masonry.js

This PR updates the `key` for measurement nodes so that they don't get reused and ensures that all components being measurement are mounted rather than updated.  
Currently, measurement nodes are reused per column since the key always remains the same so subsequent components go through update phases.  This becomes an issue when components have local state that persists through updates.

fix measurement index

---

CHANGELOG.md
docs/src/GroupAvatar.doc.js
packages/gestalt/src/GroupAvatar/GroupAvatar.js
packages/gestalt/src/GroupAvatar/__tests__/GroupAvatar.test.js
packages/gestalt/src/GroupAvatar/__tests__/__snapshots__/GroupAvatar.test.js.snap

This makes the `size` prop optional on Group Avatar.
I also updated the text sizing to be consistent with the single-collaborator Avatar case.
Before:
After: 
Avatar: 
(The text sizing difference is more obvious if you open the docs from the different versions in 2 tabs and quickly toggle between them.)

Container-based sizing for GroupAvatar

---

CHANGELOG.md
packages/gestalt/src/behaviors/OutsideEventBehavior.js

Change OutsideEventBehavior to capture click early to prevent subcomponents re-rendering and the event.target being removed from the DOM.

Fix OutsideEventBehavior capturing events too late

---

CHANGELOG.md
package.json
yarn.lock

Adds [husky](https://yarnpkg.com/en/package/husky) and [link-staged](https://yarnpkg.com/en/package/lint-staged) packages to help lint files and test components locally before they are checked in so that our CI can do less work. This can pave the way to eventually helping standardize commits or even generating changelogs on the fly. Some example commits:

Gestalt commit hooks for linting and testing

---

CHANGELOG.md
docs/src/Image.doc.js

Fix labels for *Square*, *Wide*, and *Tall* fits and corresponding *contain vs cover* label in Image docs example
**Before**
**After**

Fix Image docs

---

CHANGELOG.md
package.json
yarn.lock

Previously:
Now:
This change fixes 3 of our 5 peer dependency issues by upgrading stylelint and jest-puppeteer to the latest versions.

Fix peer dependency issues in gestalt

---

.flowconfig
CHANGELOG.md
package.json
yarn.lock

Currently we are on flow 0.71.0, this change moves that version to 0.75.0. Luckily no new errors arise from this bump 🙌

Bump Flow version to v0.75.0

---

CHANGELOG.md
docs/src/Layer.doc.js
packages/gestalt/src/Layer.jsdom.test.js
packages/gestalt/src/index.js

This component looks ready for use, so I'm adding documentation here and adding it to the export. I'm going to try it out with our internal `Modal` usage first and after testing it out there will evaluate making gestalt `Modal` use `Layer` itself.

Add docs and export for Layer component

---

CHANGELOG.md
packages/gestalt/src/TextArea.js
packages/gestalt/src/TextArea.test.js
packages/gestalt/src/TextField.test.js
packages/gestalt/src/__snapshots__/TextArea.test.js.snap
packages/gestalt/src/__snapshots__/TextField.test.js.snap

Add hasError prop to `TextArea` (identical to `TextField`)
I have a component which renders errors inline on TextFields (rather than in a flyout) using the hasError prop.  This component is adjacent to TextArea's which do not provide this functionality.  Updating to allow a homogenous UI
Before:
After:

TextArea: Add hasError prop

---

CHANGELOG.md
packages/gestalt/src/Masonry.js

These two cannot use the `instanceof` prop type checker because they are `Symbol`s
https://github.com/pinterest/gestalt/blob/master/packages/gestalt/src/legacyLayoutSymbols.js
We need to use the `PropTypes.symbol` to capture the other two
https://reactjs.org/docs/typechecking-with-proptypes.html

Fix the React prop typing for Masonry

---

CHANGELOG.md
packages/gestalt/package.json

Fixing the react prop type checking for `Masonry` in this dot release

Gestalt 0.76.1 dot release for Masonry fix

---

.flowconfig
CHANGELOG.md
package.json
yarn.lock

No new errors arising from the bump to version 0.77.0

Bump flow version to 0.77.0

---

CHANGELOG.md
flow-typed/npm/filesize_v3.x.x.js
flow-typed/npm/node-fetch_v1.x.x.js

Adds the flow-typed library definitions for the [filesize](https://yarnpkg.com/en/package/filesize) and [node-fetch](https://yarnpkg.com/en/package/node-fetch) packages we use in our danger file.
I am adding this as I will be turning on a flow rule in a followup PR that requires typing on these

Add flow-typed declarations for filesize and node-fetch packages

---

CHANGELOG.md

Gestalt 0.77 has not been released yet since #295 was committed, however, after that, #291 landed which includes the `Collage` component. This updates the Changelog appropriately so we can create a new commit to release off of.

Move 0.77 release up a commit

---

.flowconfig
CHANGELOG.md
packages/gestalt/src/Column.js
packages/gestalt/src/throttle.js

Adds the new [sketchy-number](https://flow.org/en/docs/linting/rule-reference/#toc-sketchy-number) lint rule from Flow as an error and fixes all issues that arise from it.

Turn on sketchy number rule from Flow

---

CHANGELOG.md
packages/gestalt/src/Box.js
packages/gestalt/src/style.js
packages/gestalt/src/transforms.js

Adds proper flow typings to the `transforms.js` file based on the usage which allows us to remove the flow lint disable in `Box.js`

Add flow typing to Box transform functors

---

packages/gestalt/src/Masonry.js
packages/gestalt/src/MasonryInfinite.js
packages/gestalt/src/__integration__/loadMore.integration.js
packages/gestalt/src/__integration__/nullItems.integration.js
packages/gestalt/src/__integration__/reflowItemPropChanges.integration.js
packages/gestalt/src/__integration__/reflowItemPropRemoval.integration.js
packages/gestalt/src/__integration__/scrollFetchOnload.integration.js
packages/gestalt/src/__integration__/serverRenderLayout.integration.js
packages/gestalt/src/defaultLayout.js
packages/gestalt/src/index.js
test/containers/MasonryExample.js

- Pulled fetching out from Masonry
- MasornyInfinite is exported as the old Masonry
and should function the same
- export MasonryBeta as it can be used with custom
fetching logic
- This provides a graceful migration path.
- Final migration will involve renaming
MasonryBeta/MasonryInfinite/Masrony
- Existing Masonry integration will be testing MasonryInfinite to ensure
compatibility

Masonry: MasonryInfinite for infinite fetching

---

packages/gestalt/src/Masonry.js
packages/gestalt/src/Masonry.jsdom.test.js
packages/gestalt/src/__integration__/scrollFetchOnload.integration.js
packages/gestalt/src/__snapshots__/Masonry.jsdom.test.js.snap

Masonry: update state so it matches when items prop is updated

---

CHANGELOG.md
packages/gestalt/src/SelectList.js
packages/gestalt/src/TextArea.js
packages/gestalt/src/TextField.js

 TextField / TextArea / SelectList: Fix issue with flyout when errorMessage is set

---

.flowconfig
CHANGELOG.md
package.json
yarn.lock

Upgrading this package to match the version we are using internally. Seems to be no errors so its a smooth upgrade.

Bump flow to 0.81.0

---

CHANGELOG.md
docker-compose.yml

I added `greenkeeper-lockfile` in #327 but it hasnt been able to successfully write to github because of a known hosts issue, I'm curious if its because I forgot to add the token name here to the docker file since I only listed it in the buildkite pipeline file.
I wonder if its possible forgetting to list the ENV variable in the `docker-compose` file made the greenkeeper commands on buildkite fail as such:

Add forgotten env variable to docker-compose file

---

.buildkite/pipeline.yml
CHANGELOG.md
docker-compose.yml

Greenkeeper lockfile updating is still failing and the best result I could find online is this https://github.com/greenkeeperio/greenkeeper-lockfile/issues/206 I am following the suggestion to expose and set these variables (even though they should be defaulted) in the hopes it finally works.

Add in env variables for git email and username for greenkeeper

---

CHANGELOG.md
packages/gestalt/rollup.config.js
test/webpack.config.js

When attempting to add `react-virtualized` in my Masonry9 branch, I ran into issues where the test package would explode. Turns out, it was trying to babelify all node_modules. This PR excludes node_modules in both the Gestalt package and test.
See exact problem and recommended solution here:
https://github.com/bvaughn/react-virtualized/issues/1112

Exclude node_modules from babelification

---

CHANGELOG.md
packages/gestalt/src/Pulsar.css

Updating Pulsar animation to one that causes the ring to be invisible, so as to allow full visibility of any content underneath.

Updating Pulsar animation

---

CHANGELOG.md
packages/gestalt/src/icons/index.js
packages/gestalt/src/icons/text-align-center.svg
packages/gestalt/src/icons/text-align-left.svg
packages/gestalt/src/icons/text-align-right.svg

New icons added:
```
text-align-center: packages/gestalt/src/icons/text-align-center.svg
text-align-left: packages/gestalt/src/icons/text-align-left.svg
text-align-right: packages/gestalt/src/icons/text-align-right.svg
```

Add new icons for text alignment

---

CHANGELOG.md
docs/src/Flyout.doc.js
docs/src/Tooltip.doc.js
packages/gestalt/src/Flyout.js

Tooltip basically does the same things as `Flyout`, lets move that one differentiator into `Flyout` so we can deprecate it later.
Migration plan:
- Add `Tooltip` unique props to `Flyout` which is only the `color` and update docs (this change)
- Release gestalt with this new ability
- Migrate all client calls to use the new `Flyout` once gestalt is bumped
- Remove `Tooltip` from codebase
- Release the next version of gestalt without `Tooltip`

Add Tooltip abilities to Flyout for future deprecation

---

CHANGELOG.md
packages/gestalt/package.json

This migrates gestalt to `React 16.6`

Bump gestalt version to 0.83.0

---

CHANGELOG.md
packages/gestalt/src/__integration__/optimizedRemount.integration.js

When we upgraded to React 16.6 with #406, it exposed an issue with our integration tests where Jest was terminating early without finishing all asserts. This diff fixes that by adding more `waitFor` to ensure Masonry fully renders and also a deterministic termination in the Jest test.

Fixed flakey integration test

---

CHANGELOG.md
docs/src/Masonry.doc.js

Made a few additions/edits to Masonry docs in response to @rootvar's comments about lack of clarity on Masonry props.

Updated Masonry docs to have better prop descriptions

---

CHANGELOG.md
packages/gestalt/src/Tabs.js

PR #368 changed tab keys to use only `href`. This is technically correct, but didn't work out in practice. In a perfect world, `href` would either be required and tabs would use A tags, or `href` would be removed and tabs would use buttons. In the meantime, we're using tabs in both ways all over and using `href` as the key resulted in a lot of key collisions where key was `""`.

Updated tabs key to be a composite of index and href

---

CHANGELOG.md
packages/gestalt/src/Masonry.js

About a week ago, I added a new prop to Masonry called `onFinishedRendering` to better help with integration tests. After talking with Chris and taking another run at tests, I've chosen to remove it. The DOM serves as a better source of truth to integration tests than an event system ever could.

Removed Masonry onFinishedRendering

---

packages/gestalt-codemods/0.85.0-0.86.0/deprecate-tooltip.js

Forgot to add the `size="md"` prop to the codemod if no size was previously set

Fix the codemod for deprecating tooltip

---

CHANGELOG.md
packages/gestalt/package.json

Deploying the backlog of features that landed in gestalt over holiday break

Bump gestalt from 0.85 to 0.86

---

CHANGELOG.md
packages/gestalt/src/Box.js

Makes `<Box>` maintain its old display name in tests and dev tools

Fix display name for Box

---

CHANGELOG.md
packages/gestalt/package.json

Patch release to fix the naming issue in tests to reduce churn

Patch release gestalt 0.86.1

---

CHANGELOG.md
docs/src/Box.doc.js

Gestalt v0.86.0 implemented `React.forwardRef()` so this updates the docs to avoid confusion

Update documentation for Box to mention new ref forwarding

---

docs/src/Text.doc.js
docs/src/components/Card.js
docs/src/components/Example.js
docs/src/components/PropTable.js

I often find myself looking at the table of props for each component, then scrolling down to find an example usage for that prop.  This adds the ability to make the name of a prop a link which scrolls to the relevant example on the page.
This is a little hacky atm.  I tried just wrapping the name of the prop in a `<Link href="#someId"/>` but I end up getting navigated to `/#/someId` instead of scrolling to the element with associated id.

Make <PropTable/> in docs link to <Example/>'s

---

CHANGELOG.md
docs/src/SegmentedControl.doc.js
packages/gestalt-codemods/0.88.0-0.89.0/segmented-control-responsive-widths.js
packages/gestalt/src/SegmentedControl.js
packages/gestalt/src/SegmentedControl.test.js
packages/gestalt/src/__snapshots__/SegmentedControl.test.js.snap

Per the [design spec](https://design.pinadmin.com/pds/#segmented-controls), the width of each item in a segmented control should be the same, rather than based on what's inside of the segmented control item.
~I added an optional prop `equalWidths`. If it's true, the segmented control items would have equal widths.~
**UPDATE**: Before this PR, the items in `<SegmentedControl>` have width responsive to their content. After this PR is merged, the items in `<SegmentedControl>` will have equal width by default and will be adhere the design spec. To use the old behavior, pass the optional prop `responsive`.
~I am including an example in the doc that shows the side-by-side comparison between responsive width (default) and the equal/fixed widths.~
**UPDATE**: I am including an example in the doc …

<SegmentedControl /> should have equal item widths by default

---

CHANGELOG.md
packages/gestalt/package.json

This release includes flow upgrade #479
Breaking change:
- `Layer`: the `children` prop is now a required prop

Bump gestalt to 0.90.0

---

CHANGELOG.md
packages/gestalt/src/Borders.css
packages/gestalt/src/Button.css
packages/gestalt/src/Button.js
packages/gestalt/src/Button.test.js
packages/gestalt/src/__snapshots__/Button.test.js.snap

Design has updated their standard regarding button border radius
When a button is inline render it with a border radius of 8px
When a button is full width render it with a border radius of 12px
- [N/A] Documentation
- [✔️] Tests
- [N/A] Experimental evidence (required for Masonry changes)

Update <Button/> border radius

---

CHANGELOG.md
docs/src/Button.doc.js
docs/src/Checkbox.doc.js
docs/src/Collage.doc.js
docs/src/Flyout.doc.js
docs/src/Heading.doc.js
docs/src/Icon.doc.js
docs/src/IconButton.doc.js
docs/src/Image.doc.js
docs/src/Mask.doc.js
docs/src/Modal.doc.js
docs/src/Pog.doc.js
docs/src/SelectList.doc.js
docs/src/Switch.doc.js
docs/src/TextArea.doc.js
docs/src/TextField.doc.js
docs/src/Toast.doc.js
docs/src/Touchable.doc.js
docs/src/Video.doc.js

Add links from the propTable to the relevant examples in component documentation.

Docs: Add links to remaining component propTables

---

CHANGELOG.md
packages/gestalt/src/Contents.css

Spoke to @collino and we are going to keep the shadow on the flyout at all times regardless of focus.

Add flyout shadow regardless of focus

---

CHANGELOG.md
packages/gestalt/src/Avatar.js
packages/gestalt/src/__snapshots__/Avatar.test.js.snap

We were getting reports of a bug (BUG-90851 internally) where the Avatar component was being displayed incorrectly on Edge when there was no image available (and thus the first initial was displayed). MS Edge doesn't support dominantBaseline in SVGs, so the text was being pinned to the top of the container.
This PR fixes the issue by repositioning the text based on line height. It appears to look good on all Avatar sizes.

Updated Avatar to avoid Edge’s lack of support for SVG dominantBaseline

---

CHANGELOG.md
docs/src/Modal.doc.js
packages/gestalt/src/Modal.js

Makes this component more closely align with what we do for Flyouts by allowing an back door custom sizing option https://github.com/pinterest/gestalt/blob/master/packages/gestalt/src/Flyout.js#L14

[Modal] Add an escape hatch size option to Modal for custom sizes

---

CHANGELOG.md
docs/src/Modal.doc.js
packages/gestalt/src/Modal.js

This opens the Modal `heading` prop up for more extensibility similar to the `footer` prop

Make Modal heading an overloaded prop to accept react elements

---

CHANGELOG.md
docs/src/Tooltip.doc.js
packages/gestalt/src/Tooltip.js
packages/gestalt/src/__snapshots__/Tooltip.jsdom.test.js.snap

Removing the focus behaviors of tooltips

Show tooltips only on hover (not focus)

---

CHANGELOG.md
docs/src/TextField.doc.js
packages/gestalt/src/TextField.js

Add `new-password` prop value for `autocomplete` on TextFields to make it possible for browsers to suggest strong passwords.

Update TextField to take new-password as a prop value for autocomplete

---

.flowconfig
package.json
packages/gestalt/src/Box.js
packages/gestalt/src/Contents.js
packages/gestalt/src/Masonry.js
packages/gestalt/src/MasonryBeta.js
packages/gestalt/src/MasonryInfiniteBeta.js
packages/gestalt/src/MeasurementStore.js
packages/gestalt/src/Tooltip.js
packages/gestalt/src/defaultLayout.js
packages/gestalt/src/fullWidthLayout.test.js
packages/gestalt/src/uniformRowLayout.test.js
yarn.lock

https://github.com/facebook/flow/releases/tag/v0.96.0

Upgrade to flow v0.69.0

---

CHANGELOG.md
docs/src/IconButton.doc.js
packages/gestalt/src/IconButton.css
packages/gestalt/src/IconButton.js
packages/gestalt/src/IconButton.test.js
packages/gestalt/src/__snapshots__/IconButton.test.js.snap

Stop gap solution to introduce `disabled` prop to `<IconButton />` until we get a more cohesive unified solution to buttons.

Disabled IconButton states

---

CHANGELOG.md
packages/gestalt/src/SegmentedControl.css

Design request to make the outer border radius 8px (which means 6px inner radius for the white selected state)

Update segmented control border radius to match new design spec

---

CHANGELOG.md
docs/src/Spinner.doc.js
packages/gestalt/src/Spinner.css
packages/gestalt/src/Spinner.js
packages/gestalt/src/Spinner.test.js
packages/gestalt/src/__snapshots__/Spinner.test.js.snap

Sometimes we show a `<Spinner>` as part of an 'educational loading state' that has a minimum display time determined by the client. In these cases `<Spinner>`'s built in delay results in a distracting flickering as it appears 300ms after the rest of 'educational loading state' component renders. E.g.
This change provides a way to remove the 300ms delay to display from `<Spinner>` for use in these cases.

Add delay prop to Spinner

---

CHANGELOG.md
packages/gestalt/src/Borders.css
packages/gestalt/src/Button.css
packages/gestalt/src/Button.js
packages/gestalt/src/Button.test.js
packages/gestalt/src/__snapshots__/Button.test.js.snap

Design has abandoned their spec where inline and full width buttons have different border radii and height.  Removing logic for changing button border radius depending on the inline prop.  All buttons will now have a border radius of 8px

Button- Make the border radius 8px regardless of button width

---

docs/src/Icon.doc.js
docs/src/IconButton.doc.js
docs/src/Pog.doc.js
packages/gestalt/src/Icon.js
packages/gestalt/src/IconButton.js
packages/gestalt/src/IconButton.test.js
packages/gestalt/src/Pog.js
packages/gestalt/src/Pog.test.js
packages/gestalt/src/__snapshots__/IconButton.test.js.snap
packages/gestalt/src/__snapshots__/Pog.test.js.snap

Adding custom icons to gestalt seems to be the source of a great deal of friction.  This change allows you to use `dangerouslySetSvgPath` in `IconButton` (and `Pog`).  Previously we supported this for `Icon` but not `IconButton`.  
One downside of this implementation is that previously `Icon` had type checking that would require `icon` _or_ `dangerouslySetSvgPath` but not both. For this change, I was unable to arrive at a good solution, so made both `icon` and `dangerouslySetSvgPath` optional props in `IconButton`, `Pog` and `Icon`.  
As a result, a user _could_ create one of the these components and fail to pass `icon` or `dangerouslySetSvgPath`.  In this case they would not receive a flow error (and we'd render an empty path in `Icon`).  However, this does not seem like a huge risk …

 Allow dangerouslySetSvgPath in IconButton

---

CHANGELOG.md
packages/gestalt/src/SegmentedControl.css

Previously when using `Tooltip` inside of a `SegmentedControl` clicking on the buttons would cause the flyout to go bonkers because of this little bit of CSS that changes the position attribute.
Removing it seems to fix the issue and it looks like nothing needed the position relative when focused
Before:
After:

Fix tooltips when used inside a segmented control

---

CHANGELOG.md
packages/gestalt/src/SearchField.js

- Remove the white background color of SeachField to make it can be used on background which has color other than white without the weird white sharp corner.
Before:
After:

Remove the white background of the outer box of SearchField

---

CHANGELOG.md
docs/src/Box.doc.js
packages/gestalt/src/Box.js
packages/gestalt/src/Layout.css

Enable the use of `space-evenly` with `justify-content` and `align-content` on `Box`.
Support looks reasonable:
https://caniuse.com/#search=space-evenly

[Box] Allow `justifyContent` and `alignContent` props to be passed `evenly` as a value

---

CHANGELOG.md
docs/src/Spinner.doc.js
packages/gestalt/src/Spinner.js
packages/gestalt/src/Spinner.test.js
packages/gestalt/src/__snapshots__/Spinner.test.js.snap

Add the `size` prop for the Spinner. The value of `size` can be the following: `"xs" | "sm" | "md" | "lg" | "xl"`.
`size="sm"`
No `size` prop present (size defaults to `"md"`)

Add the size prop to Spinner

---

.eslintrc
CHANGELOG.md
packages/gestalt/src/Contents.js
packages/gestalt/src/Controller.js

In order to prepare for an upgrade to React 17, we need to rename `componentWillReceiveProps` to `UNSAFE_componentWillRecieveProps`.
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#gradual-migration-path

Update componentWillReceiveProps to UNSAFE_componentWillReceiveProps

---

CHANGELOG.md
docs/src/IconButton.doc.js
docs/src/Pog.doc.js
packages/gestalt/src/IconButton.js
packages/gestalt/src/Pog.css
packages/gestalt/src/Pog.js

Adding blue as an allowable prop for IconButton and Pog bgColor (background color), and setting the default color combination for blue background color and white icon for Pog, and updating CHANGELOG

Adding blue background color to Icon Button and Pog

---

CHANGELOG.md
packages/gestalt/src/Masonry.js

When comparing Gestalt's Masonry (Masonry8) with Masonry9, I stumbled on a bug in Masonry8. The bug is that a single `MeasurementCache` gets created when `defaultProps` are defined, and then this same `MeasurementCache` is used for _all_ grids that don't specify their own `measurementCache` via props. This means, since the `defaultProps` are static and live outside any instance of a component, the cache is shared across grids and it's never cleared, even when grids are unmounted.
This PR fixes the issue by turning `measurementCache` into an unmanaged prop and pulling it into `state` on component construction. While I tend not to like unmanaged props (especially when they're not named something like `initialMeasurementCache` or `defaultMeasurementCache`), I think this is the simplest …

Fixed memory leak in Masonry’s measurementStore

---

packages/gestalt/src/Masonry.js

I accidentally broke the build with my latest push to fix Masonry. Flow didn't catch the issue, but it didn't build. This PR fixes the types and passes the build.
Why wasn't this caught when I originally pushed my Masonry PR? It… was. I just failed to understand that I was using admin privileges to override the error when I really thought I was doing the normal push.

Fix Masonry types

---

CHANGELOG.md
packages/gestalt/src/Contents.js
packages/gestalt/src/Controller.js

As part of the React 17 readiness effort, we're doing our best to remove/refactor the deprecated lifecycle methods. In PR #566, we renamed the only remaining occurrences of these methods to use the `UNSAFE_` prefix. This diff follows this up by killing those methods outright, and instead migrating to `getDerivedStateFromProps`.
To test, I used the docs page to verify the Flyouts and Tooltips (both of these use Controller/Contents) still worked as intended. I also triggered props changes and validated that things work. Lastly, I validated that the snapshot test did not change.

Removed unsafe lifecycle methods from Controller/Contents

---

CHANGELOG.md
packages/gestalt/src/ScrollFetch.js

With #569, we updated the way ScrollFetch specifies default props to use `static` instead of setting an object after the class definition. This was functionally the same, but flow interpreted them differently. Specifically: flow is now covering these defaults whereas it wasn't before. Unfortunately, this didn't get exposed until we tried to import Gestalt v106 into pinboard.
This diff attempts to fix the default prop type. Unfortunately, I don't know how to test it other than to land it and pull it down from there.

Fix flow types on ScrollFetch

---

.flowconfig
CHANGELOG.md
packages/gestalt/src/VideoControls.js

https://flow.org/en/docs/config/options/#toc-include-warnings-boolean
Makes sure that we're not accidentally adding new flow warnings to gestalt.

Internal: include flow warnings in error output

---

.github/workflows/publish.yml
CHANGELOG.md

In the past we had to manually run `./scripts/publish.js` which was painful since you've had to set up your npm / yarn and GitHub permissions. 
With this PR, we will automatically publish to npm and update GitHub pages whenever we create a new version tag. Please check out the [successful build & npm release for the `gestalt-copy` package](https://github.com/christianvuerings/gestalt-copy/commit/4516c8a82d386033f2e354e2ed09c722f983ff51/checks?check_suite_id=365763646)
Follow up after we've tested publishing through CI:

Internal: Perform releases with GitHub CI

---

docs/src/IconWithTooltip.doc.js
packages/gestalt/src/IconWithTooltip.js
packages/gestalt/src/IconWithTooltip.jsdom.test.js
packages/gestalt/src/IconWithTooltip.test.js
packages/gestalt/src/__snapshots__/IconWithTooltip.test.js.snap
packages/gestalt/src/index.js

Background: We have an initiative to push for in product education within the sterling codebase in H1 that requires a tooltip on an info-icon hover with support for a "Learn More" link.
Proposed: We don't want to support this for all our Tooltips so this new IconWithTooltip component will allow us to be very specific in the implementation. PDS approved it for the info-icon specifically- i'm leaving the icon assignment flexible for others' use cases.
~Open question: accessibility standards. I had one suggestion to make the tooltip visible on focus in addition to on hover. Is this sufficient?~
*Updated behavior with focus and blur*

Add IconWithTooltip component and tests

---

.gitignore
CHANGELOG.md
packages/gestalt/src/IconWithTooltip.js

- Accessibility improvement: add `tabIndex=0` to the `Box` surrounding the tooltip. That way, keyboard navigation to the tooltip is possible
- Convert `IconWithTooltip` to hooks

IconWithTooltip: Improve accessibility and convert component to hooks

---

.github/workflows/publish.yml
CHANGELOG.md

When we push to `gh-pages` via GitHub Workflows, the GitHub Pages don't get updated. This is a workaround to make sure a Github Pages build gets triggered.
https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/m-p/43192/highlight/true#M5281

Internal: Fix publish to GitHub pages

---

CHANGELOG.md
packages/gestalt/src/Masonry.js

This PR sets up an experimental flag `fixFetchMoreBug` that fixes a bug in Masonry. Because Masonry is the bread and butter of Pinterest, we can't simply fix the bug -- we need to measure the effects of the fix and decide if we should investigate a further change.
Here's the issue:
Let's say we have 1000px of content and Masonry is configured to fetch more content when the user scrolls within 200px of the bottom. The user will start scrolling, and as soon as the user gets 800px down the screen, it will fetch more. Masonry will do this perfectly by measuring the scroll position and the content height (along with the height of the user's viewport).
Now, let's say we have a header above Masonry that's 15000px tall. This means the user would have to scroll 14800px before we need to fetch more …

Add flag for fixing “fetch more” bug

---

README.md

@christianvuerings did a great job in updating our publishing flow to use GitHub Actions. This updates the publish instructions in the README to detail the new flow.

Update README to reflect GitHub Actions publishing

---

CHANGELOG.md
docs/src/Flyout.doc.js
docs/src/Modal.doc.js
docs/src/Toast.doc.js

Fixes ticket #630 by adding `Layer` tags around `Modal`, `Toast`, and `Flyout` in the examples. I also refactored some of the docs to hooks while I was in there

Fix documentation overlap issues

---

CHANGELOG.md
packages/gestalt/src/Masonry.js

Reverting the last change to add longer throttling to Masonry scrolling (#641) based on the advice of @bishwei and @chrislloyd. We can revisit this with an experiment or punt until the rewrite of Masonry lands.

Reverted Masonry throttle change

---

CHANGELOG.md
packages/gestalt/src/Masonry.js

Following the results of internal experimentation (see web_fix_masonry_fetchmore_bug), I decided it's fine to ship this fix. This will cause Masonry to fetch less aggressively on pages where there's lots of content inside the scroll container above Masonry. An example of this is the Pinterest Pin Closeup page.

Ship "fixFetchMoreBug”

---

CHANGELOG.md
packages/gestalt/package.json

- Color: update dark gray color to #111 (#648)
- Masonry: Shipped "fixFetchMoreBug" behavior and removed flag. This makes Masonry fetch less aggressively in some cases. (#651)

Bump version to v0.123.0

---

CHANGELOG.md
packages/gestalt/package.json

- Box: Add new prop `opacity` to set css opacity with values 0 to 1 in tenth increments. (#654)
- Button: Update border radius / small size + add dark gray option (#655)

Version bump: 0.124.0

---

CHANGELOG.md
docs/src/Button.doc.js
docs/src/IconButton.doc.js
docs/src/Pog.doc.js
docs/src/components/PropTable.js
packages/gestalt/src/Button.css
packages/gestalt/src/Button.js
packages/gestalt/src/IconButton.js
packages/gestalt/src/Pog.css
packages/gestalt/src/Pog.js

We decided to go for a selected state instead of a `darkGray` color option:
* It makes the intent of this new color more explicit
* Allows us to easily update the selected state moving forward
```js
<Button color={selected ? 'darkGray' : 'gray' } text="Show info" />
```
```js
<Button selected={selected} text="Show info" />
```

Button/IconButton/Pog: Convert 'darkGray' color to selected state

---

CHANGELOG.md
packages/gestalt/src/Contents.css
packages/gestalt/src/Flyout.js
packages/gestalt/src/__snapshots__/Flyout.jsdom.test.js.snap

This PR updates Flyout to the Lego spec:
- Remove caret
- Update shadow
- Update border radius

Flyout: Remove caret, update shadow

---

CHANGELOG.md
packages/gestalt/package.json

- Masonry: Allow string enum types for Masonry layout prop (in prep of removing symbols/classes) (#667)

Version bump: 1.1.0

---

CHANGELOG.md
packages/gestalt/package.json

- Internal: Update dependencies (#671)
- Heading: removed unused weight prop from docs (#653)

Version bump 1.2.0

---

packages/gestalt/src/Layout.css

My mistake, landed this as part of #676 where I changed `borderBox` to `borderBoxs` to test the feature. Looks like it's working...

Internal: fix master build

---

CHANGELOG.md
CODE_OF_CONDUCT.md
docs/src/components/App.js

In order to qualify for Netlify's open source plan, we need to add a Code of Conduct + a powered by Netlify link

Internal: Add code of conduct & powered by netlify link

---

CHANGELOG.md
packages/gestalt/package.json

- Box: Add `borderSize` prop for styling borders (#678)
- Modal: visual refresh + heading optional + add closeOnOutsideClick (#680)
Codemods:
`cd gestalt; yarn run codemod --parser=flow -t=packages/gestalt-codemods/1.3.0-1.4.0/modal-remove-close-label.js ~/code/repo`

Version bump 1.5.0

---

CHANGELOG.md
yarn.lock

Before we were seeing the following error after the Node.js 12 upgrade:
```
warning Error running install script for optional dependency: "/Users/cvuerings/code/gestalt/node_modules/chokidar/node_modules/fsevents, /Users/cvuerings/code/gestalt/node_modules/watchpack/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments:
Directory: /Users/cvuerings/code/gestalt/node_modules/chokidar/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.0
node-pre-gyp info using node@12.14.1 | darwin | x64
node-pre-gyp info check checked for \"/Users/cvuerings/code/gestalt/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET …
```

Internal: update yarn.lock file

---

CHANGELOG.md
packages/gestalt/package.json

Internal: Update Node.js version to 12.x (#686)
Internal: update yarn.lock file (#687)

Version bump 1.6.0

---

CHANGELOG.md
packages/gestalt/src/Button.css

Before the spacing `left/right` was `14px`, now it's `12px` which is the same as our Figma files. Design signed off on these changes.
Before: https://deploy-preview-688--gestalt.netlify.com/#/Button
After: https://deploy-preview-689--gestalt.netlify.com/#/Button

Button: update horizontal padding to 12px

---

CHANGELOG.md
docs/src/Flyout.doc.js
packages/gestalt/src/Caret.js
packages/gestalt/src/Caret.test.js
packages/gestalt/src/Contents.css
packages/gestalt/src/Contents.js
packages/gestalt/src/Contents.test.js
packages/gestalt/src/Controller.js
packages/gestalt/src/Flyout.js
packages/gestalt/src/IconWithTooltip.js
packages/gestalt/src/Masonry.js
packages/gestalt/src/Tooltip.js
packages/gestalt/src/__snapshots__/Caret.test.js.snap
packages/gestalt/src/__snapshots__/Controller.jsdom.test.js.snap
packages/gestalt/src/__snapshots__/Flyout.jsdom.test.js.snap

[Revert] Masonry: Allowing string enums for Masonry layout
[Revert] Flyout: Update spacing around items to 8px + remove caret code

Revert bad Masonry and Flyout commits

---

CHANGELOG.md
packages/gestalt/package.json

- Button: update horizontal padding to 12px (#688)
- [Revert] Flyout: Update spacing around items to 8px + remove caret code (#668)
- [Revert] Masonry: Allow string enum types for Masonry layout prop (in prep of removing symbols/classes) (#667)

Version bump: 1.7.0

---

CHANGELOG.md
packages/gestalt/package.json

- Text / Heading [Breaking]: Added codemod to support breaking changes from #693 (removed support for responsive size prop values smSize, mdSize, and lgSize in Text and Heading component) (#696)
- Heading / Text [Breaking]: Reduce size options from xs-xl to sm-lg (#693)
Run codemods for breaking changes in order:
1. `cd gestalt; yarn run codemod --parser=flow -t=packages/gestalt-codemods/1.8.0-1.9.0/remove-responsive-text-sizing.js ~/code/repo`
2. `yarn run codemod --parser=flow -t=packages/gestalt-codemods/1.8.0-1.9.0/heading-size-replace.js ~/code/repo`
3. `yarn run codemod --parser=flow -t=packages/gestalt-codemods/1.8.0-1.9.0/text-size-replace.js ~/code/repo`

Update version to 1.9.0

---

CHANGELOG.md
docs/src/Modal.doc.js

I got the default value wrong in our docs in #680

Modal: [Docs] Fix default value for closeOnOutsideClick

---

CHANGELOG.md
README.md
package.json

Removed references and script to run already deprecated integrations tests.
- [x ] Documentation
- ~~[ ] Tests~~
- ~~[ ] Experimental evidence (required for Masonry changes)~~
- ~~[ ] Accessibility checkup~~

Docs: Remove references to integrations tests

---

CHANGELOG.md
packages/gestalt/package.json

- Text / Heading: Made typography changes more backwards-compatible by adding xl size back in as deprecated feature (#707)

Release 1.10.1

---

CHANGELOG.md
docs/src/Flyout.doc.js
packages/gestalt/src/Flyout.js

We have a request to make `caret` optional - we do leave the default `false`

Flyout: Make caret optional

---

CHANGELOG.md
packages/gestalt/package.json

- SelectList / TextField / TextArea: Add `label` and `helperText` props (#705)
- Flyout: Make caret optional (#706)

Version bump: 1.11.0

---

CHANGELOG.md
packages/gestalt/src/Tooltip.js
packages/gestalt/src/Tooltip.jsdom.test.js
packages/gestalt/src/__snapshots__/Tooltip.jsdom.test.js.snap

Notice how the tooltip now sits above the editor:

Tooltip bugfix: add Layer

---

CHANGELOG.md
packages/gestalt/package.json

- Tabs: update horizontal padding to 12px (#698)
- SelectList/TextArea/TextField: Update focus states (#720)
- Docs: make checkerboard optional (#714)

Version bump: 1.12.0

---

CHANGELOG.md
packages/gestalt/package.json

- Form fields: Add "lg" size option (#713)

Version bump: v1.13.0

---

CHANGELOG.md
packages/gestalt/src/FormErrorMessage.js
packages/gestalt/src/FormHelperText.js
packages/gestalt/src/FormLabel.css
packages/gestalt/src/__snapshots__/FormErrorMessage.test.js.snap
packages/gestalt/src/__snapshots__/TextArea.test.js.snap
packages/gestalt/src/__snapshots__/TextField.test.js.snap

Remove horizontal spacing for label / helperText and errorMessage

Form Elements: Remove horizontal spacing for label / helperText and errorMessage

---

CHANGELOG.md
packages/gestalt/package.json

- Text [Breaking]: Removes deprecated size=xl (#729)
Run codemod:
`cd gestalt; yarn run codemod --parser=flow -t=packages/gestalt-codemods/1.14.0-1.15.0/remove-text-size-xl.js ~/code/repo`

Release 1.15.0

---

CHANGELOG.md
packages/gestalt/src/Button.css
packages/gestalt/src/Layout.css
packages/gestalt/src/Tabs.css

This PR adds "overlays" (not actual overlays, represented as hex colors) for active and focus/hover states for tabs in the Tabs component.. Additionally, to ensure text is always readable regardless of what color background Tabs are used on, this adds a white background to each tab. Finally, this adds a tab min width of 60px — since this matches Button's min width, I moved things around a bit so both are composing from the same style.

Tabs: Add white background, background colors for active/focus/hover states

---

CHANGELOG.md
packages/gestalt/package.json

- Tabs: Add white background, backgrounds for active and hover/focus states, 60px min width (#731)
- Internal: Detect and remove unused eslint disables (#723)

Version bump: v1.16.0

---

CHANGELOG.md
packages/gestalt/package.json

- Icon: Add credit-card and conversion-tag icons (#716)
- Box [Breaking]: Removes support to deprecated props deprecatedMargin & deprecatedPadding (#711)
Run codemods:
`cd gestalt; yarn run codemod --parser=flow -t=packages/gestalt-codemods/1.15.0-1.16.0/deprecatedMargin-box-replace.js ~/code/repo`
`cd gestalt; yarn run codemod --parser=flow -t=packages/gestalt-codemods/1.15.0-1.16.0/deprecatedPadding-box-replace.js ~/code/repo`

Version bump 1.17.0

---

CHANGELOG.md
packages/gestalt/package.json

- Flyout/Tooltip: Update spacing around to 8px when caret is hidden (#737)
- Docs: Open in CodeSandbox & remove checkerbox from example (#735)
- Internal: fail build when CSS flow changes are required (#738)

Version bump: 1.18.0

---

CHANGELOG.md
packages/gestalt/package.json

- IconWithTooltip: Remove deprecated component (#741)

Version bump: v1.19.0 / Remove IconWithTooltip

---

CHANGELOG.md
packages/gestalt/src/FormElement.css

The focus state when there is an `error` on the field is wrong. So updated it to be consistent with regular focus styles:
**Before**
**After**

TextField / TextArea / SelectList: Fix error focus state

---

CHANGELOG.md
docs/src/Flyout.doc.js
packages/gestalt/src/Contents.css
packages/gestalt/src/Contents.js
packages/gestalt/src/Controller.js
packages/gestalt/src/__snapshots__/Controller.jsdom.test.js.snap
packages/gestalt/src/__snapshots__/Flyout.jsdom.test.js.snap

Makes `Flyout` responsive between `180px` and the specified width. It's especially nice for for flyouts that don't have that much content.
* Doesn't make changes to `Tooltip` - in that case `width` is set to `null` so we don't apply `minDimensions`

Flyout: Responsive, updated sizes + minimum width

---

CHANGELOG.md

- Flyout: Responsive, updated sizes + minimum width (#743)
- Internal: upgrade packages (#751)

Version bump: 1.21.0

---

CHANGELOG.md
packages/gestalt/package.json

- Docs: Use same React version as package (#753)

Version bump: 1.22.0

---

packages/gestalt/src/SelectList.js
packages/gestalt/src/__snapshots__/SelectList.test.js.snap

Fixes SelectList wrapper Box rounding bug. 
Before:
After:

SelectList: Update wrapper rounding

---

CHANGELOG.md
docs/src/Mask.doc.js
docs/src/Toast.doc.js
docs/src/components/Combination.js
packages/gestalt-codemods/1.22.0-1.23.0/__testfixtures__/.eslintrc.json
packages/gestalt-codemods/1.22.0-1.23.0/__testfixtures__/toast-remove-color-icon-both.input.js
packages/gestalt-codemods/1.22.0-1.23.0/__testfixtures__/toast-remove-color-icon-both.output.js
packages/gestalt-codemods/1.22.0-1.23.0/__testfixtures__/toast-remove-color-icon-single.input.js
packages/gestalt-codemods/1.22.0-1.23.0/__testfixtures__/toast-remove-color-icon-single.output.js
packages/gestalt-codemods/1.22.0-1.23.0/__tests__/toast-remove-color-icon.test.js
packages/gestalt-codemods/1.22.0-1.23.0/toast-remove-color-icon.js
packages/gestalt/src/Toast.js
packages/gestalt/src/Toast.test.js
packages/gestalt/src/__snapshots__/Toast.test.js.snap

Also changes:
* Codemod to remove `color` and `icon`
* Combinations cards: easily see the different variations for a `<Toast />` component.
* Add `fullWidth` and `showValues` option to `<Combination />`
* `xs={{ display: 'flex' }}` syntax on `<Box />` with `display="flex"`
  | Before | After
-- | -- | --
Button | (does not exist) | (added)
Color | ‘orange’ \| ‘blue’ \| ‘darkGray’ | ‘darkGray’
Icon | (exists) | (removed)
Padding (inside) | 20px / 32px | 24px
Thumbnail Shape | ‘square’ | ‘circle’ \| ‘rectangle’ \| ‘square’ (default)
Width | 376px | 360px

Toast: Update design + remove icon/color + add thumbnailShape/button

---

CHANGELOG.md
packages/gestalt/package.json

- Toast: Update design + remove icon/color + add thumbnailShape/button (#755)
Run codemods:
`cd gestalt; yarn run codemod --parser=flow -t=packages/gestalt-codemods/1.22.0-1.23.0/toast-remove-color-icon.js ~/code/repo`

Version bump: v1.23.0

---

CHANGELOG.md
packages/gestalt/src/Toast.js
packages/gestalt/src/Toast.test.js
packages/gestalt/src/__snapshots__/Toast.test.js.snap

We removed the color option on `Toast` in #755. This was a breaking change and it is a bad user experience to suddenly see errors as success messages.
We are add just the color `red` back in and will leave it undocumented as a deprecated feature.

Toast: add back the color red as a deprecated feature

---

CHANGELOG.md
packages/gestalt/package.json

- Toast: add back the color `red` as a deprecated feature (#760)

Version bump: 1.23.1

---

packages/gestalt/src/Toast.js

Added the `color` option back to `Toast` in #760 but forgot to update the propTypes.

Toast: Fix color proptypes

---

CHANGELOG.md
packages/gestalt/package.json

- Toast: Fix color proptypes (#762)

Version bump: 1.23.2

---

CHANGELOG.md
packages/gestalt/src/Badge.css
packages/gestalt/src/Heading.css
packages/gestalt/src/Text.css
packages/gestalt/src/Typography.css
packages/gestalt/src/Typography.css.flow

We ramped experiments on pinterest.com to 100% to set the letter spacing back to the default, which is `normal`. This improves readability and i18n support (no more overlapping)

Text/Heading: Update letter spacing to default (normal)

---

CHANGELOG.md
packages/gestalt/package.json

- Text/Heading: Update letter spacing to default (normal) (#764)

Version bump: 1.24.0

---

CHANGELOG.md
packages/gestalt/src/Text.js

- Removing `__dangerouslyIncreaseLineHeight` on `Text` components OR
- `__dangerouslyIncreaseLineHeight` is an equivalent of `leading='tall'` on `Text` components
- They both modify `line-height`,  property in CSS controls the space between lines of text. 
From Gestalt. leading: short: line-height 1.2, tall: line-height 1.5, default: browser determines line-height based on language
~~- [ ] Documentation~~

Text: removed __dangerouslyIncreaseLineHeight

---

CHANGELOG.md
packages/gestalt/src/SelectList.js
packages/gestalt/src/SelectList.test.js

React warns against using "selected" prop directly on an "option". We currently only use "selected" for the placeholder feature.
This change removes "selected" and instead uses "value" prop when a placeholder is used.

SelectList: Refactor placeholder for better React support

---

CHANGELOG.md
packages/gestalt/package.json

- Text: Remove deprecated prop `__dangerouslyIncreaseLineHeight` (#773)
- SelectList: Remove selected prop from the placeholder option tag for better React support (#759)

Version bump: 1.27.0

---

CHANGELOG.md
docs/src/components/Example.js

Before, it looked like we had a 1px white border below the code example. Instead, it should look like the heights are equal between the code & buttons
Before
After

Docs: Fix layout for 1 line code example

---

CHANGELOG.md
packages/gestalt/package.json

- Borders: Update lightgray border color to `#ddd` (#776)
- Docs: Fix layout for 1 line code example (#779)

Version bump: 1.28.0

---

CHANGELOG.md
docs/src/IconButton.doc.js
docs/src/Pog.doc.js
packages/gestalt/src/IconButton.js
packages/gestalt/src/Pog.css
packages/gestalt/src/Pog.css.flow
packages/gestalt/src/Pog.js
packages/gestalt/src/__snapshots__/IconButton.test.js.snap
packages/gestalt/src/__snapshots__/Pog.test.js.snap

About a year ago, I forked a handful of Gestalt components into Pinboard to make changes necessary for Lego PinRep and Closeup. This PR will allow the deletion of the last of those forks, by making two changes:
- Add the background color "red" to both IconButton and Pog, including active/focus/hover states
- Update icon sizes app-wide

IconButton/Pog: Add "red" backgroundColor + update icon sizes

---

CHANGELOG.md
packages/gestalt/package.json

- IconButton/Pog: Add "red" backgroundColor + update icon sizes (#778)

Version bump: 1.29.0

---

CHANGELOG.md
packages/gestalt/package.json

- Modal: Update OutsideEventBehavior to work well with Portals (#777)

Version bump: 1.30.0

---

CHANGELOG.md
packages/gestalt/package.json

- [Revert] Modal: Update OutsideEventBehavior to work well with Portals (#778)

Version bump: v1.31.0

---

CHANGELOG.md
docs/src/Avatar.doc.js
docs/src/GroupAvatar.doc.js
packages/gestalt-codemods/1.26.0-1.27.0/__testfixtures__/.eslintrc.json
packages/gestalt-codemods/1.26.0-1.27.0/__testfixtures__/avatar-update-sizes-remove-icon-avatar.input.js
packages/gestalt-codemods/1.26.0-1.27.0/__testfixtures__/avatar-update-sizes-remove-icon-avatar.output.js
packages/gestalt-codemods/1.26.0-1.27.0/__testfixtures__/avatar-update-sizes-remove-icon-groupavatar.input.js
packages/gestalt-codemods/1.26.0-1.27.0/__testfixtures__/avatar-update-sizes-remove-icon-groupavatar.output.js
packages/gestalt-codemods/1.26.0-1.27.0/__testfixtures__/avatar-update-sizes-remove-icon-icon.input.js
packages/gestalt-codemods/1.26.0-1.27.0/__testfixtures__/avatar-update-sizes-remove-icon-icon.output.js
packages/gestalt-codemods/1.26.0-1.27.0/__tests__/avatar-update-sizes-remove-icon.test.js
packages/gestalt-codemods/1.26.0-1.27.0/avatar-update-sizes-remove-icon.js
packages/gestalt/src/Avatar.js
packages/gestalt/src/Avatar.test.js
packages/gestalt/src/GroupAvatar.js
packages/gestalt/src/__snapshots__/Avatar.test.js.snap
packages/gestalt/src/__snapshots__/GroupAvatar.test.js.snap

  | Before | After
-- | -- | --
Sizes | sm: 24px, md: 40px, lg: 72px | xs: 24px, sm: 32px, md: 48px, lg: 64px, xl: 120px
Verified outline | 2px white | (removed)
Text color (default) | #fff (White) | #111 (darkGray)
Background color (default) | #8e8e8e (Gray) | #efefef (lightGray)
Icon | "check-circle" \| "pinterest" | (removed - always “check-circle”)
Before | After
-- | --
sm: 24px | xs: 24px
md: 40px | sm: 32px
-- | md: 48px
lg: 72px | lg: 64px
-- | xl: 120px

Avatar/GroupAvatar: update sizes / default avatar / remove verified outline

---

CHANGELOG.md
packages/gestalt/package.json

- Avatar/GroupAvatar: update sizes / default avatar / remove verified outline (#771)

Version bump: v1.32.0

---

CHANGELOG.md
docs/src/Avatar.doc.js
packages/gestalt/src/Avatar.js
packages/gestalt/src/Avatar.jsdom.test.js
packages/gestalt/src/Avatar.test.js
packages/gestalt/src/__snapshots__/Avatar.test.js.snap

Hey guys, as i spoked with Christian V. i'm adding `__dangerouslyUseDefaultIcon` prop to avatar.
This is my first contribution to this repo, so, let me know if i need to improve something
I know this will raise conflicts with [this pr](https://github.com/pinterest/gestalt/pull/771) so, just ping me when it's merged and i'll fix them

Adds avatar __dangerouslyUseDefaultIcon prop

---

CHANGELOG.md
packages/gestalt/package.json

- Avatar: Add `__dangerouslyUseDefaultIcon` prop (#774)

Version bump: 1.33.0

---

CHANGELOG.md
docs/src/Text.doc.js
docs/src/components/Example.js
docs/src/components/Markdown.js
docs/src/components/PageHeader.js
docs/src/components/PropTable.js
packages/gestalt-codemods/1.35.0-1.36.0/__testfixtures__/.eslintrc.json
packages/gestalt-codemods/1.35.0-1.36.0/__testfixtures__/leading-text-remove.input.js
packages/gestalt-codemods/1.35.0-1.36.0/__testfixtures__/leading-text-remove.output.js
packages/gestalt-codemods/1.35.0-1.36.0/__tests__/leading-text-remove.test.js
packages/gestalt-codemods/1.35.0-1.36.0/leading-text-remove.js
packages/gestalt/src/Text.js
packages/gestalt/src/Text.test.js
packages/gestalt/src/TextArea.css
packages/gestalt/src/Typography.css
packages/gestalt/src/Typography.css.flow
packages/gestalt/src/__snapshots__/Text.test.js.snap

- Removed `leading` props (`leading='tall'`  & `leading='short' `)  from `<Text>`. 
To support this change, run codemods
cd gestalt; yarn run codemod --parser=flow -t=packages/gestalt-codemods/1.35.0-1.36.0/leading-text-remove.js ~/code/repo
- `leading` modifies `line-height`,  property in CSS that controls the space between lines of text. 
- leading: short: line-height 1.2, tall: line-height 1.5, default: browser determines line-height based on language
- By removing `leading,` the browser determines line-height based on language. To make sure we support all of them, including Thai, making sure they fully render. `leading` prop forces the line-height in CSS, which in certain conditions might cut text on the top. 
- Removing leading props might remove the override of the `line-height` …

Text: Remove "leading" prop

---

CHANGELOG.md
packages/gestalt/package.json

- Text: Remove prop `leading` and related css properties (#784)
Run codemods:
cd gestalt; yarn run codemod --parser=flow -t=packages/gestalt-codemods/1.35.0-1.36.0/leading-text-remove.js ~/code/repo

Version bump: 1.35.0

---

CHANGELOG.md
packages/gestalt/src/Masonry.js

This is my second attempt at landing this PR, after #667 needed to be reverted. I root-caused the previous issue to be one instance of the `flexible` variable that I had modified despite the fact that we still want to support `flexible` in its current form until we've modified Pinboard code.
Masonry currently allows three ways to specify which layout you'd like to use:
1. Use a `Symbol` as part of `legacyLayoutSymbols.js`, although this is not exported so only relevant inside the package.
2. Use one of class-based layouts in the `/layouts` folder. These _are_ exported but are considered "legacy".
3. Specify nothing and get the default columnar layout.
Because extra exports are annoying and we're already split on what to use, I'd like to update to one true system: strings. I'd like layout …

Allow string enums for Masonry layout

---

CHANGELOG.md
packages/gestalt/package.json

- Masonry: Allow string enum types for Masonry layout prop (in prep of removing symbols/classes) (#782)

Version bump: v1.37.0

---

CHANGELOG.md
packages/gestalt/package.json

- Modal: support Flyout inside of a Modal (#793)

Version bump: 1.38.0

---

CHANGELOG.md
packages/gestalt/src/SegmentedControl.css

Update the border radius from 8px outer / 6px inner to 16px outer / 14px inner
~~[ ] Documentation~~
~~[ ] Tests~~
~~[ ] Experimental evidence (required for Masonry changes)~~
~~[ ] Accessibility checkup~~

[SegmentedControl]: Update the border radius from 8px outer / 6px inner to 16px outer / 14px inner  (#798)

---

CHANGELOG.md
packages/gestalt/package.json

- SegmentedControl: Update the border radius from 8px outer / 6px inner to 16px outer / 14px inner (#798)

Version bump: 1.39.0

---

.eslintrc.json
scripts/test.sh
yarn.lock

We no longer have `*.integration.js` files so remove reference to it

Internal: remove reference to unused .integration.js

---

.github/workflows/ci.yml
CHANGELOG.md
packages/gestalt/src/Typography.css

Internal mweb and desktop experiments were successful, so let's ship the default (manual) hyphenation
The default value of `hyphens` is `manual`, so there is no need to explicitly set it
https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens

Text/Heading: Use default (manual) hyphenation

---

CHANGELOG.md
packages/gestalt/package.json

- Text/Heading: Use default (manual) hyphenation (#807)
- Internal: remove reference to unused .integration.js (#808)

Version bump: 1.40.0

---

CHANGELOG.md
packages/gestalt/src/Borders.css
packages/gestalt/src/Borders.css.flow
packages/gestalt/src/Colors.css
packages/gestalt/src/SearchField.css
packages/gestalt/src/Switch.css
packages/gestalt/src/TextArea.css
packages/gestalt/src/TextField.css

- Previously Gray mapped to #8E8E8E which is a non-accessible color for small type sizes. 
- To improve accessibility and aligned with criteria for AA rating in WCAG for small text, all Gray color references change from  #8E8E8E  to #767676.
~~- [ ] Documentation~~

[Color] Update gray color to #767676 for improved accessibility

---

CHANGELOG.md
packages/gestalt/package.json

- Color: update gray color to #767676 (#804)
- Icon: update default #8e8e8e to #767676 (#811)

Version bump: v1.41.0

---

CHANGELOG.md
docs/package.json
package.json
packages/gestalt/package.json
yarn.lock

This updates a few dependencies to the latest versions:
- react, react-dom, and react-test-renderer
- @testing-library/react and @testing-library/jest-dom
- jest and babel-jest
- stylelint

Minor version updates for several dependencies

---

CHANGELOG.md
packages/gestalt/src/Button.css
packages/gestalt/src/Tabs.css

- Changes the horizontal padding from 12px to 16px for  48px Buttons (large) & Tabs components
~~- [ ] Documentation~~

[Buttons/Tabs]: Increase paddingX to 16px on lg Buttons and Tabs

---

CHANGELOG.md
packages/gestalt/package.json

- RadioButton/Checkbox: Moved shared classes to RadioButtonCheckbox.css (#810)
- Internal: update yarn.lock file (#814)
- Internal: Minor version updates for several dependencies (#815)
- Buttons/Tabs: Increase paddingX to 16px on lg Buttons and Tabs (#816)
- Docs: Add a note on the Tabs documentation about use with react-router (#813)

Version bump: 1.42.0

---

CHANGELOG.md
docs/src/index.js

https://reactjs.org/docs/strict-mode.html
>StrictMode is a tool for highlighting potential problems in an application. Like Fragment, StrictMode does not render any visible UI. It activates additional checks and warnings for its descendants.
The only error/warning I found is caused by `react-live` which uses an unsafe lifecycle method: `UNSAFE_componentWillMount`: https://github.com/FormidableLabs/react-live/blob/05e0ad7ab8231a2c119a91240a2bcc67cf8c6d02/src/components/Live/LiveProvider.js#L27

Internal: Enable React Strict Mode on documentation

---

CHANGELOG.md
packages/gestalt/src/Borders.css
packages/gestalt/src/Borders.css.flow
packages/gestalt/src/Checkbox.css
packages/gestalt/src/Checkbox.css.flow
packages/gestalt/src/Checkbox.js
packages/gestalt/src/RadioButton.css
packages/gestalt/src/RadioButton.css.flow
packages/gestalt/src/RadioButton.js
packages/gestalt/src/__snapshots__/Checkbox.test.js.snap
packages/gestalt/src/__snapshots__/RadioButton.test.js.snap

- Updated Checkbox and Radiobutton borders for the disabled state to fix color mismatch introduced in 
1.28.0 (Mar 27, 2020) Minor: - Borders: Update lightgray border color to `#ddd` (#776)
~~[ ] Documentation~~
~~[ ] Tests~~
~~[ ] Experimental evidence (required for Masonry changes)~~
~~[ ] Accessibility checkup~~

[Checkbox/Radiobutton]: Updated checkbox and radiobutton borders for disabled state

---

CHANGELOG.md
docs/src/IconButton.doc.js
docs/src/Pog.doc.js
packages/gestalt/src/IconButton.js
packages/gestalt/src/Pog.js

- IconButton/Pog: Removed unused `iconColor` options: `blue`, `orange`; added `bgColor` option: `darkGray`
- Docs for Pog: Replaced `Combination: Color` for `Combinations: Icon Color` & `Combinations: Background Color` to match IconButton.
- Removed IconButton-bgColor-blue option from Docs.

[IconButton/Pog]: Removed unused iconColor options: blue, orange; added bgColor: darkGray

---

CHANGELOG.md
packages/gestalt/package.json

- Tooltip: Show tooltip when React children have focus (#824)
- IconButton/Pog: Removed unused iconColor options: blue, orange; added darkGray; added bgColor: darkGray (#823)
- Docs: Replaced combinations in Pog with Combinations: Icon Color & Background Color. Removed IconButton-bgColor-blue option from Docs. (#823)
- Internal: Enable React.Strict on documentation (#821)
- Checkbox/Radiobutton: Updated checkbox and radiobutton borders for disabled state (disabled controls don't show outlines) (#795)

Version bump: v1.43.0

---

.github/workflows/ci.yml
CHANGELOG.md

Test the Gestalt build on Node.js 14 - allows us to spot issues early.

Internal: Test builds on Node.js 14

---

CHANGELOG.md
docs/src/SearchField.doc.js
packages/gestalt/src/SearchField.js

#819 converted `SearchField` from a class to a function component. That is great, since it makes the code more readable but it introduced issues in Pinterest specific code which uses `ref` on the components.
An alternative is to use `forwardRef` but that would encourage abstraction leaking, which is not something we'd like to do.

SearchField: convert back to class component

---

docs/src/Touchable.doc.js
packages/gestalt/src/Touchable.js
packages/gestalt/src/__snapshots__/Video.test.js.snap
packages/gestalt/src/__snapshots__/VideoControls.test.js.snap
packages/gestalt/src/__snapshots__/touchable.test.js.snap
packages/gestalt/src/touchable.jsdom.test.js

Use case: in order to make a more accessible `Tooltip`, we need to fire onBlur / onFocus events from `Touchable` so the design syncs up.
In this example you can see the issue, hovering the Icon changes the color but focussing it does not.

Touchable: add optional onBlur / onFocus props

---

CHANGELOG.md
packages/gestalt/package.json

- IconButton/Pog: Deprecated bgColor=blue in Pog and IconButton (#827)
- Touchable: add optional onBlur / onFocus props (#832)

Version bump: v1.46.0

---

CHANGELOG.md
packages/gestalt/package.json

- Readme: Remove greenkeeper reference (#835)

Version bump: v1.46.1

---

docs/src/Flyout.doc.js
packages/gestalt/src/Flyout.js

Adding "flexible" as an acceptable prop string to Flyout's size prop that will allow custom sizing on a flyout's contents.
Screenshot of custom sizing in acton:

Add flexible size prop to Flyout

---

CHANGELOG.md
packages/gestalt/package.json

- Flyout: Add flexible size prop to flyout (#840)
- Icon: Add story pin icon (#842)
- Internal: Enable + enforce flow strict on every file (#841)
- Flyout: Fix stroke on caret (#837)

Version bump: v1.47.0

---

CHANGELOG.md
packages/gestalt/src/VideoControls.js
packages/gestalt/src/__snapshots__/Video.test.js.snap
packages/gestalt/src/__snapshots__/VideoControls.test.js.snap

Video controls were wrapping when too long.
Broken:
Fixed:

VideoControls: overwriting overflow default behavior on timestamp text

---

CHANGELOG.md
docs/src/Badge.doc.js
packages/gestalt/src/Badge.css
packages/gestalt/src/Badge.js
packages/gestalt/src/Badge.test.js
packages/gestalt/src/__snapshots__/Badge.test.js.snap

This change updates the existing Badge component to match updated specs featuring:
- solid background (blue)
- white text
- remove enforcement of upper casing (consensus is sentence casing is better)
- update docs examples to include sentence casing, remove sentence suggesting we encourage use of top with headings.
I anticipate extending the implementation to include additional sizing and color props so i've tried to write this with that in mind while still being restrictive to match our current spec. For example, I allow for an optional color prop but I don't list this in the documentation and I restrict the Proptypes. Let me know if this is confusing in any way but I figured we'll likely be expanding this in the near future.
After
Before
- [x ] Documentation
- [x ] Tests

Add support for Badge with blue background and white text

---

packages/gestalt/src/Button.css
packages/gestalt/src/Colors.css
packages/gestalt/src/Colors.css.flow
packages/gestalt/src/Pog.css

Make `Button` and `IconButton` white background colors more consistent.
Example of where this is an issue, it should be a transparent white instead.

Button/IconButton: update white background colors

---

.github/workflows/requireReleaseType.yml
scripts/releaseSteps.js

Suggestion by @bishwei in #848 to make the release type required:
> thinking out loud - is defaulting to `patch` here the right behavior or should we throw if a release type label wasn't properly specified?
We also require for just one release type to be defined, if you define multiple, the build will fail. Uses [zwaldowski/match-label-action](https://github.com/zwaldowski/match-label-action) under the hood.

Internal: Require release type on every PR

---

.github/workflows/ci.yml

It takes [+60 seconds](https://github.com/pinterest/gestalt/pull/853/checks?check_run_id=667646012) to install our package dependencies:
```bash
Run yarn install --force
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "eslint-plugin-jest > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree > tsutils@3.17.1" has unmet peer …
```

Internal: Cache yarn dependencies in CI

---

CHANGELOG.md
scripts/releaseSteps.js

Introduced by #853 - we added too many spaces when updating the `CHANGELOG.md` file

Internal: Fix Changelog formatting

---

.github/workflows/addDefaultReleaseType.yml
.github/workflows/release.yml

Developers have been reaching out to me to understand why their build fails when they create a new PR. The root cause is #853 which requires a release type label to be set. That label can only be set by a maintainer or GitHub bot, so this PR automatically adds the patch release label upon opening a new PR.

Internal: Add default release type label on PR creation

---

.github/workflows/addDefaultReleaseType.yml
README.md

We no longer upload our code coverage to codecov.io - so let's remove the badge for now.

Docs: Remove code coverage status badge

---

.github/workflows/release.yml

Most likely an update to "octokit/graphql-action" caused the release action to break.
```
2020-05-18T16:24:54.3601454Z Prepare workflow directory
2020-05-18T16:24:54.3800455Z Prepare all required actions
2020-05-18T16:24:54.3812673Z Download action repository 'octokit/graphql-action@v2.x'
2020-05-18T16:24:55.3819475Z Download action repository 'actions/checkout@v2'
2020-05-18T16:24:56.3636660Z Download action repository 'actions/setup-node@v1'
2020-05-18T16:24:56.5667147Z ##[warning]Unexpected input 'owner', valid inputs are ['query']
2020-05-18T16:24:56.5670079Z ##[warning]Unexpected input 'name', valid inputs are ['query']
2020-05-18T16:24:56.5670677Z ##[warning]Unexpected input 'oid', valid inputs are ['query']
2020-05-18T16:24:56.5705049Z ##[group]Run octokit/graphql-action@v2.x …
```

Internal: Fix automatic releases

---

.github/workflows/release.yml

https://codeload.github.com/octokit/graphql-action/legacy.tar.gz/v2.1 does not exist
https://codeload.github.com/octokit/graphql-action/legacy.tar.gz/v2.1.0 does exist

Internal: Fix automatic releases (second try)

---

.github/workflows/release.yml

Tried it out at https://github.com/christianvuerings/gestalt-copy/runs/686104220
The issue seems to be https://github.com/octokit/graphql-action/commit/cb8e559edb9aa23c11b50e1e98f9223b8f1f1fbc where they changed how they parse the yaml

Internal: Use octokit/graphql-action@v2.0.0

---

packages/gestalt/src/Video.js

- Fix for n.video.load is not a function. (In 'n.video.load()', 'n.video.load' is undefined) in Safari
- This is an issue specific to Safari 11 or below, and comes from the `load` call on HTMLMediaElement in gestalt https://github.com/pinterest/gestalt/blob/master/packages/gestalt/src/Video.js#L298
- According to MDN doc, it should be supported since Safari 6.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/load
- It could be some kind of race condition where the ref (this.video) exists but doesn’t yet have the load function.
~~- [ ] Update documentation~~
~~- [ ] Add/update Tests~~

Video: Fix for `n.video.load is not a function` in Safari

---

packages/gestalt/src/Modal.css
packages/gestalt/src/Modal.css.flow
packages/gestalt/src/Modal.js

We have these bugs with shadows that should show when you scroll:
1. On Safari, the shadow is too thick and shows up a grey border
2. Components like `<TextField />` show on top of the shadow
This PR addresses both by moving away from the CSS only approach and add event listeners + use box shadow instead.
**Chrome before / after**
**Safari before / after**

Modal: Fix shadows on scroll

---

packages/gestalt/src/Modal.css

On pinterest.com, we have an issue where the default `:focus` style overrides the gestalt style. Since we make it more specific, the gestalt style will override the default Pinterest on.
Example of the issue:

Modal: make focus state more specific

---

package.json
packages/gestalt/package.json
yarn.lock

Use `sane` instead of rollup's `watch method which kept appending CSS (instead of replacing it) with every change.

Internal: fix yarn watch keeps appending CSS

---

packages/gestalt/src/Table.js
packages/gestalt/src/__snapshots__/Table.test.js.snap

We always see a horizontal scrollbar on `Table` even when it's not necessary. I have the following OS X settings set:

Table: Only show scrollbar when necessary

---

docs/src/Row.doc.js
docs/src/Stack.doc.js

This adds missing available props to the docs for Row and Stack: height, width, min/max for both

[Row, Stack] Add missing props to docs

---

docs/src/Tabs.doc.js
packages/gestalt/src/Tabs.js
packages/gestalt/src/Tabs.test.js

Allow a developer to specify ids for tabs, for use in selecting elements for tests and other uses.

Tabs: Allow an id on tabs

---

docs/src/Toast.doc.js

* Docs: The parameter `color` exists in the code but not in the docs. Add the parameter and a corresponding example for it in Toast.

Docs: Add missing parameter for Toast

---

.prettierignore
docs/public/index.html
docs/src/components/DocSearch.css
docs/src/components/DocSearch.js
docs/src/components/Header.js

Add search to the Gestalt docs
* Under the hood this uses Algolia DocSearch: see the docs at https://docsearch.algolia.com/docs/what-is-docsearch/
* The demo will trigger a reload to another page (so navigation will be slow)
* Design is ok, we should add a search icon link and perhaps a reset button in a follow up PR
* We could not use the Gestalt `<SearchField />` since Algolia makes DOM mutations outside of the React tree

Docs: Add search

---

packages/gestalt/src/Table.css
packages/gestalt/src/TableSortableHeaderCell.js
packages/gestalt/src/__snapshots__/TableSortableHeaderCell.test.js.snap

Changed the clickable area on the sortable header cell to only be around the children and the sorting icon, so that the clickable area doesn't span the entire width of the header cell. I added a Box with width as fit-content around the Touchable, and added fullWidth={false} to Touchable.
Focus state:
After clicking:

TableSortableHeaderCell: Change clickable area

---

.flowconfig
docs/src/TextField.doc.js
flow-typed/npm/jest_v26.x.x.js
packages/gestalt-codemods/1.61.0-2.0.0/textfield-find-deprecated-refs.js
packages/gestalt/src/TextField.js
packages/gestalt/src/TextField.jsdom.test.js

Adds ref forwarding to `TextField`
We have 13 places in the Pinterest codebase where we already set a `ref` on the current `<TextField />`. However, that ref is set on the component's instance, not the actual input. So in each of those cases, people drill down to get the `<input />`. That is pretty hacky, so let's add a way for them to get it in a cleaner way.
https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers
> When you start using forwardRef in a component library, you should treat it as a breaking change and release a new major version of your library. This is because your library likely has an observably different behavior (such as what refs get assigned to, and what types are exported), and this can break apps and other libraries that depend on the …

TextField: Add forward ref (BREAKING CHANGE)

---

packages/gestalt/src/TextField.js

We added `forwardedRef` in #901 but the propType was incorrect. See https://stackoverflow.com/a/51127130/117193 for more info
Note that we still need to use `current: PropTypes.any,` since `current: PropTypes.instanceOf(Element)` breaks in jest - for testEnvironment set to `node`
https://github.com/facebook/jest/issues/7786

TextField: fix forwardedRef propType

---

packages/gestalt/src/Tabs.css

Tabs: remove underline on hover/focus

---

docs/src/Pog.doc.js
packages/gestalt/src/Pog.js
packages/gestalt/src/Pog.test.js
packages/gestalt/src/__snapshots__/IconButton.test.js.snap
packages/gestalt/src/__snapshots__/Pog.test.js.snap

- add `padding` prop where possible value are 1 ~ 5 boints. if omitted, default padding (which may or may not be an integer boint) would be used.
- removed unnecessary use of `Box` in the component

Pog: Add padding prop

---

packages/gestalt/src/Touchable.js

This is so that Touchable component is still named Touchable in shallow snapshots. manually tested by running shallow snapshot tests in Pinboard.

Touchable: displayName should still be Touchable

---

.github/pull_request_template.md

Require a Pinterest designer for design changes in Gestalt. Makes it easier to get context around a change.

Internal: Request a Pinterest designer for design changes

---

.flowconfig
package.json
packages/gestalt/src/Box.js
packages/gestalt/src/Layer.js
packages/gestalt/src/Video.js
packages/gestalt/src/VideoControls.js
yarn.lock

Upgrade to 0.127.0 with more exact error suppressions + it unlocks types first: https://medium.com/flow-type/types-first-a-scalable-new-architecture-for-flow-3d8c7ba1d4eb
Release notes: https://github.com/facebook/flow/releases

Internal: upgrade to flow 0.127.0

---

packages/gestalt/src/Row.js
packages/gestalt/src/Stack.js

`React.Children` doesn't filter out nullish children before mapping, so we were padding empty Boxes and throwing off layouts. This PR adds a nullish check and only wraps the child in a Box if it's defined, otherwise passing through null.
Before:
After:

Row, Stack: Fix nullish child gap bug

---

packages/gestalt/src/Masonry.js
packages/gestalt/src/defaultLayout.js
packages/gestalt/src/defaultLayout.test.js

The Masonry grid renders items from left to right with the first item left justified.  This change adds an option to the Masonry `layout` prop called `basicCentered`.  When passed this value `defaultLayout` modifies its calculation of position to center justify the contents of the grid.
Example board: https://www.pinterest.com/pinterestcreators/story-pins/
Masonry.props.layout === 'basic'
Masonry.props.layout === 'basicCentered'
- [✓] Add/update Tests
- [✓] Pinterest Designer (for design changes) (@annieteng)
- [✓] [Format PR title](https://github.com/pinterest/gestalt/#releasing): `ComponentName: Description`.

Masonry/defaultLayout: Add a layout `basicCentered` to center justify grid content

---

flow-typed/npm/react-datepicker_v2.x.x.js
packages/gestalt-datepicker/src/DatePicker.js

Fixed `locale object was not found for the provided string` warning due to locale not have been register yet.

DatePicker: Fix "locale object was not found for the provided string" warning

---

packages/gestalt-datepicker/src/DatePicker.css

Fixed hover CSS for the same date selection in range.
- [-] Accessibility checkup
- [-] Update documentation
- [-] Add/update Tests
- [-] Pinterest Designer (for design changes)

[DatePicker] Fixed hover CSS for the same date selection in range.

---

docs/src/IconButton.doc.js
packages/gestalt/src/IconButton.js

- Add optional `padding` prop, allowing custom padding
Note: This is a follow up of #911 where we add custom `padding` to `<Pog>`
Screenshots:

IconButton: add optional padding prop

---

packages/gestalt/src/Button.css

A bug was reported were Tooltips wrapping disabled buttons were persisting.
`<Tooltip inline text='wow great tooltip'>
<Button disabled text='Submit Application' size="lg" />
</Tooltip>`
Mouse events don't fire when the pointer is over disabled form elements but pointer-events do.  
For example, if console.logging inside `onMouseEnter` and `onMouseLeave` for Tooltip and Button:
**enabled**
**disabled** 
Based on this [article](https://jakearchibald.com/2017/events-and-disabled-form-fields/), a workaround is to disable pointer events so disabled buttons cannot be interacted with at all. 
From this [article](https://css-tricks.com/almanac/properties/p/pointer-events/), 
- The pointer-events property allows for control over how HTML elements respond to mouse/touch events – including CSS …

Button: Fix disabled state to prevent it to be interacted with and event bubbling

---

docs/src/Box.doc.js
docs/src/Link.doc.js
packages/gestalt/src/Box.js
packages/gestalt/src/Link.js
packages/gestalt/src/Link.test.js
packages/gestalt/src/__snapshots__/Link.test.js.snap

- Add `role` prop to `<Box>`
- Add `role` prop to `<Link>`
- Add `accessibilitySelected` prop to `<Link>`
This will allow us to implement the `<Tabs>` component with just `<Box>`, `<Text>`, and `<Link>`.
Docs Screenshots

Box/Link: add role prop to both and accessibilitySelected prop to Link

---

docs/src/DatePicker.doc.js
docs/src/Tooltip.doc.js

Both `DatePicker` and `Tooltip` had the wrong default value for `idealDirection` in the docs.

DatePicker/Tooltip: update idealDirection default value in docs

---

docs/public/index.html

Conditionally load a script with polyfills in IE 11 so the docs render correctly.

Docs: support IE11

---

packages/gestalt/src/Modal.css

Modal: fix scroll behavior in IE11

---

.devcontainer/devcontainer.json
.gitignore
.vscode/settings.json

Add support for [GitHub Codespaces](https://github.com/features/codespaces/) - a new beta feature from GitHub to allow
* Editing of files in VS Code in a browser window
* Run Gestalt docs on a remote browser

Internal: Support GitHub Codespaces

---

docs/src/Avatar.doc.js
packages/gestalt/src/Avatar.js

We currently always use the name for the aria-label (or svg title), which is a decent default but not always desired. For example, when using an Avatar next to the user's name, a screen reader will read the name twice (once for the Avatar's aria-label, once for the text content). This also allows for more flexibility if the aria-label should be something instead of the user's name.

Avatar: Add accessibilityLabel

---

docs/src/components/CollapsibleSection.js
docs/src/components/CollapsibleSubsection.js
docs/src/components/sidebarIndex.js

Update the docs navigation to expand the sections/subsections by default.
Potential improvements:
1. Collapse all for components
2. Make the navigation sticky so that it stays in view when scrolling through longer component docs

Docs: Expand Navigation subsections

---

docs/public/index.html
docs/src/index.js
packages/gestalt-core/build.js
packages/gestalt/src/Colors.css
packages/gestalt/src/Colors.css.flow
packages/gestalt/src/Contents.js
packages/gestalt/src/Modal.css
packages/gestalt/src/Pog.css
packages/gestalt/src/SearchField.css
packages/gestalt/src/TextArea.css
packages/gestalt/src/TextField.css
packages/gestalt/src/__snapshots__/Flyout.jsdom.test.js.snap

This sets up our css generation so it's ready to support dark mode in follow up PRs
Because css variables do not work on older browsers such as IE11, I'm generating a new css file with the css vars preserved and kept the old one with the existing behavior to substitute in the values during builds.
It's also possible to support both legacy and modern browsers in one css file by including a fallback value and the variable in each rule, but that ended up roughly doubling the css filesize.
Once this has had more testing and we consider dark mode stable, I'd like to make the "future" css the default one and rename the existing one "legacy". Anyone using gestalt who needs to support IE or doesn't need theme support can load that version of the css.
The design team has already worked with the …

Styling: Prepare css for dark mode support

---

packages/gestalt/src/SearchField.css
packages/gestalt/src/SearchField.js

Add RTL (Right to Left) support to `SearchField`.

SearchField: RTL support

---

docs/src/Tabs.doc.js
packages/gestalt/src/Tabs.js
packages/gestalt/src/Tabs.test.js
packages/gestalt/src/__snapshots__/Tabs.test.js.snap

This PR adds the ability to render a small circular icon in a tab to indicate that the tab should be clicked per a new design we received in ads.

Tabs: Add optional dot indicator

---

docs/src/Box.doc.js
docs/src/Sticky.doc.js
packages/gestalt/src/Box.js
packages/gestalt/src/Box.test.js
packages/gestalt/src/Sticky.js
packages/gestalt/src/Sticky.test.js
packages/gestalt/src/__snapshots__/Box.test.js.snap
packages/gestalt/src/__snapshots__/Sticky.test.js.snap
packages/gestalt/src/index.js
packages/gestalt/src/zIndex.js
packages/gestalt/src/zIndex.test.js

The `z-index` CSS property is difficult to work with as:
1. It's global. There's one index for the entire page, which goes against the composability of React's component model.
2. It's implicit. There's usually a relationship between `100` & `101` but at best that's only captured in comments and can't be verified. If `100` changes, `101` will break.
Previously, Gestalt has taken the ["War Games" approach](https://www.youtube.com/watch?v=MpmGXeAtWUw) to `z-index` - the only winning move is to not play the game. This resulted in components like `<Layer>` which help developers change the render order while still respecting the React component order. However, over time, `z-index` usage hasn't decreased and it remains one of the most commonly usages of `dangerouslySetInlineStyles` on `<Box>`. …

ZIndex: Add support for Fixed & Composite zIndexes

---

docs/src/GestaltProvider.doc.js
docs/src/components/App.js
docs/src/components/Header.js
docs/src/components/sidebarIndex.js
packages/gestalt/src/GestaltProvider.js
packages/gestalt/src/GroupAvatar.js
packages/gestalt/src/__snapshots__/GroupAvatar.test.js.snap
packages/gestalt/src/contexts/Theme.js
packages/gestalt/src/contexts/Theme.jsdom.test.js
packages/gestalt/src/index.js

This creates two new components `GestaltProvider` and `ThemeProvider` and a hook `useTheme`.
This is a component that may **optionally** be set up to wrap gestalt components and provide context to them. In this PR I am just setting up support for color schemes, but we've also discussed using this provider for RTL support and to make `Link` work properly with react-router. Providers can be nested to override context set above. For now it's just a thin wrapper around `ThemeProvider`.
Open to better naming suggestions 😄 
This is used internally by `GestaltProvider` to set up the theme context and generate a style tag for a custom class name. The style tag overrides the css variables we use to a new value. Options for `colorScheme` are:
- light: The standard gestalt theme
- dark: A new theme …

GestaltProvider: Adding a provider for color scheme and other future context used by Gestalt

---

docs/src/components/App.js
docs/src/components/Header.js

* Header in the docs becomes less crowded
* Easy one-click toggle (instead of having to use the dropdown)
Major downside is that we can no longer test with user selected option but since it's either light or dark, that should be ok.

Dark Mode: update toggle in docs

---

docs/src/components/Checkerboard.js
packages/gestalt/src/Avatar.js

Avatar: Update hardcoded svg fills to use theme colors

---

packages/gestalt/src/Box.js
packages/gestalt/src/Box.test.js
packages/gestalt/src/__snapshots__/Box.test.js.snap

We found with #966 that Box's props are effectively untyped - `any`. This lead to an incident where somebody was incorrectly setting `zIndex` on Box, but Flow didn't catch it. This fixes the Flow suppressions on Box.
I know this changed worked because Flow immediately found type errors in the DatePicker due to `role` and `zIndex` being (incorrectly) marked as required props. This diff also fixes those.

Fix Box types

---

docs/src/Link.doc.js

Fixes: https://github.com/pinterest/gestalt/issues/1005

[Docs: Link] Fixed/Improved examples

---

packages/gestalt/src/Borders.css

[Partially] Fixes https://github.com/pinterest/gestalt/issues/984
Pending fixing non-adhered to scheme lightGrays

[Borders.css][DarkMode] Replaced naming in Borders.css to scheme standard

---

packages/gestalt/src/Avatar.js
packages/gestalt/src/GroupAvatar.js
packages/gestalt/src/__snapshots__/Avatar.test.js.snap
packages/gestalt/src/__snapshots__/AvatarPair.test.js.snap

Closes #990 
Also noticed the same issue on `GroupAvatar` as in the ticket so fixed that too.

Avatar and GroupAvatar: Use correct outline for dark mode

---

packages/gestalt/src/Button.css
packages/gestalt/src/Button.css.flow
packages/gestalt/src/Button.js
packages/gestalt/src/Colors.css
packages/gestalt/src/Colors.css.flow

Closes #992 
This checks if we're in dark mode and adjusts the colors slightly if so to keep an accessible contrast

Button: Use accessible colors for darkMode red button

---

packages/gestalt/src/Table.css

Fixes: https://github.com/pinterest/gestalt/issues/980

[Table] Fix sticky header in darkMode

---

packages/gestalt/src/Contents.js
packages/gestalt/src/__snapshots__/Flyout.jsdom.test.js.snap

Flyout: Fix caret appearance in dark mode

---

packages/gestalt/src/Box.js

In #986 I removed the explicit setting of Box's displayName because I named the function that's passed to `forwardRef`. This resulted in React (correctly) setting the displayName of the resulting component to "ForwardRef(Box)". However, that breaks basically every snapshot test we have that expects the `displayName` to be Box. Considering upgrading is already delayed due to type errors, I want to minimize the number of changes we introduce.
This is worth coming back and refactoring later.

Box: Set display name

---

.mergify.yml

This isn't technically needed as Mergeify will rebase and it seems to be blocking other commits from being merged.

Merge: Remove status-check=0 check

---

CHANGELOG.md

Adds correct info to the changelog since some data was missing before #1035 was added
Checked the added descriptions match the PR titles

Docs: Add missing release details to the changelog

---

package.json
scripts/cssValidate.js
scripts/test.sh

Improves safety of our CSS variables.
We introduced a split CSS bundle for legacy and future CSS in #963 but this resulted in potential breakages:
await duplicateVariablesDifferentValues();
await noVarInLegacyCSS();
We already saw this issue in #971 where the font-size variables for `Text` and `Heading` got overridden resulting in heading sizes to be the same as text sizes
*Test*: change a color that appears multiple times in 1 location: 
```
--gestalt-colorGray100: #efefef;
```
to
```
--gestalt-colorGray100: #efefed;
```
This will break in IE11 since the compiled CSS will still contain the `var()`. We can only use `:root` for now so it does get replaced in the legacy build.
*Test*: Add this to any file CSS file
```css
.textFieldTemp {
--gestalt-colorGrad: #111;
color: …
```

Internal: Add CSS variables CI checks

---

packages/gestalt/src/Colors.css
packages/gestalt/src/__snapshots__/Video.test.js.snap
packages/gestalt/src/contexts/ColorScheme.js
packages/gestalt/src/contexts/ColorScheme.jsdom.test.js

Pogs using these background colors now properly inverse in dark mode. The hover colors are still not quite right in dark mode but this is an improvement
Check Pogs in docs in light mode and dark mode. Make sure the "transparentDarkGray" and "white" colors reverse in dark mode

ColorScheme: Set transparent colors in dark mode

---

packages/gestalt/src/Pog.js
packages/gestalt/src/__snapshots__/Pog.test.js.snap

The `padding` prop for `Pog` and `IconButton`, added in #911 and #949 respectively, is expected to be in boints (1 means 4 px), but I incorrectly treated it as pixels (1 means 1px). This PR fixes it.
Before
After

IconButton, Pog: fix padding prop

---

docs/src/index.js
packages/gestalt-datepicker/src/DatePicker.css
packages/gestalt/src/Pog.css
packages/gestalt/src/__snapshots__/Video.test.js.snap
packages/gestalt/src/contexts/ColorScheme.js
packages/gestalt/src/contexts/ColorScheme.jsdom.test.js

Fixes:
https://github.com/pinterest/gestalt/issues/995
https://github.com/pinterest/gestalt/issues/976
PENDING: Navigation Icon on Hover/Click should go DarkGray
PENDING: Day color upon hovering in days.

DatePicker: Implementing DarkMode color scheme

---

scripts/cssValidate.js

Internal: Catch CSS variable usage in legacy build

---

packages/gestalt/src/Video.js
packages/gestalt/src/VideoControls.js
packages/gestalt/src/VideoControls.jsdom.test.js
packages/gestalt/src/VideoControls.test.js
packages/gestalt/src/__snapshots__/Video.test.js.snap

Currently, the `captions` attribute on videos doesn't actually show captions on a video, we need to update the video text track state to show the captions.

Video: Add captions + controls

---

docs/src/Link.doc.js
packages/gestalt/src/Link.js

Follow up from #1044 with the following changes:
* Uses the same forwardRef approach as we do with other components
* Add docs
* Sets the `displayName` to `Link` (avoid having to update too many snapshots)
* Add the correct propType
From @chrislloyd 
> When trying to add Next.js in #1043, I've run into a few issues with the Next link and Gestalt's Link. Mostly, it expects access to the underlying ref. I think this is pretty straight-forward and a fairly safe change (seeing and not many places use Link). It also feels similar to other places where we use `forwardRef` (like `<Box/>`) in that Link is just a thin wrapper over `HTMLLinkElement`.
CI

Link: add React.forwardRef

---

docs/src/components/sidebarIndex.js

Restructure sidebar display order as decided by the Gestalt team.
* Have you involved other stakeholders (such as a Pinterest Designer)? YES

Docs: restructure sidebar display order

---

docs/src/components/DocSearch.css
docs/src/components/DocSearch.js

* Is it accessible? YES
* Have you involved other stakeholders (such as a Pinterest Designer)? YES: based on Datepicker darkMode adoption

Docs: Added darkMode to Algolia's DocsSearch feature

---

docs/src/Pog.doc.js
packages/gestalt/src/Pog.js
packages/gestalt/src/Pog.test.js
packages/gestalt/src/__snapshots__/Pog.test.js.snap

Add optional `accessibilityLabel` prop to `Pog` component for the following use case:
```jsx
<Link to="/following/">
<Pog icon="people" accessibilityLabel="Following" />
</Link>
```
jest

Pog: add optional accessibilityLabel

---

docs/src/TextArea.doc.js
packages/gestalt-codemods/6.2.0-7.0.0/textarea-find-deprecated-refs.js
packages/gestalt/src/TextArea.js
packages/gestalt/src/TextArea.jsdom.test.js
packages/gestalt/src/TextField.jsdom.test.js

- Adds ref forwarding to TextArea
- Added ref example to Docs
- Added codemod helper
- Added test for ref 
[ Follows the implementation in TextField ]
We have _0_ places in the Pinterest codebase where we set a ref on the current <TextArea />.  
However, without forwardedRefs, refs are set on the component's instance, not the actual input. So in each of those cases, people drill down to get the <textarea />.
That is pretty hacky, so let's add a way for them to get it in a cleaner way.
[https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers](https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers
)
> When you start using forwardRef in a component library, you should treat it as a breaking change and release a new major version of …

TextArea: Add forward ref (BREAKING CHANGE)

---

docs/src/Button.doc.js
packages/gestalt/src/Button.js
packages/gestalt/src/IconButton.js
packages/gestalt/src/Link.js
packages/gestalt/src/TapArea.js
packages/gestalt/src/Touchable.css
packages/gestalt/src/Touchable.css.flow
packages/gestalt/src/__snapshots__/IconButton.test.js.snap
packages/gestalt/src/__snapshots__/Link.test.js.snap
packages/gestalt/src/__snapshots__/TableSortableHeaderCell.test.js.snap
packages/gestalt/src/__snapshots__/Tabs.test.js.snap
packages/gestalt/src/__snapshots__/TapArea.test.js.snap
packages/gestalt/src/__snapshots__/Toast.test.js.snap
packages/gestalt/src/__snapshots__/Video.test.js.snap
packages/gestalt/src/__snapshots__/VideoControls.test.js.snap
packages/gestalt/src/useTapFeedback.js

Add compress styles to `Button` and `IconButton`
To enforce consistency on how buttons and icon buttons behave. We currently have it set conditionally on `Link` and `TapArea` but want to eventually make it consistent across all components.
We updated the class names in `Touchable.css` so the snapshots changed.
Try out the `Button` and `IconButton` out with the new compress style:
* https://deploy-preview-1054--gestalt.netlify.app/#/components/Button
* https://deploy-preview-1054--gestalt.netlify.app/#/components/IconButton

Button/IconButton: compress onClick or onTouch

---

.mergify.yml

The prior regex was slightly too specific and excluded "Blocking PRs with no label".
Triaged this by looking through [the build log](https://github.com/pinterest/gestalt/runs/879721281) on #1054 which saw Mergify pass but other checks fail.

[Merge] Fix merging with no label

---

docs/src/Checkbox.doc.js
packages/gestalt/src/Checkbox.js
packages/gestalt/src/Checkbox.jsdom.test.js
packages/gestalt/src/__snapshots__/Checkbox.test.js.snap

- Adds ref forwarding to Checkbox
- Added ref example to Docs
- Added test for ref 
We have use cases in the Pinterest codebase where we set a ref on a wrapping container for Checkbox in order to anchor other components on it.
<Box><Checkbox/></Box>
To abstract this implementation, let's add a way for them to get it in a dryer way.
Moreover, without forwardedRefs, refs are set on the component's instance, not the actual input. So in each of those cases, people drill down to get the <input />.
That is pretty hacky, so let's add a way for them to get it in a cleaner way.
[https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers](https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers
)
> When you start using forwardRef in a component …

Checkbox: Add forward ref (BREAKING CHANGE)

---

docs/src/Pulsar.doc.js
packages/gestalt/src/Pulsar.js
packages/gestalt/src/__snapshots__/Pulsar.test.js.snap

Changed the default size from 135px to 136px since our boint system encourages lengths to be multiple of 4px. We actually had 136px as the default initially until we changed the default to 120px in #126 and then to 135px in #169 
Also updated the doc, which had wrong default size.

Pulsar: update default size from 135px to 136px

---

docs/src/components/Example.js

This PR fixes CodeSandbox links in docs, which do not work since #1058
before
after
manually tested on localhost

Docs: fix broken CodeSandbox links

---

packages/gestalt/src/Box.test.js

In #986 we discovered `Box` was untyped for a while. In this PR we add an initial test to confirm Box is correctly typed.
Next steps:
* Add this kind of test to other components.
* Flow & jest tests pass
* When changing `margin` on `Box` to a valid type, we should see an error:

Box: add test for flowtypes

---

docs/src/components/Header.js

The `<Sticky />` header causes issues in our docs. It was introduced as part of #952 /cc @AlbertCarreras 
However,  it is convenient to have a sticky header on Gestalt Docs due to the amount of scrolling that is required when reading the Docs. 
A proposed solution is to keep the sticky header on full windows and remove it when windows downsize to a size that doesn't allow the correct display of Modals.

Docs: Fix Header to remove sticky header on reduced window size

---

docs/src/Button.doc.js
docs/src/IconButton.doc.js
packages/gestalt/src/Button.js
packages/gestalt/src/Button.jsdom.test.js
packages/gestalt/src/Checkbox.jsdom.test.js
packages/gestalt/src/IconButton.js
packages/gestalt/src/IconButton.jsdom.test.js

- Adds ref forwarding to `IconButton` & `Button`
- Added ref example to Docs
- Added test for ref 
+ Cleaned examples to use empty tags when needed.
We have use cases in the Pinterest codebase where we set a ref on a wrapping container for `IconButton`/`Button` in order to anchor other components on it.
`<Box><IconButton/></Box>`
To abstract this implementation, let's add a way for them to get it in a dryer way.
Moreover, without `forwardedRef`s, refs are set on the component's instance, not the actual input. So in each of those cases, people drill down to get the innermost `<button />` element.
That is pretty hacky, so let's add a way for them to get it in a cleaner way.
[https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers](https://reactjs.org/docs/forward …

InputButton/Button: Add forward ref (BREAKING CHANGE)

---

packages/gestalt/src/Button.css
packages/gestalt/src/Button.css.flow
packages/gestalt/src/Button.js
packages/gestalt/src/__snapshots__/Toast.test.js.snap
packages/gestalt/src/useFocusVisible.js

Adds `useFocusVisible` a React hook we can use in all of our components to only show the blue outline (focus ring) when using the keyboard.
In this first PR we only apply it to `<Button />`

useFocusVisible: Only show focus ring on keyboard input

---

docs/src/RadioButton.doc.js
packages/gestalt/src/RadioButton.js
packages/gestalt/src/RadioButton.jsdom.test.js

- refactored to function component
- Adds ref forwarding to RadioButton
- Added ref example to Docs
- Added test for ref 
Link to same issue as Checkbox https://github.com/pinterest/gestalt/issues/1068
Without forwardedRefs, refs are set on the component's instance, not the actual input. So in each of those cases, people drill down to get the input.
That is pretty hacky, so let's add a way for them to get it in a cleaner way.
[https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers](https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers
)
> When you start using forwardRef in a component library, you should treat it as a breaking change and release a new major version of your library. This is because your library likely has an …

RadioButton: Add forward ref (BREAKING CHANGE)

---

packages/gestalt/src/Box.js

Fixes https://github.com/pinterest/gestalt/issues/1086
Added support to responsive `marginEnd` `marginStart` for sm/md/lg window size

Box: added support to responsive marginEnd marginStart

---

.eslintrc.json
packages/gestalt/src/Avatar.flowtest.js
packages/gestalt/src/AvatarPair.flowtest.js
packages/gestalt/src/Badge.flowtest.js
packages/gestalt/src/Box.flowtest.js
packages/gestalt/src/Button.flowtest.js
packages/gestalt/src/Callout.flowtest.js
packages/gestalt/src/Card.flowtest.js

Instead of add flow tests to `.test.js` files and having to add a useless `expect` statement, let's create flow specific test files
* Flow passed on CI

Flowtest: Add flow specific test files

---

packages/gestalt/src/RadioButton.jsdom.test.js

Issue was introduced in #1057 @AlbertCarreras 
```
A "describe" callback must not return a value.
Returning a value from "describe" will fail the test in a future version of Jest.
```

RadioButton: fix warning in jest test

---

packages/gestalt/src/TypeaheadInputField.js

The label property is not required for the Typeahead component. This was not reflected in the proptypes.

Typeahead: Fix prop type

---

packages/gestalt/src/Button.js
packages/gestalt/src/Checkbox.css
packages/gestalt/src/Checkbox.css.flow
packages/gestalt/src/Checkbox.js
packages/gestalt/src/Focus.css
packages/gestalt/src/Focus.css.flow
packages/gestalt/src/IconButton.css
packages/gestalt/src/IconButton.js
packages/gestalt/src/Link.js
packages/gestalt/src/RadioButton.css
packages/gestalt/src/RadioButton.css.flow
packages/gestalt/src/RadioButton.js
packages/gestalt/src/Switch.css
packages/gestalt/src/Switch.css.flow
packages/gestalt/src/Switch.js
packages/gestalt/src/TapArea.js
packages/gestalt/src/Touchable.css
packages/gestalt/src/Touchable.css.flow
packages/gestalt/src/TypeaheadOption.js
packages/gestalt/src/__snapshots__/Callout.test.js.snap
packages/gestalt/src/__snapshots__/Link.test.js.snap
packages/gestalt/src/__snapshots__/TableSortableHeaderCell.test.js.snap
packages/gestalt/src/__snapshots__/Tabs.test.js.snap
packages/gestalt/src/__snapshots__/TapArea.test.js.snap
packages/gestalt/src/__snapshots__/Toast.test.js.snap
packages/gestalt/src/__snapshots__/Video.test.js.snap
packages/gestalt/src/__snapshots__/VideoControls.test.js.snap

Follow up from #1073 where we only show the blue outline (focus ring) when using the keyboard.
Other changes:
* Convert Switch to React hooks (in order to use `useFocusVisible`)
* TapArea: no longer prevent bubbling up /cc @jackhsu978 in #906 
For each of these components:
* Button
* Checkbox
* IconButton
* Link
* RadioButton
* Switch
* TapArea
Verify the following:
* Click on the component => You should see no focus style
* Tab to set the focus on the component => You should see the focus style

Button/Checkbox/IconButton/Link/RadioButton/Switch/TapArea: useFocusVisible

---

packages/gestalt-datepicker/package.json

Previously `gestalt` was listed under dependencies which causes a weird yarn.lock file for codebases that use `gestalt-datepicker`.
```
"gestalt-datepicker@https://registry.npmjs.org/gestalt-datepicker/-/gestalt-datepicker-11.4.0.tgz":
--
version "11.4.0"
resolved "https://registry.npmjs.org/gestalt-datepicker/-/gestalt-datepicker-11.4.0.tgz#a468b6bdf145d73c8a4051a3e32334770ad7e1b2"
dependencies:
classnames "^2.2.6"
gestalt ">0.0.0"
prop-types "^15.7.2"
react-datepicker "2.15.0"
 
gestalt@>0.0.0, "gestalt@https://registry.npmjs.org/gestalt/-/gestalt-11.4.0.tgz":
version "11.4.0"
resolved "https://registry.npmjs.org/gestalt/-/gestalt-11.4.0.tgz#6072a8a165bf5252973862f8fe4abe7dd069aa39"
dependencies:
classnames "^2.2.6"
prop-types "^15.7.2"
```
```
rm -rf node_modules
yarn && yarn start
```

Datepicker: move gestalt to peerDependencies

---

.vscode/extensions.json

In #1108 @ashleyseto ran into an issue where VSCode was incorrectly formatting code (not using prettier). The root cause is that the prettier extension is not installed.
After this lands, users will see the following upon restarting VSCode:

VSCode: add recommended extensions

---

packages/gestalt/src/Callout.js

Monetization design requested a change to the info callout icon. They wanted it to be the info icon rather than the check circle. Also VS code seems to have made adjustments in how the code layout automatically on save.
**Before**
**After**

Callout: Update info callout icon

---

docs/src/Provider.doc.js
docs/src/components/App.js
docs/src/components/sidebarIndex.js
packages/gestalt-codemods/11.5.5-12.0.0/__testfixtures__/.eslintrc.json
packages/gestalt-codemods/11.5.5-12.0.0/__testfixtures__/gestaltprovider-to-provider-1.input.js
packages/gestalt-codemods/11.5.5-12.0.0/__testfixtures__/gestaltprovider-to-provider-1.output.js
packages/gestalt-codemods/11.5.5-12.0.0/__testfixtures__/gestaltprovider-to-provider-2.input.js
packages/gestalt-codemods/11.5.5-12.0.0/__testfixtures__/gestaltprovider-to-provider-2.output.js
packages/gestalt-codemods/11.5.5-12.0.0/__testfixtures__/gestaltprovider-to-provider-3.input.js
packages/gestalt-codemods/11.5.5-12.0.0/__tests__/gestaltprovider-to-provider.test.js
packages/gestalt-codemods/11.5.5-12.0.0/gestaltprovider-to-provider.js
packages/gestalt/src/GestaltProvider.flowtest.js
packages/gestalt/src/Provider.flowtest.js
packages/gestalt/src/Provider.js
packages/gestalt/src/index.js

Request by Kelly (UX Writer) to rename `GestaltProvider` to `Provider` & move the component under the configuration section.
Test on Netlify

GestaltProvider: rename to Provider & move under configuration section

---

docs/src/Video.doc.js

Updated Video.doc.js so that the required props match the flow types in Video.js
Here are the required props for Video according to the docs:
Docs did not match with flowtyping from Video.js:

Docs: Updated Required Props for Video

---

packages/gestalt/src/Button.css
packages/gestalt/src/Button.js
packages/gestalt/src/Focus.css
packages/gestalt/src/Link.js
packages/gestalt/src/TypeaheadOption.js
packages/gestalt/src/__snapshots__/Callout.test.js.snap
packages/gestalt/src/__snapshots__/Link.test.js.snap
packages/gestalt/src/__snapshots__/Tabs.test.js.snap
packages/gestalt/src/__snapshots__/Toast.test.js.snap

1) Add the following global CSS to the docs CSS (e.g. `DocSearch.css`)
```
:focus {
outline: 1px auto #d1d1d1;
}
```
2) Ensure you don't see a double / light gray focus style

Focus Styles: override CSS outline if a global one is specified

---

docs/src/Box.doc.js
packages/gestalt/src/Box.js
packages/gestalt/src/Box.jsdom.test.js

- Refactored forwardRef logic to a [proposed standard](https://paper.dropbox.com/doc/Gestalt-forwardRefs--A43M3_lujiEigRQ81g_pZJqoAg-Mp93uiR5uRp7Hb9iLwbiW) for consolidation inside Gestalt components
- forwardRef test
- forwardRef example in Docs

Box: Refactored forwardRef logic + forwardRef test + forwardRef example in Docs

---

docs/src/Button.doc.js
docs/src/Checkbox.doc.js
docs/src/RadioButton.doc.js
packages/gestalt/src/Button.js
packages/gestalt/src/Checkbox.js
packages/gestalt/src/IconButton.js
packages/gestalt/src/RadioButton.js

- Refactored `forwardRef` implementation to prevent rendering 2 components and fix `displayName` in:
1. Button
2. IconButton
3. CheckBox
4. RadioButton
- Fix Doc examples for  CheckBox, RadioButton

Button/IconButton/CheckBox/RadioButton: refactored forwardRef

---

packages/gestalt/src/SearchField.js
packages/gestalt/src/TextArea.js
packages/gestalt/src/TextField.js
packages/gestalt/src/Typeahead.js
packages/gestalt/src/TypeaheadInputField.js

- Refactored `forwardRef` implementation to prevent rendering 2 components and fix `displayName` in:
1. TextArea
2. TextField
3. Typeahead & TypeaheadInputField
4. SeachField
- Fix Proptypes for  SeachField, Typeahead

SearchField/Typeahead/TypeaheadInputField/TextField/TextArea: refactored forwardRef

---

packages/gestalt-datepicker/src/DatePicker.js
packages/gestalt/src/Link.js
packages/gestalt/src/TapArea.js

- Refactored `forwardRef` implementation to prevent rendering 2 components and fix `displayName` in:
1. Link
2. TapArea
3. DatePicker
- Fixed  DatePicker `forwardRef` implementation

Link/TapArea/DatePicker: Refactored forwardRef

---

packages/gestalt/src/zIndex.js

The current type of Indexable leaks an implementation detail with a very unhelpful Flow error message if a user tries to pass integers in the deps array.
Users shouldn't need to know about Indexable; they should only need to know about the exported classes FixedZIndex and CompositeZIndex. While using the Indexable interface for that type is technically correct, it leaks out via the error message. Since we don't anticipate adding many (or any) further implementations of Indexable, it's fine to be explicit with the deps array type to provide a more useful error message.

CompositeZIndex: Update deps array type

---

docs/src/ZIndexClasses.doc.js

ZIndexClasses: Fix typos and linting in docs

---

docs/src/Checkbox.doc.js
docs/src/RadioButton.doc.js
docs/src/Switch.doc.js
docs/src/components/Card.js
docs/src/components/Combination.js
docs/src/components/PropTable.js
docs/src/docs.css
docs/src/index.js
docs/src/reset.css
package.json
yarn.lock

Improve A11Y / SEO and search by adding an anchor to every heading on our docs. It becomes way easier to go to a certain example / section of the page.
Note that the improved search functionality will only start working once the Algolia crawls our pages (every 24 hours).
* Algolia DocSearch: [Add anchors to headings](https://docsearch.algolia.com/docs/tips/#add-anchors-to-headings)
1. Click on a reference in the prop table
2. Ensure the page scrolls to the correct section
1. Go to https://deploy-preview-1123--gestalt.netlify.app/data-display/Avatar#Fixed-Sizes
2. It should scroll to the correct location on the page

Docs: Add id to every heading (improves SEO & Search)

---

docs/src/components/Navigation.js
docs/src/components/SidebarSection.js
docs/src/components/sidebarIndex.js
docs/src/index.js

Internal request by couple of developers.
Before
`https://gestalt.netlify.app/layout/Box`
After
`https://gestalt.netlify.app/Box`
Pros
* Allows developers to quickly go to a component without knowing which subsection it is in.
Cons
* Means that every section in itself needs to be unique. E.g. we can't do `layout/Box` and `forms/Box`.

Docs: single subdirectory URLs

---

packages/gestalt/src/Typeahead.js
scripts/test.sh

We currently have 1 flow warning on master. We didn't catch this because we do allow warnings.
CI checks pass

Internal: disallow flow warnings

---

docs/src/components/Card.js

Algolia was able to re-index our pages but the search doesn't look good. Let's try to improve it by nesting the anchor inside of the heading.
Search improves on the next crawl

Docs: nest anchor inside of heading

---

packages/gestalt/src/useReducedMotion.js

`addEventListener` is not supported in Safari / Edge on the Media Query object
https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList#Methods mentions we should use `addEventListener` with the `change` event when possible. So we use that before trying `addListener`
1. Open Safari
2. Go to the `useReducedMotion` page
3. Ensure there are no exceptions in the console

useReducedMotion: fix in Safari/Edge

---

docs/src/Sticky.doc.js
packages/gestalt/src/Sticky.js
packages/gestalt/src/Sticky.test.js
packages/gestalt/src/__snapshots__/Sticky.test.js.snap

`<Sticky>` container always have the same height has the height of its content. This adds the `height` prop which allows the container to have a different height than its content.

Sticky: add height prop

---

README.md
docs/src/Installation.doc.js

Running `yarn start` serves the docs at http://localhost:8888 after #1115
Confirm this is the right port to use

[Docs] Update port number for running locally

---

packages/gestalt/src/Pog.js

The color red was missing in the prop types causing an erorr:

[Pog]: Add red to prop type

---

docs/src/SelectList.doc.js
packages/gestalt/src/SelectList.js
packages/gestalt/src/SelectList.jsdom.test.js
packages/gestalt/src/SelectList.test.js
packages/gestalt/src/__snapshots__/SelectList.test.js.snap

This is an update adding in the ability to disable options within SelectList as supported in the native select https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option
Tested locally to verify that it works as expected and added two tests.

SelectList: Add disabled to options prop

---

packages/gestalt/src/Avatar.js
packages/gestalt/src/Avatar.jsdom.test.js
packages/gestalt/src/Avatar.test.js
packages/gestalt/src/__snapshots__/Avatar.test.js.snap

We decided to move forward with the `first initial` version of the Avatar when the user has no profile pic
- Removes person icon fallback variant
- Removes `__dangerouslyUseDefaultIcon` prop
Before we had the possibility to choose between person icon or first initial variants for default avatar 
We decided to deprecate the person icon variant. So the first initial is the one to show when the user has no profile pic
Tested locally

Avatar: Remove person icon fallback variant

---

docs/src/components/Markdown.js
netlify.toml

https://gestalt.netlify.app/Installation is currently blank because of a CORS issue. Netlify tries to make a request from https://gestalt.netlify.app/ to https://master--gestalt.netlify.app/ which is not allowed.
Fixes #1147 
1. Go to https://gestalt.netlify.app/Installation
2. Ensure the page loads & shows content

Docs: fix blank installation page

---

docs/src/Video.doc.js
packages/gestalt/src/Video.js

What is the purpose of this PR?
- Adding an option to choose the `crossOrigin` mode for videos so that users can use captions from a different domain if needed
- Additional Context: I broke Gestalt video for [some folks](https://github.com/pinterest/gestalt/pull/1046#discussion_r454048460), and @simkessy [fixed them](https://github.com/pinterest/gestalt/pull/1077)
* What kind of feedback do you want?
- Make sure changes seem reasonable

Video: add crossOrigin option

---

packages/gestalt/src/Button.css
packages/gestalt/src/Button.js
packages/gestalt/src/Checkbox.css
packages/gestalt/src/Checkbox.css.flow
packages/gestalt/src/Checkbox.js
packages/gestalt/src/Focus.css
packages/gestalt/src/Focus.css.flow
packages/gestalt/src/IconButton.css
packages/gestalt/src/IconButton.js
packages/gestalt/src/Link.js
packages/gestalt/src/RadioButton.css
packages/gestalt/src/RadioButton.css.flow
packages/gestalt/src/RadioButton.js
packages/gestalt/src/Switch.css
packages/gestalt/src/Switch.css.flow
packages/gestalt/src/Switch.js
packages/gestalt/src/TapArea.js
packages/gestalt/src/Touchable.css
packages/gestalt/src/Touchable.css.flow
packages/gestalt/src/TypeaheadOption.js
packages/gestalt/src/__snapshots__/Callout.test.js.snap
packages/gestalt/src/__snapshots__/Link.test.js.snap
packages/gestalt/src/__snapshots__/TableSortableHeaderCell.test.js.snap
packages/gestalt/src/__snapshots__/Tabs.test.js.snap
packages/gestalt/src/__snapshots__/TapArea.test.js.snap
packages/gestalt/src/__snapshots__/Toast.test.js.snap
packages/gestalt/src/__snapshots__/Video.test.js.snap
packages/gestalt/src/__snapshots__/VideoControls.test.js.snap

Revert/Revert these 2 PRs:
* #1098: Button/Checkbox/IconButton/Link/RadioButton/Switch/TapArea: useFocusVisible
* #1118: Focus Styles: override CSS outline if a global one is specified
This reverts commit ad4e4d75ac01fc61e45f6aa64c20a903801a36ae.
We previous saw an issue with `useFocusVisible` since we had a page on pinterest.com which was rendering 15000+ TapArea's. Since the bug was discovered, they switched over to using a virtualized list.
For each of these components:
* Button
* Checkbox
* IconButton
* Link
* RadioButton
* Switch
* TapArea
Verify the following:
* Click on the component => You should see no focus style
* Tab to set the focus on the component => You should see the focus style

Revert/Revert "Button/Checkbox/IconButton/Link/RadioButton/Switch/TapArea: useFocusVisible"

---

packages/gestalt/src/SegmentedControl.css
packages/gestalt/src/SegmentedControl.js
packages/gestalt/src/__snapshots__/SegmentedControl.test.js.snap

Make use of `useFocusVisible` in SegmentedControl
1. Go to https://deploy-preview-1157--gestalt.netlify.app/SegmentedControl
2. Click on each SegmentedControl item
3. No outline is visible
1. Go to https://deploy-preview-1157--gestalt.netlify.app/SegmentedControl
2. Tab through each SegmentedControl item
3. Outline is visible

SegmentedControl: make use of useFocusVisible

---

docs/src/components/Markdown.css

After #1145 the docs for each component look off (indented description):
/cc @AlbertCarreras

Docs: update margin/padding for markdown elements

---

packages/gestalt-codemods/11.25.2-11.26.0/__testfixtures__/box_deprecate_size_props.input.js
packages/gestalt-codemods/11.25.2-11.26.0/__testfixtures__/box_deprecate_size_props.output.js
packages/gestalt-codemods/11.25.2-11.26.0/__tests__/box_deprecate_size_props.test.js
packages/gestalt-codemods/11.25.2-11.26.0/box_deprecate_size_props.js

Box: removed deprecated xs, sm, md, lg props + codemod helper
```
<Box xs={{ column: 12, display: "flex" }}>
<RenamedBox md={{ column: 12, display: false }} />
<RenamedBox sm={{ column: 12, display: "flexColumn" }} />
<RenamedBox lg={{ column: 12, display: true }} />
</Box>
```
```
<Box column={12} display="flex">
<RenamedBox mdColumn={12} mdDisplay="none" />
<RenamedBox smColumn={12} smDisplay="flex" smDirection="column" />
<RenamedBox lgColumn={12} />
</Box>
```
Codemod helper, run
`yarn codemod --parser=flow -t=packages/gestalt-codemods/11.25.2-11.26.0/box_deprecate_size_props.js relative/path/to/your/code
`

Box: removed deprecated xs, sm, md, lg props + codemod helper

---

docs/src/components/Navigation.js

Add scrolling to the sidebar, separate from the main content. Allows you to navigate between pages without losing the navigation context.

Docs: separate sidebar scrolling

---

packages/gestalt/src/SelectList.js
packages/gestalt/src/__snapshots__/SelectList.test.js.snap

Convert `SelectList` to a function component. Main reason is to get rid of the duplicated flow types in `defaultProps`. This recently caused an issue with `SelectList` in #1151 
* SelectList tests pass
* SelectList works as expected in the docs

SelectList: convert to function component

---

docs/src/Box.doc.js
docs/src/components/Combination.js

Docs: remove heading for multiple Combination sections on Box

---

docs/src/components/CardPage.js
docs/src/index.js

Makes it easier for people to make updates to a specific page. They only have to click the link on that page + make the updates on GitHub.
1. Go to `/Box` in the Gestalt Docs: https://deploy-preview-1170--gestalt.netlify.app/Box
2. Scroll down to the bottom of the page
3. Click on `Edit this page`
4. It opens https://github.com/pinterest/gestalt/blob/master/docs/src/Box.doc.js

Docs: Add 'edit this page' link to every doc page

---

docs/src/Flyout.doc.js

I recently added a `Flyout` and couldn't figure out why it wasn't using the `size` I set for the width. After reading the code, I saw that `size` actually sets the **max** width for the `Flyout` so I needed to make my content at least that wide. I'm updating the docs to make it more clear for the next person.
Confirm updated documentation makes sense

Flyout: Update docs to mention that size is max width

---

docs/src/components/DocSearch.js

Add search shortcut with forward forward slash to the gestalt docs.
1. Set focus on the page 
2. Type `/`
3. The search box opens
1. Set focus on an input 
2. Type `/`
3. `/` shows up in the input

Docs: Add search shortcut with forward slash

---

docs/src/components/sidebarIndex.js
docs/src/useFocusVisible.doc.js
packages/gestalt/src/index.js

Export the a11y `useFocusVisible` hook which can be used to only show a focus style when tabbing through with a keyboard.
1. Go to `/useFocusVisible`
2. Click on `Button 1` and `Button 2`
3. Only `Button 2` shows the focus style
1. Go to `/useFocusVisible`
2. Tab through `Button 1` and `Button 2`
3. Both buttons the focus style

useFocusVisible: export hook & add docs

---

docs/src/components/App.js

See divider overlap on `SegmentedControl`
No divider overlap on `SegmentedControl`

Docs: fix Divider overlap on bottom of the page

---

docs/src/Modal.doc.js
packages/gestalt/src/Modal.js
packages/gestalt/src/Modal.jsdom.test.js
packages/gestalt/src/__snapshots__/Modal.jsdom.test.js.snap

The purpose of this PR is to add React `forwardRef` to `Modal` in order to be able to reference the Modal container from parent components
Tested locally
There are no UI changes
Renders as expected

Modal: Add forwardRef

---

docs/src/Modal.doc.js
packages/gestalt/src/Modal.css
packages/gestalt/src/Modal.css.flow
packages/gestalt/src/Modal.js
packages/gestalt/src/__snapshots__/Modal.jsdom.test.js.snap

This fix the problem of showing the zoom out icon even when `closeOnOutsideClick` is set to `false`.
That behavior might confuse user thinking that if they click outside the modal this will be closed.
Tested locally

Modal: Prevent showing zoom out icon if closeOnOutsideClick is false

---

package.json
yarn.lock

More info:
* https://github.com/advisories/GHSA-pp7h-53gx-mx7r
* https://nvd.nist.gov/vuln/detail/CVE-2020-8244
>A buffer over-read vulnerability exists in bl <4.0.3, <3.0.1 and <2.2.1 which could allow an attacker to supply user input (even typed) that if it ends up in consume() argument and can become negative, the BufferList state can be corrupted, tricking it into exposing uninitialized memory via regular .slice() calls.
1. `yarn start`
2. Docs still show up correctly

Internal: update bl package (security)

---

packages/gestalt/src/Button.js

`name` is a submit-type button attribute that will be deprecated. However, there are instances in Pinboard using it as an `id`. Initially, it was added just to the submit button and was not reintroduced to type-button buttons. Adding it back. It will be renamed as id in the future.

Button: Flow + name prop fixes

---

docs/src/Layouts.doc.js
docs/src/components/sidebarIndex.js

* Add a "Layouts" page
* Add a `Form Layout` example which is responsive, works with RTL and dark mode

Layouts: Add form layout example

---

packages/gestalt/src/Layer.js
packages/gestalt/src/Layer.test.js

Convert `<Layer />` to a function component. Makes the code more readable + consistent with other components in our codebase.
1. Jest tests pass for `<Layer />`
2. Go to `/Layer` in the docs & verify the layer shows + hides correctly

Layer: convert to function component

---

package.json
packages/gestalt-core/build.js
packages/gestalt-datepicker/package.json
packages/gestalt/package.json
yarn.lock

Make incremental builds (when developing locally) 4x faster than before.
We had to disable rollup watch mode in #877 because it kept appending to the output CSS file instead of updating what is required which caused for an inconsistent dev experience and having to restart a lot.
We fixed this issue by using a cache and setting the id to the CSS filename.
Since gestalt-datepicker relies on gestalt, we will momentarily see errors on every incremental change. Those do get resolved though, as soon as `gestalt.js` is build.
* Run `yarn start` locally
* Make a change
* Changes should take about 3 seconds (compared to 13+ seconds before)

Internal: make incremental builds 4x faster

---

packages/gestalt-core/build.js

Bug caused by #1191 - the legacy CSS was correct but the future CSS was not.
We were seeing the following CSS in the future CSS output:
```
undefined.Qoc{padding-bottom:8px}
```
https://deploy-preview-1198--gestalt.netlify.app/TextField
* Gestalt form components have 8px padding below the label.

Internal: fix 'undefined' CSS in future CSS

---

packages/gestalt/src/Box.js

Reviewing https://github.com/pinterest/gestalt/pull/1193 I realize `xs`,`sm`, `md`, `lg` props were not removed on the PR https://github.com/pinterest/gestalt/pull/1164 as intended.

Box: removal xs, sm, md, lg props

---

docs/public/index.html
docs/src/Icon.doc.js
docs/src/Table.doc.js

* We previously showed a blank page when running `yarn start`, this PR should fix that.
* During incremental builds, we were continuously seeing exceptions about `icons` not being defined on `Icon`.
* Check out this branch
* Run `yarn start`
* Verify the docs show correctly (no blank page)

Internal: avoid blank page on startup in dev + fix most docs exceptions in incremental builds

---

docs/src/Table.doc.js
packages/gestalt/src/Table.css
packages/gestalt/src/Table.css.flow
packages/gestalt/src/TableBody.js
packages/gestalt/src/__snapshots__/TableBody.test.js.snap

Request from design - add a bottom border to each row in a Table
- Test in `<Table />` docs

Table: add bottom border to each row (apart from last item)

---

docs/src/Faq.doc.js
docs/src/components/Markdown.js
docs/src/index.js
packages/gestalt-core/build.js
packages/gestalt-datepicker/src/DatePicker.css
packages/gestalt/src/Borders.css
packages/gestalt/src/Button.css
packages/gestalt/src/Colors.css
packages/gestalt/src/FormElement.css
packages/gestalt/src/Pog.css
packages/gestalt/src/SearchField.css
packages/gestalt/src/Table.css
packages/gestalt/src/TextArea.css
packages/gestalt/src/TextField.css
scripts/cssValidate.js

After experimenting in the main repo with the gestalt-future.css file that has css vars in it, we've determined this is safe to ship. I'm marking this as a breaking change because any app using gestalt that needs to support older browsers such as IE11 will need to use a polyfill. I've already added this one to our app's build for legacy browsers: https://github.com/nuxodin/ie11CustomProperties
Possible improvement: We still have `:root` declarations spread across a few css files. This is nice from a code organization perspective (border width vars defined in Borders.css, color vars defined in Colors.css for example) but makes less sense in the output css file. Perhaps we could combine the declarations into one Variables.css file? Some vars like the ones specific to the datepicker could be …

Internal: BREAKING only build css file with css vars

---

docs/src/Modal.doc.js

Use `<ButtonGroup />` component introduced in #1186 in the Modal examples.
/cc @jennyscript @ashleyseto 
Before and after should be the same in this case
* All spacing between buttons within each modal is 8px

Docs: use ButtonGroup in Modal examples

---

docs/src/Button.doc.js
docs/src/TapArea.doc.js
packages/gestalt-codemods/13.2.0-13.3.0/__testfixtures__/tapArea-remove-tapStyle-prop.input.js
packages/gestalt-codemods/13.2.0-13.3.0/__testfixtures__/tapArea-remove-tapStyle-prop.output.js
packages/gestalt-codemods/13.2.0-13.3.0/__tests__/tapArea-remove-tapStyle-prop.test.js
packages/gestalt-codemods/13.2.0-13.3.0/tapArea-remove-tapStyle-prop.js
packages/gestalt/src/InternalLink.js
packages/gestalt/src/TableSortableHeaderCell.js
packages/gestalt/src/TapArea.flowtest.js
packages/gestalt/src/TapArea.js
packages/gestalt/src/TapArea.jsdom.test.js
packages/gestalt/src/TapArea.test.js
packages/gestalt/src/Video.js
packages/gestalt/src/VideoControls.js
packages/gestalt/src/__snapshots__/InternalLink.test.js.snap
packages/gestalt/src/__snapshots__/TapArea.test.js.snap

- TapArea: implemented href with InternalLink.
- Improved test coverage
- Updated Docs
- Codemod to remove deprecated tapStyle prop
Codemod helper, run
`yarn codemod --parser=flow -t=packages/gestalt-codemods/13.2.0-13.3.0/tapArea-remove-tapStyle-prop.js relative/path/to/your/code
`
Go to Docs, check all new and previous functionality works

TapArea: implemented href with InternalLink

---

docs/src/Table.doc.js
packages/gestalt/src/Table.css

1. Go to `/Table#stickyHeader` in the gestalt docs
2. Scroll down the table
3. Ensure the header is always on top

Table.Header: fix stacking context on sticky header

---

docs/src/Callout.doc.js
packages/gestalt/src/Callout.js
packages/gestalt/src/__snapshots__/Callout.test.js.snap

- Replaced links with link-role Buttons
- Implemented accessibility labels for primary/secondary links
- Updated Docs API

Callout: implement Link Button on primary/secondary links

---

docs/src/Text.doc.js

Raised by @rootvar - the current example is not so helpful. Let's reduce the width so it does become more helpful.

Docs: update Text wrap/overflow example

---

docs/src/Development.doc.js
docs/src/Faq.doc.js
docs/src/Installation.doc.js
docs/src/Layouts.doc.js
docs/src/components/PageHeader.js

Use `<PageHeader />` on all pages + remove the `View Source` on non-component pages
* All page headers look consistent
* Layouts page doesn't show a `View Source` link

Docs: use PageHeader on all pages

---

docs/src/Installation.doc.js
docs/src/Row.doc.js
docs/src/Stack.doc.js
packages/gestalt/src/Row.flowtest.js
packages/gestalt/src/Row.js
packages/gestalt/src/Stack.flowtest.js
packages/gestalt/src/Stack.js

Given how Row/Stack implement `gap` on their children, each child needs to be a React Element — styles won't be applied if given an unwrapped string or other non-Element Nodes.
This PR updates the `children` type for both components, and fixes one non-standard usage in the docs (no visual change that I can detect in the [preview](https://deploy-preview-1216--gestalt.netlify.app/Installation)). The Flow suppressions aren't ideal, but we really don't care what kind of Element we're getting, just that each child is an Element.

Row, Stack: Update `children` type

---

packages/gestalt/src/Box.js
packages/gestalt/src/FlexBox.js
packages/gestalt/src/Row.js
packages/gestalt/src/Stack.js
packages/gestalt/src/boxTransforms.js
packages/gestalt/src/boxTypes.js
packages/gestalt/src/style.js
packages/gestalt/src/transforms.js
packages/gestalt/src/utils/omit.js

After [yet another failed attempt](https://github.com/pinterest/gestalt/pull/1221) at improving Row/Stack, I'm putting that work on the back burner for a month or so. But I don't want to lose the work put into extracting types, transforms, and general cleanup to Box, so here are those changes. This should be a pure refactor, with no visual or API differences.

Box: Extract types and transforms, cleanup

---

docs/src/Box.doc.js
docs/src/Layer.doc.js
docs/src/Modal.doc.js
docs/src/components/DocSearch.css
packages/gestalt/src/Layer.js
packages/gestalt/src/Layer.jsdom.test.js

Add `zIndex` as a prop to `<Layer />`.
In too many cases in the Pinterest codebase, we see the a `<Box />` with position: absolute & zIndex inside of a Layer, just to show the content on top: 
```
<Layer>
<Box position="absolute" zIndex={MODAL_ZINDEX}>
{children}
</Box>
</Layer>
```
Instead, we would like to write the following:
```
<Layer zIndex={MODAL_ZINDEX}>
{children}
</Layer>
```
* Verify the `Layer` with zIndex shows on top of the sticky header (with zIndex of `1`) in the docs.
Sticky header is on top of the Layer
Sticky header is below the Layer

Layer: add zIndex prop

---

.flowconfig
packages/gestalt-codemods/13.14.0-14.0.0/sticky-find-deprecated-dangerouslySetZIndex.js
packages/gestalt/src/Sticky.flowtest.js
packages/gestalt/src/Sticky.js

`dangerouslySetZIndex` has been removed from the Pinterest codebase.
* Remove `dangerouslySetZIndex` from `<Sticky />`
* Add a codemod to find legacy usages when other people upgrade
* Add flow test for `<Sticky />`
* `dangerouslySetZIndex` is no longer available on Sticky

Sticky: remove deprecated dangerouslySetZIndex

---

cypress/integration/accessibility_button_spec.js
cypress/integration/accessibility_root_spec.js
docs/src/components/Checkerboard.js
docs/src/components/Example.js

Add accessibility tests to the Button tests. This is our first test for a component page so it should set the foundation for other pages as well.
* CI tests (especially the cypress one) passes

Button: add accessibility integration tests

---

docs/src/Masonry.doc.js
packages/gestalt-datepicker/src/LocaleDataTypes.js
packages/gestalt/src/Masonry.js
packages/gestalt/src/MeasurementStore.js
packages/gestalt/src/SelectList.js

We added the linter `flowtype/require-exact-type` in #946, but we disable the linter in several places. 
For the same reasons we added the `flowtype/require-exact-type` linter, disabling these errors is actually very bad because the downstream projects do not really respect the exact-by-default logic and would still treat `{ }` as inexact. We should avoid using `{ }` to flow running in downstream projects correctly know whether object type is exact and inexact without any ambiguity. 
This PR fixes all linter errors. Note that in some cases we actually meant to use inexact types. I have made sure that they are correctly typed as inexact.
Flow

Internal: fix `flowtype/require-exact-type` errors

---

README.md

Adds a link + badge for Cypress to our README file.
- Badge + link show up in the readme

Internal: Add Cypress badge + link to Readme

---

docs/src/components/Example.js
docs/src/components/ExampleCode.js
docs/src/components/handleCodeSandbox.js

While scrolling through our component docs, the amount of code we see is overwhelming. This PR adds an `Expand code` button which expands the code when required.
* The max height of the code is `100` with a threshold of `80`. So we will only show the expand button when the height is > 180px.
* This is a first stab - definitely open for design suggestions.
* On the netlify preview, we see `Expand code` on all code examples which have a height of + 180px.

Docs: add ability to expand code examples

---

docs/src/Video.doc.js
packages/gestalt/src/Video.js
packages/gestalt/src/Video.test.js
packages/gestalt/src/__snapshots__/Video.test.js.snap

When Story Pins started using the Gestalt `Video` component for MP4s (experiment gated), employees noticed that the "poster", or placeholder while the video loads, was being displayed distorted. 
Setting the style as 'object-fill: contain` seems to fix the issue, so this PR adds the specific `object-fill` part of the style as an optional prop.
Internal e2e testing confirms this will be a fix, and you can locally observe the style is passed correctly:

Video: add `objectFill`  as a prop

---

.github/workflows/integration-tests.yml
cypress/fixtures/example.json

Since we added more Cypress integration tests in #1233, the builds now take +11 minutes to complete. Let's see what the impact is of parallelizing these tests.
This does expose the cypress record key since it's [required for parallelization](https://docs.cypress.io/guides/guides/parallelization.html#CI-parallelization-interactions). The risk is that others would pollute our dashboard runs (unlikely) but the benefits are:
* Forked runs are recorded in the dashboard
* Parallelization should work 
* Integration tests pass
* Total time to run is < 11 minutes

Internal: Parallelize Cypress integration tests (2x speed improvement)

---

docs/src/Text.doc.js

The default value of `size` prop of the `<Text>` component has been changed from "md" to "lg", but the [code example](https://gestalt.netlify.app/Text#size) in the doc hasn't been updated. This PR updates the code example.
Before:
After:

Doc: update Text size example

---

docs/src/Sheet.doc.js
packages/gestalt/src/Sheet.flowtest.js
packages/gestalt/src/Sheet.js
packages/gestalt/src/Sheet.jsdom.test.js
packages/gestalt/src/__snapshots__/Sheet.jsdom.test.js.snap

Depends on https://github.com/pinterest/gestalt/pull/1236
This PR adds a new prop "subHeading" to support a use case where certain designs ask for a sub-heading docked under the heading.
This "subHeading" prop shall take a Node or a Render prop to behave similar to "footer" and "children" so it can contain exitpoints which may trigger "out" animations.
Tested on <Sheet> docs
Tested with OS reduced motion activated

Sheet: Add subHeading prop [Depends on #1236]

---

docs/src/Button.doc.js
docs/src/IconButton.doc.js
docs/src/TapArea.doc.js
packages/gestalt/src/Button.js
packages/gestalt/src/Button.jsdom.test.js
packages/gestalt/src/IconButton.js
packages/gestalt/src/IconButton.jsdom.test.js
packages/gestalt/src/InternalLink.flowtest.js
packages/gestalt/src/InternalLink.js
packages/gestalt/src/InternalLink.jsdom.test.js
packages/gestalt/src/InternalLink.test.js
packages/gestalt/src/Link.jsdom.test.js
packages/gestalt/src/TapArea.js
packages/gestalt/src/TapArea.jsdom.test.js
packages/gestalt/src/__snapshots__/ActivationCard.test.js.snap
packages/gestalt/src/__snapshots__/ButtonGroup.test.js.snap
packages/gestalt/src/__snapshots__/Callout.test.js.snap
packages/gestalt/src/__snapshots__/IconButton.test.js.snap
packages/gestalt/src/__snapshots__/InternalLink.test.js.snap
packages/gestalt/src/__snapshots__/Sheet.jsdom.test.js.snap
packages/gestalt/src/__snapshots__/TableSortableHeaderCell.test.js.snap
packages/gestalt/src/__snapshots__/TapArea.test.js.snap
packages/gestalt/src/__snapshots__/Toast.test.js.snap
packages/gestalt/src/__snapshots__/Video.test.js.snap
packages/gestalt/src/__snapshots__/VideoControls.test.js.snap

For accessibility reasons, sometimes we have to remove components from the sequential keyboard navigation.
We use implement `tabIndex` https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex in `Button`, `TapArea`, and `IconButton`.
Added tests and updated documentation for each component to cover all tabIndex combinations.
- Added test coverage to check for tabIndex in the innermost component
- Tested in Docs https://www.loom.com/share/91f4c25c87bb4be69579084ff5199446

Button/TapArea/IconButton: add tabIndex prop

---

package.json
scripts/generateComponent.js

I noticed a couple of ESLint warnings sneaked in due to my PR: #1243. Let's:
* Disallow any ESLint warnings + fail CI if there are any
* Fix the current warnings with an ESLint disable
* ESLint passes in CI

Internal: fail CI on ESLint warnings

---

docs/src/components/CardPage.js
docs/src/components/Example.js
docs/src/components/ExampleCode.js

Updates the design for code examples:
* Auto collapse a code example when it gets focus
* List buttons horizontally so we can add more (if required) over time
* Increase whitespace
Thanks to @ajmoo for the designs!
* CodeSandbox / Copy code + expand code work as expected

Docs: update design for code examples

---

docs/src/components/Example.js

We landed #1245 after #1248 which used `borderSize` instead of the new `borderStyle`

Docs: fix borderSize to borderStyle for Example

---

cypress/integration/accessibility_ActivationCard_spec.js
package.json
scripts/test.sh
scripts/validateAccessibilitySpecs.js

Adds a test to CI to ensure every page in our docs has an accessibility integration test /cc @AlbertCarreras @ayeshakmaz 
CI passes

Internal: Validate that each doc page has an a11y test

---

docs/src/Box.doc.js

Box: fix docs for Layout section

---

docs/src/Table.doc.js
packages/gestalt/src/TableRowExpandable.flowtest.js
packages/gestalt/src/TableRowExpandable.js
packages/gestalt/src/TableRowExpandable.jsdom.test.js
packages/gestalt/src/TableRowExpandable.test.js

The purpose of this PR is to add the onExpand function prop to the Table.RowExpandable component. 
An example use case for this prop would be if a user wanted to request an API call **only** when the row is expanded. 
I used the docs and created more tests to make sure the function prop works as needed.

Table: Add onExpand function prop to RowExpandable

---

docs/src/ActivationCard.doc.js
packages/gestalt/src/ActivationCard.js
packages/gestalt/src/__snapshots__/ActivationCard.test.js.snap

Now that Box supports drop shadow, this PR updates activation card to use the the shadow border per original designs. Also included in this PR is an update to the docs to ensure that the activation cards within a group are the same width.
Before:
After:

ActivationCard: Add shadow border and polish docs

---

package.json
packages/gestalt-datepicker/package.json
packages/gestalt/package.json

https://www.skypack.dev/view/gestalt surfaced a couple of fields we should add to our `package.json` file:
* `repository`: Make it easy to see where the code lives when you've install the package
* `keywords`: Improves discoverability of the the package
* `exports`: Explicitly states which files are meant to be imported:
Before
```
import "../node_modules/gestalt/dist/gestalt.css";
```
After
```
import "gestalt/css";
```
CI Passes

Internal: improve package.json with repository / keywords + exports information

---

cypress/integration/accessibility_root_spec.js

Issue was that in the sidebar we wrap a `TextField` in a `<div />` which we don't do on the `What's New` Page
* CI tests pass

Tests: Fix flaky test on master

---

docs/src/components/App.js
docs/src/components/Header.js
docs/src/components/useLocalStorage.js

* Persist dark mode and RTL settings across refreshes (using local storage)
* Introduces `useLocalStorage` to make it easier to work with local storage in our docs. Forked from https://usehooks.com/useLocalStorage/
1. Go to `/`
2. Switch to dark mode
3. Reload
Expected result: dark mode is still enabled.

Docs: persist dark mode and RTL settings across refreshes

---

docs/src/Tooltip.doc.js
packages/gestalt/src/Tooltip.js
packages/gestalt/src/Tooltip.jsdom.test.js

This diff adds a zIndex prop to the Tooltip component, allowing users to set a zIndex value.
* What is the context surrounding this PR? Include links if possible.
Tooltip doesnt work well with modals as modals have a higher Z index. This enables developers to set a custom z index on the tooltip so it can show over the modals.
* What kind of feedback do you want? Code review
* Have you [formatted the PR title](https://github.com/pinterest/gestalt/#releasing)? `ComponentName: Description` Yes
How can reviewers verify this is good to merge?
* Is it tested? Yes, unit tests pass
* Is it accessible? No changes to accessibility
* Is it documented? Yes
* Have you involved other stakeholders (such as a Pinterest Designer)? yes

Tooltip: Add zIndex prop

---

docs/src/Masonry.doc.js
packages/gestalt/src/Masonry.js

The UniformRowLayout example is not showing uniform rows

Docs: Fix UniformRowLayout example

---

cypress.json

Avoid flaky test runs by adding retries. We had a few instances where we had to re-run the whole test suite in GitHub CI just to fix 1 flaky test.
* Add retries: https://docs.cypress.io/guides/guides/test-retries.html#Global-Configuration
* Add JSON schema to show a description of each property on hover (in VSCode)
https://www.cypress.io/blog/2020/06/18/extending-the-cypress-config-file/
* Cypress integration tests pass

Internal: Add integration test retries

---

docs/src/Upsell.doc.js

Updating the example for the title and message upsell so we don't hit the first breakpoint in the docs. Design will be confused at the buttons being on the 2nd line.

Docs: Update Upsell.doc.js with better examples

---

docs/src/components/PropTable.js

We currently have a combination of single quotes and double quotes in the proptable.
https://gestalt.netlify.app/Toast
https://deploy-preview-1292--gestalt.netlify.app/Toast

Docs: unify quotes in the proptable

---

packages/gestalt/src/Flex.js
packages/gestalt/src/FlexItem.js

Update to give display names to Flex and FlexItem to help debug react components 
Before:
After:

Internal: Give Flex and FlexItem display names for debugging

---

cypress/integration/accessibility_What's New_spec.js
cypress/integration/accessibility_root_spec.js

The accessibility tests for the What's New page are timing out (probably since it's such a big page)
https://github.com/pinterest/gestalt/pull/1298/checks?check_run_id=1484632738
```
2020-12-02T06:36:27.4710907Z Running: accessibility_root_spec.js
2020-12-02T06:36:27.4714615Z Estimated: 35 seconds
2020-12-02T06:36:30.3826130Z Browserslist: caniuse-lite is outdated. Please run:
2020-12-02T06:36:30.3834718Z npx browserslist@latest --update-db
2020-12-02T06:36:31.8556132Z 
2020-12-02T06:36:31.8767576Z Accessibility
2020-12-02T12:33:42.7476928Z ##[error]The operation was canceled.
```
CI passes

Internal: Fix a11y tests on master

---

docs/public/index.html
docs/public/opensearch.xml

Adds OpenSearch support to the Gestalt docs so users don't have to manually set up their browsers. Thanks to @ayeshakmaz for pointing us in this direction
https://developer.mozilla.org/en-US/docs/Web/OpenSearch
https://www.chromium.org/tab-to-search
1) Go to https://gestalt.netlify.app/ once
2) Type `Gest` in the URL bar
3) You should see an autocomplete for Gestalt
4) Hit the `TAB` key
5) Type `Box`
6) It takes you to the `Box` docs page
Note: we'll only be able to test this once `opensearch.xml` is on the prod docs

Docs: Add search autodiscovery (OpenSearch)

---

docs/src/Upsell.doc.js
packages/gestalt/src/Upsell.flowtest.js
packages/gestalt/src/Upsell.js
packages/gestalt/src/Upsell.test.js
packages/gestalt/src/__snapshots__/Upsell.test.js.snap

This PR adds an optional image prop that can be used to add in an image or icon to the left side of the banner.
Icon and Image examples 
On smaller screens
Added additional tests and manually verified that components respond to different screen sizes as expected.

Upsell: Add image prop

---

packages/gestalt/src/Callout.js
packages/gestalt/src/Upsell.js
packages/gestalt/src/__snapshots__/Callout.test.js.snap
packages/gestalt/src/__snapshots__/Upsell.test.js.snap
packages/gestalt/src/useReducedMotion.js
packages/gestalt/src/useResponsiveMinWidth.js
packages/gestalt/src/useResponsiveMinWidth.jsdom.test.js
packages/gestalt/src/useResponsiveMinWidth.test.js
packages/gestalt/src/utils/matchMedia.js

Implemented `useResponsiveMinWidth` which uses `window.matchMedia` to return the size of the screen for each breakpoint size. This new hook implementation allows implementing responsiveness to any component props.
Having duplicated components in the `render()`  on tests is confusing for developers. Test could require changes as a result of having to duplicate one same component using `display='none'` & `smDisplay='none'` to  be able to achieve some responsiveness behaviors.
For example, we had this in `Callout` and `Upsell`
```
{/* We repeat this code block to ensure that text is 
centered for our smaller displays and left aligned 
for larger displays */}
<Box smDisplay="none">
{title && (
<Box marginBottom={2}>
<Heading align="center" size="sm">
{title}
</Heading>
</Box>
)}
<Text …
```

Callout/Upsell: Implemented new useResponsiveMinWidth hook and utils

---

packages/gestalt/src/Backdrop.css
packages/gestalt/src/Colors.css
packages/gestalt/src/Mask.css

Update Modal's Backdrop wash to 80% opacity black
- added new var   --g-colorTransparentGray800: rgba(0, 0, 0, 0.8);
- Also changed the Mask wash to be 4% opacity to be consistent with mobile
Before:
After:
Manually verified visually

Modal: Update backdrop wash to 80% opacity

---

docs/src/Flyout.doc.js

Design realized there was a mistake in the docs with the text being bold by default in flyouts. It should be regular weight.

Update Flyout Docs - Remove bold text

---

docs/src/Tag.doc.js
docs/src/TextField.doc.js

Updating the docs for the tags example
- Link to Tag component
- Enter/return and whitespace characters now create a new tag in the example
- We now filter out empty tags
Played around with the example, made sure the above works

Textfield: update tags props docs

---

docs/src/Modal.doc.js
packages/gestalt/src/Modal.flowtest.js
packages/gestalt/src/Modal.js

This PR updates modal so that it can take a subHeading prop to add a subtitle under the heading and an align prop to justify the heading text left or center.
All tests are passing and I manually checked the doc examples to make sure that no unintended changes occurred.

Modal: Add subHeading and align props

---

docs/src/Layer.doc.js

This diff is just improving documentation for Layer to explain and illustrate with an example the importance of avoiding re-renderings to prevent the content from being destroyed with an accidental parent re-render.

Layer: Update documentation examples around avoiding unwanted re-rendering

---

packages/gestalt/src/Callout.js
packages/gestalt/src/__snapshots__/Callout.test.js.snap

This PR intends to fix a bogus vertical padding behavior of Callout component when there isn't action buttons and the message is long and its width transitions from something around 750px to 700px. Current behavior presents a bottom padding that is taller than the upper padding. That behavior can be confirmed by adjusting the window width in the sandbox link and the screenshot below.
https://codesandbox.io/s/error-example-forked-mg0ji?file=/example.js
The only change was to avoid rendering a Box without action buttons in the Callout component
Manually tested the change by loading the Callout Gestalt Docs page and set a long message in a sample that has no action buttons, then narrowing window width and checking that the isn't a vertical padding issue anymore. See attached screen …

Callout: Fix vertical padding in md viewport when no actions present

---

docs/src/Layer.doc.js
packages/gestalt/src/Layer.js

This fixes #1326.
When we pass `zIndex` indexable object and the reference is changed, the cleanup routine of `useEffect` hook, which depends on `zIndex` would be fired and would replace the entire children tree with a new one. I believe this is an oversight when we added `zIndex` support in #1223. I am fixing this bug by:
1. make sure the `useEffect` hook which appends/removes a div element only runs on mount/unmount.
2. the zIndex is handled by a separate `useEffect` after the `useEffect` hook above so that it (1) initiailizes the zIndex after the div has been created on mount, and (2) updates zIndex-related attributes of the div element whenever the value of the zIndex prop changes.
I also removed the documentation where we encourage people to avoid rerendering. Avoid rerendering …

Layer: fix a bug where Layer ummounts children on rerender when zIndex changes

---

docs/src/DatePicker.doc.js
docs/src/Development.doc.js

Add info about versioning to the Development docs page
n/a

Docs: Add versioning info to development page

---

package.json

This adds the `sideEffects: false` setting to package.json. It's used by bundlers like webpack to [determine if it's safe to tree shake](https://webpack.js.org/guides/tree-shaking/) out unused code such as re-exports. No modules in gestalt have side effects as defined in the webpack docs, so this should be safe to add. This appears to have no effect on the build generated by rollup, but rather will be used by projects importing gestalt.
Code builds as normal

Internal: Mark package as not having side effects

---

docs/src/Callout.doc.js
docs/src/Upsell.doc.js
packages/gestalt/src/Callout.js
packages/gestalt/src/Upsell.js
packages/gestalt/src/commonTypes.js

We were showing this type as required when it's actually optional. This PR updates the docs for both Callout and Upsell to reflect the correct type.
I also deduped the common types between the two components, putting them in a `commonTypes.js` file. That file has a lot of potential to become a "kitchen sink" type dumping ground, so we'll need to revisit the name in the future. That more correct name wasn't obvious to me now, so I went with the (temporary) generic name.

Callout, Upsell: Fix action href type in docs, dedupe type definitions

---

cypress/integration/accessibility_Module_spec.js
docs/src/Module.doc.js
packages/gestalt/src/ModuleExpandable.flowtest.js
packages/gestalt/src/ModuleExpandable.js
packages/gestalt/src/ModuleExpandable.jsdom.test.js
packages/gestalt/src/ModuleExpandable.test.js
packages/gestalt/src/__snapshots__/ModuleExpandable.test.js.snap
packages/gestalt/src/moduleTypes.js

ModuleExpandable: added external collapsing control (expandedIndex and onExpandedChange)
with Tests and Docs examples

ModuleExpandable: added external collapsing control (expandedIndex and onExpandedChange)

---

docs/src/components/PageHeader.js

A couple of small tweaks to the source link on component pages:
- Update copy to "View source on Github" to make the link more prominent and clear
- Add `target="blank"` to open the target in a new tab

Docs: component source link tweaks

---

docs/src/Typeahead.doc.js
packages/gestalt/src/Typeahead.js

Typeahead didn't include zIndex prop to support component within Modals with existing zIndex. Other components as Dropdown do include zIndex to support these cases.
This PR implements zIndex prop in Typeahead and adds an example to the Docs
Without the zIndex, the Typeahead is overlayed by the Modal zIndex.
NOTE: This fix allows Typeahead in Modals with zIndex but scrollable Modals will present Flyout positioning issue.  To be fixed with the upcoming ScrollableBox component.

Typeahead: add zIndex prop to support component in Modals with zIndex

---

packages/gestalt/src/Box.js
packages/gestalt/src/Dropdown.js
packages/gestalt/src/Sticky.js
packages/gestalt/src/Typeahead.js
packages/gestalt/src/zIndex.js

Also so that future updates are easier when we figure out the correct PropType to use.
And some unrelated type de-duping in Sticky, since I was in there.

Z-Index: Consolidate proptype to reduce needed suppressions

---

package.json
yarn.lock

`immer` is a dependency of `react-dev-utils`, which is a dependency (and sub-package) of `react-scripts`, part of Create React App. (We use CRA for the docs site.) There is a security concern with the current version (7.0.9), which has been fixed in 8.0.1. Neither `react-scripts` nor `react-dev-utils` have updated, so this PR adds a resolution (hopefully temporarily) to use the newer version of that package.

Internal: bump resolved version of immer due to security concern

---

docs/src/Button.doc.js
docs/src/components/Card.js
docs/src/components/Example.js
docs/src/components/ExampleCode.js
docs/src/components/MainSection.js
docs/src/components/MainSectionCard.js
docs/src/components/MainSectionSubsection.js

Adds MainSection, MainSection.Subsection, and MainSection.Card components for docs redesign
Supports small and medium sizes (2 vs 3 across), and Do, Don't, or Info styles
**Dos and Don'ts:**
**Variants Info:**

Docs: Add shared documentation components for docs redesign

---

docs/src/components/Card.js

Linking icon scrolls to top, hashes url in browser, and (NEW!) now it also copies new hashed url for quick sharing.

Docs: copyPaste functionality implemented into linking icon

---

docs/src/Box.doc.js
docs/src/components/MainSectionCard.js
scripts/templates/ComponentName.doc.js

You can now make Do/Don't bullet-lists, with no code or example
Do/Don't also no longer show code blocks

Docs: Add ability for Do/Don't in bullet lists

---

docs/src/Provider.doc.js
docs/src/components/MainSection.js
docs/src/components/MainSectionCard.js
docs/src/components/MainSectionSubsection.js
docs/src/components/PropTable.js
docs/src/components/atomDark.js
docs/src/components/utils.js

Move title and description above large Cards
(also fixes a code editor bug where the cursor wasn't visible)

Docs: Adjust spacing for large examples with titles

---

packages/eslint-plugin-gestalt/src/__fixtures__/prefer-box/invalid/invalid-border.js
packages/eslint-plugin-gestalt/src/no-dangerous-style-duplicates.js
packages/eslint-plugin-gestalt/src/prefer-box.js
packages/eslint-plugin-gestalt/src/prefer-box.test.js
packages/eslint-plugin-gestalt/src/validators.js

Shares logic with the existing `no-dangerous-style-duplicates` to check for divs that could be a `Box`.
New unit test added to check rule works as expected

[Eslint] Add border to prefer-box eslint rule

---

docs/src/components/App.js
docs/src/components/CardPage.js
docs/src/components/Toc.js

and other misc cleanup.
[Bug ticket](https://jira.pinadmin.com/browse/BUG-121250)
This is essentially a copy/paste of Christian's fix for the left sidebar scroll behavior, but for the right sidebar. For some components (e.g. Box) that sidebar can be pretty lengthy, and on shorter viewport heights it can be taller than the viewport. The current behavior is that the sidebar doesn't scroll up until the user reaches the end of the content, which isn't great. This PR adds the ability to scroll that sidebar independent from the content. For most users, there should be no noticeable change.
New scroll behavior on shorter screens:
https://user-images.githubusercontent.com/12059539/107691248-0fa40600-6c60-11eb-867d-1da88a1f442f.mov
No changes for normal height screens: …

Docs: fix right sidebar scrolling bug

---

docs/src/Box.doc.js
docs/src/Button.doc.js
docs/src/Checkbox.doc.js
docs/src/IconButton.doc.js
docs/src/Provider.doc.js
docs/src/RadioButton.doc.js
docs/src/Sheet.doc.js
docs/src/TapArea.doc.js
docs/src/Upsell.doc.js
docs/src/Video.doc.js
docs/src/components/Markdown.js
docs/src/components/PropTable.js

Change prop table descriptions to use Markdown (allows for links)
Before: 
After:

Docs: Update Prop Table to support Markdown for descriptions

---

docs/src/ActivationCard.doc.js
docs/src/Callout.doc.js
docs/src/Upsell.doc.js
packages/gestalt/src/ActivationCard.js
packages/gestalt/src/Callout.js
packages/gestalt/src/Upsell.js
packages/gestalt/src/commonTypes.js

- Link, Button, IconButton, and TapArea all had the same link API: `href`, `target`, `rel`, `onNavigationProps`
- Callout, Upsell, ActivationCard only had `href` and `onNavigationProps`
- This PR standardizes the link API by adding `target`, `rel` to Callout, Upsell, ActivationCard
- Updates Docs
- This change would also help the implementation of `OnNavigation` context as `target` is one of the parameters passed to the OnNavigation prop.

Callout, Upsell, ActivationCard: implemented missing target, ref props for link functionality

---

docs/package.json
package.json
packages/gestalt-datepicker/package.json
packages/gestalt/package.json
yarn.lock

This updates React-related dependencies to version 17.x and also allows these versions as a peerDependency. This should be safe because react is set up as an external in the build and the main repo using gestalt has already been on React 17 for a few weeks without issue.
Confirmed gestalt is working properly in the main repo

Internal: Update to React 17

---

docs/src/components/Toc.js

The recent right sidebar scrolling bugfix has a bug, where the sidebar is overlaid on the footer. This PR adds a bottom margin to the right sidebar to account for the footer height.
https://user-images.githubusercontent.com/12059539/108290663-bb0ff780-7145-11eb-951e-7d12d16bef00.mov

Docs: Make sure right sidebar doesn't extend over footer

---

docs/src/Typeahead.doc.js
packages/gestalt/src/Typeahead.js

As described in [this bug](https://jira.pinadmin.com/browse/BUG-122028), Typeahead doesn't update when `options` changes. Because it was storing the initial value of `options` in a ref (which is persisted over renders), the component doesn't respond to any changes to that prop.
This PR removes that ref and uses the `options` value directly instead.

Typeahead: Bugfix to ensure the current value of `options` is used, not just the initial

---

cypress/integration/accessibility_Dropdown_spec.js
docs/src/components/Card.js
docs/src/components/ExampleCode.js
docs/src/components/MainSectionSubsection.js
docs/src/components/Markdown.css
docs/src/components/PropTable.js
docs/src/components/Toc.js

JIRA[ PDS-2499](https://jira.pinadmin.com/browse/PDS-2499)
- Swap expand/collapse icons (both the chevron next to props and the eye next to code blocks) with maximize/minimize icons.
- Swap the copy code icon (currently using the Story Pin icon) with the drag-drop icon.
- Update Icon Button size next to section titles from "s" to "xs" (so that all icons are consistently sized at 24x24)
- Update all Icon Button colors to "darkGray" instead of "gray"
- Ensure that every icon provides a Tooltip on hover. Make sure the Tooltip text is in sentence case.
No tooltip → "Copy link"
"Expand/Collapse Props" → "Expand/Collapse props"
current docs tests

Docs: Update IconButton styling and size across docs

---

docs/src/Box.doc.js

We have a subtle bug on the new Box docs page, where the code example covers the header:
https://user-images.githubusercontent.com/12059539/109564651-381c6480-7a96-11eb-93bc-262c8e1e5e57.mov
Obviously not a show-stopper, but a little annoying, right?
While reading a blog post, [this section](https://www.joshwcomeau.com/css/stacking-contexts/#airtight-abstractions-with-isolation) jumped out at me. A possible solution for this bug? As it turns out: yes!
https://user-images.githubusercontent.com/12059539/109564848-79ad0f80-7a96-11eb-90d4-24556dae01f1.mov

Docs: fix Box z-index bug

---

docs/src/Module.doc.js
packages/gestalt/src/Module.js
packages/gestalt/src/ModuleExpandable.js
packages/gestalt/src/ModuleExpandableItem.js
packages/gestalt/src/ModuleTitle.js
packages/gestalt/src/__snapshots__/Module.test.js.snap
packages/gestalt/src/__snapshots__/ModuleExpandable.test.js.snap
packages/gestalt/src/__snapshots__/ModuleExpandableItem.test.js.snap
packages/gestalt/src/moduleTypes.js

Per https://jira.pinadmin.com/browse/PDS-2601, Module was using the wrong border-radius. This PR updates that value. It also includes misc cleanup to simplify markup, lint/prettify the docs examples code, etc.
- Border radius to 16px
DESIGN | BEFORE | AFTER
------------- | ------------ | -------------
- Refactor Module and subModules props so shared ones are in separate files but non-shared ones stay in the same file. Alphabetize.
- Refactor Module and subModules to replace Flex with Box when possible
- Refactor Module.Expandable/ExpandableItem to replace misused Fragments with Box
- Docs: cleanup for better reading and prop alphabetization.

Module: Fix border-radius + misc cleanup

---

docs/src/Box.doc.js
docs/src/Callout.doc.js
docs/src/Tooltip.doc.js
docs/src/components/FeedbackCallout.js

These are all using the same URL, with the only change being the component name query param. This PR makes FeedbackCallout simpler to use and eliminates possible copy/paste errors with the link.

FeedbackCallout: Simplify API

---

docs/src/Image.doc.js
packages/gestalt/src/Image.js

This PR adds the `elementTiming` attribute to `<img>` tag rendered by the `<Image>` component so that it is possible to use the [Element Timing API](https://developer.mozilla.org/en-US/docs/Web/API/Element_timing_API) to get the image timings such as [`loadTime`](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceElementTiming/loadTime) and [`renderTime`](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceElementTiming/renderTime)
Note that while the actual HTML attribute is all lowercased, the `elementTiming` prop is camelCased since it is an established Gestalt convention.

Image: add elementtiming attribute for profiling

---

.eslintrc.json
.flowconfig
babel.config.js
docs/src/components/Header.js
package.json
yarn.lock

This just enables the transform. A future PR will codemod away all the now-unneeded React imports — I left that off this one to make the PR cleaner and easier to read.

Internal: Upgrade JSX transform so React no longer needs to be in scope

---

docs/src/components/Card.js
docs/src/components/ExampleCode.js
docs/src/components/Header.js
docs/src/components/HeaderMenu.js
docs/src/components/MainSectionSubsection.js
docs/src/components/PageHeader.js
docs/src/components/appContext.js
docs/src/components/buttons/CollapseExpandCodeButton.js
docs/src/components/buttons/CopyCodeButton.js
docs/src/components/buttons/CopyLinkButton.js
docs/src/components/buttons/DarkModeButton.js
docs/src/components/buttons/LTRButton.js
docs/src/components/buttons/OpenSandboxButton.js
docs/src/components/buttons/SidebarCategorizationButton.js
docs/src/components/buttons/trackButtonClick.js
docs/src/components/navigationContext.js

This PR adds Google Analytics event tracking to all our buttons across the docs. If there's a button I missed, please let me know!
We're logging the button clicked, and sometimes additional metadata where useful. You can check this by viewing the [real-time events](https://analytics.google.com/analytics/web/#/realtime/rt-event/a12967896w242172598p225758288/metric.type=5&filter.list=40==button;) and clicking around on the preview site.

Docs: Add event tracking for buttons

---

packages/gestalt/src/Tooltip.js

[bugfix](https://jira.pinadmin.com/browse/BUG-122739)
We currently delay the fade-out on mouseLeave/blur to allow the user to interact with the Tooltip content. However, this is only necessary if a `link` is present, and the delay leads to a confusing UI when multiple tooltips are used in a row. Long-term, we should create a more robust solution to allow user interaction with the tooltip content while not needing a delay. As a short-term fix, this PR only applies the delay if the `link` prop is used.

Tooltip: Only delay visibility on interaction if `link` present

---

docs/src/SearchField.doc.js
packages/gestalt/src/SearchField.js
packages/gestalt/src/SearchField.jsdom.test.js

I was trying to implement search results dropdown UI for the SearchField gestalt component. But I ran into a roadblock figuring out how to implement keyboard navigation in the search results dropdown since there is no way to handle keyboard events in SearchField. I concluded that this was not possible without adding a `onKeyDown` prop to SearchField. 
Alternatively, I could have used TextField component which has `onKeyDown` prop but I would lose some of the UI benefits of using SearchField such as the icons.
I also considered using Typeahead component but I need to customize the search results UI to more than just rows of text. 
Here is a screenshot of what I'm trying to build:
I plan to handle ArrowUp, ArrowDown, and Enter keyboard events to implement keyboard navigation on this …

SearchField: Add onKeyDown prop 

---

packages/gestalt/src/Typeahead.js
packages/gestalt/src/TypeaheadInputField.js

Allow people to close the menu by clicking outside of the typeahead, after the icon button was used to open the typeahead menu
Also focus on the input when icon button is used to open typeahead
Manual testing
JIRA:[ BUG-122962](https://jira.pinadmin.com/browse/BUG-122962)

Typeahead: Close container on icon button click

---

packages/gestalt/src/Tabs.js
packages/gestalt/src/__snapshots__/Tabs.test.js.snap

[Design doc](https://www.figma.com/file/vlihOKdfamsqUQhd9ybkQv/Tab-component-redesign?node-id=30%3A2387)
This PR adds a new tab variant for the Tabs component, accessible by passing a new undocumented prop, `_dangerouslyUseV2`. The rest of the component API remains the same, with one exception: the `indicator` field of each tab object can now also accept a number. Though not used initially, this will be used in future experiments as a replacement for the notification dot. (For now we need to support both; we _may_ be able to deprecate the dot variant in the future.)
Add `_dangerouslyUseV2={true}` to the docs example to see the new UI. Note that we're dropping support for the `'md'` size, so both examples will be identical. Try passing a number instead of `'dot'` as the `indicator` for a …

Tabs: Add experimental redesign

---

docs/src/Box.doc.js
packages/gestalt/src/Box.js
packages/gestalt/src/Contents.js
packages/gestalt/src/Controller.js
packages/gestalt/src/Modal.js
packages/gestalt/src/ScrollBoundaryContainer.js
packages/gestalt/src/Sheet.js
packages/gestalt/src/Tooltip.js
packages/gestalt/src/boxTypes.js
packages/gestalt/src/contexts/ScrollBoundaryContainer.js
packages/gestalt/src/utils/positioningUtils.js

For SEO and a11y purposes, we need to improve our support for semantic HTML elements. A simple way to accomplish this is to add a new prop to Box that will allow that component to output more than just `div` elements. This PR adds the prop `as`, which is an enum of block-level elements. This enum should cover our current use cases, and is easily added to in the future.
The easiest way to verify this is working is to navigate to the Box docs on the preview link, then add something like `as="article"` to a Box example. Inspect the element and note that it now uses the `<article>` tag instead of `<div>`.

Box: add `as` prop to use semantic tags

---

docs/src/ActivationCard.doc.js
docs/src/Button.doc.js
docs/src/Callout.doc.js
docs/src/Dropdown.doc.js
docs/src/IconButton.doc.js
docs/src/Link.doc.js
docs/src/TapArea.doc.js
docs/src/Upsell.doc.js
packages/gestalt/src/ActivationCard.js
packages/gestalt/src/Button.js
packages/gestalt/src/DropdownItem.js
packages/gestalt/src/IconButton.js
packages/gestalt/src/InternalLink.js
packages/gestalt/src/Link.js
packages/gestalt/src/MenuOption.js
packages/gestalt/src/TableSortableHeaderCell.js
packages/gestalt/src/TapArea.js
packages/gestalt/src/commonTypes.js

`disableOnNavigation`  is not always passed to onClick. Within Link or Internal Link, it does disable the logic from Provider. 
Outside of it, it's just a noop function.
This change changes the flow type so `disableOnNavigation` isn't optional. This prevents having to call `disableOnNavigation` with optional chaining `disableOnNavigation?.()` in the best of the cases or conditional statements within `onClick`:
`disableOnNavigation && disableOnNavigation()
`
`if (disableOnNavigation)  disableOnNavigation()
`
This change won't break code but might require cleaning optional chaining to prevent eslint complains.

Link/Button/IconButton/TapArea +composed components: always pass disableOnNavigation to onClick

---

docs/src/What's New.doc.js

https://cdn.jsdelivr.net heavily caches their files so our What's New Page stays outdated for a while.

Docs: Fix outdated What's New Page

---

docs/src/Eslint Plugin.doc.js
docs/src/components/MainSection.js
docs/src/components/MainSectionSubsection.js
docs/src/components/Markdown.css

Makes it possible to link to a specific rule: `/Eslint%20Plugin#gestaltno-box-marginleft-marginright`
1. Go to https://gestalt.netlify.app/Eslint%20Plugin
2. Ensure everything looks good

Docs: convert ESLint docs to new format

---

packages/gestalt/src/Typeahead.js

Typeahead initializes its displayed value with the passed-in `value` prop (if present), but ignores any changes to that prop. So if, say an action elsewhere on the page causes a new `value` to be passed in, Typeahead completely ignores it.
This PR adds a useEffect to listen for any changes to `value` and update the internal displayed value variable accordingly.
I recommend copying the code from [this sandbox](https://codesandbox.io/s/default-item-example-forked-5z7sb?file=/example.js:179-183) into one of the docs examples, then play around and see if you can break it. You should be able to select a new value via the dropdown or by typing, and the programmatic selection via the buttons should work fine as well.

Typeahead: Fix static `value` bug

---

docs/src/ZIndex Classes.doc.js

Copyediting the new z-index docs page.
Will fast-follow with another PR updating the sidebar link format — left out of this PR to make the copy changes easier to review.

Z-Index: copyediting new docs page

---

docs/src/components/App.js

1. Go to `/PageHeader`
2. Resize the browser window
3. Ensure the contents of the docs don't overlap the navigation

Docs: Fix responsiveness on PageHeader

---

docs/package.json
package.json
yarn.lock

Dependabot alerts:
- Upgrade `is-svg` to version 4.2.2 or later
- Upgrade `ssri` to version 8.0.1 or later
`is-svg`-> `postcss-svgo` -> `cssnano-preset-default` -> `cssnano` -> `optimize-css-assets-webpack-plugin` -> `react-scripts`
I tried upgrading `react-scripts` from 4.0.0 -> 4.0.3. This didn't fix the issue, but I left the upgrade since it's unlikely to cause issues. `cssnano` [released a patch version](https://github.com/cssnano/cssnano/releases/tag/v4.1.11) just ahead of our current version (4.1.10 -> 4.1.11), so I added a resolution to that new version. Hopefully we can remove this when `react-scripts updates their `cssnano` dependency in the future. This new version uses [a new patch version](https://github.com/cssnano/cssnano/compare/v4.1.10...v4.1.11#diff-b46451d710460df9202ca56 …

Internal: Upgrade ssri and is-svg dependencies for security alerts

---

docs/src/Heading.doc.js
packages/gestalt/src/Heading.css
packages/gestalt/src/Heading.flowtest.js
packages/gestalt/src/Heading.js
packages/gestalt/src/Heading.test.js
packages/gestalt/src/__snapshots__/Heading.test.js.snap

Adds `accessibilityLevel="none"` option to `Heading`
* #1462 where we wanted a `Heading` without any accessibility level. In that case we added a new class `.TextLikeHeadingSm` but that approach is limited to just 1 font size & isn't exposed externally. /cc @ayeshakmaz 
* Pinterest's codebase has a few places where folks create their own components to get around this limitation.
See flow tests and unit tests.

Heading: add accessibilityLevel="none" option

---

cypress/integration/accessibility_Sheet_spec.js
docs/src/Sheet.doc.js
docs/src/components/ExampleCode.css
docs/src/components/ExampleCode.js

- Bump height to hit mid-line
- Change cursor to `zoom-in`

Docs: Make unexpanded code example more obviously interactive

---

docs/src/Flex.doc.js
packages/gestalt/src/Flex.js
packages/gestalt/src/FlexItem.js

Extra-wide children can overflow their parent Flex container, breaking the layout. Adding a `minWidth` prop to Flex.Item fixes this by allowing us to wrap the wide child in `<Flex.Item minWidth={0}>`. See [this blog post](https://css-tricks.com/flexbox-truncated-text/#the-solution-is-min-width-0-on-the-flex-child) for more details.
Check out the new "FlexItem-minWidth" example on the Flex docs.

Flex: add `minWidth` prop to Flex.Item

---

docs/src/Module.doc.js
packages/gestalt/src/Badge.js
packages/gestalt/src/Module.js
packages/gestalt/src/Module.test.js
packages/gestalt/src/ModuleExpandable.js
packages/gestalt/src/ModuleExpandableItem.js
packages/gestalt/src/ModuleExpandableItem.test.js
packages/gestalt/src/ModuleTitle.js
packages/gestalt/src/__snapshots__/Module.test.js.snap
packages/gestalt/src/__snapshots__/ModuleExpandable.test.js.snap
packages/gestalt/src/__snapshots__/ModuleExpandableItem.test.js.snap
packages/gestalt/src/moduleTypes.js

[Figma designs](https://www.figma.com/file/B5S5iyikCHqKUcmofquJOe/Web-Creation-Improvements?node-id=136%3A5387)
This PR adds an optional `badgeText` prop to Module (and related Module components) to display a badge after the title text.
Check out the new "Static – Badge" and "Expandable - Icon and Badge " sections in the docs.

Module: Add badgeText prop

---

.gitignore

What is the purpose of this PR?
* Added .DS_Store to our .gitignore to avoid those pesky files showing up in commits.

Internal: Add .DS_Store to .gitignore

---

packages/eslint-plugin-gestalt/package.json
packages/gestalt-datepicker/package.json
packages/gestalt/package.json

In #1471 we introduced the new JSX transform. However, because we didn't set the `NODE_ENV` when building so it included the wrong version in our published package.
Results in the following Gestalt exception:
```
TypeError: Cannot read property 'setExtraStackFrame' of undefined
at setExtraStackFrame (webpack:///node_modules/gestalt/dist/gestalt.es.js:1569:35)
at setCurrentlyValidatingElement$1 (webpack:///node_modules/gestalt/dist/gestalt.es.js:1680:8)
at validateExplicitKey (webpack:///node_modules/gestalt/dist/gestalt.es.js:1707:14)
at validateChildKeys (webpack:///node_modules/gestalt/dist/gestalt.es.js:1864:18)
at jsxs (webpack:///node_modules/gestalt/dist/gestalt.es.js:12998:43)
at render (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:187:187)
at qi …
```

Internal: Fix setExtraStackFrame exception

---

package.json
yarn.lock

[Security alert](https://github.com/pinterest/gestalt/security/dependabot/yarn.lock/trim/open)
The parent package all the way up the chain is `stylelint`. The most recent of that package (minor upgrade from our current version) no longer uses the vulnerable `trim` package.

Internal: Upgrade `stylelint` to obviate `trim` security vulnerability

---

package.json
yarn.lock

[Security alert](https://github.com/pinterest/gestalt/security/dependabot/yarn.lock/lodash/open)
`lodash` is a dependency for nearly fifty packages, so it's not practical to track down upgrades for each one. Instead, this PR adds a new resolution to the latest version of `lodash`, which has fixed the vulnerability. This _shouldn't_ be an issue, since all packages currently use the same major version of `lodash`. 🤞

Internal: Add resolution to latest version of `lodash`

---

packages/eslint-plugin-gestalt/src/no-box-disallowed-props.js
packages/eslint-plugin-gestalt/src/no-box-disallowed-props.test.js
packages/gestalt/src/Box.js

Lint against non-standard `Box` props since they result in warnings.
Example
```js
<Box backgroundColor="#fff" />
```
Results in
> Warning: React does not recognize the `backgroundColor` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `backgroundcolor` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
Add an ESLint rule to disallow non-standard Box props. That way we can detect these issues as we code and will no longer have these warnings show up.
That we duplicate the list of `Box` props in the ESLint rule. However, that seems better than trying to import `Box` in the ESLint plug-in, running an AST to get the list of available props. That would make the rule slower and …

ESLint: add rule to disallow non-standard Box props

---

packages/eslint-plugin-gestalt/src/no-box-disallowed-props.js
packages/eslint-plugin-gestalt/src/no-box-disallowed-props.test.js

* ` box-no-disallowed-improvements` takes a long time & currently errors on non-Box components since we do not have a check for the locally imported name.
* Improve error message when we use import aliases for `Box`: `import { Box as GestaltBox } from 'gestalt'`

ESLint: improve performance & bug fix for box-no-disallowed-props

---

cypress/integration/accessibility_Datapoint_spec.js
packages/gestalt/src/Datapoint.js

Replace `Iconbutton` with `TapArea` + `Icon` to remove default click compression in  IconButtons (info Icon). 
Tooltips are rendered on hover and the click event has no effect on hiding/showing the tooltip.
The compression on click is confusing as the user could expect an event after clicking the button.
Context: An interactive element is needed inside the Tooltip as Tooltip should be anchored with interactive elements. Interactive elements provide keyboard navigation. On keyboard navigation, the tooltip is rendered automatically. TapArea with tapStyle="none" provides the same navigation without the compression.

Datapoint: remove compression on click

---

docs/src/Datapoint.doc.js

Made a minor change to the Datapoint documentation to explicitly call out color treatments in trendSentiment variant

Datapoint trendSentiment docs enhancement

---

docs/src/TextArea.doc.js
docs/src/TextField.doc.js
packages/gestalt/src/FormErrorMessage.css
packages/gestalt/src/FormErrorMessage.js
packages/gestalt/src/TextArea.js
packages/gestalt/src/TextField.js
packages/gestalt/src/__snapshots__/Checkbox.test.js.snap
packages/gestalt/src/__snapshots__/FormErrorMessage.test.js.snap
packages/gestalt/src/__snapshots__/TextArea.test.js.snap
packages/gestalt/src/__snapshots__/TextField.test.js.snap

We have need in the product for clickable text in the error messages for TextField, specifically as part of the login flow:
In order to allow this, we need to update the `errorMessage` type from `string` to `React.Node`. Unfortunately this opens the flood gates to pass anything as the error message, so we'll need to monitor usage to avoid abuse. I added a note about usage in the prop description.
Paste this code into an example to test the new functionality (replace TextField with TextArea accordingly for that doc).
I specifically didn't update the docs with examples of this behavior because it's something we want to _support_ but not _encourage_.
```js
function Example(props) {
const [value, setValue] = React.useState('')
const errorMessage = (
<React.Fragment>
This field can't be …
```

TextField, TextArea: Open errorMessage type to accept Node

---

docs/src/Box.doc.js
docs/src/Layer.doc.js
docs/src/Typeahead.doc.js

Based on Slack feedback, adding better linking to our z-index docs

Docs: Link to zIndex documentation in relevant components

---

docs/src/Tabs.doc.js
packages/gestalt/src/Tabs.js

In at least one place in Pinboard, we're passing text wrapped in a Box setting a ref and a height to attach an Experience popover to a tab. That height breaks the Tabs V2 UI, but is necessary to properly space the popover from the entire tab element (since the ref is on the text, not the element as a whole). By allowing the user to set a ref on a tab element, it will no longer be necessary to use the wrapping Box with a height set, this unbreaking the Tabs V2 UI.

Tabs: Add ref to tab items

---

package.json
yarn.lock

[Security alert](https://github.com/pinterest/gestalt/security/dependabot/yarn.lock/dns-packet/open)
dns-packet -> multicast-dns -> bonjour -> webpack-dev-server -> react-scripts
`multicast-dns` updated yesterday to fix this vulnerability. `bonjour` has not updated yet. Therefore, this PR adds a resolution to the latest version of `multicast-dns`. There was one major version difference between our previous `multicast-dns` and the fixed one; it appears this was from a previous upgrade of `dns-packet` which changes its API a bit. 
I didn't dig into how `multicast-dns` is used within `bonjour` (and therefore within `webpack-dev-server`), but presumably if the `yarn start` script runs fine and the local docs seem fine, it's all good.

Internal: bump resolved version of multicast-dns due to security concern for dns-packet

---

package.json
yarn.lock

[Security alert](https://github.com/pinterest/gestalt/security/dependabot/yarn.lock/browserslist/open)
`browserslist` is used by a number of other packages, so updating all would be a bit much. However, only three usages are on a previous major version from the fixed version, and all three are used  by the same parent module: `postcss-cssnext`. This module is now deprecated and recommended to be replaced with `postcss-preset-env`. However, this is not a drop-in replacement — some configuration will need to be updated as well.
Because the new module isn't a drop-in replacement, I'm adding the resolution as a short-term solution, and will add a Jira ticket for us to update `postcss-cssnext` in the future.

Internal: Update browserslist dependency resolution

---

scripts/releaseSteps.js

This reverts commit 67f32d5e9d6ad48ddbe10027864731c1ce0a5b76.
Revert because the `yarn publish` didn't go through: https://github.com/pinterest/gestalt/runs/2680315007
```
2021-05-27T00:01:39.1026540Z [2/4] Logging in...
2021-05-27T00:01:39.1034991Z [3/4] Publishing...
2021-05-27T00:01:39.1051762Z $ NODE_ENV=production rollup -c rollup.config.js
2021-05-27T00:01:40.6646277Z 
2021-05-27T00:01:40.6649522Z src/index.js → dist/gestalt.js, dist/gestalt.es.js...
2021-05-27T00:01:40.7061802Z [!] Error: Could not resolve entry module (src/index.js).
2021-05-27T00:01:40.7120830Z Error: Could not resolve entry module (src/index.js).
2021-05-27T00:01:40.7121873Z     at error (/home/runner/work/gestalt/gestalt/node_modules/rollup/dist/shared/rollup.js:5305:30)
2021-05-27T00:01:40.7123175Z     at …
```

Revert "Internal: src/ directories: remove test files &  only publish.js.flow (#1525)

---

packages/eslint-plugin-gestalt/package.json
packages/gestalt-datepicker/package.json
packages/gestalt/package.json
scripts/releaseSteps.js

* Folks are importing files within `src/` directories which results in us not being able to change internal file names
* We publish unnecessary files (e.g. test files) which makes the npm/yarn package bigger than it needs to be
Approach was inspired by https://github.com/facebook/relay/blob/625552c31ca4f5f35df1698c39f7f1eac176d1e7/gulpfile.js#L278
The initial try #1525 failed because during the release/publish, we were seeing the following exception:
https://github.com/pinterest/gestalt/runs/2680315007
```
2021-05-27T00:01:39.1026540Z [2/4] Logging in...
2021-05-27T00:01:39.1034991Z [3/4] Publishing...
2021-05-27T00:01:39.1051762Z $ NODE_ENV=production rollup -c rollup.config.js
2021-05-27T00:01:40.6646277Z 
2021-05-27T00:01:40.6649522Z src/index.js → dist/gestalt.js, …
```

Internal: src/ directories: remove test files & only publish .js.flow (second try)

---

docs/src/TextField.doc.js
packages/gestalt/src/TextField.js

Add email as an option (request from slack for a11y tests)

TextField: Add email option for autocomplete

---

package.json
packages/gestalt-core/build.js
yarn.lock

As noted in #1524, we need to update our current dependency `postcss-cssnext`. This module has been deprecated for a few years now, and we're likely to get more Dependabot alerts in the future that will require more resolutions, since this module won't be updated.
The [module author recommends](https://moox.io/blog/deprecating-cssnext) replacing with `postcss-preset-env`. It's not _quite_ a drop-in replacement, but almost. I used a [previous attempt at this upgrade](https://github.com/pinterest/gestalt/pull/432) (and the [bug it caused](https://github.com/pinterest/gestalt/issues/448#issuecomment-452475281)) and [recommendations from the previous module's author](https://github.com/csstools/postcss-preset-env/issues/32#issuecomment-393754060) to adjust our build configuration.
CSS file …

Internal: replace deprecated `postcss-cssnext` with `postcss-preset-env`

---

package.json
yarn.lock

[Security alert](https://github.com/pinterest/gestalt/security/dependabot/yarn.lock/ws/open)
`ws` is used by two dependencies: `jsdom` and `webpack-dev-server`. Unfortunately neither have upgraded to address this vulnerability yet, and they are on different major versions (`7.x.x` and `6.x.x` respectively).
This PR adds a resolution for the earliest fixed version (`7.4.6`). 🤞 that `webpack-dev-server` still works!

Internal: add resolution for vulnerable `ws` package

---

docs/src/Tabs.doc.js
packages/gestalt/src/Tabs.js

To keep logic consistent across all cmps with link behavior, we are adding `disableOnNavigation` to Tabs (accessible in `onChange`)

Tabs: pass disableOnNavigation arg in onChange for link behavior management

---

package.json
yarn.lock

[Security alert](https://github.com/pinterest/gestalt/security/dependabot/yarn.lock/normalize-url/open)
`normalize-url` is used by three modules: `cacheable-request`, `mini-css-extract-plugin`, and `postcss-normalize-url`. Unfortunately only the first has upgraded to the latest fixed version.
This PR adds a resolution for `normalize-url` to the latest fixed version, `4.5.1`. This represents a major version change for all three modules using this package, so 🤞 that nothing breaks.

Internal: add resolution for `normalize-url` to fix vulnerability

---

package.json
yarn.lock

[Security alert](https://github.com/pinterest/gestalt/security/dependabot/yarn.lock/trim-newlines/open)
`trim-newlines` is used by a couple of versions of `meow` (3.7.0 + 9.0.0). Both of those versions are used by our direct dependencies (`stylelint` + `css-modules-flow-types-cli`), but sadly neither of those modules have been updated.
A [previous attempt at this fix](https://github.com/pinterest/gestalt/pull/1544) (adding a resolution for `meow`) failed CI, likely due to the multiple major version jump involved.
This PR adds a resolution for the latest version of `trim-newlines`. 🤞 this doesn't break anything, since it's a multiple major version jump for both `meow` versions.

Internal: add resolution for `trim-newlines` to fix vulnerability

---

package.json
yarn.lock

[Security alert](https://github.com/pinterest/gestalt/security/dependabot/yarn.lock/css-what/open)
`css-what` is used by a couple of versions of `css-select` (1.1.0 + 2.0.0), which are used by a pretty wide array of dependencies (most leading back up to `react-scripts`). Some upstream dependencies have updated their `css-select` versions, but not all, so that module is our lower common denominator for this vulnerability.
This PR adds a resolution to the latest version of `css-select`, which uses the fixed version of `css-what`.

Internal: add resolution for `css-select` to fix `css-what` vulnerability

---

package.json
yarn.lock

[Security alert](https://github.com/pinterest/gestalt/security/dependabot/yarn.lock/glob-parent/open)
`glob-parent` is used by eight versions/modules:
3.1.0 - `chokidar` 2.1.8
5.1.0 - `chokidar` 3.0.2
5.1.0 - `chokidar` 3.4.1
5.0.0 - `eslint` 7.11.0
3.1.0 - `fast-glob` 2.2.6
5.1.0 - `fast-glob` 3.0.3
5.1.0 - `fast-glob` 3.1.1
5.1.0 - `fast-glob` 3.2.5
Given the variety of modules and versions, a resolution for `glob-parent` is the likely best option.
This PR adds a resolution for `glob-parent` to the latest fixed version. Unfortunately this is a major version change for two of the current modules, so 🤞 nothing breaks.

Internal: add resolution for `glob-parent` to fix vulnerability

---

packages/gestalt/src/Video.js
packages/gestalt/src/__snapshots__/Video.test.js.snap

This fixes a typo in which `<video />` contains a style prop with `{ 'object-fit': objectFit }`  when properties on the style prop should be camelCase.
- JIRA: https://jira.pinadmin.com/browse/PDS-2861

Video: Use objectFit instead of object-fit

---

docs/src/Image.doc.js
packages/gestalt/src/Image.js
packages/gestalt/src/__snapshots__/Image.test.js.snap

When we scale an image (`fit` of "cover" or "contain") , we use `<div role="img">` instead of `<img>`. This causes screen readers to ignore reading any child elements — not great for accessibility.
This PR moves the child content to be a sibling of the `<div role="img">` rather than a child, un-hiding the child content from screen readers.
TO TEST: Navigate to https://gestalt.pinterest.systems/Image#fit. Add a Button as a child to the examples. Turn your screen reader on, then tab to the button. Note that while you can tab to the button and interact with it, the screen reader doesn't read the button text. Now repeat these steps on the preview docs for this PR. Note that now the screen reader reads the button text.
- JIRA: https://jira.pinadmin.com/browse/BUG-126875

Image: fit children

---

scripts/releaseSteps.js

Follow up from #1558 where we introduced links to our documentation from code.
Looking at https://unpkg.com/gestalt@24.2.0/src/Box.js.flow I noticed that the URLs weren't stripped so we do see double URLs in the editor (one clickable and the other one not).
Root cause is that I didn't escape characters in the regex.

Internal: fix stripping URLs from code

---

packages/eslint-plugin-gestalt/src/__fixtures__/no-medium-formfields/invalid/invalid-tabs-default.js
packages/eslint-plugin-gestalt/src/no-medium-formfields.js
packages/eslint-plugin-gestalt/src/no-medium-formfields.test.js

Whoops — [we recently removed](https://github.com/pinterest/gestalt/pull/1566) the `size` prop from Tabs, but I didn't realize that was part of a lint rule as well. This PR removes Tabs from that lint rule.

Lint Rules: Remove Tabs from `no-medium-formfields` rule

---

docs/src/Image.doc.js
packages/gestalt/src/Image.js
packages/gestalt/src/Image.test.js
packages/gestalt/src/__snapshots__/Image.test.js.snap

For cases like our Today articles, where we have Images using a fit option that don't need any alt text or aria label, we need a way to specify them as  presentational with role="presentation"
- [Slack Convo](https://pinterest.slack.com/archives/C045W45GC/p1624384582379700)

Image: Add option for presentation role

---

docs/src/Table.doc.js
packages/gestalt/src/TableSortableHeaderCell.js

Add support for sticky columns on sortable header cells
- [Jira](https://jira.pinadmin.com/browse/PDS-2857)
- GitHub Issue: https://github.com/pinterest/gestalt/issues/1541

Table: Add sticky column support to sortable header

---

packages/gestalt/src/InternalLink.js
packages/gestalt/src/Tabs.js
packages/gestalt/src/TapArea.js
packages/gestalt/src/__snapshots__/Tabs.test.js.snap
packages/gestalt/src/ariaTypes.js

The previous version of Tabs supported `aria-selected` to indicate the selected tab. However, [that is only correct if used with `role="tab"`](https://www.stefanjudis.com/blog/aria-selected-and-when-to-use-it/), which we removed because that does not refer to a collection of links (we really need to rename Tabs and SegmentedControl). [The proper way to indicate the current location in a collection of links is `aria-current="page"`](https://www.w3.org/WAI/tutorials/menus/structure/), so this PR adds support for that.
Note: this is a purposefully simplified implementation of `aria-current`. `aria-current` is actually an enum, not a boolean. However, for our _current_ (:pun_dog:) needs, this will suffice. If we decide to implement support for other enum values in the future, that can be a …

Tabs, TapArea, InternalLink: Add support for aria-current

---

packages/gestalt/src/Typography.css

This updates the `lineClamp` styles to break on word, not character. This will prevent this sort of undesirable UI:

Text: Update `word-break` style

---

docs/src/Modal.doc.js
packages/gestalt-codemods/28.0.0/sheet_modal_deprecate_ref_props.js
packages/gestalt/src/Modal.js
packages/gestalt/src/Modal.jsdom.test.js
packages/gestalt/src/Sheet.js
packages/gestalt/src/Sheet.jsdom.test.js
packages/gestalt/src/__snapshots__/Modal.jsdom.test.js.snap

Modal, Sheet: deprecate ref (forwardRef removal)
Deprecating refs as there are no cases for accessing the inner tags on any case and could lead to bad practices
Modal
Sheet
Codemod to console.log existing refs in Moalds and Sheets. Run
```
yarn codemod --parser=flow -t=packages/gestalt-codemods/28.0.0/sheet_modal_deprecate_ref_props.js relative/path/to/your/code
```

Modal, Sheet: deprecate ref (forwardRef removal) + codemod

---

docs/src/Upsell.doc.js

Our Upsell.Form examples were wrong (weren't destructuring `event` from the `onSubmit` args), so this PR fixes them and has a bunch of general cleanup for the markup of that page (alphabetizing props, breaking up blocks with semantic whitespace, etc).

Upsell: Docs cleanup

---

packages/gestalt/src/Button.js

As noted in #1556, there's weird behavior on Safari browsers (mobile and desktop) relating to text color and changing disabled state. This seems to be an issue specific to Safari itself and how it handles `pointer-events: none` vis-a-vis repaints.
This PR implements the simplest fix for this issue: adding a key to the underlying DOM element based on the `disabled` prop, forcing a re-render whenever that prop changes.
To review:
- Use Safari 😛 
- Paste this code (or something similar) in one of the Button examples:
```js
function Demo() {
const [disabled, setDisabled] = React.useState(true);
React.useEffect(() => setTimeout(() => setDisabled(false), 1000), []);
return <Button color="red" text="Button" disabled={disabled} />;
}
```
- The Button should flip from disabled -> enabled after a …

Button: Add key to fix Safari bug

---

packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/invalid/absolute-bottom.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/invalid/absolute-left.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/invalid/absolute-right.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/invalid/absolute-top.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/invalid/fit-max-width.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/invalid/flex-align-content.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/invalid/flex-align-items.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/invalid/flex-direction.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/invalid/flex-justify-content.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/invalid/flex-wrap.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/absolute-bottom.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/absolute-left.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/absolute-right.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/absolute-top.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/fit-max-width.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/fit.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/flex-align-content.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/flex-align-items.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/flex-direction.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/flex-justify-content.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/flex-wrap.js
packages/eslint-plugin-gestalt/src/no-box-useless-props.js
packages/eslint-plugin-gestalt/src/no-box-useless-props.test.js

We see a lot of unfortunate Box props usage, where props are applied that are either useless without other props, or conflict with other props. This is provides a frustrating DX.
This PR adds a lint rule to check for three categories of useless props:
- `alignContent`, `alignItems`, `direction`, `justifyContent`, or `wrap` without `display="flex"`
- `bottom`, `left`, `right`, or `top` without `position="absolute"`
- `fit` and `maxWidth` used together, since `fit` sets `maxWidth` under the hood
The rule and tests are written to be easily extensible, so we can provide further guidance with future updates.
- [Jira](https://jira.pinadmin.com/browse/PDS-2910)

Lint rules: Add `no-box-useless-props` rule

---

packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/invalid/absolute-bottom.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/invalid/absolute-left.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/invalid/absolute-right.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/invalid/absolute-top.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/absolute-bottom.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/absolute-left.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/absolute-right.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/absolute-top.js
packages/eslint-plugin-gestalt/src/no-box-useless-props.js
packages/eslint-plugin-gestalt/src/no-box-useless-props.test.js

Previous version was wrong: `top` `bottom` `left` `right` are useful even if not using `position="absolute"`

Lint Rules: Fix no-box-useless-props rule

---

packages/eslint-plugin-gestalt/src/no-box-useless-props.js

Whoops, forgot the responsive versions of `direction` and `display` 😬

Lint Rules: Add support for responsive props in no-box-useless-props

---

packages/eslint-plugin-gestalt/src/no-box-useless-props.js
packages/eslint-plugin-gestalt/src/no-box-useless-props.test.js

A few flex props are also valid for use in grid layouts. Although we don't explicitly support grid yet, it can be set using `dangerouslySetInlineStyle`, so this PR improves the error message to note when suppression is recommended.

Lint Rules: Better error message for grid props

---

docs/src/Callout.doc.js
docs/src/Upsell.doc.js
packages/gestalt/src/Callout.js
packages/gestalt/src/Upsell.js
packages/gestalt/src/commonTypes.js

Allow actions in callouts and upsells to be disabled 

Callout, Upsell: Allow actions to be disabled

---

docs/src/Eslint Plugin.doc.js
packages/eslint-plugin-gestalt/src/button-icon-restrictions.js
packages/eslint-plugin-gestalt/src/no-box-disallowed-props.js
packages/eslint-plugin-gestalt/src/no-box-marginleft-marginright.js
packages/eslint-plugin-gestalt/src/no-box-useless-props.js
packages/eslint-plugin-gestalt/src/no-dangerous-style-duplicates.js
packages/eslint-plugin-gestalt/src/no-medium-formfields.js
packages/eslint-plugin-gestalt/src/no-role-link-components.js
packages/eslint-plugin-gestalt/src/prefer-box.js

Updates Eslint Plugin guidelines page in Docs with missing rules to Docs
Categorizes rules in 
- Gestalt alternatives
- Gestalt restrictions
- Deprecated rules
Standardize rule config to follow:
```
meta: {
type: 'suggestion',
docs: {
description: '____',
category: 'Gestalt restrictions',
recommended: false,
url: 'https://gestalt.pinterest.systems/Eslint%20Plugin#_________',
},
```

Eslint Plugin: Add missing rules to Docs, categorize, and standardize rule config  

---

docs/src/Callout.doc.js
docs/src/Datapoint.doc.js
docs/src/Upsell.doc.js

Add note in PageHeader of Callout and Upsell that dark mode is not yet supported

Callout, Upsell, Datapoint: Add note about dark mode support

---

docs/src/Upsell.doc.js
packages/gestalt/src/UpsellForm.js

Typically our handlers are `({ event }) => {}`. Upsell.Form's onSubmit is `(event) => {}`. This PR fixes that handler's arguments to match our convention.

Upsell: Fix Upsell.Form onSubmit API to match convention

---

packages/eslint-plugin-gestalt/src/__fixtures__/no-medium-formfields/invalid/invalid-combobox-default.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-medium-formfields/invalid/invalid-combobox-medium.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-medium-formfields/invalid/invalid-combobox-renamed.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-medium-formfields/valid.js
packages/eslint-plugin-gestalt/src/no-medium-formfields.js
packages/eslint-plugin-gestalt/src/no-medium-formfields.test.js

Eslint Plugin: Add missing ComboBox to "no-medium-formfields" Eslint rule
"ComboBox" is part of the form field family. 
Tests upgraded as well.

Eslint Plugin: Add missing ComboBox to "no-medium-formfields" Eslint rule

---

docs/src/Text.doc.js
packages/gestalt-codemods/next/__testfixtures__/text-replace-truncate-lineClamp-renamed.input.js
packages/gestalt-codemods/next/__testfixtures__/text-replace-truncate-lineClamp-renamed.output.js
packages/gestalt-codemods/next/__testfixtures__/text-replace-truncate-lineClamp.input.js
packages/gestalt-codemods/next/__testfixtures__/text-replace-truncate-lineClamp.output.js
packages/gestalt-codemods/next/__tests__/text-replace-truncate-lineClamp.test.js
packages/gestalt-codemods/next/text-replace-truncate-lineClamp.js
packages/gestalt/src/ComboBox.js
packages/gestalt/src/ModuleExpandableItem.js
packages/gestalt/src/ModuleTitle.js
packages/gestalt/src/OptionItem.js
packages/gestalt/src/PageHeader.js
packages/gestalt/src/Text.js
packages/gestalt/src/Text.test.js
packages/gestalt/src/__snapshots__/Dropdown.jsdom.test.js.snap
packages/gestalt/src/__snapshots__/Module.test.js.snap
packages/gestalt/src/__snapshots__/ModuleExpandable.test.js.snap
packages/gestalt/src/__snapshots__/ModuleExpandableItem.test.js.snap
packages/gestalt/src/__snapshots__/PageHeader.test.js.snap
packages/gestalt/src/__snapshots__/Text.test.js.snap

We previously added an undocumented `lineClamp` prop to Text, allowing us to use `-webkit-line-clamp`. After running [an experiment in Pinboard](https://helium.pinadmin.com/web_pin_rep_line_clamp), we've determined that replacing `truncate` with `lineClamp={1}` will not have detrimental metrics effects.
This PR removes `truncate` and adds documentation for `lineClamp`. It also includes a codemod to transform `<Text truncate />` to `<Text lineClamp={1} />`.

Text: Remove `truncate`, document `lineClamp`

---

.vscode/tasks.json
docs/src/Development.doc.js

* Add a VSCode task to launch the docs when you open VSCode.
* Add instructions on how to enable this settings (you only have to do this once)

[Internal] Automatically launch docs & watcher when you open VSCode

---

docs/src/Eslint Plugin.doc.js
packages/eslint-plugin-gestalt/src/__fixtures__/prefer-box-as-tag/invalid/gestalt-import-HTML-multiple-tag-with-props-input.js
packages/eslint-plugin-gestalt/src/__fixtures__/prefer-box-as-tag/invalid/gestalt-import-HTML-multiple-tag-with-props-output.js
packages/eslint-plugin-gestalt/src/__fixtures__/prefer-box-as-tag/invalid/gestalt-import-HTML-single-tag-input.js
packages/eslint-plugin-gestalt/src/__fixtures__/prefer-box-as-tag/invalid/gestalt-import-HTML-single-tag-output.js
packages/eslint-plugin-gestalt/src/__fixtures__/prefer-box-as-tag/invalid/no-gestalt-import-HTML-single-tag-input.js
packages/eslint-plugin-gestalt/src/__fixtures__/prefer-box-as-tag/invalid/no-gestalt-import-HTML-single-tag-output.js
packages/eslint-plugin-gestalt/src/__fixtures__/prefer-box-as-tag/valid.js
packages/eslint-plugin-gestalt/src/eslintASTFixers.js
packages/eslint-plugin-gestalt/src/eslintASTHelpers.js
packages/eslint-plugin-gestalt/src/prefer-box-as-tag.js
packages/eslint-plugin-gestalt/src/prefer-box-as-tag.test.js

new Eslint rule:
prefer-box-as-tag: Prefer Box: prevent HTML tags supported in Box through the `as` prop
With Eslint rules, this PR initiates an AST helper library.
Context: Gestalt Tooling Ecosystem Exploration Doc
OTHER REFACTORS TO CLEAN UP / STANDARDIZE TESTS

Eslint plugin: prefer-box-as-tag rule w/ autofix

---

docs/src/Sheet.doc.js
packages/gestalt/src/Sheet.js
packages/gestalt/src/__snapshots__/Sheet.jsdom.test.js.snap

This PR adds onAnimationEnd to Sheet so events can get triggered once the component is fully rendered or removed. Examples can be placing educational focus on elements inside Sheet.
To detect which animation is (in vs out) the callback `({ animationState }) => void` has access to `animationState`
ALSO, fix for [BUG-131248 Sheet dismiss button unreachable when heading is missing
](https://jira.pinadmin.com/browse/BUG-131248)

Sheet: new onAnimationEnd prop + fix for bug

---

packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/invalid/flex-dangerous.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/invalid/flex-dynamic-dangerous.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/invalid/flex-dynamic-display.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/flex-dangerous-grid.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/flex-dangerous-inline-flex.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/flex-dangerous-inline-grid.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/flex-dynamic-dangerous.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/flex-dynamic-display.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-useless-props/valid/flex-reference-display.js
packages/eslint-plugin-gestalt/src/no-box-useless-props.js
packages/eslint-plugin-gestalt/src/no-box-useless-props.test.js

This PR adds support for a few more scenarios, which should eliminate most/all suppressions in Pinboard:
- `display={condition ? 'flex' : 'block'}`
- `dangerouslySetInlineStyle={{ __style: { display: 'grid' }
}}`
- `dangerouslySetInlineStyle={{ __style: { display: condition ? 'grid' : 'block' }
}}`

Lint rules: Add support for dynamic/dangerous styles in `no-box-useless-props`

---

packages/eslint-plugin-gestalt/src/no-box-useless-props.js

Lint rules: Fix name bug in no-box-useless-props

---

packages/gestalt/src/Button.js

Revert "Revert "Button: Add key to fix Safari bug (#1584)""
This reverts commit e29ab9d2f0dae3e5e870f834140fa3b8450a440b.
We needed to temporarily revert the original PR to ease the Image refactor revert. This PR reverts the revert, bringing the original back to life.

Button: Add key to fix Safari bug, take two

---

packages/gestalt/src/Button.js

Reverts pinterest/gestalt#1587
This solution is hacky and is leading to unintended downstream effects, namely breaking unit and integration tests in Pinboard.
We've decided to not fix this bug, as it's actually a Safari bug and [has been fixed in 14.7](https://github.com/mui-org/material-ui/issues/26251#issuecomment-867109199).
There are a few less-hacky hacks that various other libraries have tried, which we may explore in the future if needed:
- https://github.com/CirclesUBI/circles-myxogastria/pull/219/files
- https://github.com/microsoft/fluentui/pull/18851

Revert "Button: Add key to fix Safari bug, take two"

---

packages/gestalt/src/Modal.js

Add documentation for every prop in `Modal`.
* See documentation in your IDE
* Quicker navigation to a specific section of the docs from within IDE
* Duplicate types: we now inline these types so we have better documentation while coding. See Next steps to show how we can mitigate this downside.
* Use [React Docgen](https://github.com/reactjs/react-docgen): parse the flow docs out & use those in our documentation
* Remove PropTypes: we should be able to do this as soon as we have SSR integration tests & monitor the console

Modal: Add flow docs for props

---

packages/gestalt/src/Colors.css
packages/gestalt/src/index.js

`@import` in the middle of the file
CSS gets inlined

Internal: fix gestalt-design-tokens variables import

---

docs/pages/_document.js

I noticed the favicon was missing from the docs (since upgrading to Next.js).
Before/After:

Docs: fix favicon

---

docs/pages/flex.js
packages/gestalt/src/FlexItem.js
packages/gestalt/src/boxTransforms.js

Extending the usefulness of Flex.Item by adding [`flex-basis`](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis)
- [Jira](https://jira.pinadmin.com/browse/PDS-2458)

Flex: Add `flexBasis` prop to Flex.Item

---

docs/pages/image.js
packages/gestalt/src/Image.js
packages/gestalt/src/Image.test.js
packages/gestalt/src/__snapshots__/Image.test.js.snap

Add ability to specify cross origin for Images

Image: Add crossorigin property

---

packages/eslint-plugin-gestalt/src/helpers/eslintASTHelpers.js
packages/eslint-plugin-gestalt/src/helpers/styleHelpers.js
packages/eslint-plugin-gestalt/src/prefer-box-no-disallowed.js

added options to `prefer-box-no-disallowed`
`excludeTests` we can pass `true` and all files ending in '.test.js' we'll be excluded
`excludePaths` we can pass [`app/amp/', `app/sterling/']  and all files containing the strings in their filenames we'll be excluded

Eslint plugin: added schema options to `prefer-box-no-disallowed` rule

---

docs/pages/design_tokens.js
docs/pages/toast.js
packages/gestalt/src/Toast.js
packages/gestalt/src/__snapshots__/Toast.test.js.snap

Based on feedback from Marcy Sutton's audit. Ensure Toasts announce themselves to a screen reader.
- [Jira](https://jira.pinadmin.com/browse/PDS-2950)

Toast: Add role of status for accessibility

---

docs/next.config.js

Root cause: webpack watcher in Next.js does not re-trigger a new build when a file quickly changes from containing JS => empty ==> containing JS
Fixes #1652 
Rollup uses the async version of `fs.writeFile` https://github.com/rollup/rollup/blob/ce951973e1a33fccfb81e8701317c896c26a050d/src/utils/fs.ts#L31 which results in a file momentarily being empty and then containing JS. If they would use `fs.writeFileSync`, the file would never be empty (but this blocks the Node.js process from doing anything else).
Next.js uses Webpack to continuously compile pages. However, when one of the imports of the pages changes from a file with content => empty => file with content, it doesn't re-compile with the second step. The only solution I found is to override the next.js config & use webpack polling. …

Internal: fix Element type is invalid

---

docs/components/GeneratedPropTable.js
docs/components/PropTable.js
docs/pages/text.js
packages/gestalt/src/Text.js

Docs for `<Text />` now use the generated version. See #1669 for the initial PR
* Use `react-docgen` docs for `<Text />`
* Add `href` support (some of our docs still had this)
* Fix issue when a flow union starts with `|`
* Support booleans & numbers for default values
https://deploy-preview-1671--gestalt.netlify.app/text

Text: use generated docs

---

docs/pages/video.js
packages/gestalt/src/Video.flowtest.js
packages/gestalt/src/Video.js
packages/gestalt/src/Video.jsdom.test.js
packages/gestalt/src/__snapshots__/Video.test.js.snap

Adds a `disableRemotePlayback` to `<Video />`
In Pinterest's codebase we use:
```
video::-internal-media-controls-overlay-cast-button {
display: none;
}
```
Which results in the following warning:
> [Deprecation] The disableRemotePlayback attribute should be used in order to disable the default Cast integration instead of using -internal-media-controls-overlay-cast-button selector. See https://www.chromestatus.com/feature/5714245488476160 for more details.
In this diff we fix the issue by adding `disableRemotePlayback` as a prop on `Video`, which will allow us to remove the CSS in Pinterest's codebase.
- https://www.chromestatus.com/feature/5714245488476160

Video: add disableRemotePlayback prop

---

docs/pages/accessibility.js
docs/pages/fieldset.js
docs/pages/tooltip.js
packages/gestalt/src/Fieldset.test.js
packages/gestalt/src/__snapshots__/Fieldset.test.js.snap

A quick pr to fix some doc typos and add a note about Links in Tooltips.
We also got approval to make our accessible design deck public, so updating the link there

Docs: Update link to accessible design deck

---

docs/pages/toast.js
packages/gestalt-codemods/33.0.0/__tests__/heading-replace-truncate-lineClamp.test.js
packages/gestalt-codemods/33.0.0/heading-replace-truncate-lineClamp.js
packages/gestalt-codemods/next/__testfixtures__/color-red.input.js
packages/gestalt-codemods/next/__testfixtures__/color-red.output.js
packages/gestalt-codemods/next/__testfixtures__/color-white.input.js
packages/gestalt-codemods/next/__testfixtures__/color-white.output.js
packages/gestalt-codemods/next/__testfixtures__/empty-string-color.input.js
packages/gestalt-codemods/next/__testfixtures__/empty-string-color.output.js
packages/gestalt-codemods/next/__testfixtures__/no-color.input.js
packages/gestalt-codemods/next/__testfixtures__/no-color.output.js
packages/gestalt-codemods/next/__testfixtures__/null-color.input.js
packages/gestalt-codemods/next/__testfixtures__/null-color.output.js
packages/gestalt-codemods/next/__testfixtures__/renamed.input.js
packages/gestalt-codemods/next/__testfixtures__/renamed.output.js
packages/gestalt-codemods/next/__testfixtures__/ternary-color.input.js
packages/gestalt-codemods/next/__testfixtures__/ternary-color.output.js
packages/gestalt-codemods/next/__testfixtures__/undefined-color.input.js
packages/gestalt-codemods/next/__testfixtures__/undefined-color.output.js
packages/gestalt-codemods/next/__testfixtures__/variable-color.input.js
packages/gestalt-codemods/next/__testfixtures__/variable-color.output.js
packages/gestalt-codemods/next/__tests__/toast-replace-color-variant.test.js
packages/gestalt-codemods/next/toast-replace-color-variant.js
packages/gestalt/src/Toast.js
packages/gestalt/src/Toast.test.js
packages/gestalt/src/__snapshots__/Toast.test.js.snap

We'd like to remove direct color specification for Toast, re-aligning to "default" and "error" variants. This PR removes the `color` prop and replaces it with `variant`. The included codemod converts `color="red"` to `variant="error"`, `color="white"` to `variant="default"`.
- [Jira](https://jira.pinadmin.com/browse/PDS-2836)

Toast: Replace `color` with `variant`

---

README.md

Makes it obvious to see under which license we publish Gestalt

Internal: add license badge to Readme

---

packages/gestalt-core/build.js
scripts/releaseSteps.js

When using the flow comments in Pinterest's codebase, I noticed all the URLs to the docs are missing. That's caused by #1561 which strips all the URLs from the `src` file, which is not what we want.
Instead, in this diff, we remove all comments (apart from [terser pure annotation comments](https://terser.org/docs/api-reference.html#annotations)) from the `dist/` directory (build files)

Internal: Keep URLs in flow docs

---

docs/pages/scrollboundarycontainer.js
packages/gestalt/src/Modal.js
packages/gestalt/src/ScrollBoundaryContainer.js
packages/gestalt/src/ScrollBoundaryContainerWithForwardRef.js
packages/gestalt/src/Sheet.js

@AlbertCarreras noticed that generating the docs for `ScrollBoundaryContainer` didn't work because of multiple exports:
Fix is to split the components up into multiple files (also makes it more straightforward to see the dependencies of each one)
We previously didn't specify that `children` is a required prop.

ScrollBoundaryContainer: use generated docs (multiple exports)

---

docs/components/GeneratedPropTable.js
docs/components/PropTable.js
docs/components/docgen.js
docs/pages/avatargroup.js
packages/gestalt/src/AvatarGroup.js
packages/gestalt/src/Modal.js
packages/gestalt/src/Text.js

@AlbertCarreras noticed that `AvatarGroup` didn't export any types when using the generated docs. That was due to the fact that the component had a `forwardRef`.
* **Use autogenerated docs for AvatarGroup** (forwardRef)
* **Automatically get default value**: `react-docgen` already knows about the value so no need to duplicate it.
* **Add ability to link to specific prop in proptable**: makes it easy to reference other props from other components
Since we previously were setting these manually, we didn't discover these

Docs: add autogenerated docs for AvatarGroup (forwardRef), automatically get default value & add ability to link to specific prop in docs

---

docs/pages/video.js
packages/gestalt/src/Video.css
packages/gestalt/src/Video.js
packages/gestalt/src/__snapshots__/Video.test.js.snap

Add backgroundColor prop to fill the video's placeholder
Previously black color by default, now we can pass an alternative color: transparent.
This provides a fix for Box/Mask: Box/Mask containing Video shows unexpected corner border when hiding overflowing content
Fixes bugs:
- https://jira.pinadmin.com/browse/BUG-123359
BEFORE 
AFTER
BEFORE
AFTER

Video: add backgroundColor prop

---

packages/gestalt-design-tokens/build.js
packages/gestalt-design-tokens/config.json

Update space tokens to use `dimen` format with `dp` for the Android output, as this is what Android [expects for dimensions](https://developer.android.com/guide/topics/resources/more-resources#Dimension) instead of `px`.

Design Tokens: Update format for Android

---

packages/gestalt/src/ComboBox.js
packages/gestalt/src/__snapshots__/ComboBox.jsdom.test.js.snap

ComboBox: removed minWidth
minWidth of 280 px was added with no design specs backing it. Removing it so designers can use it with less size restrictions.

ComboBox: removed minWidth

---

packages/gestalt/src/Toast.css
packages/gestalt/src/Toast.js

We're looking to move the default Toast color back to dark gray, but this time we'd like to make the change behind an experiment to gauge user behavior changes. This PR adds an undocumented prop to use dark gray instead of white for the toast background. It also adds an override (specific to the experimental color treatment) to ensure that all contained text is the correct color, regardless of any colors set on more complex `text` Node props.
- [Jira](https://jira.pinadmin.com/browse/PDS-2837)

Toast: Add experimental prop for dark gray color

---

docs/pages/dropdown.js
packages/gestalt/src/Dropdown.js

Layer is built-in Dropdown. However, in some cases we don't need this Layer and it does break the Dropdown positioning. For example, sticky headers.
Adding this prop so Dropdown can be adopted in those cases.

Dropdown: add dangerouslyRemoveLayer prop

---

packages/gestalt/src/Button.js
packages/gestalt/src/InternalLink.js

Buttons with role = link should not have selected state as the link is an interaction. However, some current designs are hybrids of Button that are simple links but act as Tabs and show a selected state.
Standarizing styles across variants to prevent buggy styles.

Button: fix style bug on selected state and role link

---

docs/pages/searchfield.js
packages/gestalt/src/SearchField.js

This PR updates SearchField docs to use a generated props table, and adds new/updated guidance to several sections:
- Props (updated)
- Best Practices (new)
- Localization (new)
- Related components (new)
I tweaked the copy in some places from the Paper doc where it seemed awkward or overly wordy. Happy to keep iterating on that if needed.
- [Jira](https://jira.pinadmin.com/browse/PDS-3160)
- [TDD](https://paper.dropbox.com/doc/Gestalt-doc-SearchField--BShJNCXR~Bq~3G4Atf5G~xKMAg-eHpPNX2DD4I903RaJG0kK)

SearchField: Update docs to autogenerated props, design guidelines

---

docs/pages/callout.js
packages/gestalt/src/Callout.js

Callout: use generated props table in docs

---

docs/components/docgen.js
docs/pages/selectlist.js
packages/gestalt/src/SelectList.js

Conversion to generated props yielded a couple of errors:
- When we provide a default value for a required prop, docgen interprets that as meaning the prop isn't actually required. If we want to keep our defensive approach of providing a default for a required prop, we have to move that default out of the function signature. This PR moves the default value for `options` from the destructured args to the `.map` call.
- Docgen doesn't resolve types defined elsewhere, so we see `FooType` instead of the definition of FooType. We can solve this in some places by inlining the type definition. However, that approach isn't always the best (and hopefully we can avoid it in the future somehow), so this PR adds a helper to manually override generated prop types.

SelectList: Tweaks to generated props

---

docs/components/GeneratedPropTable.js

Certain components, like Box, don't have defaults set in JS (they're either set in CSS or browser defaults). This PR essentially reverts part of #1688, re-adding the ability to specify default values in comments.
This PR also adds the ability to override the given type in the comments, which may prove useful while we wait to write the Babel transform to resolve types — or it may not, and we may delete it in the future.

Internal: add ability to override default value and type in generated docs

---

cypress/integration/accessibility_Icon_spec.js
cypress/integration/accessibility_Iconography and SVGs_spec.js
docs/components/sidebarIndex.js
docs/pages/faq.js
docs/pages/icon.js
docs/pages/iconbutton.js
docs/pages/iconography_and_svgs.js
packages/gestalt/src/AvatarGroup.js
packages/gestalt/src/ComboBox.js
packages/gestalt/src/Icon.js
packages/gestalt/src/__snapshots__/ComboBox.jsdom.test.js.snap

Icon: new docs + Iconography and svgs guidelines

Icon: new docs

---

docs/pages/module.js
packages/gestalt/src/Module.flowtest.js
packages/gestalt/src/Module.js
packages/gestalt/src/Module.test.js
packages/gestalt/src/ModuleExpandable.flowtest.js
packages/gestalt/src/ModuleExpandable.js
packages/gestalt/src/ModuleExpandable.jsdom.test.js
packages/gestalt/src/ModuleExpandableItem.flowtest.js
packages/gestalt/src/ModuleExpandableItem.js
packages/gestalt/src/ModuleExpandableItem.jsdom.test.js
packages/gestalt/src/ModuleExpandableItem.test.js
packages/gestalt/src/ModuleTitle.flowtest.js
packages/gestalt/src/ModuleTitle.js
packages/gestalt/src/__snapshots__/Module.test.js.snap
packages/gestalt/src/__snapshots__/ModuleExpandable.test.js.snap
packages/gestalt/src/__snapshots__/ModuleExpandableItem.test.js.snap
packages/gestalt/src/moduleTypes.js

Add an `IconButton` element to be placed after the title for a supplemental help CTA. Will not be displayed if `title` is not provided. Not to be used with `badgeText` or `icon`.
Also, refactor types so that these props are mutually exclusive: `badgeText`, `icon` and `iconButton`.
- [Jira](https://jira.pinadmin.com/browse/PDS-3079)
- [TDD](https://paper.dropbox.com/doc/Gestalt-TDD-Modules-help-IconButton--BS4TjZGhn~rEVeVBa3YZgGeqAg-SFDuQbfYhXfiOdorq2vrn)
- [Figma](https://www.figma.com/file/vjhfBsOtHw0wVg67vqwz1v/01-.-Web-Sticker-Sheet?node-id=4068%3A7200)

Module: iconButton prop

---

packages/eslint-plugin-gestalt/src/__fixtures__/no-box-dangerous-style-duplicates/invalid/invalid-zIndex-input.js
packages/eslint-plugin-gestalt/src/__fixtures__/no-box-dangerous-style-duplicates/invalid/invalid-zIndex-output.js
packages/eslint-plugin-gestalt/src/helpers/styleHelpers.js
packages/eslint-plugin-gestalt/src/no-box-dangerous-style-duplicates.js
packages/eslint-plugin-gestalt/src/no-box-dangerous-style-duplicates.test.js

Eslint plugin: add zIndex props coverage to gestalt/no-box-dangerous-style-duplicates

---

packages/gestalt/src/Upsell.js
packages/gestalt/src/__snapshots__/Upsell.test.js.snap

If Upsell is used with no children and no actions, it will render with an extra div that can add unneeded whitespace at certain widths. This PR adds logic to ensure that div is only shown when it's needed.
_Before_
_After_

Upsell: don't render empty div if no actions and no children

---

package.json

ansi-regex is used in the following dependencies:
- ansi-regex "^0.2.0" - has-ansi@^0.1.0
- ansi-regex "^0.2.1" - strip-ansi@^0.3.0
- ansi-regex "^2.0.0" - has-ansi@^2.0.0, strip-ansi@^3.0.0, strip-ansi@^3.0.1, 
- ansi-regex "^3.0.0" - strip-ansi@^4.0.0
- ansi-regex "^4.0.0" - pretty-format@^24.9.0
- ansi-regex "^4.1.0" - strip-ansi@^5.0.0, strip-ansi@^5.1.0, strip-ansi@^5.2.0
- ansi-regex "^5.0.0" - pretty-format@^25.2.1, pretty-format@^26.4.2, pretty-format@^26.4.2, pretty-format@^27.0.2, pretty-format@^27.0.2, pretty-format@^27.1.0, strip-ansi@6.0.0, strip-ansi@^6.0.0
SEMVER NOTE: _^1.2.3 permits versions from 1.2.3 all the way up to, but not including, the next major version, 2.0.0._
Given the variety of modules and versions, a resolution for ansi-regex is the likely best option.
This …

Bump ansi-regex to "5.0.1"

---

docs/pages/activationcard.js
docs/pages/button.js
docs/pages/colorschemeprovider.js
docs/pages/dropdown.js
docs/pages/iconbutton.js
docs/pages/link.js
docs/pages/onlinknavigationprovider.js
docs/pages/tabs.js
docs/pages/taparea.js
docs/pages/upsell.js
packages/gestalt/src/ActivationCard.js
packages/gestalt/src/Button.js
packages/gestalt/src/Callout.js
packages/gestalt/src/DropdownLink.js
packages/gestalt/src/IconButton.js
packages/gestalt/src/InternalLink.js
packages/gestalt/src/Link.js
packages/gestalt/src/OptionItem.js
packages/gestalt/src/TableSortableHeaderCell.js
packages/gestalt/src/Tabs.js
packages/gestalt/src/TapArea.js
packages/gestalt/src/commonTypes.js

Link/Button/IconButton/TapArea +composed components: rename `disableOnNavigation` to `dangerouslyDisableOnNavigation`
Prefixed `dangerously`, à la React, to decentivize/alert about the usage this navigation functionality.
No codemod included, to prevent update in codebase, grep for `disableOnNavigation` strings in  your VSCode editor and replace all instances with `dangerouslyDisableOnNavigation`.

Link/Button/IconButton/TapArea +composed components: rename `disableOnNavigation` to `dangerouslyDisableOnNavigation`

---

docs/pages/module.js
packages/gestalt/src/ModuleExpandableItem.js
packages/gestalt/src/TapArea.js

Fix for https://github.com/pinterest/gestalt/issues/1721
Bonus: simplified the approach by no longer requiring the clients to use `event.preventDefault()` and `event.stopPropagation` on the `onClick` prop for the `IconButton`

Prevent iconButton firing collapse/expand events on Module.Expandable

---

docs/pages/status.js
packages/gestalt/src/Status.js
packages/gestalt/src/Status.test.js
packages/gestalt/src/__snapshots__/Status.test.js.snap

There is a need for the Status icons without the text (or with different text), so this PR makes that prop optional. To keep things accessible, this also adds an optional accessibility label prop.
Ideally we would use union types to make one of {accessbilityLabel, title} required, but that doesn't currently work with our generated props tables. That will be a good upgrade once we figure out the union type story.
- [Jira](https://jira.pinadmin.com/browse/PDS-3190)

Status: make `title` optional, add `accessibilityLabel`

---

.eslintrc.json
docs/components/DocSearch.js
docs/pages/_app.js
docs/pages/_document.js
docs/pages/whats_new.js
package.json
yarn.lock

Enables the Next.js ESLint plugin: https://nextjs.org/docs/basic-features/eslint
* Google Analytics
* Docsearch
* Images load correctly in the docs
* https://github.com/vercel/next.js/blob/canary/errors/no-script-in-document-page.md
* https://github.com/vercel/next.js/blob/canary/errors/next-script-for-ga.md#using-gtagjs

Internal: enable Next.js ESLint plugin

---

cypress/integration/accessibility_NumberField_spec.js
docs/components/sidebarIndex.js
docs/pages/numberfield.js
docs/pages/textfield.js
packages/gestalt/src/InternalTextField.js
packages/gestalt/src/NumberField.js
packages/gestalt/src/NumberField.jsdom.test.js
packages/gestalt/src/NumberField.test.js
packages/gestalt/src/TextField.test.js
packages/gestalt/src/__snapshots__/NumberField.test.js.snap
packages/gestalt/src/__snapshots__/TextField.test.js.snap
packages/gestalt/src/index.js

We've had requests to add a version of TextField that is specific to numerical input. This makes numbers easier to work with in a couple of ways:
- Inputs (`value`) and outputs (in handlers) are all numbers, not strings, so the dev doesn't need to parse and stringify
- Add min/max/step props, mirroring those `<input>` attributes
This PR also converts TextField to use generated docs, and cleans up some copy slightly. Converting the docs page to our newer style is out of scope, as is converting NumberField's docs to the newer style (since it's so similar to TextField, so copy/paste/modify).
- [Jira](https://jira.pinadmin.com/browse/PDS-2860)

NumberField: add new component

---

packages/gestalt/src/TextField.js

In #1760, we removed the "number" type from TextField. While this is our eventual goal, a lot of components depend on this type. To make it easier to land NumberField in Pinboard, this PR re-adds that type back to TextField, allowing for a more gradual migration path:
- Identify TextFields that can be replaced with NumberField, including wrappers around TextField
- Replace all existing usages
- Remove "number" type from TextField, which will be a breaking change but won't have any usages to codemod

TextField: re-add "number" type for now

---

packages/eslint-plugin-gestalt/src/__fixtures__/prefer-link/invalid/no-gestalt-import-input.js
packages/eslint-plugin-gestalt/src/__fixtures__/prefer-link/invalid/no-gestalt-import-multiple-input.js
packages/eslint-plugin-gestalt/src/__fixtures__/prefer-link/invalid/no-gestalt-import-multiple-output.js
packages/eslint-plugin-gestalt/src/__fixtures__/prefer-link/invalid/no-gestalt-import-multiple-taparea-suggestion.js
packages/eslint-plugin-gestalt/src/__fixtures__/prefer-link/invalid/no-gestalt-import-output.js
packages/eslint-plugin-gestalt/src/__fixtures__/prefer-link/invalid/no-gestalt-import-single-input.js
packages/eslint-plugin-gestalt/src/__fixtures__/prefer-link/invalid/no-gestalt-import-single-output.js
packages/eslint-plugin-gestalt/src/__fixtures__/prefer-link/invalid/no-gestalt-import-single-taparea-suggestion.js
packages/eslint-plugin-gestalt/src/__fixtures__/prefer-link/valid/valid.js
packages/eslint-plugin-gestalt/src/helpers/eslintFlowTypes.js
packages/eslint-plugin-gestalt/src/prefer-link.js
packages/eslint-plugin-gestalt/src/prefer-link.test.js

Eslint plugin: prefer-link fixes (p.e. single href prop now gets converted, better messaging) and added suggestions (to fix to TapArea)

Eslint plugin: prefer-link fixes and added suggestions

---

packages/gestalt-codemods/README.md

@EduhCosta created some [great documentation](https://paper.dropbox.com/doc/Codemod-instructions--BVrid0cRnS6be4QLvLXH5V8bAg-OBUZ5f4Bl3MZbNvsx8nCT) for our codemod development process. However, it occurred to me that the best place for that information to live is in the repo itself, so I adapted it to this README file.
As I was writing this doc, it also occurred to me that we should scaffold much of this boilerplate, so I created a [Jira ticket](https://jira.pinadmin.com/browse/PDS-3368) for myself to write that script later this year. I'll update this README once that script is in place.
Feedback on content/presentation very much sought and appreciated! Where does this not make sense, where am I glossing over important details, what am I forgetting?

Codemods: add README

---

packages/gestalt/src/Toast.js
packages/gestalt/src/__snapshots__/Toast.test.js.snap

I flubbed some of the markup in Toast when converting to use Flex back in September…whoops. This PR fixes the layout to ensure that the elements are properly spaced: thumbnail left-aligned, button right-aligned, text left-aligned and taking up available space in the middle.
[Jira bug](https://jira.pinadmin.com/browse/BUG-135135)
(not quite before/after screenshots, but you get the gist)
_Before_
_After_

Toast: fix layout issues

---

docs/pages/divider.js

showcase vertical dividers with Flex

Divider: Add vertical example to docs

---

packages/gestalt/src/Masonry.js

**TLDR:** This changes the `updateScrollPosition` strategy in Masonry from: making sure that updating isn't called multiple times w/in 100ms, to: not calling `updateScrollPosition` at all until scroll callbacks stop occurring.
The browser API for scroll callbacks is called multiple times per scroll events. Therefore, any code called within the scroll handler callback can very easily slow down scroll. This seems to be the idea behind the `throttle`ing here, to ensure multiple callbacks aren't called within 100ms of each other: 
https://github.com/pinterest/gestalt/blob/6021664f7341a7f3f7a52887e388c1203da77e41/packages/gestalt/src/Masonry.js#L135
https://github.com/valbooth28/gestalt/blob/aefb6127eacbe19a23bdfdc0ecf8d326c4eb6dac/packages/gestalt/src/throttle.js#L10
At the start of a scroll, …

Masonry: delay updating React scroll state until scroll events stop coming in

---

packages/gestalt/src/Masonry.js

To add a separate scroll position update strategy in #1774, I split `updateScrollPosition` into two functions- one with the majority of the updating logic, to be called by a new `handleScroll`, and a throttled counterpart to match the original functionality, `throttledUpdateScrollPosition`.
The `throttle` wrapper call that provided `this.updateScrollPosition` with a `.clearTimeout` property no longer wraps `this.updateScrollPosition` -  it wraps `throttledUpdateScrollPosition`. If we want to clear the timeout in the unmount lifecycle, we need to call `this.throttledUpdateScrollPosition.clearTimeout` instead, especially to prevent downstream errors.
- [Jira](https://jira.pinadmin.com/browse/PERF-10216)

Masonry: FIX this.updateScrollPosition.clearTimeout is not a function

---

packages/gestalt/src/InternalTextField.js
packages/gestalt/src/TextField.js

We're currently using "number" for telephone numbers, which isn't great. Adding the "tel" option will yield a better UX on mobile right now, and we can explore adding additional props (`pattern`, `maxLength`, etc) in the future if needed.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel

TextField: add "tel" option for `type` prop

---

cypress/integration/accessibility_Module_spec.js
docs/components/PropTable.js
docs/pages/card.js
docs/pages/dropdown.js
docs/pages/flex.js
docs/pages/iconbutton.js
docs/pages/module.js
docs/pages/table.js
docs/pages/upsell.js

Main change: Added design guidelines to Table component
Other improvement:
Refactor subcomponent proptable heading to show up on the right navigation bar.
Moved the subcomponent props to a sublevel in the right nav sidebar to give more sense of structure and readability it.
The props tables are VERY long, so it might take a lot of scrolling to get to the Guidelines. So I thought that Variants is for engineers as well as the Subcomponent section, so I placed it at the end assuming engineers already go to Variants to figure out doubts etc,
We know engineers wanted the Props at the top… but very long Props sections including subcomponents might be too much to get to the sections designers go more often.
So by calling it Subcomponents we make it more eng focused so it can just go over …

Table: Update design guidelines in Docs

---

docs/components/DocSearch.js
docs/components/Header.js
docs/components/HeaderMenu.js

I couldn't remember what our search keyboard shortcut was, so I figured others probably couldn't either. 😅
The GitHub link tooltip seems a bit obvious, but added to match all other elements in the header

Docs: add a couple of tooltips to header elements

---

docs/components/TokenExample.js
docs/pages/design_tokens.js
packages/gestalt-design-tokens/build.js
packages/gestalt-design-tokens/config.json
packages/gestalt-design-tokens/tokens/color/alias.json
packages/gestalt/src/Colors.css

Add Color alias tokens for Background and Text, re-work how the Design Tokens page is rendered, add JS output from design tokens package 

Design tokens: Add Color alias tokens

---

docs/pages/divider.js
packages/gestalt/src/Divider.js

Divider: updated design guidelines

Divider: updated design guidelines

---

.eslintrc.json

Accessing state in `this.setState` is an anti-pattern, and can lead to subtle bugs. This PR enables [the lint rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-access-state-in-setstate.md) (already available as part of `eslint-plugin-react`) to guard against this usage. (We have none currently.)
Given that most of our components are functional, it would be a lot more useful if we had a similar lint rule for `useState`. There is an [open feature request](https://github.com/facebook/react/issues/21448) for this that I'm watching — hopefully someone has time soon to write the rule (I personally don't).

Internal: enable `no-access-state-in-setstate` lint rule

---

docs/components/PageHeader.js

As noted in [this ticket](https://jira.pinadmin.com/browse/GESTALT-3225), the docs have a UI bug at narrow viewport widths where the GitHub link text gets all wonky. This PR allows that text to (collectively) wrap, so it gets bumped to the next line instead of insisting on staying on the title line
_the bug_
_Fixed!_
.

Docs: allow GitHub link text in page header to wrap

---

docs/components/Markdown.js
docs/pages/faq.js
docs/pages/how_to_work_with_us.js
packages/eslint-plugin-gestalt/src/no-box-dangerous-style-duplicates.js
packages/eslint-plugin-gestalt/src/no-box-dangerous-style-duplicates.test.js
packages/eslint-plugin-gestalt/src/no-box-disallowed-props.js
packages/eslint-plugin-gestalt/src/no-box-disallowed-props.test.js
packages/eslint-plugin-gestalt/src/no-box-marginleft-marginright.js

`s/'gestalt.netlify.app'/'gestalt.pinterest.systems'/`
I guess we missed these when we updated to use the new domain. These are the last references I can find in the repo!

Internal: update straggling references to the old docs domain

---

docs/pages/how_to_work_with_us.js

Edited the design section of the page "How to work with us," making the content simpler and easier on the eyes. In addition, I deleted a few lines and added new ones.
Updated all links to go through pinch links
Refactored to remove Card components in page.
Reason: we explain the whole process of contribution during our office hours; there isn't a need to make it too granular on the docs, as it is causing a long scrolling and heavy content. Trying to make it more digestible.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-3413)

Docs: Updated the design section of the page "How to work with us" 

---

docs/components/TokenExample.js
docs/pages/design_tokens.js
packages/gestalt-design-tokens/build.js
packages/gestalt-design-tokens/config.json
packages/gestalt-design-tokens/tokens/color/base.json
packages/gestalt-design-tokens/tokens/font/base.json

Add tokens for font-size, font-family, and font-weight + documentation
(Also updates our roboflow 100 to #F1F1F1)
Create tokens for all platforms to align on typography decisions 
- [Jira](https://jira.pinadmin.com/browse/GESTALT-3006)

Design tokens: Add font tokens for size, weight, and family

---

.flowconfig
docs/package.json
package.json
yarn.lock

0.165.1 -> 0.167.1
Also upgrade `react-live` to 2.3.0, which removes the dependency `fbjs` that was causing Flow errors, as it uses invalid `@flow weak` syntax

Internal: Upgrade Flow to 0.167.1

---

docs/pages/accessibility.js

Docs: Fixed links under Labels on the Accessibility 
Avatar Group, Callout, Upsell
Changed the Capital letters on the links to fix the 404 errors. 
Test - GitHub with Ayesha 
https://docs.google.com/presentation/d/1jwaHeYg4CPWyyeKRl2AvBIv1CvqHMiOSdKjv9LWuzI4/edit#slide=id.g1059ad83a94_0_80
Slide 16
- Tested on the local host

Docs: Fixed links under Labels on the Accessibility page

---

docs/pages/upsell.js
packages/gestalt/src/Upsell.js

Not worrying about Upsell.Form for now. We'll probably need to move it out to its own file in the future, but we should figure out the sidebar plan for that.

Upsell: convert to use generated props table

---

docs/pages/accessibility.js

Fixed the Popover link in the ARIA attributes section so that it is not capitalized.
was generating a 404.

Docs: Fixed broken Popover link on Accessibility page

---

docs/components/Footer.js
docs/pages/whats_new.js

-  Added loading spinner for changelog
- Refactor footer to change row to direction layout in small screens 
Before 
After

Docs: small layout and changelog loading improvements

---

docs/pages/whats_new.js

Loads markdown inline instead of fetching it remotely from GitHub.
Follow up from #1820 by @AlbertCarreras 
With Create React App we had to load the changelog from GitHub.
Now that we're on Next.js, we can fetch the markdown file in  `getStaticProps`.

Docs: avoid spinner on What's new page

---

docs/pages/card.js
docs/pages/checkbox.js
docs/pages/column.js
packages/gestalt/src/Card.js
packages/gestalt/src/Checkbox.js
packages/gestalt/src/Column.js

Only adding content where needed — these will still need another pass later to modernize the prop descriptions

Card, Checkbox, Column: refactor to use generated props tables

---

CHANGELOG.md

`transform` followed with a back-tick resulted in our `Markdown` rendering breaking.

Docs: fix changelog rendering on What's new page

---

packages/gestalt/src/Box.js
packages/gestalt/src/Column.js

per a [great suggestion](https://github.com/pinterest/gestalt/pull/1821#discussion_r771104441) by @christianvuerings, adding comments to responsive props for Box and Column to provide guidance in IDEs (we filter these props out of the docs props tables)

Box, Column: add comments for responsive props

---

.github/workflows/ci.yml
.github/workflows/release.yml

Updates GitHub actions to the latest version
Security & reliability of the Gestalt CI pipeline
Beta releases explain the changes:
- https://github.com/actions/setup-node/releases/tag/v2.0.0
- https://github.com/actions/setup-node/releases/tag/v2.1.0
- https://github.com/actions/setup-node/releases/tag/v2.1.1
- https://github.com/actions/setup-node/releases/tag/v2.1.2
- https://github.com/actions/setup-node/releases/tag/v2.1.3

Internal: Update GitHub actions to latest version

---

.github/workflows/release.yml

Every change to Gestalt triggers a VSCode Gestalt release.
So VSCode Gestalt always has the latest snippets
- https://github.com/pinterest/vscode-gestalt/pull/6
Since there was no way for me to test the integration, it could be that the new trigger fails. However, we added the trigger as the last step so packages will still be published

Internal: publish a new version of VSCode Gestalt for every Gestalt change

---

packages/gestalt/src/Tabs.js
packages/gestalt/src/Tabs.test.js

No longer export `TabWithForwardRef` from the `Tabs.js` file
1. When running `react-docgen` on the `Tabs.js` file, we received the following output:
```
out/gestalt/packages/gestalt/src/Tabs.js: Multiple exported component definitions found.
```
The issue is that we have multiple exports in `Tabs.js`. `TabWithForwardRef` is only exported for a certain test and we can achieve similar test coverage by looking for certain props instead.
2. It allows the VSCode Gestalt to generate a `Tabs` code snippet .

Internal: avoid TabWithForwardRef export to fix generated types

---

packages/gestalt/src/OptionItem.js
packages/gestalt/src/__snapshots__/Dropdown.jsdom.test.js.snap

Updated logic to only add aria-selected when item has role=option, since aria-selected is not valid on role=menuitem
This bug breaks accessibility tests since aria-selected is not valid when role=menuitem, only role=option (needed for ComboBox)

Dropdown: Remove aria selected from menuitems

---

docs/components/GestaltLogo.js
docs/components/Header.js

As noted by @christianvuerings [in another PR](https://github.com/pinterest/gestalt/pull/1813#discussion_r770368520), using an inline SVG for our logo in the header would allow crisper zoomed display and obviate the need to load the image.

Docs: use inline SVG for header logo

---

docs/components/DocSearch.js

Update Algolia API keys
**Note** :  Only r+ the PR, do not merge it yourself. I need to do some extra validation.
Our docs search engine (Algolia) asked us to update our API keys.
- https://docsearch.algolia.com/docs/migrating-from-legacy/#what-do-i-need-to-do-to-migrate

Docs: Update Algolia API keys

---

CHANGELOG.md

Fixes a few rendering issues on the What's New page
So the layout no longer looks broken to our users

Docs: fix changelog render on What's New page

---

docs/pages/box.js
docs/pages/dropdown.js
docs/pages/layer.js
docs/pages/tooltip.js
packages/gestalt/src/zIndex.js

Fixes links to the zIndex page in our docs
To avoid a broken experience for our users
Thanks to Algolia's new crawler, we can now automatically surface invalid links:
1. Go to https://gestalt.netlify.app/dropdown
2. Click on `zIndex Classes`
3. Results in: 
```
{"errorType":"TypeError","errorMessage":"Request path contains unescaped characters","trace":["TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters","    at new NodeError (internal/errors.js:322:7)","    at new ClientRequest (_http_client.js:155:13)","    at request (http.js:94:10)","    at /var/task/.netlify/functions-internal/___netlify-handler/bridge.js:169:19","    at new Promise (<anonymous>)","    at Bridge.launcher (/var/task/.netlify/functions-internal/___netlify-handler/bridge.js:167:12)"," …
```

Docs: fix links to zIndex page

---

package.json

* Fail ESLint when we find any ESLint warnings
I noticed that adding a `console.log` in code did not fail CI, which was unexpected. We do want the build to fail if someone pushes up code with an accidental `console.log`.

Internal: disallow ESLint warnings

---

.github/workflows/release.yml

#1833 introduced a bug - now, the last step of a Gestalt release results in an error:
https://github.com/pinterest/gestalt/runs/4723953815?check_suite_focus=true
```
Run actions/github-script@v5
with:
github-token: ***
script: await github.rest.actions.createWorkflowDispatch({
owner: 'pinterest',
repo: 'vscode-gestalt',
workflow_id: 'workflows/publish.yml',
ref: 'main',
inputs: {
version: `${steps.release.outputs.VERSION}`
}
});
debug: false
user-agent: actions/github-script
result-encoding: json
ReferenceError: steps is not defined
at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4942:56), <anonymous>:9:17)
at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4943:12)
at main …
```

Internal: fix steps is not defined exception on VSCode Gestalt release step

---

docs/pages/whats_new.js

Use `getServerSideProps` to load the changelog markdown file on the Gestalt docs page.
For more context see #1844.
Fixes a bug with setting a user preference and reloading a page.
1. Go to `/`
2. Enable dark mode
3. Reload the page
Expected result: dark mode is enabled

Docs: fix SSR on what's new page

---

docs/pages/_app.js
docs/pages/_document.js

* Bug fix: RTL works correctly with SSR
1) Go to https://deploy-preview-1840--gestalt.netlify.app/how_to_work_with_us
2) Enable RTL
3) Refresh
Expected: RTL loads correctly without a client re-render
64342756

Docs: fix cookie issues

---

docs/pages/how_to_work_with_us.js

Primary motivation: add info about eng testing to the How to Work With Us. This page is getting a bit unwieldy, but that's fine for now — we're getting the info out there, and we'll organize it better as part of the docs redesign.
Also random formatting and copyediting on this page for clarity and style.

Docs: update How to Work With Us page

---

docs/pages/avatargroup.js
docs/pages/collage.js
docs/pages/container.js
docs/pages/datapoint.js
docs/pages/fieldset.js
docs/pages/heading.js
packages/gestalt/src/AvatarGroup.flowtest.js
packages/gestalt/src/Collage.js
packages/gestalt/src/Container.js
packages/gestalt/src/Datapoint.flowtest.js
packages/gestalt/src/Datapoint.js
packages/gestalt/src/Datapoint.test.js
packages/gestalt/src/DatapointTrend.js
packages/gestalt/src/DatapointTrend.test.js
packages/gestalt/src/Fieldset.js
packages/gestalt/src/Heading.js

Refactor docs to use generated props tables: Collage, Container, Datapoint, Fieldset, Heading
Also, removed unneeded React imports (probably from an older version of the scaffolding script)

Collage, Container, Datapoint, Fieldset, Heading: use generated props tables

---

.github/workflows/release.yml

`Trigger VSCode Gestalt release` is failing with the following exception:
```
RequestError [HttpError]: Not Found
at /home/runner/work/_actions/actions/github-script/v5/dist/index.js:4614:21
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4942:56), <anonymous>:3:1)
at async main (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4997:20) {
name: 'HttpError',
status: 404,
response: {
url: 'https://api.github.com/repos/pinterest/vscode-gestalt/actions/workflows/workflows%2Fpublish.yml/dispatches',
```
Most likely because of the `workflow_id` being incorrect.
- [Repo 1 yaml](https://github.com/botblock/data/blob/423199b4e90f899283a13bfdf5acb4e3683be27 …

Internal: fix workflow id for VSCode Gestalt release step

---

package.json
yarn.lock

This package is pretty deep in dependency chains, so easier to add a resolution. Needs to be at least `1.0.0`.
[Alerts · pinterest_gestalt.pdf](https://github.com/pinterest/gestalt/files/7842081/Alerts.pinterest_gestalt.pdf)

Internal: add resolution for `node-forge` to fix vulnerability

---

docs/components/TokenExample.js
docs/pages/design_tokens.js
packages/gestalt-design-tokens/build.js
packages/gestalt-design-tokens/config.json
packages/gestalt-design-tokens/tokens/color/alias.json
packages/gestalt/src/contexts/ColorSchemeProvider.js
packages/gestalt/src/contexts/ColorSchemeProvider.jsdom.test.js

Add dark mode values for our color design tokens
This isn't the full dark mode palette, but for the moment it matches our current dark mode configuration to allow for Android adoption
- [Jira](https://jira.pinadmin.com/browse/GESTALT-3462)

Design Tokens: Add dark mode values

---

cypress/integration/accessibility_How To Hack Around Gestalt_spec.js
docs/components/AppLayout.js
docs/components/Navigation.js
docs/components/sidebarIndex.js
docs/pages/how_to_hack_around_gestalt.js
docs/pages/how_to_hack_gestalt.js

This PR adds a new "How to Hack Gestalt" page to the docs. Though we'd prefer that such a page weren't necessary, people can and do hack around Gestalt's restrictions. Some of these techniques are more or less terrible than others, so it could be beneficial to make these trade-offs more explicit to push users towards the less-terrible options.

Docs: add "How to Hack Gestalt" page

---

docs/components/GeneratedPropTable.js
docs/pages/pulsar.js
docs/pages/radiobutton.js
docs/pages/spinner.js
docs/pages/switch.js
docs/pages/tooltip.js
packages/gestalt/src/Pulsar.js
packages/gestalt/src/RadioButton.js
packages/gestalt/src/Spinner.js
packages/gestalt/src/Switch.js
packages/gestalt/src/Tooltip.js

Also a tiny tweak to make sure we replace _all_ Gestalt docs domain instances in the comments, not just the first one

Pulsar, RadioButton, Spinner, Switch, Tooltip: use autogenerated props tables

---

packages/gestalt/src/Upsell.js
packages/gestalt/src/__snapshots__/Upsell.test.js.snap

Updated  left and right padding at sizes below 576px 
At small sizes, the close button was overlapping the text. This should fix that bug
- [Jira](https://jira.pinadmin.com/browse/BUG-137879)

Upsell: Fix layout bug at small sizes

---

cypress/integration/accessibility_Datapoint_spec.js
packages/gestalt/src/Datapoint.js
packages/gestalt/src/Tooltip.js

* Add optional `accessibilityLabel` prop to `Tooltip`
* Fix `Datapoint` accessibility integration test
`aria-command-name` was failing in multiple places in pinboard. The root cause was the `Datapoint` component
Ensure that VoiceOver still works correctly with `Tooltip` / `Datapoint`

Tooltip: add optional accessibilityLabel prop & fix Datapoint a11y integration test

---

cypress/integration/accessibility_IconButton_spec.js
docs/pages/iconbutton.js
packages/gestalt/src/IconButton.js
packages/gestalt/src/IconButton.test.js
packages/gestalt/src/__snapshots__/IconButton.test.js.snap

Add `tooltip` object prop to allow for easy addition of a Tooltip to an IconButton
eventually we want to make Tooltips required on IconButtons to help provide clarity around the intention of an IconButton. This is an initial step to make this easier, as well as an initial step toward creating HelpButton
- [Jira](https://jira.pinadmin.com/browse/GESTALT-2900)

IconButton: Add Tooltip prop

---

package.json
yarn.lock

This package is used by a number of other packages, so adding a resolution is much easier than tracking down updates for all the others.

Internal: add resolution for `node-fetch` to fix vulnerability

---

docs/pages/toast.js

Clicking is annoying — let's just give the people what they want!
This PR tweaks the Toast docs:
- Add a default example
- Add a "working" example showing how Toast should be displayed
- Refactor all other examples to show the UI element without requiring the user to click

Toast: show examples directly in docs

---

cypress/integration/accessibility_Icon_spec.js
cypress/integration/accessibility_Tooltip_spec.js
docs/components/buttons/CollapseExpandCodeButton.js
docs/components/buttons/CopyCodeButton.js
docs/components/buttons/CopyLinkButton.js
docs/components/buttons/OpenSandboxButton.js
docs/pages/icon.js
docs/pages/iconbutton.js
docs/pages/tooltip.js
packages/gestalt/src/IconButton.js
packages/gestalt/src/IconButton.test.js
packages/gestalt/src/Tooltip.js
packages/gestalt/src/__snapshots__/IconButton.test.js.snap

Avoid duplicate, redundant tooltips on IconButton by allowing accessibilityLabel to be empty on Tooltip
Right now, we require an accessibilityLabel on IconButton, and when that gets wrapped in a tooltip, we create a redundant experience when the accessibilityLabel and Tooltip text match (simple iconButtons like share). This change recommends people override the tooltip accessibilityLabel to be an empty string, thereby allowing screen readers to only read out the content on the button itself.

IconButton, Tooltip: Update accessibility guidance

---

docs/pages/tooling.js

Docs: update Visual Studio Code extension for Gestalt extension information 
@christianvuerings recently added new features to  the Visual Studio Code extension for Gestalt which were not reflected in the Docs. https://marketplace.visualstudio.com/items?itemName=pinterest.vscode-gestalt

Docs: update Visual Studio Code extension for Gestalt extension information

---

docs/components/GeneratedPropTable.js

We don't use them often, but occasionally we need internal-only props for use in experiments and other unusual needs. This PR adjusts the automatic docs generation to filter these props out of the props table.

Docs: automatically filter out "_fooProp" internal-only props

---

CHANGELOG.md
docs/components/GeneratedPropTable.js
docs/pages/masonry.js
docs/pages/toast.js
packages/gestalt/src/Masonry.js

Of note:
- Several overrides were needed to match the current props table types and default values.
- getStaticProps serializes the props data to JSON, meaning that any `undefined` values will throw. I added a one-off helper to replace those values with `null`, which we can pull out to a more reusable location if needed for other components. I was specifically seeing issues with the component methods, so this will likely only be an issue for other class components.

Masonry: use generated props table

---

docs/pages/tabs.js
docs/pages/textarea.js
packages/gestalt/src/NumberField.js
packages/gestalt/src/Tabs.js
packages/gestalt/src/TextArea.js
packages/gestalt/src/TextField.js

also added the missing `ref` prop for TextField + NumberField (whoops)

Tabs, TextArea: use generated props tables

---

CHANGELOG.md
scripts/releaseSteps.js

1. Run prettier on `CHANGELOG.md` file
2. Prevent future breakages by scripting the prettier run
Master broke due to an extra space in the PR title in #1890
```
$ prettier --check .
Checking formatting...
[warn] CHANGELOG.md
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```
https://github.com/pinterest/gestalt/runs/5011272978?check_suite_focus=true

Internal: Fix broken master due to prettier error on CHANGELOG.md

---

docs/components/GeneratedPropTable.js
docs/components/PropTable.js
docs/components/docgen.js
docs/pages/popover.js
packages/gestalt/src/Popover.js

Popover: updated Docs to use autogenerated prop table

Popover: updated Docs to use autogenerated prop table

---

docs/components/GeneratedPropTable.js
docs/pages/combobox.js
packages/gestalt/src/ComboBox.js

ComboBox: updated Docs to use autogenerated prop table

ComboBox: updated Docs to use autogenerated prop table

---

CHANGELOG.md
packages/gestalt-codemods/44.0.0/__testfixtures__/segmentedcontrol-size-renamed.input.js
packages/gestalt-codemods/44.0.0/__testfixtures__/segmentedcontrol-size-renamed.output.js
packages/gestalt-codemods/44.0.0/__testfixtures__/segmentedcontrol-size.input.js
packages/gestalt-codemods/44.0.0/__testfixtures__/segmentedcontrol-size.output.js
packages/gestalt-codemods/44.0.0/__tests__/segmentedcontrol-size.js
packages/gestalt-codemods/44.0.0/segmentedcontrol-size.js
packages/gestalt/src/SegmentedControl.js
packages/gestalt/src/SegmentedControl.jsdom.test.js

Removing the `size` prop from SegmentedControl.
This prop was only used once in Pinboard, where it was set to the default value. Since it is not needed, removing to simplify the component API.
- [Jira](https://jira.pinadmin.com/browse/GESTALT-3233)

SegmentedControl: remove size prop
